// src/features/metadata-edit/ui/atoms/AnnotationItem.tsx
/**
 * AnnotationItem Atom
 *
 * Single annotation list item display with optional inline edit.
 * Thin wrapper around shared ListItemBase molecule.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Zero state
 * - No domain logic
 * - Props-only API
 * - Uses shared ListItemBase
 *
 * @module features/metadata-edit/ui/atoms/AnnotationItem
 */

import React, { useState } from 'react';
import { ListItemBase } from '@/src/shared/ui/molecules/ListItemBase';
import { Button, Icon } from '@/src/shared/ui/atoms';
import { getIIIFValue, type IIIFAnnotation } from '@/src/shared/types';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';

export interface AnnotationItemProps {
  /** Annotation data */
  annotation: IIIFAnnotation;
  /** Current language for labels */
  language: string;
  /** Whether the item is selected */
  selected?: boolean;
  /** Called when item is clicked */
  onClick?: () => void;
  /** Called when delete button is clicked */
  onDelete?: () => void;
  /** Called when annotation text is edited */
  onEdit?: (newText: string) => void;
  /** Whether to show expanded inline edit */
  expanded?: boolean;
  /** Contextual styles from parent */
  cx: ContextualClassNames;
  /** Field mode flag */
  fieldMode: boolean;
  /** Additional CSS class */
  className?: string;
  /** Whether to show a selection checkbox */
  showCheckbox?: boolean;
  /** Whether the checkbox is checked */
  checked?: boolean;
  /** Callback when checkbox changes */
  onCheckChange?: (checked: boolean) => void;
}

export const AnnotationItem: React.FC<AnnotationItemProps> = ({
  annotation,
  language,
  selected = false,
  onClick,
  onDelete,
  onEdit,
  expanded = false,
  cx,
  fieldMode = false,
  className = '',
  showCheckbox = false,
  checked = false,
  onCheckChange,
}) => {
  const body = annotation.body as unknown as Record<string, unknown> | undefined;
  const bodyText = (body?.value as string) || getIIIFValue(annotation.label, language) || 'Untitled';
  const motivation = Array.isArray(annotation.motivation)
    ? annotation.motivation.join(', ')
    : (annotation.motivation || 'commenting');

  const [editText, setEditText] = useState(bodyText);

  const getMotivationColor = () => {
    if (motivation.includes('painting')) return 'bg-nb-blue/20 text-nb-blue';
    if (motivation.includes('supplementing')) return 'bg-nb-green/20 text-nb-green';
    if (motivation.includes('commenting')) return 'bg-nb-orange/20 text-nb-orange';
    if (motivation.includes('tagging')) return 'bg-nb-purple/10 text-nb-purple';
    if (motivation.includes('describing')) return fieldMode ? 'bg-nb-purple/20 text-nb-purple' : 'bg-nb-purple/10 text-nb-purple';
    return fieldMode ? 'bg-nb-black text-nb-yellow/40' : 'bg-nb-cream text-nb-black/60';
  };

  const handleSaveEdit = () => {
    if (onEdit && editText.trim() !== bodyText) {
      onEdit(editText.trim());
    }
  };

  return (
    <ListItemBase
      selected={selected}
      onClick={onClick}
      showDelete={!!onDelete}
      onDelete={onDelete}
      fieldMode={fieldMode}
      className={className}
    >
      <div className="flex items-center gap-2 mb-1">
        {showCheckbox && (
          <input
            type="checkbox"
            checked={checked}
            onChange={(e) => { e.stopPropagation(); onCheckChange?.(e.target.checked); }}
            onClick={(e) => e.stopPropagation()}
            className={`w-3 h-3 shrink-0 accent-nb-blue ${fieldMode ? 'accent-nb-yellow' : ''}`}
          />
        )}
        <span className={`text-xs font-bold truncate ${fieldMode ? cx.text : 'text-nb-black/80'}`}>
          {bodyText}
        </span>
        <span className={`text-[8px] px-1.5 py-0.5 uppercase font-bold shrink-0 ${getMotivationColor()}`}>
          {motivation}
        </span>
      </div>
      <p className={`text-[10px] truncate ${fieldMode ? (cx.textMuted || 'text-nb-yellow/60') : 'text-nb-black/50'}`}>
        {annotation.id}
      </p>

      {/* Inline edit when expanded and onEdit provided */}
      {expanded && onEdit && (
        <div className="mt-2 space-y-2" onClick={e => e.stopPropagation()}>
          <textarea
            value={editText}
            onChange={e => setEditText(e.target.value)}
            rows={2}
            className={`w-full px-2 py-1.5 text-xs outline-none border resize-none ${
              fieldMode
                ? 'bg-nb-black text-white border-nb-yellow/30 focus:border-nb-yellow'
                : 'bg-nb-white text-nb-black border-nb-black/20 focus:border-nb-blue'
            }`}
          />
          <div className="flex gap-1.5 justify-end">
            <Button variant="ghost" size="bare"
              onClick={() => setEditText(bodyText)}
              className={`px-2 py-1 text-[10px] font-bold ${fieldMode ? 'text-nb-yellow/60' : 'text-nb-black/50'}`}
            >
              Reset
            </Button>
            <Button variant="ghost" size="bare"
              onClick={handleSaveEdit}
              disabled={!editText.trim() || editText.trim() === bodyText}
              className={`px-2 py-1 text-[10px] font-bold disabled:opacity-40 ${
                fieldMode ? 'bg-nb-yellow text-nb-black' : 'bg-nb-blue text-white'
              }`}
            >
              <Icon name="save" className="text-[10px] mr-0.5 inline" />
              Save
            </Button>
          </div>
        </div>
      )}
    </ListItemBase>
  );
};

export default AnnotationItem;

// src/features/metadata-edit/ui/atoms/AnnotationItem.svelte
<!--
  AnnotationItem — Annotation list item with inline edit capability.
  React source: src/features/metadata-edit/ui/atoms/AnnotationItem.tsx
  Architecture: Atom (internal editText state, props-driven, Rule 5.D: cx + fieldMode)
-->
<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import type { IIIFAnnotation } from '@/src/shared/types';
  import { getIIIFValue } from '@/src/shared/types';
  import { cn } from '@/src/shared/lib/cn';
  import ListItemBase from '@/src/shared/ui/molecules/ListItemBase.svelte';
  import Button from '@/src/shared/ui/atoms/Button.svelte';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';

  interface Props {
    annotation: IIIFAnnotation;
    language?: string;
    selected?: boolean;
    onclick?: () => void;
    onDelete?: (id: string) => void;
    onEdit?: (id: string, text: string) => void;
    expanded?: boolean;
    cx: ContextualClassNames;
    fieldMode: boolean;
    class?: string;
    showCheckbox?: boolean;
    checked?: boolean;
    onCheckChange?: (checked: boolean) => void;
  }

  let {
    annotation,
    language = 'en',
    selected = false,
    onclick,
    onDelete,
    onEdit,
    expanded = false,
    cx,
    fieldMode,
    class: className = '',
    showCheckbox = false,
    checked = false,
    onCheckChange,
  }: Props = $props();

  let isEditing = $state(false);
  let editText = $state('');

  let bodyText = $derived.by(() => {
    const body = Array.isArray(annotation.body) ? annotation.body[0] : annotation.body;
    if (!body) return '';
    if ('value' in body) return body.value;
    if ('label' in body && body.label) return getIIIFValue(body.label, language);
    return '';
  });

  let motivation = $derived(
    Array.isArray(annotation.motivation) ? annotation.motivation[0] : annotation.motivation
  );

  function startEdit() {
    editText = bodyText;
    isEditing = true;
  }

  function cancelEdit() {
    isEditing = false;
    editText = '';
  }

  function saveEdit() {
    if (onEdit && editText.trim()) {
      onEdit(annotation.id, editText.trim());
    }
    isEditing = false;
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter') {
      e.preventDefault();
      saveEdit();
    } else if (e.key === 'Escape') {
      cancelEdit();
    }
  }
</script>

<div class={cn('group', className)}>
  <ListItemBase {selected} {onclick} {cx}>
    {#snippet leading()}
      {#if showCheckbox}
        <!-- svelte-ignore a11y_click_events_have_key_events -->
        <!-- svelte-ignore a11y_no_static_element_interactions -->
        <div onclick={(e) => e.stopPropagation()}>
          <input
            type="checkbox"
            {checked}
            onchange={(e) => onCheckChange?.(e.currentTarget.checked)}
            class="w-4 h-4 accent-nb-orange"
          />
        </div>
      {/if}
      <Icon
        name={motivation === 'commenting' ? 'comment' : motivation === 'tagging' ? 'label' : 'description'}
        class={cn('text-lg', fieldMode ? 'text-nb-yellow/60' : cx.textMuted ?? 'text-nb-black/40')}
      />
    {/snippet}

    {#snippet children()}
      {#if isEditing}
        <div class="flex items-center gap-2" onclick={(e) => e.stopPropagation()} role="presentation">
          <input
            type="text"
            bind:value={editText}
            onkeydown={handleKeydown}
            class={cn(
              'flex-1 px-2 py-1 text-sm border outline-none focus:ring-1',
              fieldMode
                ? 'bg-nb-black text-nb-yellow border-nb-yellow/30 focus:ring-nb-yellow'
                : cx.input ?? 'bg-nb-white text-nb-black border-nb-black/20 focus:ring-nb-blue'
            )}
          />
          <Button variant="ghost" size="bare" onclick={saveEdit} class="p-1">
            {#snippet children()}<Icon name="check" class="text-nb-green text-base" />{/snippet}
          </Button>
          <Button variant="ghost" size="bare" onclick={cancelEdit} class="p-1">
            {#snippet children()}<Icon name="close" class="text-nb-red text-base" />{/snippet}
          </Button>
        </div>
      {:else}
        <div class="flex flex-col gap-0.5">
          <span class={cn(
            'text-sm truncate',
            fieldMode ? 'text-nb-yellow' : cx.text ?? 'text-nb-black'
          )}>
            {bodyText || '(empty annotation)'}
          </span>
          {#if expanded}
            <span class={cn(
              'text-xs font-mono',
              fieldMode ? 'text-nb-yellow/50' : cx.textMuted ?? 'text-nb-black/40'
            )}>
              {motivation} &middot; {annotation.id.split('/').pop()}
            </span>
          {/if}
        </div>
      {/if}
    {/snippet}

    {#snippet trailing()}
      {#if !isEditing}
        <div class="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
          {#if onEdit}
            <Button
              variant="ghost"
              size="bare"
              onclick={(e) => { e.stopPropagation(); startEdit(); }}
              title="Edit annotation"
              class="p-1"
            >
              {#snippet children()}<Icon name="edit" class="text-base" />{/snippet}
            </Button>
          {/if}
          {#if onDelete}
            <Button
              variant="ghost"
              size="bare"
              onclick={(e) => { e.stopPropagation(); onDelete(annotation.id); }}
              title="Delete annotation"
              class="p-1"
            >
              {#snippet children()}<Icon name="delete" class={cn('text-base', cx.danger ?? 'text-nb-red')} />{/snippet}
            </Button>
          {/if}
        </div>
      {/if}
    {/snippet}
  </ListItemBase>
</div>
