// src/features/metadata-edit/ui/atoms/AutoMapButton.tsx
/**
 * AutoMapButton Atom
 *
 * Button to trigger automatic column mapping detection.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Zero state
 * - No domain logic
 * - Props-only API
 * - Uses design tokens
 *
 * @module features/metadata-edit/ui/atoms/AutoMapButton
 */

import React from 'react';
import { Button, Icon } from '@/src/shared/ui/atoms';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';

export interface AutoMapButtonProps {
  /** Called when auto-map is triggered */
  onClick: () => void;
  /** Whether auto-mapping is in progress */
  isLoading?: boolean;
  /** Whether the button is disabled */
  disabled?: boolean;
  /** Button label (default: "Auto-Detect Mappings") */
  label?: string;
  /** Contextual styles from parent */
  cx?: ContextualClassNames;
  /** Field mode flag */
  fieldMode?: boolean;
}

export const AutoMapButton: React.FC<AutoMapButtonProps> = ({
  onClick,
  isLoading = false,
  disabled = false,
  label = 'Auto-Detect Mappings',
}) => {
  return (
    <Button
      onClick={onClick}
      disabled={disabled || isLoading}
      variant="secondary"
      size="sm"
      icon={
        isLoading ? (
          <span className="animate-spin">
            <Icon name="refresh" />
          </span>
        ) : (
          <Icon name="auto_fix_high" />
        )
      }
    >
      {isLoading ? 'Detecting...' : label}
    </Button>
  );
};

export default AutoMapButton;

// src/features/metadata-edit/ui/atoms/AutoMapButton.svelte
<!--
  AutoMapButton — Button that triggers automatic column mapping detection.
  React source: src/features/metadata-edit/ui/atoms/AutoMapButton.tsx (62 lines)
  Architecture: Atom (zero state, props-only, Rule 5.D: cx + fieldMode)
-->
<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import Button from '@/src/shared/ui/atoms/Button.svelte';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';

  interface Props {
    onclick: () => void;
    isLoading?: boolean;
    disabled?: boolean;
    label?: string;
    cx?: Partial<ContextualClassNames>;
    fieldMode?: boolean;
  }

  let {
    onclick,
    isLoading = false,
    disabled = false,
    label = 'Auto-Detect Mappings',
    cx = {},
    fieldMode = false,
  }: Props = $props();
</script>

<Button
  {onclick}
  disabled={disabled || isLoading}
  variant="secondary"
  size="sm"
>
  {#snippet icon()}
    {#if isLoading}
      <span class="animate-spin inline-flex">
        <Icon name="refresh" />
      </span>
    {:else}
      <Icon name="auto_fix_high" />
    {/if}
  {/snippet}
  {isLoading ? 'Detecting...' : label}
</Button>
