// src/features/metadata-edit/ui/atoms/BehaviorTag.svelte
<!--
  BehaviorTag — Pill/tag for IIIF behavior with category-based styling.
  React source: src/features/metadata-edit/ui/atoms/BehaviorTag.tsx (92 lines)
  Architecture: Atom (zero state, props-only, Rule 5.D: cx + fieldMode)
-->
<script module lang="ts">
  const CATEGORY_COLORS: Record<string, string> = {
    time: 'bg-nb-purple/10 text-nb-purple',
    layout: 'bg-nb-orange/20 text-nb-orange',
    browsing: 'bg-nb-green/20 text-nb-green',
    page: 'bg-nb-blue/20 text-nb-blue',
    navigation: 'bg-nb-blue/20 text-nb-blue',
  } as const;
</script>

<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import { cn } from '@/src/shared/lib/cn';
  import { BEHAVIOR_DEFINITIONS } from '@/src/shared/constants/iiif';

  interface Props {
    behavior: string;
    active?: boolean;
    showCategory?: boolean;
    cx?: Partial<ContextualClassNames>;
    fieldMode?: boolean;
    class?: string;
    onclick?: () => void;
  }

  let {
    behavior,
    active = true,
    showCategory = false,
    cx = {},
    fieldMode = false,
    class: className = '',
    onclick,
  }: Props = $props();

  let definition = $derived(BEHAVIOR_DEFINITIONS[behavior]);
  let displayLabel = $derived(definition?.label ?? behavior);
  let category = $derived(definition?.category);

  let categoryColor = $derived(
    category
      ? CATEGORY_COLORS[category] ?? (fieldMode ? 'bg-nb-black text-nb-black/50' : 'bg-nb-cream text-nb-black/60')
      : ''
  );

  let tagClass = $derived(
    cn(
      'inline-flex items-center gap-1 text-[10px] px-2 py-0.5 font-semibold',
      onclick && 'cursor-pointer hover:opacity-80 transition-nb',
      active
        ? 'bg-nb-blue text-white'
        : fieldMode
          ? 'bg-nb-black text-nb-black/40'
          : 'bg-nb-cream text-nb-black/60',
      className
    )
  );
</script>

<button
  type="button"
  class={tagClass}
  {onclick}
  title={definition?.description ?? behavior}
>
  <span>{displayLabel}</span>
  {#if showCategory && category}
    <span class={cn('text-[8px] px-1 uppercase', categoryColor)}>
      {category}
    </span>
  {/if}
</button>

// src/features/metadata-edit/ui/atoms/BehaviorTag.tsx
/**
 * BehaviorTag Atom
 *
 * Pill/tag displaying an IIIF behavior with category-based styling.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Zero state
 * - No domain logic
 * - Props-only API
 * - Uses design tokens
 *
 * @module features/metadata-edit/ui/atoms/BehaviorTag
 */

import React from 'react';
import { BEHAVIOR_DEFINITIONS } from '@/src/shared/constants/iiif';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';

export interface BehaviorTagProps {
  /** Behavior value (e.g., 'auto-advance') */
  behavior: string;
  /** Whether the tag is active (selected) */
  active?: boolean;
  /** Whether to show category badge */
  showCategory?: boolean;
  /** Contextual styles from parent */
  cx?: ContextualClassNames;
  /** Field mode flag */
  fieldMode?: boolean;
  /** Additional CSS class */
  className?: string;
  /** Callback when tag is clicked */
  onClick?: () => void;
  /** Size variant */
  size?: 'xs' | 'sm' | 'md' | 'lg';
}

export const BehaviorTag: React.FC<BehaviorTagProps> = ({
  behavior,
  active = true,
  showCategory = false,
  cx,
  fieldMode = false,
  className = '',
  onClick,
}) => {
  const definition = BEHAVIOR_DEFINITIONS[behavior];
  const label = definition?.label || behavior;
  const category = definition?.category;

  const getCategoryColor = () => {
    switch (category) {
      case 'time':
        return 'bg-nb-purple/10 text-nb-purple';
      case 'layout':
        return 'bg-nb-orange/20 text-nb-orange';
      case 'browsing':
        return 'bg-nb-green/20 text-nb-green';
      case 'page':
        return 'bg-nb-blue/20 text-nb-blue';
      case 'navigation':
        return 'bg-nb-blue/20 text-nb-blue';
      default:
        return fieldMode ? 'bg-nb-black text-nb-black/50' : 'bg-nb-cream text-nb-black/60';
    }
  };

  const baseClass = onClick ? 'cursor-pointer hover:opacity-80 transition-nb' : '';

  return (
    <div
      className={`inline-flex items-center gap-1 text-[10px] px-2 py-0.5 font-semibold ${baseClass} ${
        active
          ? 'bg-nb-blue text-white'
          : fieldMode
            ? 'bg-nb-black text-nb-black/40'
            : 'bg-nb-cream text-nb-black/60'
      } ${className}`}
      onClick={onClick}
      title={definition?.description || behavior}
    >
      <span>{label}</span>
      {showCategory && category && (
        <span className={`text-[8px] px-1 uppercase ${getCategoryColor()}`}>
          {category}
        </span>
      )}
    </div>
  );
};

export default BehaviorTag;
