// src/features/metadata-edit/ui/atoms/ColumnSelector.tsx
/**
 * ColumnSelector Atom
 *
 * Dropdown for selecting CSV column headers.
 * Thin wrapper around shared SelectField molecule.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Zero state
 * - No domain logic
 * - Props-only API
 * - Uses shared SelectField
 *
 * @module features/metadata-edit/ui/atoms/ColumnSelector
 */

import React from 'react';
import { SelectField } from '@/src/shared/ui/molecules';
import type { ContextualClassNames } from '@/hooks/useContextualStyles';

export interface ColumnSelectorProps {
  /** Available column headers */
  columns: string[];
  /** Currently selected column */
  value: string;
  /** Called when selection changes */
  onChange: (column: string) => void;
  /** Placeholder text for empty selection */
  placeholder?: string;
  /** Whether the selector is disabled */
  disabled?: boolean;
  /** Contextual styles from parent */
  cx?: ContextualClassNames;
  /** Field mode flag */
  fieldMode?: boolean;
}

export const ColumnSelector: React.FC<ColumnSelectorProps> = ({
  columns,
  value,
  onChange,
  placeholder = 'Select a column...',
  disabled = false,
  fieldMode = false,
}) => {
  const options = columns.map(col => ({ value: col, label: col }));

  return (
    <SelectField
      value={value}
      onChange={onChange}
      options={options}
      placeholder={placeholder}
      disabled={disabled}
      fieldMode={fieldMode}
    />
  );
};

export default ColumnSelector;

// src/features/metadata-edit/ui/atoms/ColumnSelector.svelte
<!--
  ColumnSelector — Dropdown for selecting CSV column headers.
  React source: src/features/metadata-edit/ui/atoms/ColumnSelector.tsx (60 lines)
  Architecture: Atom (zero state, props-only, Rule 5.D: cx + fieldMode)
-->
<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import SelectField from '@/src/shared/ui/molecules/SelectField.svelte';

  interface Props {
    columns: string[];
    value: string;
    onchange: (column: string) => void;
    placeholder?: string;
    disabled?: boolean;
    cx?: Partial<ContextualClassNames>;
    fieldMode?: boolean;
  }

  let {
    columns,
    value,
    onchange,
    placeholder = 'Select a column...',
    disabled = false,
    cx = {},
    fieldMode = false,
  }: Props = $props();

  let options = $derived(columns.map(col => ({ value: col, label: col })));
</script>

<SelectField
  {value}
  {options}
  {disabled}
  {onchange}
  cx={cx as ContextualClassNames}
/>
