// src/features/metadata-edit/ui/atoms/FilePreview.svelte
<!--
  FilePreview — CSV data preview table with column/row limits.
  React source: src/features/metadata-edit/ui/atoms/FilePreview.tsx
  Architecture: Atom (zero state, props-only, Rule 5.D: cx + fieldMode)
-->
<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import { cn } from '@/src/shared/lib/cn';

  interface Props {
    headers: string[];
    rows: Record<string, string>[];
    maxColumns?: number;
    maxRows?: number;
    cx?: Partial<ContextualClassNames>;
    fieldMode?: boolean;
  }

  let {
    headers,
    rows,
    maxColumns = 5,
    maxRows = 3,
    cx = {},
    fieldMode = false,
  }: Props = $props();

  let displayHeaders = $derived(headers.slice(0, maxColumns));
  let displayRows = $derived(rows.slice(0, maxRows));
  let hasMoreColumns = $derived(headers.length > maxColumns);
  let hasMoreRows = $derived(rows.length > maxRows);

  let cellClass = $derived(
    cn(
      'px-3 py-1.5 text-xs font-mono border truncate max-w-[160px]',
      fieldMode
        ? 'border-nb-yellow/20 text-nb-yellow'
        : cx.text ?? 'border-nb-black/10 text-nb-black/80'
    )
  );

  let headerCellClass = $derived(
    cn(
      'px-3 py-2 text-xs font-bold uppercase tracking-wider font-mono border text-left',
      fieldMode
        ? 'bg-nb-yellow/20 border-nb-yellow/30 text-nb-yellow'
        : cx.headerBg ?? 'bg-nb-cream border-nb-black/20 text-nb-black'
    )
  );
</script>

<div class="overflow-x-auto">
  <table class={cn(
    'w-full border-collapse border',
    fieldMode ? 'border-nb-yellow/30' : 'border-nb-black/20'
  )}>
    <thead>
      <tr>
        {#each displayHeaders as header (header)}
          <th class={headerCellClass}>{header}</th>
        {/each}
        {#if hasMoreColumns}
          <th class={headerCellClass}>+{headers.length - maxColumns} more</th>
        {/if}
      </tr>
    </thead>
    <tbody>
      {#each displayRows as row, i (i)}
        <tr>
          {#each displayHeaders as header (header)}
            <td class={cellClass}>{row[header] ?? ''}</td>
          {/each}
          {#if hasMoreColumns}
            <td class={cn(cellClass, 'text-center opacity-50')}>...</td>
          {/if}
        </tr>
      {/each}
    </tbody>
  </table>

  {#if hasMoreRows}
    <p class={cn(
      'text-xs font-mono mt-2',
      fieldMode ? 'text-nb-yellow/60' : cx.textMuted ?? 'text-nb-black/50'
    )}>
      +{rows.length - maxRows} more row{rows.length - maxRows !== 1 ? 's' : ''}
    </p>
  {/if}
</div>

// src/features/metadata-edit/ui/atoms/FilePreview.tsx
/**
 * FilePreview Atom
 *
 * CSV data preview table showing first few rows.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Zero state
 * - No domain logic
 * - Props-only API
 * - Uses design tokens
 *
 * @module features/metadata-edit/ui/atoms/FilePreview
 */

import React from 'react';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';

export interface FilePreviewProps {
  /** Column headers */
  headers: string[];
  /** Data rows */
  rows: Record<string, string>[];
  /** Maximum number of columns to display (default: 5) */
  maxColumns?: number;
  /** Maximum number of rows to display (default: 3) */
  maxRows?: number;
  /** Contextual styles from parent */
  cx?: ContextualClassNames;
  /** Field mode flag */
  fieldMode?: boolean;
}

export const FilePreview: React.FC<FilePreviewProps> = ({
  headers,
  rows,
  maxColumns = 5,
  maxRows = 3,
}) => {
  const displayHeaders = headers.slice(0, maxColumns);
  const displayRows = rows.slice(0, maxRows);
  const hasMoreColumns = headers.length > maxColumns;
  const hasMoreRows = rows.length > maxRows;

  return (
    <div className="overflow-x-auto border border-nb-black/20 ">
      <table className="min-w-full text-sm">
        <thead className="bg-nb-white border-b border-nb-black/20">
          <tr>
            {displayHeaders.map((header) => (
              <th
                key={header}
                className="px-3 py-2 text-left font-medium text-nb-black/80"
              >
                {header}
              </th>
            ))}
            {hasMoreColumns && (
              <th className="px-3 py-2 text-left font-medium text-nb-black/50">
                +{headers.length - maxColumns} more
              </th>
            )}
          </tr>
        </thead>
        <tbody>
          {displayRows.map((row, rowIndex) => (
            <tr
              key={rowIndex}
              className="border-b border-nb-black/10 last:border-0"
            >
              {displayHeaders.map((header) => (
                <td
                  key={header}
                  className="px-3 py-2 text-nb-black/60 truncate max-w-xs"
                >
                  {row[header] || '-'}
                </td>
              ))}
              {hasMoreColumns && (
                <td className="px-3 py-2 text-nb-black/40">...</td>
              )}
            </tr>
          ))}
          {hasMoreRows && (
            <tr className="border-b border-nb-black/10 last:border-0">
              <td
                colSpan={displayHeaders.length + (hasMoreColumns ? 1 : 0)}
                className="px-3 py-2 text-nb-black/40 italic text-center"
              >
                +{rows.length - maxRows} more rows
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
};

export default FilePreview;
