// src/features/metadata-edit/ui/atoms/FileDropZone.svelte
<!--
  FileDropZone — Drag-and-drop file upload zone with loading state.
  React source: src/features/metadata-edit/ui/atoms/FileDropZone.tsx
  Architecture: Atom (internal isDragging state, props-driven, Rule 5.D: cx + fieldMode)
-->
<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import { cn } from '@/src/shared/lib/cn';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';

  interface Props {
    isLoading?: boolean;
    accept?: string;
    onFileSelect: (file: File) => void;
    buttonLabel?: string;
    loadingLabel?: string;
    cx?: Partial<ContextualClassNames>;
    fieldMode?: boolean;
  }

  let {
    isLoading = false,
    accept = '.csv,text/csv',
    onFileSelect,
    buttonLabel = 'Choose File',
    loadingLabel = 'Processing...',
    cx = {},
    fieldMode = false,
  }: Props = $props();

  let isDragging = $state(false);
  let fileInputRef: HTMLInputElement | undefined = $state();

  function handleDragOver(e: DragEvent) {
    e.preventDefault();
    e.stopPropagation();
    isDragging = true;
  }

  function handleDragLeave(e: DragEvent) {
    e.preventDefault();
    e.stopPropagation();
    isDragging = false;
  }

  function handleDrop(e: DragEvent) {
    e.preventDefault();
    e.stopPropagation();
    isDragging = false;

    const file = e.dataTransfer?.files[0];
    if (file) {
      onFileSelect(file);
    }
  }

  function handleFileChange(e: Event) {
    const target = e.target as HTMLInputElement;
    const file = target.files?.[0];
    if (file) {
      onFileSelect(file);
    }
    // Reset input so the same file can be selected again
    target.value = '';
  }

  function handleClick() {
    if (!isLoading) {
      fileInputRef?.click();
    }
  }

  let zoneClass = $derived(
    cn(
      'flex flex-col items-center justify-center gap-3 p-8 border-2 border-dashed cursor-pointer transition-colors',
      isDragging && !isLoading && (fieldMode
        ? 'border-nb-yellow bg-nb-yellow/10'
        : 'border-nb-blue bg-nb-blue/5'),
      !isDragging && !isLoading && (fieldMode
        ? 'border-nb-yellow/40 hover:border-nb-yellow hover:bg-nb-yellow/5'
        : cx.border ? `border-${cx.border}/40` : 'border-nb-black/30 hover:border-nb-black hover:bg-nb-cream/50'),
      isLoading && 'cursor-wait opacity-70',
      fieldMode ? 'bg-nb-black' : ''
    )
  );
</script>

<button
  type="button"
  class={zoneClass}
  ondragover={handleDragOver}
  ondragleave={handleDragLeave}
  ondrop={handleDrop}
  onclick={handleClick}
>
  {#if isLoading}
    <span class="animate-spin">
      <Icon name="refresh" class={cn('text-3xl', fieldMode ? 'text-nb-yellow' : cx.accent ?? 'text-nb-blue')} />
    </span>
    <p class={cn('text-sm font-mono', fieldMode ? 'text-nb-yellow' : cx.text ?? 'text-nb-black')}>
      {loadingLabel}
    </p>
  {:else}
    <Icon
      name={isDragging ? 'file_download' : 'upload_file'}
      class={cn('text-3xl', fieldMode ? 'text-nb-yellow/60' : cx.textMuted ?? 'text-nb-black/40')}
    />
    <p class={cn('text-sm', fieldMode ? 'text-nb-yellow' : cx.text ?? 'text-nb-black')}>
      Drag & drop a file here, or
      <span class={cn('font-bold underline', fieldMode ? 'text-nb-yellow' : cx.accent ?? 'text-nb-blue')}>
        {buttonLabel}
      </span>
    </p>
    <p class={cn('text-xs font-mono', fieldMode ? 'text-nb-yellow/50' : cx.textMuted ?? 'text-nb-black/40')}>
      Accepted: {accept}
    </p>
  {/if}
</button>

<input
  bind:this={fileInputRef}
  type="file"
  {accept}
  onchange={handleFileChange}
  class="hidden"
  tabindex="-1"
/>

// src/features/metadata-edit/ui/atoms/FileDropZone.tsx
/**
 * FileDropZone Atom
 *
 * Drag-and-drop file upload area with validation state.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Minimal local UI state (drag state only)
 * - No domain logic
 * - Props-only API
 * - Uses design tokens
 *
 * @module features/metadata-edit/ui/atoms/FileDropZone
 */

import React, { useCallback, useState } from 'react';
import { Icon } from '@/src/shared/ui/atoms';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';

export interface FileDropZoneProps {
  /** Whether file processing is in progress */
  isLoading?: boolean;
  /** Accepted file types (MIME types or extensions) */
  accept?: string;
  /** Called when a file is selected */
  onFileSelect: (file: File) => void;
  /** Optional label text (defaults to "Choose File") */
  buttonLabel?: string;
  /** Optional loading text (defaults to "Processing...") */
  loadingLabel?: string;
  /** Contextual styles from parent */
  cx?: ContextualClassNames;
  /** Field mode flag */
  fieldMode?: boolean;
}

export const FileDropZone: React.FC<FileDropZoneProps> = ({
  isLoading = false,
  accept = '.csv,text/csv',
  onFileSelect,
  buttonLabel = 'Choose File',
  loadingLabel = 'Processing...',
}) => {
  const [isDragging, setIsDragging] = useState(false);

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
  }, []);

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      setIsDragging(false);
      const file = e.dataTransfer.files?.[0];
      if (file) {
        onFileSelect(file);
      }
    },
    [onFileSelect]
  );

  const handleFileChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0];
      if (file) {
        onFileSelect(file);
      }
    },
    [onFileSelect]
  );

  const dropZoneClasses = isDragging
    ? 'bg-nb-blue/20 border-nb-blue'
    : 'bg-nb-blue/10 border-transparent';

  return (
    <div
      className={`flex flex-col items-center justify-center py-12 px-6 border-2 border-dashed transition-nb ${dropZoneClasses}`}
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
    >
      <div className="w-24 h-24 bg-nb-white flex items-center justify-center mb-6 shadow-brutal-sm">
        <Icon name="cloud_upload" className="text-4xl text-nb-blue" />
      </div>
      <h3 className="text-lg font-semibold text-nb-black mb-2">
        Upload CSV File
      </h3>
      <p className="text-sm text-nb-black/50 text-center max-w-md mb-6">
        Drag and drop a CSV file here, or click to select. The first row should
        contain column headers.
      </p>
      <label className="relative cursor-pointer">
        <input
          type="file"
          accept={accept}
          onChange={handleFileChange}
          disabled={isLoading}
          className="sr-only"
        />
        <span
          className={`px-6 py-3 font-medium inline-flex items-center gap-2 transition-nb ${
            isLoading
              ? 'bg-nb-cream text-nb-black/50 cursor-not-allowed'
              : 'bg-nb-blue text-white hover:bg-nb-blue'
          }`}
        >
          {isLoading ? (
            <>
              <Icon name="hourglass_empty" className="animate-spin" />
              {loadingLabel}
            </>
          ) : (
            <>
              <Icon name="file_upload" />
              {buttonLabel}
            </>
          )}
        </span>
      </label>
    </div>
  );
};

export default FileDropZone;
