// src/features/metadata-edit/ui/atoms/LanguageTag.tsx
/**
 * LanguageTag Atom
 *
 * Language code badge/selector for metadata mappings.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Zero state
 * - No domain logic
 * - Props-only API
 * - Uses design tokens
 *
 * @module features/metadata-edit/ui/atoms/LanguageTag
 */

import React from 'react';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';
export interface LanguageOption {
  code: string;
  label: string;
}

export interface LanguageTagProps {
  /** Available language options */
  languages: LanguageOption[];
  /** Currently selected language code */
  value: string;
  /** Called when language changes */
  onChange: (code: string) => void;
  /** Whether the selector is disabled */
  disabled?: boolean;
  /** Contextual class names for theming */
  cx?: Partial<ContextualClassNames>;
  /** Field mode styling */
  fieldMode?: boolean;
}

export const LanguageTag: React.FC<LanguageTagProps> = ({
  languages,
  value,
  onChange,
  disabled = false,
  cx,
}) => {
  const inputBg = cx?.input ?? 'bg-nb-white text-nb-black/80 border-nb-black/20';
  const disabledBg = cx?.surface ?? 'bg-nb-cream';

  return (
    <select
      value={value}
      onChange={(e) => onChange(e.target.value)}
      disabled={disabled}
      className={`w-full px-2 py-1.5 text-sm border focus:ring-2 focus:ring-nb-blue focus:border-nb-blue outline-none ${inputBg} ${
        disabled ? `opacity-50 cursor-not-allowed ${disabledBg}` : ''
      }`}
    >
      {languages.map((lang) => (
        <option key={lang.code} value={lang.code}>
          {lang.label}
        </option>
      ))}
    </select>
  );
};

export default LanguageTag;

// src/features/metadata-edit/ui/atoms/LanguageTag.svelte
<!--
  LanguageTag — Language code selector for metadata mappings.
  React source: src/features/metadata-edit/ui/atoms/LanguageTag.tsx (65 lines)
  Architecture: Atom (zero state, props-only, Rule 5.D: cx + fieldMode)
-->
<script module lang="ts">
  // Static types
  export interface LanguageOption { code: string; label: string; }
</script>

<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import { cn } from '@/src/shared/lib/cn';

  interface Props {
    languages: LanguageOption[];
    value: string;
    onchange: (code: string) => void;
    disabled?: boolean;
    cx?: Partial<ContextualClassNames>;
    fieldMode?: boolean;
  }

  let { languages, value, onchange, disabled = false, cx = {}, fieldMode = false }: Props = $props();
</script>

<select
  {value}
  onchange={(e) => onchange(e.currentTarget.value)}
  {disabled}
  class={cn(
    'w-full px-2 py-1.5 text-sm border outline-none focus:ring-2 focus:ring-nb-blue focus:border-nb-blue',
    fieldMode
      ? 'bg-nb-black text-nb-yellow border-nb-yellow/30 focus:ring-nb-yellow focus:border-nb-yellow'
      : cx.input ?? 'bg-nb-white text-nb-black/80 border-nb-black/20',
    disabled && 'opacity-50 cursor-not-allowed'
  )}
>
  {#each languages as lang (lang.code)}
    <option value={lang.code}>{lang.label}</option>
  {/each}
</select>
