// src/features/metadata-edit/ui/atoms/PropertyInput.tsx
/**
 * PropertyInput Atom
 *
 * Input field for metadata property values with optional label and location picker.
 * Thin wrapper around shared FormInput molecule.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Zero state
 * - No domain logic
 * - Props-only API
 * - Uses shared FormInput
 *
 * @module features/metadata-edit/ui/atoms/PropertyInput
 */

import React from 'react';
import { FormInput } from '@/src/shared/ui/molecules';
import { LocationPicker } from '../atoms/LocationPicker';
import type { ContextualClassNames } from '@/hooks/useContextualStyles';

export interface PropertyInputProps {
  /** Current input value */
  value: string;
  /** Called when value changes */
  onChange: (value: string) => void;
  /** Input label (optional) */
  label?: string;
  /** Input placeholder */
  placeholder?: string;
  /** Input type (default 'text') */
  type?: 'text' | 'textarea' | 'datetime-local';
  /** Whether this field is a location field (shows location picker button) */
  isLocationField?: boolean;
  /** Called when location picker button is clicked */
  onLocationPick?: () => void;
  /** Whether the input is disabled */
  disabled?: boolean;
  /** Contextual styles from parent */
  cx?: ContextualClassNames;
  /** Field mode flag */
  fieldMode?: boolean;
}

export const PropertyInput: React.FC<PropertyInputProps> = ({
  value,
  onChange,
  label,
  placeholder = '',
  type = 'text',
  isLocationField = false,
  onLocationPick,
  disabled = false,
  cx,
  fieldMode = false,
}) => {
  // Create location picker action button if needed
  const actionButton = isLocationField && onLocationPick ? (
    <LocationPicker
      onClick={onLocationPick}
      disabled={disabled}
      cx={cx}
      fieldMode={fieldMode}
      title="Pick Location on Map"
    />
  ) : undefined;

  return (
    <FormInput
      value={value}
      onChange={onChange}
      type={type}
      label={label}
      placeholder={placeholder}
      disabled={disabled}
      fieldMode={fieldMode}
      actionButton={actionButton}
    />
  );
};

export default PropertyInput;

// src/features/metadata-edit/ui/atoms/PropertyInput.svelte
<!--
  PropertyInput — Input field for metadata property values with optional location picker.
  React source: src/features/metadata-edit/ui/atoms/PropertyInput.tsx (84 lines)
  Architecture: Atom (zero state, props-only, Rule 5.D: cx + fieldMode)
-->
<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import FormInput from '@/src/shared/ui/molecules/FormInput.svelte';
  import LocationPicker from './LocationPicker.svelte';

  interface Props {
    value: string;
    onchange: (value: string) => void;
    label?: string;
    placeholder?: string;
    type?: 'text' | 'textarea' | 'datetime-local' | 'url';
    isLocationField?: boolean;
    onLocationPick?: () => void;
    disabled?: boolean;
    cx?: Partial<ContextualClassNames>;
    fieldMode?: boolean;
  }

  let {
    value,
    onchange,
    label,
    placeholder = '',
    type = 'text',
    isLocationField = false,
    onLocationPick,
    disabled = false,
    cx = {},
    fieldMode = false,
  }: Props = $props();
</script>

<FormInput
  {value}
  oninput={onchange}
  {type}
  {label}
  {placeholder}
  {disabled}
  cx={cx as import('@/src/shared/lib/contextual-styles').ContextualClassNames}
>
  {#snippet action()}
    {#if isLocationField && onLocationPick}
      <LocationPicker
        onclick={onLocationPick}
        {disabled}
        {cx}
        {fieldMode}
        title="Pick Location on Map"
      />
    {/if}
  {/snippet}
</FormInput>
