// src/features/metadata-edit/ui/atoms/PropertyLabel.tsx
/**
 * PropertyLabel Atom
 *
 * Field label with optional Dublin Core hint badge.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Zero state
 * - No domain logic
 * - Props-only API
 * - Uses design tokens
 *
 * @module features/metadata-edit/ui/atoms/PropertyLabel
 */

import React from 'react';
import { ValidationDot } from './ValidationDot';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';

export interface PropertyLabelProps {
  /** Label text */
  label: string;
  /** Optional Dublin Core mapping (e.g., 'dc:title') */
  dcHint?: string;
  /** Whether the label is in field mode */
  fieldMode?: boolean;
  /** Contextual styles from parent */
  cx?: ContextualClassNames;
  /** Additional CSS class */
  className?: string;
  /** Whether to show the DC hint badge */
  showHint?: boolean;
  /** Optional help text (tooltip or inline) */
  helpText?: string;
  /** Optional validation state for inline indicator */
  validation?: { status: 'pristine' | 'invalid'; message?: string };
}

export const PropertyLabel: React.FC<PropertyLabelProps> = ({
  label,
  dcHint,
  fieldMode = false,
  cx,
  className = '',
  showHint = true,
  validation,
}) => {
  const baseClass = `block text-xs font-bold ${fieldMode ? 'text-nb-black/30' : 'text-nb-black/80'} ${className}`;

  return (
    <div className="flex justify-between items-center">
      <span className={`flex items-center gap-1 ${baseClass}`}>
        {label}
        {validation && (
          <ValidationDot status={validation.status} message={validation.message} />
        )}
      </span>
      {showHint && dcHint && (
        <span
          className={`text-[9px] font-mono px-1 ${
            fieldMode ? 'bg-nb-black text-nb-black/50' : 'bg-nb-white text-nb-black/40'
          }`}
          title="Dublin Core Mapping"
        >
          {dcHint}
        </span>
      )}
    </div>
  );
};

export default PropertyLabel;

// src/features/metadata-edit/ui/atoms/PropertyLabel.svelte
<!--
  PropertyLabel — Label with optional Dublin Core hint badge and ValidationDot.
  React source: src/features/metadata-edit/ui/atoms/PropertyLabel.tsx (71 lines)
  Architecture: Atom (zero state, props-only, Rule 5.D: cx + fieldMode)
-->
<script module lang="ts">
  export interface ValidationState {
    status: 'pristine' | 'invalid';
    message?: string;
  }
</script>

<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import { cn } from '@/src/shared/lib/cn';
  import ValidationDot from './ValidationDot.svelte';

  interface Props {
    label: string;
    dcHint?: string;
    fieldMode?: boolean;
    cx?: Partial<ContextualClassNames>;
    class?: string;
    showHint?: boolean;
    validation?: ValidationState;
  }

  let {
    label,
    dcHint,
    fieldMode = false,
    cx = {},
    class: className = '',
    showHint = true,
    validation,
  }: Props = $props();

  let labelClasses = $derived(
    cn(
      'block text-xs font-bold',
      fieldMode ? 'text-nb-black/30' : cx.label ?? 'text-nb-black/80',
      className
    )
  );

  let hintClasses = $derived(
    cn(
      'text-[9px] font-mono px-1',
      fieldMode
        ? 'bg-nb-black text-nb-black/50'
        : 'bg-nb-white text-nb-black/40'
    )
  );
</script>

<div class="flex justify-between items-center">
  <span class={cn('flex items-center gap-1', labelClasses)}>
    {label}
    {#if validation}
      <ValidationDot status={validation.status} message={validation.message} />
    {/if}
  </span>
  {#if showHint && dcHint}
    <span class={hintClasses} title="Dublin Core Mapping">
      {dcHint}
    </span>
  {/if}
</div>
