// src/features/metadata-edit/ui/atoms/PropertySelector.tsx
/**
 * PropertySelector Atom
 *
 * Dropdown for selecting IIIF properties grouped by category.
 * Thin wrapper around shared SelectField molecule.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Zero state
 * - No domain logic
 * - Props-only API
 * - Uses shared SelectField
 *
 * @module features/metadata-edit/ui/atoms/PropertySelector
 */

import React, { useMemo } from 'react';
import { SelectField, type SelectOptionGroup } from '@/src/shared/ui/molecules';
import type { ContextualClassNames } from '@/hooks/useContextualStyles';

export interface PropertyOption {
  value: string;
  label: string;
  description?: string;
  category: string;
}

export interface PropertySelectorProps {
  /** Available properties grouped by category */
  propertiesByCategory: Record<string, PropertyOption[]>;
  /** Currently selected property value */
  value: string;
  /** Called when selection changes */
  onChange: (property: string) => void;
  /** Placeholder text for empty selection */
  placeholder?: string;
  /** Whether the selector is disabled */
  disabled?: boolean;
  /** Contextual styles from parent */
  cx?: ContextualClassNames;
  /** Field mode flag */
  fieldMode?: boolean;
}

export const PropertySelector: React.FC<PropertySelectorProps> = ({
  propertiesByCategory,
  value,
  onChange,
  placeholder = '(Skip this column)',
  disabled = false,
  fieldMode = false,
}) => {
  // Convert propertiesByCategory to SelectOptionGroup format
  const groups: SelectOptionGroup[] = useMemo(() => {
    return Object.entries(propertiesByCategory).map(([category, props]) => ({
      label: category,
      options: props.map(p => ({
        value: p.value,
        label: p.label,
        description: p.description,
      })),
    }));
  }, [propertiesByCategory]);

  return (
    <SelectField
      value={value}
      onChange={onChange}
      groups={groups}
      placeholder={placeholder}
      disabled={disabled}
      fieldMode={fieldMode}
    />
  );
};

export default PropertySelector;

// src/features/metadata-edit/ui/atoms/PropertySelector.svelte
<!--
  PropertySelector — Grouped property dropdown for IIIF metadata columns.
  React source: src/features/metadata-edit/ui/atoms/PropertySelector.tsx (77 lines)
  Architecture: Atom (zero state, props-only, Rule 5.D: cx + fieldMode)
-->
<script module lang="ts">
  export interface PropertyOption {
    value: string;
    label: string;
    description?: string;
    category: string;
  }
</script>

<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import SelectField from '@/src/shared/ui/molecules/SelectField.svelte';

  interface SelectOptionGroup {
    label: string;
    options: { value: string; label: string }[];
  }

  interface Props {
    propertiesByCategory: Record<string, PropertyOption[]>;
    value: string;
    onchange: (property: string) => void;
    placeholder?: string;
    disabled?: boolean;
    cx?: Partial<ContextualClassNames>;
    fieldMode?: boolean;
  }

  let {
    propertiesByCategory,
    value,
    onchange,
    placeholder = '(Skip this column)',
    disabled = false,
    cx = {},
    fieldMode = false,
  }: Props = $props();

  let groups: SelectOptionGroup[] = $derived(
    Object.entries(propertiesByCategory).map(([category, props]) => ({
      label: category,
      options: props.map(p => ({
        value: p.value,
        label: p.label,
      })),
    }))
  );
</script>

<SelectField
  {value}
  {onchange}
  {groups}
  {disabled}
  cx={cx as import('@/src/shared/lib/contextual-styles').ContextualClassNames}
/>
