// src/features/metadata-edit/ui/atoms/RightsSelector.svelte
<!--
  RightsSelector — SelectField wrapper for IIIF rights statement selection.
  React source: src/features/metadata-edit/ui/atoms/RightsSelector.tsx (67 lines)
  Architecture: Atom (zero state, props-only, Rule 5.D: cx + fieldMode)
-->
<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import SelectField from '@/src/shared/ui/molecules/SelectField.svelte';
  import { RIGHTS_OPTIONS } from '@/src/shared/constants/metadata';

  interface Props {
    value: string;
    onchange: (value: string) => void;
    placeholder?: string;
    disabled?: boolean;
    cx?: Partial<ContextualClassNames>;
    fieldMode?: boolean;
    label?: string;
    showLabel?: boolean;
  }

  let {
    value,
    onchange,
    placeholder = '(None Selected)',
    disabled = false,
    cx = {},
    fieldMode = false,
    label = 'Rights Statement',
    showLabel = true,
  }: Props = $props();

  // RIGHTS_OPTIONS is const-asserted; cast to mutable for SelectField options prop
  const options = RIGHTS_OPTIONS.map(o => ({ value: o.value, label: o.label }));
</script>

<SelectField
  {value}
  {options}
  label={showLabel ? label : undefined}
  hint="dc:rights"
  {disabled}
  {onchange}
  cx={cx as ContextualClassNames}
/>

// src/features/metadata-edit/ui/atoms/RightsSelector.tsx
/**
 * RightsSelector Atom
 *
 * Dropdown for selecting a rights statement.
 * Thin wrapper around shared SelectField molecule.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Zero state
 * - No domain logic
 * - Props-only API
 * - Uses shared SelectField
 *
 * @module features/metadata-edit/ui/atoms/RightsSelector
 */

import React from 'react';
import { SelectField } from '@/src/shared/ui/molecules';
import { RIGHTS_OPTIONS } from '@/src/shared/constants/metadata';
import type { ContextualClassNames } from '@/hooks/useContextualStyles';

export interface RightsSelectorProps {
  /** Currently selected rights statement (URL) */
  value: string;
  /** Called when selection changes */
  onChange: (value: string) => void;
  /** Placeholder text for empty selection */
  placeholder?: string;
  /** Whether the selector is disabled */
  disabled?: boolean;
  /** Contextual styles from parent */
  cx?: ContextualClassNames;
  /** Field mode flag */
  fieldMode?: boolean;
  /** Label for the selector */
  label?: string;
  /** Whether to show label */
  showLabel?: boolean;
}

export const RightsSelector: React.FC<RightsSelectorProps> = ({
  value,
  onChange,
  placeholder = '(None Selected)',
  disabled = false,
  fieldMode = false,
  label = 'Rights Statement',
  showLabel = true,
}) => {
  return (
    <SelectField
      value={value}
      onChange={onChange}
      options={RIGHTS_OPTIONS}
      placeholder={placeholder}
      disabled={disabled}
      fieldMode={fieldMode}
      label={label}
      showLabel={showLabel}
      hint="dc:rights"
    />
  );
};

export default RightsSelector;
