// src/features/metadata-edit/ui/molecules/LocationPickerModal.svelte
<!--
  LocationPickerModal -- Modal for picking GPS coordinates on a map.
  React source: src/features/metadata-edit/ui/molecules/LocationPickerModal.tsx (121 lines)
  Architecture: Molecule (composes ModalDialog + Button, Leaflet side-effects in $effect)
-->
<script module lang="ts">
  // Leaflet is loaded globally via CDN
  declare const L: any; // eslint-disable-line @typescript-eslint/no-explicit-any

  const TILE_LAYER = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
  const TILE_ATTRIBUTION = '&copy; OpenStreetMap contributors';
</script>

<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import { cn } from '@/src/shared/lib/cn';
  import Button from '@/src/shared/ui/atoms/Button.svelte';
  import ModalDialog from '@/src/shared/ui/molecules/ModalDialog.svelte';

  interface Props {
    isOpen: boolean;
    initialValue: string;
    onSave: (val: string) => void;
    onClose: () => void;
  }

  let {
    isOpen = $bindable(),
    initialValue,
    onSave,
    onClose,
  }: Props = $props();

  let coords = $state<{ lat: number; lng: number } | null>(null);
  let mapEl: HTMLDivElement | undefined = $state();

  // Minimal cx for ModalDialog (LocationPickerModal has no fieldMode prop)
  const modalCx: ContextualClassNames = {
    surface: 'bg-nb-white border-2 border-nb-black',
    text: 'text-nb-black',
    accent: 'text-nb-green',
  };

  /* eslint-disable @field-studio/lifecycle-restrictions -- Leaflet map init (external library, arch guide §7.A) */
  $effect(() => {
    if (!isOpen) return;

    // Parse initial value for lat/lng
    const match = initialValue.match(/(-?\d+\.?\d*)\s*[,\s]\s*(-?\d+\.?\d*)/);
    let initLat = 20;
    let initLng = 0;
    let zoom = 2;

    if (match) {
      initLat = parseFloat(match[1]);
      initLng = parseFloat(match[2]);
      zoom = 10;
      coords = { lat: initLat, lng: initLng };
    }

    if (!mapEl || typeof L === 'undefined') return;

    const map = L.map(mapEl).setView([initLat, initLng], zoom);
    L.tileLayer(TILE_LAYER, { attribution: TILE_ATTRIBUTION }).addTo(map);

    const marker = L.marker([initLat, initLng], { draggable: true }).addTo(map);

    if (!match) map.locate({ setView: true, maxZoom: 10 });

    map.on('click', (e: { latlng: { lat: number; lng: number } }) => {
      marker.setLatLng(e.latlng);
      coords = e.latlng;
    });

    marker.on('dragend', () => {
      coords = marker.getLatLng();
    });

    return () => {
      map.remove();
    };
  });
  /* eslint-enable @field-studio/lifecycle-restrictions */

  function handleConfirm() {
    if (coords) {
      onSave(`${coords.lat.toFixed(6)}, ${coords.lng.toFixed(6)}`);
    }
  }
</script>

<ModalDialog
  bind:open={isOpen}
  title="Pick Location"
  size="lg"
  onClose={onClose}
  cx={modalCx}
>
  {#snippet children()}
    <div class="relative bg-nb-cream" style="height: 400px">
      <div bind:this={mapEl} class="absolute inset-0"></div>
    </div>
  {/snippet}

  {#snippet footer()}
    <div class="flex justify-between items-center">
      <div class={cn(
        'text-xs font-mono bg-nb-cream px-3 py-1.5 border',
        'border-nb-black/20'
      )}>
        {coords
          ? `${coords.lat.toFixed(6)}, ${coords.lng.toFixed(6)}`
          : 'Click map to select'}
      </div>
      <Button
        onclick={handleConfirm}
        variant="success"
        size="sm"
        disabled={!coords}
      >
        {#snippet children()}Confirm Location{/snippet}
      </Button>
    </div>
  {/snippet}
</ModalDialog>

// src/features/metadata-edit/ui/molecules/LocationPickerModal.tsx
/**
 * LocationPickerModal Molecule
 *
 * Modal for picking GPS coordinates on a map.
 * Uses shared ModalDialog with map interaction content.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Manages map state and coordinate selection
 * - Encapsulates Leaflet side effects
 * - Props-only API (initialValue, onSave, onClose)
 * - Uses shared ModalDialog and primitives
 *
 * @module features/metadata-edit/ui/molecules/LocationPickerModal
 */

import React, { useEffect, useRef, useState } from 'react';
import { Button } from '@/src/shared/ui/atoms';
import { ModalDialog } from '@/src/shared/ui/molecules/ModalDialog';
import { DEFAULT_MAP_CONFIG } from '@/src/shared/constants';

declare const L: any;

export interface LocationPickerModalProps {
  /** Whether the modal is open */
  isOpen: boolean;
  /** Initial coordinate string (e.g., "12.345, -67.890") */
  initialValue: string;
  /** Called with selected coordinate string */
  onSave: (val: string) => void;
  /** Called when modal should close */
  onClose: () => void;
}

export const LocationPickerModal: React.FC<LocationPickerModalProps> = ({
  isOpen,
  initialValue,
  onSave,
  onClose,
}) => {
  const mapRef = useRef<HTMLDivElement>(null);
  const [coords, setCoords] = useState<{ lat: number; lng: number } | null>(null);

  useEffect(() => {
    if (!isOpen) return;

    // Parse initial value
    const match = initialValue.match(/(-?\d+\.?\d*)\s*[,\s]\s*(-?\d+\.?\d*)/);
    let initLat = 20,
      initLng = 0,
      zoom = 2;

    if (match) {
      initLat = parseFloat(match[1]);
      initLng = parseFloat(match[2]);
      zoom = 10;
      setCoords({ lat: initLat, lng: initLng });
    }

    if (mapRef.current && typeof L !== 'undefined') {
      const map = L.map(mapRef.current).setView([initLat, initLng], zoom);
      L.tileLayer(DEFAULT_MAP_CONFIG.tileLayer, {
        attribution: DEFAULT_MAP_CONFIG.attribution,
      }).addTo(map);

      const marker = L.marker([initLat, initLng], { draggable: true }).addTo(map);

      if (!match) map.locate({ setView: true, maxZoom: 10 });

      map.on('click', (e: { latlng: { lat: number; lng: number } }) => {
        marker.setLatLng(e.latlng);
        setCoords(e.latlng);
      });

      marker.on('dragend', () => {
        // eslint-disable-next-line @field-studio/useeffect-restrictions
        setCoords(marker.getLatLng());
      });

      return () => map.remove();
    }
  }, [isOpen, initialValue]);

  const footer = (
    <div className="flex justify-between items-center">
      <div className="text-xs font-mono bg-nb-cream px-3 py-1.5 border">
        {coords
          ? `${coords.lat.toFixed(6)}, ${coords.lng.toFixed(6)}`
          : 'Click map to select'}
      </div>
      <Button
        onClick={() => coords && onSave(`${coords.lat.toFixed(6)}, ${coords.lng.toFixed(6)}`)}
        variant="primary"
        size="sm"
        disabled={!coords}
        className="bg-nb-green hover:bg-nb-green"
      >
        Confirm Location
      </Button>
    </div>
  );

  return (
    <ModalDialog
      isOpen={isOpen}
      onClose={onClose}
      title="Pick Location"
      icon="location_on"
      iconColor="bg-nb-green/20 text-nb-green"
      size="md"
      height="500px"
      zIndex={2000}
      footer={footer}
    >
      <div className="relative bg-nb-cream h-full">
        <div ref={mapRef} className="absolute inset-0" />
      </div>
    </ModalDialog>
  );
};

export default LocationPickerModal;
