// src/features/metadata-edit/ui/molecules/StructureTabPanel.svelte
<!--
  StructureTabPanel -- Range/Structure Editor for IIIF Manifests.
  React source: src/features/metadata-edit/ui/molecules/StructureTabPanel.tsx (742 lines)
  Architecture: Molecule (internal state, composes RangeTreeItem atom + RangeEditModal molecule)

  Provides full CRUD operations for IIIF Ranges (Table of Contents):
  - Create, edit, delete ranges
  - Nested range hierarchy with tree UI
  - Assign canvases to ranges
  - Drag-drop reordering of range items

  Conforms to IIIF Presentation 3.0 structures specification.
-->
<script module lang="ts">
  import type {
    IIIFManifest,
    IIIFRange,
    IIIFRangeReference,
    IIIFCanvas,
  } from '@/src/shared/types';
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import type { AppSettings } from '@/src/shared/stores/appSettings.svelte';

  export interface StructureTabPanelProps {
    /** The manifest containing structures */
    manifest: IIIFManifest;
    /** Callback when structure is updated */
    onUpdateManifest: (updates: Partial<IIIFManifest>) => void;
    /** App settings for theming */
    settings: AppSettings;
    /** Contextual style classes (passed from Inspector) */
    cx: ContextualClassNames;
    /** Available canvases in the manifest */
    canvases: IIIFCanvas[];
  }
</script>

<script lang="ts">
  import { getIIIFValue } from '@/src/shared/types';
  import { cn } from '@/src/shared/lib/cn';
  import Button from '@/src/shared/ui/atoms/Button.svelte';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';
  import RangeTreeItem from '../atoms/RangeTreeItem.svelte';
  import RangeEditModal from './RangeEditModal.svelte';

  let {
    manifest,
    onUpdateManifest,
    settings,
    cx,
    canvases,
  }: StructureTabPanelProps = $props();

  let expandedRanges = $state(new Set<string>());
  let selectedRangeId = $state<string | null>(null);
  let modalOpen = $state(false);
  let editingRange = $state<IIIFRange | null>(null);
  let dragOverRangeId = $state<string | null>(null);
  let draggedRangeId = $state<string | null>(null);

  let structures = $derived(manifest.structures || []);

  // ---------- Helpers ----------

  /** Generate unique ID for new ranges */
  function generateRangeId(): string {
    return `${manifest.id}/range/${Date.now()}-${crypto.randomUUID().slice(0, 9)}`;
  }

  /** Toggle range expansion */
  function toggleExpand(rangeId: string) {
    const next = new Set(expandedRanges);
    if (next.has(rangeId)) {
      next.delete(rangeId);
    } else {
      next.add(rangeId);
    }
    expandedRanges = next;
  }

  /** Get canvas IDs from a range */
  function getCanvasIdsFromRange(range: IIIFRange): string[] {
    return (range.items || [])
      .filter((item): item is IIIFRangeReference =>
        typeof item !== 'string' && 'type' in item && item.type === 'Canvas'
      )
      .map(ref => ref.id);
  }

  /** Extract nested ranges from items */
  function getNestedRanges(items: IIIFRange['items'] | undefined): IIIFRange[] {
    return (items || []).filter((item): item is IIIFRange =>
      typeof item !== 'string' && 'type' in item && item.type === 'Range'
    );
  }

  /** Extract canvas refs from items */
  function getCanvasRefs(items: IIIFRange['items'] | undefined): IIIFRangeReference[] {
    return (items || []).filter((item): item is IIIFRangeReference =>
      typeof item !== 'string' && 'type' in item && item.type === 'Canvas'
    );
  }

  // ---------- CRUD ----------

  /** Create new range */
  function handleCreateRange(label: string, canvasIds: string[]) {
    const newRange: IIIFRange = {
      id: generateRangeId(),
      type: 'Range',
      label: { [settings.language]: [label] },
      items: canvasIds.map(id => ({ id, type: 'Canvas' as const })),
    };
    onUpdateManifest({ structures: [...structures, newRange] });
  }

  /** Update existing range (recursive in tree) */
  function handleUpdateRange(rangeId: string, label: string, canvasIds: string[]) {
    function updateRangeInList(ranges: IIIFRange[]): IIIFRange[] {
      return ranges.map(range => {
        if (range.id === rangeId) {
          const nestedRanges = getNestedRanges(range.items);
          const canvasRefs: IIIFRangeReference[] = canvasIds.map(id => ({ id, type: 'Canvas' as const }));
          return {
            ...range,
            label: { [settings.language]: [label] },
            items: [...canvasRefs, ...nestedRanges],
          };
        }
        if (range.items) {
          const nested = getNestedRanges(range.items);
          if (nested.length > 0) {
            const updatedNested = updateRangeInList(nested);
            const refs = getCanvasRefs(range.items);
            return { ...range, items: [...refs, ...updatedNested] };
          }
        }
        return range;
      });
    }

    onUpdateManifest({ structures: updateRangeInList(structures) });
    editingRange = null;
  }

  /** Delete range (recursive in tree) */
  function handleDeleteRange(rangeId: string) {
    function deleteRangeFromList(ranges: IIIFRange[]): IIIFRange[] {
      return ranges
        .filter(range => range.id !== rangeId)
        .map(range => {
          if (range.items) {
            const nested = getNestedRanges(range.items);
            if (nested.length > 0) {
              const updatedNested = deleteRangeFromList(nested);
              const refs = getCanvasRefs(range.items);
              return { ...range, items: [...refs, ...updatedNested] };
            }
          }
          return range;
        });
    }

    onUpdateManifest({ structures: deleteRangeFromList(structures) });
    if (selectedRangeId === rangeId) {
      selectedRangeId = null;
    }
  }

  /** Handle save from modal (create or update) */
  function handleModalSave(label: string, canvasIds: string[]) {
    if (editingRange) {
      handleUpdateRange(editingRange.id, label, canvasIds);
    } else {
      handleCreateRange(label, canvasIds);
    }
    modalOpen = false;
    editingRange = null;
  }

  // ---------- Drag and Drop ----------

  function handleDragStart(e: DragEvent, rangeId: string) {
    if (!e.dataTransfer) return;
    e.dataTransfer.effectAllowed = 'move';
    e.dataTransfer.setData('text/plain', rangeId);
    draggedRangeId = rangeId;
  }

  function handleDragOver(e: DragEvent, rangeId: string) {
    e.preventDefault();
    if (e.dataTransfer) e.dataTransfer.dropEffect = 'move';
    if (draggedRangeId !== rangeId) {
      dragOverRangeId = rangeId;
    }
  }

  function handleDrop(e: DragEvent, targetRangeId: string) {
    e.preventDefault();
    const sourceRangeId = e.dataTransfer?.getData('text/plain');

    if (!sourceRangeId || sourceRangeId === targetRangeId) {
      draggedRangeId = null;
      dragOverRangeId = null;
      return;
    }

    // Reorder top-level structures
    const sourceIndex = structures.findIndex(r => r.id === sourceRangeId);
    const targetIndex = structures.findIndex(r => r.id === targetRangeId);

    if (sourceIndex !== -1 && targetIndex !== -1) {
      const newStructures = [...structures];
      const [removed] = newStructures.splice(sourceIndex, 1);
      newStructures.splice(targetIndex, 0, removed);
      onUpdateManifest({ structures: newStructures });
    }

    draggedRangeId = null;
    dragOverRangeId = null;
  }

  function handleDragEnd() {
    draggedRangeId = null;
    dragOverRangeId = null;
  }

  // ---------- Supplementary AnnotationCollection ----------

  function handleSupplementaryChange(
    rangeId: string,
    supplementary: { id: string; type: 'AnnotationCollection' } | undefined
  ) {
    function updateSupplementaryInList(ranges: IIIFRange[]): IIIFRange[] {
      return ranges.map(range => {
        if (range.id === rangeId) {
          const updated = { ...range } as Record<string, unknown>;
          if (supplementary) {
            updated.supplementary = supplementary;
          } else {
            delete updated.supplementary;
          }
          return updated as unknown as IIIFRange;
        }
        if (range.items) {
          const nested = getNestedRanges(range.items);
          if (nested.length > 0) {
            const updatedNested = updateSupplementaryInList(nested);
            const refs = getCanvasRefs(range.items);
            return { ...range, items: [...refs, ...updatedNested] };
          }
        }
        return range;
      });
    }

    onUpdateManifest({ structures: updateSupplementaryInList(structures) });
  }

  // ---------- Modal helpers ----------

  function openCreateModal() {
    editingRange = null;
    modalOpen = true;
  }

  function openEditModal(range: IIIFRange) {
    editingRange = range;
    modalOpen = true;
  }

  function closeModal() {
    modalOpen = false;
    editingRange = null;
  }

  let modalInitialLabel = $derived(
    editingRange ? getIIIFValue(editingRange.label, settings.language) || '' : ''
  );

  let modalInitialCanvasIds = $derived(
    editingRange ? getCanvasIdsFromRange(editingRange) : []
  );
</script>

<div class="space-y-4">
  <!-- Info banner -->
  <div class={cn('p-3 border', cx.surface, cx.border)}>
    <div class="flex items-center justify-between">
      <div class="flex items-center gap-2">
        <Icon
          name="account_tree"
          class={cn('text-sm', settings.fieldMode ? 'text-nb-purple/60' : 'text-nb-purple')}
        />
        <span class={cn('text-xs font-bold uppercase', settings.fieldMode ? 'text-nb-purple/60' : 'text-nb-purple')}>
          Table of Contents
        </span>
      </div>
      <span class={cn('text-[10px]', cx.textMuted)}>
        {structures.length} {structures.length === 1 ? 'range' : 'ranges'}
      </span>
    </div>
    <p class={cn('text-[10px] mt-1', cx.textMuted)}>
      Define structural divisions like chapters, sections, or groups
    </p>
  </div>

  <!-- Add Range button -->
  <Button
    variant="ghost"
    size="bare"
    onclick={openCreateModal}
    class={cn(
      'w-full flex items-center justify-center gap-2 px-4 py-3 border-2 border-dashed',
      'text-xs font-bold uppercase transition-nb',
      settings.fieldMode
        ? 'border-nb-black/80 text-nb-black/40 hover:border-nb-yellow hover:text-nb-yellow hover:bg-nb-yellow/20'
        : 'border-nb-black/20 text-nb-black/50 hover:border-nb-blue hover:text-nb-blue hover:bg-nb-blue/10'
    )}
  >
    {#snippet children()}
      <Icon name="add" class="text-sm" />
      Add Range
    {/snippet}
  </Button>

  <!-- Range tree -->
  {#if structures.length > 0}
    <div class={cn(
      'border overflow-hidden',
      settings.fieldMode ? 'border-nb-black/80 bg-nb-black' : 'border-nb-black/20 bg-nb-white'
    )}>
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <div ondragend={handleDragEnd}>
        {#each structures as range (range.id)}
          {@const nestedRanges = getNestedRanges(range.items)}
          {@const isExpanded = expandedRanges.has(range.id)}
          <div class="group">
            <RangeTreeItem
              {range}
              depth={0}
              {isExpanded}
              onToggle={() => toggleExpand(range.id)}
              onSelect={() => { selectedRangeId = range.id === selectedRangeId ? null : range.id; }}
              isSelected={selectedRangeId === range.id}
              onEdit={() => openEditModal(range)}
              onDelete={() => handleDeleteRange(range.id)}
              onSupplementaryChange={handleSupplementaryChange}
              fieldMode={settings.fieldMode}
              language={settings.language}
              {canvases}
              onDragStart={(e) => handleDragStart(e, range.id)}
              onDragOver={(e) => handleDragOver(e, range.id)}
              onDrop={(e) => handleDrop(e, range.id)}
              isDragOver={dragOverRangeId === range.id}
            />
            {#if isExpanded && nestedRanges.length > 0}
              <!-- svelte-ignore a11y_no_static_element_interactions -->
              <div ondragend={handleDragEnd}>
                {#each nestedRanges as nested (nested.id)}
                  {@const nestedChildren = getNestedRanges(nested.items)}
                  {@const isNestedExpanded = expandedRanges.has(nested.id)}
                  <div class="group">
                    <RangeTreeItem
                      range={nested}
                      depth={1}
                      isExpanded={isNestedExpanded}
                      onToggle={() => toggleExpand(nested.id)}
                      onSelect={() => { selectedRangeId = nested.id === selectedRangeId ? null : nested.id; }}
                      isSelected={selectedRangeId === nested.id}
                      onEdit={() => openEditModal(nested)}
                      onDelete={() => handleDeleteRange(nested.id)}
                      onSupplementaryChange={handleSupplementaryChange}
                      fieldMode={settings.fieldMode}
                      language={settings.language}
                      {canvases}
                      onDragStart={(e) => handleDragStart(e, nested.id)}
                      onDragOver={(e) => handleDragOver(e, nested.id)}
                      onDrop={(e) => handleDrop(e, nested.id)}
                      isDragOver={dragOverRangeId === nested.id}
                    />
                    {#if isNestedExpanded && nestedChildren.length > 0}
                      <!-- svelte-ignore a11y_no_static_element_interactions -->
                      <div ondragend={handleDragEnd}>
                        {#each nestedChildren as deep (deep.id)}
                          <div class="group">
                            <RangeTreeItem
                              range={deep}
                              depth={2}
                              isExpanded={expandedRanges.has(deep.id)}
                              onToggle={() => toggleExpand(deep.id)}
                              onSelect={() => { selectedRangeId = deep.id === selectedRangeId ? null : deep.id; }}
                              isSelected={selectedRangeId === deep.id}
                              onEdit={() => openEditModal(deep)}
                              onDelete={() => handleDeleteRange(deep.id)}
                              onSupplementaryChange={handleSupplementaryChange}
                              fieldMode={settings.fieldMode}
                              language={settings.language}
                              {canvases}
                              onDragStart={(e) => handleDragStart(e, deep.id)}
                              onDragOver={(e) => handleDragOver(e, deep.id)}
                              onDrop={(e) => handleDrop(e, deep.id)}
                              isDragOver={dragOverRangeId === deep.id}
                            />
                          </div>
                        {/each}
                      </div>
                    {/if}
                  </div>
                {/each}
              </div>
            {/if}
          </div>
        {/each}
      </div>
    </div>
  {:else}
    <div class={cn('text-center py-8', cx.textMuted)}>
      <Icon name="segment" class="text-4xl mb-2 opacity-30" />
      <p class="text-sm">No structural ranges defined</p>
      <p class="text-[10px] mt-1">
        Add ranges to create a table of contents for navigation
      </p>
    </div>
  {/if}

  <!-- Edit/Create Modal -->
  <RangeEditModal
    isOpen={modalOpen}
    onClose={closeModal}
    onSave={handleModalSave}
    initialLabel={modalInitialLabel}
    initialCanvasIds={modalInitialCanvasIds}
    availableCanvases={canvases}
    isEditing={!!editingRange}
    fieldMode={settings.fieldMode}
    language={settings.language}
  />
</div>

// src/features/metadata-edit/ui/molecules/StructureTabPanel.tsx
/**
 * StructureTabPanel - Range/Structure Editor for IIIF Manifests
 *
 * Provides full CRUD operations for IIIF Ranges (Table of Contents):
 * - Create, edit, delete ranges
 * - Nested range hierarchy with tree UI
 * - Assign canvases to ranges
 * - Drag-drop reordering of range items
 *
 * Conforms to IIIF Presentation 3.0 structures specification.
 */

import React, { useCallback, useMemo, useState } from 'react';
import { Button } from '@/src/shared/ui/atoms';
import { EmptyState } from '@/src/shared/ui/molecules/EmptyState';
import {
  AppSettings,
  getIIIFValue,
  IIIFCanvas,
  IIIFManifest,
  IIIFRange,
  IIIFRangeReference,
  LanguageMap
} from '@/src/shared/types';
import { Icon } from '@/src/shared/ui/atoms/Icon';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';

interface StructureTabPanelProps {
  /** The manifest containing structures */
  manifest: IIIFManifest;
  /** Callback when structure is updated */
  onUpdateManifest: (updates: Partial<IIIFManifest>) => void;
  /** App settings for theming */
  settings: AppSettings;
  /** Contextual style classes (passed from Inspector) */
  cx: ContextualClassNames;
  /** Available canvases in the manifest */
  canvases: IIIFCanvas[];
}

type RangeItem = IIIFRangeReference | IIIFRange;

interface RangeTreeItemProps {
  range: IIIFRange;
  depth: number;
  isExpanded: boolean;
  onToggle: () => void;
  onSelect: () => void;
  isSelected: boolean;
  onEdit: () => void;
  onDelete: () => void;
  onSupplementaryChange?: (rangeId: string, supplementary: { id: string; type: 'AnnotationCollection' } | undefined) => void;
  fieldMode: boolean;
  language: string;
  canvases: IIIFCanvas[];
  onDragStart?: (e: React.DragEvent) => void;
  onDragOver?: (e: React.DragEvent) => void;
  onDrop?: (e: React.DragEvent) => void;
  isDragOver?: boolean;
}

/**
 * Single range item in the tree structure
 */
const RangeTreeItem: React.FC<RangeTreeItemProps> = ({
  range,
  depth,
  isExpanded,
  onToggle,
  onSelect,
  isSelected,
  onEdit,
  onDelete,
  onSupplementaryChange,
  fieldMode,
  language,
  canvases,
  onDragStart,
  onDragOver,
  onDrop,
  isDragOver,
}) => {
  const label = getIIIFValue(range.label, language) || 'Untitled Range';
  const hasChildren = range.items && range.items.length > 0;
  const nestedRanges = range.items?.filter((item): item is IIIFRange =>
    typeof item !== 'string' && 'type' in item && item.type === 'Range'
  ) || [];
  const canvasRefs = range.items?.filter((item): item is IIIFRangeReference =>
    typeof item !== 'string' && 'type' in item && item.type === 'Canvas'
  ) || [];

  return (
    <div
      draggable
      onDragStart={onDragStart}
      onDragOver={onDragOver}
      onDrop={onDrop}
      className={`
        transition-nb
        ${isDragOver ? (fieldMode ? 'bg-nb-yellow/20' : 'bg-nb-blue/20') : ''}
      `}
    >
      <div
        onClick={onSelect}
        className={`
          flex items-center gap-2 px-2 py-2  cursor-pointer transition-nb
          ${isSelected
            ? (fieldMode ? 'bg-nb-yellow/20' : 'bg-nb-blue/20')
            : (fieldMode ? 'hover:bg-nb-black' : 'hover:bg-nb-cream')
          }
        `}
        style={{ paddingLeft: `${depth * 16 + 8}px` }}
      >
        {/* Expand/Collapse toggle */}
        {hasChildren ? (
          <Button variant="ghost" size="bare"
            onClick={(e) => { e.stopPropagation(); onToggle(); }}
            className={`p-0.5 ${fieldMode ? 'hover:bg-nb-black/80' : 'hover:bg-nb-cream'}`}
          >
            <Icon
              name={isExpanded ? 'expand_more' : 'chevron_right'}
              className={`text-sm ${fieldMode ? 'text-nb-black/40' : 'text-nb-black/50'}`}
            />
          </Button>
        ) : (
          <div className="w-5" />
        )}

        {/* Range Icon */}
        <Icon
          name="segment"
          className={`text-sm ${fieldMode ? 'text-nb-purple/60' : 'text-nb-purple'}`}
        />

        {/* Label */}
        <span className={`flex-1 text-xs font-medium truncate ${fieldMode ? 'text-white' : 'text-nb-black'}`}>
          {label}
        </span>

        {/* Item counts */}
        <div className="flex items-center gap-1.5">
          {canvasRefs.length > 0 && (
            <span className={`text-[9px] px-1.5 py-0.5 ${
              fieldMode ? 'bg-nb-black text-nb-black/40' : 'bg-nb-cream text-nb-black/60'
            }`}>
              {canvasRefs.length} pages
            </span>
          )}
          {nestedRanges.length > 0 && (
            <span className={`text-[9px] px-1.5 py-0.5 ${
              fieldMode ? 'bg-nb-purple/50 text-nb-purple/40' : 'bg-nb-purple/10 text-nb-purple'
            }`}>
              {nestedRanges.length} sub
            </span>
          )}
        </div>

        {/* Actions */}
        <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-nb">
          <Button variant="ghost" size="bare"
            onClick={(e) => { e.stopPropagation(); onEdit(); }}
            className={`p-1 ${fieldMode ? 'hover:bg-nb-black/80 text-nb-black/40' : 'hover:bg-nb-cream text-nb-black/50'}`}
          >
            <Icon name="edit" className="text-[10px]" />
          </Button>
          <Button variant="ghost" size="bare"
            onClick={(e) => { e.stopPropagation(); onDelete(); }}
            className={`p-1 hover:bg-nb-red/20 text-nb-red hover:text-nb-red`}
          >
            <Icon name="delete" className="text-[10px]" />
          </Button>
        </div>
      </div>

      {/* Supplementary AnnotationCollection link (shown when selected) */}
      {isSelected && onSupplementaryChange && (
        <div
          className={`mx-2 mb-2 p-2 border text-xs ${
            fieldMode ? 'bg-nb-black border-nb-black' : 'bg-nb-white border-nb-black/20'
          }`}
          style={{ marginLeft: `${depth * 16 + 28}px` }}
          onClick={(e) => e.stopPropagation()}
        >
          <div className={`text-[9px] font-bold uppercase tracking-wider mb-1 ${
            fieldMode ? 'text-nb-black/50' : 'text-nb-black/40'
          }`}>
            <Icon name="library_books" className="text-[10px] mr-1 inline" />
            Supplementary Annotations
          </div>
          <div className="flex gap-2 items-center">
            <input
              type="url"
              value={(range as any).supplementary?.id || ''}
              onChange={(e) => {
                const val = e.target.value.trim();
                onSupplementaryChange(
                  range.id,
                  val ? { id: val, type: 'AnnotationCollection' } : undefined
                );
              }}
              placeholder="AnnotationCollection URI"
              className={`flex-1 text-xs px-2 py-1 border outline-none ${
                fieldMode
                  ? 'bg-nb-black border-nb-black/80 text-white placeholder-nb-black/60 focus:border-nb-yellow'
                  : 'bg-nb-white border-nb-black/20 placeholder-nb-black/40 focus:border-nb-blue'
              }`}
            />
            {(range as any).supplementary?.id && (
              <Button variant="ghost" size="bare"
                onClick={() => onSupplementaryChange(range.id, undefined)}
                className="text-nb-red hover:text-nb-red p-0.5"
              >
                <Icon name="close" className="text-xs" />
              </Button>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

/**
 * Modal for creating/editing a range
 */
interface RangeEditModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (label: string, selectedCanvasIds: string[]) => void;
  initialLabel?: string;
  initialCanvasIds?: string[];
  availableCanvases: IIIFCanvas[];
  isEditing: boolean;
  fieldMode: boolean;
  language: string;
}

const RangeEditModal: React.FC<RangeEditModalProps> = ({
  isOpen,
  onClose,
  onSave,
  initialLabel = '',
  initialCanvasIds = [],
  availableCanvases,
  isEditing,
  fieldMode,
  language,
}) => {
  const [label, setLabel] = useState(initialLabel);
  const [selectedCanvasIds, setSelectedCanvasIds] = useState<Set<string>>(new Set(initialCanvasIds));

  const toggleCanvas = (id: string) => {
    setSelectedCanvasIds(prev => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  const handleSave = () => {
    if (!label.trim()) return;
    onSave(label.trim(), Array.from(selectedCanvasIds));
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[1200] flex items-center justify-center p-4">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-nb-black/50"
        onClick={onClose}
      />

      {/* Modal */}
      <div className={`
        relative w-full max-w-lg max-h-[80vh] overflow-hidden  shadow-brutal-lg
        ${fieldMode ? 'bg-nb-black border border-nb-black/80' : 'bg-nb-white'}
      `}>
        {/* Header */}
        <div className={`
          flex items-center justify-between px-4 py-3 border-b
          ${fieldMode ? 'border-nb-black/80' : 'border-nb-black/20'}
        `}>
          <h3 className={`font-bold ${fieldMode ? 'text-white' : 'text-nb-black'}`}>
            {isEditing ? 'Edit Range' : 'Create New Range'}
          </h3>
          <Button variant="ghost" size="bare"
            onClick={onClose}
            className={`p-1 ${fieldMode ? 'hover:bg-nb-black' : 'hover:bg-nb-cream'}`}
          >
            <Icon name="close" className={fieldMode ? 'text-nb-black/40' : 'text-nb-black/50'} />
          </Button>
        </div>

        {/* Content */}
        <div className="p-4 space-y-4 overflow-y-auto max-h-[60vh]">
          {/* Label input */}
          <div>
            <label className={`block text-[10px] font-bold uppercase tracking-wider mb-1.5 ${
              fieldMode ? 'text-nb-black/40' : 'text-nb-black/50'
            }`}>
              Range Label
            </label>
            <input
              type="text"
              value={label}
              onChange={(e) => setLabel(e.target.value)}
              placeholder="e.g., Chapter 1, Introduction, etc."
              autoFocus
              className={`
                w-full px-3 py-2  text-sm outline-none border
                ${fieldMode
                  ? 'bg-nb-black text-white border-nb-black/80 focus:border-nb-yellow'
                  : 'bg-nb-white border-nb-black/20 focus:border-nb-blue focus:ring-2 focus:ring-nb-blue/20'
                }
              `}
            />
          </div>

          {/* Canvas selection */}
          <div>
            <label className={`block text-[10px] font-bold uppercase tracking-wider mb-1.5 ${
              fieldMode ? 'text-nb-black/40' : 'text-nb-black/50'
            }`}>
              Select Pages/Canvases ({selectedCanvasIds.size} selected)
            </label>
            <div className={`
              border  max-h-48 overflow-y-auto
              ${fieldMode ? 'border-nb-black/80' : 'border-nb-black/20'}
            `}>
              {availableCanvases.map((canvas) => {
                const canvasLabel = getIIIFValue(canvas.label, language) || 'Untitled';
                const isSelected = selectedCanvasIds.has(canvas.id);
                return (
                  <div
                    key={canvas.id}
                    onClick={() => toggleCanvas(canvas.id)}
                    className={`
                      flex items-center gap-2 px-3 py-2 cursor-pointer transition-nb border-b last:border-b-0
                      ${fieldMode
                        ? `border-nb-black ${isSelected ? 'bg-nb-yellow/20' : 'hover:bg-nb-black'}`
                        : `border-nb-black/10 ${isSelected ? 'bg-nb-blue/10' : 'hover:bg-nb-white'}`
                      }
                    `}
                  >
                    <Icon
                      name={isSelected ? 'check_box' : 'check_box_outline_blank'}
                      className={`text-sm ${
                        isSelected
                          ? (fieldMode ? 'text-nb-yellow' : 'text-nb-blue')
                          : (fieldMode ? 'text-nb-black/60' : 'text-nb-black/40')
                      }`}
                    />
                    <Icon name="image" className={`text-xs ${fieldMode ? 'text-nb-black/50' : 'text-nb-black/40'}`} />
                    <span className={`text-xs truncate ${fieldMode ? 'text-white' : 'text-nb-black/80'}`}>
                      {canvasLabel}
                    </span>
                  </div>
                );
              })}
              {availableCanvases.length === 0 && (
                <EmptyState
                  icon="photo_library"
                  title="No Canvases"
                  message="No canvases are available in this manifest."
                  compact
                  fieldMode={fieldMode}
                />
              )}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className={`
          flex items-center justify-end gap-2 px-4 py-3 border-t
          ${fieldMode ? 'border-nb-black/80' : 'border-nb-black/20'}
        `}>
          <Button variant="ghost" size="bare"
            onClick={onClose}
            className={`
              px-4 py-2  text-sm font-medium transition-nb
              ${fieldMode
                ? 'bg-nb-black text-nb-black/30 hover:bg-nb-black/80'
                : 'bg-nb-cream text-nb-black/80 hover:bg-nb-cream'
              }
            `}
          >
            Cancel
          </Button>
          <Button variant="ghost" size="bare"
            onClick={handleSave}
            disabled={!label.trim()}
            className={`
              px-4 py-2  text-sm font-medium transition-nb disabled:opacity-50
              ${fieldMode
                ? 'bg-nb-yellow text-white hover:bg-nb-yellow'
                : 'bg-nb-blue text-white hover:bg-nb-blue'
              }
            `}
          >
            {isEditing ? 'Save Changes' : 'Create Range'}
          </Button>
        </div>
      </div>
    </div>
  );
};

/**
 * Main Structure Tab Panel Component
 */
export const StructureTabPanel: React.FC<StructureTabPanelProps> = ({
  manifest,
  onUpdateManifest,
  settings,
  cx,
  canvases,
}) => {
  const [expandedRanges, setExpandedRanges] = useState<Set<string>>(new Set());
  const [selectedRangeId, setSelectedRangeId] = useState<string | null>(null);
  const [modalOpen, setModalOpen] = useState(false);
  const [editingRange, setEditingRange] = useState<IIIFRange | null>(null);
  const [dragOverRangeId, setDragOverRangeId] = useState<string | null>(null);
  const [draggedRangeId, setDraggedRangeId] = useState<string | null>(null);

  const structures = manifest.structures || [];

  // Generate unique ID for new ranges
  const generateRangeId = useCallback(() => {
    return `${manifest.id}/range/${Date.now()}-${crypto.randomUUID().slice(0, 9)}`;
  }, [manifest.id]);

  // Toggle range expansion
  const toggleExpand = useCallback((rangeId: string) => {
    setExpandedRanges(prev => {
      const next = new Set(prev);
      if (next.has(rangeId)) {
        next.delete(rangeId);
      } else {
        next.add(rangeId);
      }
      return next;
    });
  }, []);

  // Create new range
  const handleCreateRange = useCallback((label: string, canvasIds: string[]) => {
    const newRange: IIIFRange = {
      id: generateRangeId(),
      type: 'Range',
      label: { [settings.language]: [label] },
      items: canvasIds.map(id => ({ id, type: 'Canvas' as const })),
    };

    const newStructures = [...structures, newRange];
    onUpdateManifest({ structures: newStructures });
  }, [structures, generateRangeId, settings.language, onUpdateManifest]);

  // Update existing range
  const handleUpdateRange = useCallback((rangeId: string, label: string, canvasIds: string[]) => {
    const updateRangeInList = (ranges: IIIFRange[]): IIIFRange[] => {
      return ranges.map(range => {
        if (range.id === rangeId) {
          // Keep nested ranges, update canvas refs
          const nestedRanges = range.items?.filter((item): item is IIIFRange =>
            typeof item !== 'string' && 'type' in item && item.type === 'Range'
          ) || [];
          const canvasRefs = canvasIds.map(id => ({ id, type: 'Canvas' as const }));

          return {
            ...range,
            label: { [settings.language]: [label] },
            items: [...canvasRefs, ...nestedRanges],
          };
        }
        // Recursively check nested ranges
        if (range.items) {
          const nestedRanges = range.items.filter((item): item is IIIFRange =>
            typeof item !== 'string' && 'type' in item && item.type === 'Range'
          );
          if (nestedRanges.length > 0) {
            const updatedNested = updateRangeInList(nestedRanges);
            const canvasRefs = range.items.filter((item): item is IIIFRangeReference =>
              typeof item !== 'string' && 'type' in item && item.type === 'Canvas'
            );
            return { ...range, items: [...canvasRefs, ...updatedNested] };
          }
        }
        return range;
      });
    };

    const newStructures = updateRangeInList(structures);
    onUpdateManifest({ structures: newStructures });
    setEditingRange(null);
  }, [structures, settings.language, onUpdateManifest]);

  // Delete range
  const handleDeleteRange = useCallback((rangeId: string) => {
    const deleteRangeFromList = (ranges: IIIFRange[]): IIIFRange[] => {
      return ranges
        .filter(range => range.id !== rangeId)
        .map(range => {
          if (range.items) {
            const nestedRanges = range.items.filter((item): item is IIIFRange =>
              typeof item !== 'string' && 'type' in item && item.type === 'Range'
            );
            if (nestedRanges.length > 0) {
              const updatedNested = deleteRangeFromList(nestedRanges);
              const canvasRefs = range.items.filter((item): item is IIIFRangeReference =>
                typeof item !== 'string' && 'type' in item && item.type === 'Canvas'
              );
              return { ...range, items: [...canvasRefs, ...updatedNested] };
            }
          }
          return range;
        });
    };

    const newStructures = deleteRangeFromList(structures);
    onUpdateManifest({ structures: newStructures });
    if (selectedRangeId === rangeId) {
      setSelectedRangeId(null);
    }
  }, [structures, selectedRangeId, onUpdateManifest]);

  // Handle save from modal
  const handleModalSave = useCallback((label: string, canvasIds: string[]) => {
    if (editingRange) {
      handleUpdateRange(editingRange.id, label, canvasIds);
    } else {
      handleCreateRange(label, canvasIds);
    }
    setModalOpen(false);
    setEditingRange(null);
  }, [editingRange, handleCreateRange, handleUpdateRange]);

  // Drag and drop handlers
  const handleDragStart = useCallback((e: React.DragEvent, rangeId: string) => {
    e.dataTransfer.effectAllowed = 'move';
    e.dataTransfer.setData('text/plain', rangeId);
    setDraggedRangeId(rangeId);
  }, []);

  const handleDragOver = useCallback((e: React.DragEvent, rangeId: string) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = 'move';
    if (draggedRangeId !== rangeId) {
      setDragOverRangeId(rangeId);
    }
  }, [draggedRangeId]);

  const handleDrop = useCallback((e: React.DragEvent, targetRangeId: string) => {
    e.preventDefault();
    const sourceRangeId = e.dataTransfer.getData('text/plain');

    if (sourceRangeId === targetRangeId) {
      setDraggedRangeId(null);
      setDragOverRangeId(null);
      return;
    }

    // Reorder top-level structures
    const sourceIndex = structures.findIndex(r => r.id === sourceRangeId);
    const targetIndex = structures.findIndex(r => r.id === targetRangeId);

    if (sourceIndex !== -1 && targetIndex !== -1) {
      const newStructures = [...structures];
      const [removed] = newStructures.splice(sourceIndex, 1);
      newStructures.splice(targetIndex, 0, removed);
      onUpdateManifest({ structures: newStructures });
    }

    setDraggedRangeId(null);
    setDragOverRangeId(null);
  }, [structures, onUpdateManifest]);

  const handleDragEnd = useCallback(() => {
    setDraggedRangeId(null);
    setDragOverRangeId(null);
  }, []);

  // Update supplementary on a range
  const handleSupplementaryChange = useCallback((rangeId: string, supplementary: { id: string; type: 'AnnotationCollection' } | undefined) => {
    const updateSupplementaryInList = (ranges: IIIFRange[]): IIIFRange[] => {
      return ranges.map(range => {
        if (range.id === rangeId) {
          const updated = { ...range } as any;
          if (supplementary) {
            updated.supplementary = supplementary;
          } else {
            delete updated.supplementary;
          }
          return updated;
        }
        if (range.items) {
          const nestedRanges = range.items.filter((item): item is IIIFRange =>
            typeof item !== 'string' && 'type' in item && item.type === 'Range'
          );
          if (nestedRanges.length > 0) {
            const updatedNested = updateSupplementaryInList(nestedRanges);
            const canvasRefs = range.items.filter((item): item is IIIFRangeReference =>
              typeof item !== 'string' && 'type' in item && item.type === 'Canvas'
            );
            return { ...range, items: [...canvasRefs, ...updatedNested] };
          }
        }
        return range;
      });
    };

    const newStructures = updateSupplementaryInList(structures);
    onUpdateManifest({ structures: newStructures });
  }, [structures, onUpdateManifest]);

  // Get canvas IDs from a range
  const getCanvasIdsFromRange = (range: IIIFRange): string[] => {
    return (range.items || [])
      .filter((item): item is IIIFRangeReference =>
        typeof item !== 'string' && 'type' in item && item.type === 'Canvas'
      )
      .map(ref => ref.id);
  };

  // Render range tree recursively
  const renderRanges = (ranges: IIIFRange[], depth: number = 0): React.ReactNode => {
    return ranges.map(range => {
      const nestedRanges = (range.items || []).filter((item): item is IIIFRange =>
        typeof item !== 'string' && 'type' in item && item.type === 'Range'
      );
      const isExpanded = expandedRanges.has(range.id);

      return (
        <div key={range.id} className="group">
          <RangeTreeItem
            range={range}
            depth={depth}
            isExpanded={isExpanded}
            onToggle={() => toggleExpand(range.id)}
            onSelect={() => setSelectedRangeId(range.id === selectedRangeId ? null : range.id)}
            isSelected={selectedRangeId === range.id}
            onEdit={() => { setEditingRange(range); setModalOpen(true); }}
            onDelete={() => handleDeleteRange(range.id)}
            onSupplementaryChange={handleSupplementaryChange}
            fieldMode={settings.fieldMode}
            language={settings.language}
            canvases={canvases}
            onDragStart={(e) => handleDragStart(e, range.id)}
            onDragOver={(e) => handleDragOver(e, range.id)}
            onDrop={(e) => handleDrop(e, range.id)}
            isDragOver={dragOverRangeId === range.id}
          />
          {isExpanded && nestedRanges.length > 0 && (
            <div onDragEnd={handleDragEnd}>
              {renderRanges(nestedRanges, depth + 1)}
            </div>
          )}
        </div>
      );
    });
  };

  return (
    <div className="space-y-4">
      {/* Info banner */}
      <div className={`p-3 border ${cx.surface} ${cx.border}`}>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Icon name="account_tree" className={`text-sm ${settings.fieldMode ? 'text-nb-purple/60' : 'text-nb-purple'}`} />
            <span className={`text-xs font-bold uppercase ${settings.fieldMode ? 'text-nb-purple/60' : 'text-nb-purple'}`}>
              Table of Contents
            </span>
          </div>
          <span className={`text-[10px] ${cx.textMuted}`}>
            {structures.length} {structures.length === 1 ? 'range' : 'ranges'}
          </span>
        </div>
        <p className={`text-[10px] mt-1 ${cx.textMuted}`}>
          Define structural divisions like chapters, sections, or groups
        </p>
      </div>

      {/* Add Range button */}
      <Button variant="ghost" size="bare"
        onClick={() => { setEditingRange(null); setModalOpen(true); }}
        className={`
          w-full flex items-center justify-center gap-2 px-4 py-3  border-2 border-dashed
          text-xs font-bold uppercase transition-nb
          ${settings.fieldMode
            ? 'border-nb-black/80 text-nb-black/40 hover:border-nb-yellow hover:text-nb-yellow hover:bg-nb-yellow/20'
            : 'border-nb-black/20 text-nb-black/50 hover:border-nb-blue hover:text-nb-blue hover:bg-nb-blue/10'
          }
        `}
      >
        <Icon name="add" className="text-sm" />
        Add Range
      </Button>

      {/* Range tree */}
      {structures.length > 0 ? (
        <div className={`
          border  overflow-hidden
          ${settings.fieldMode ? 'border-nb-black/80 bg-nb-black' : 'border-nb-black/20 bg-nb-white'}
        `}>
          <div onDragEnd={handleDragEnd}>
            {renderRanges(structures)}
          </div>
        </div>
      ) : (
        <div className={`text-center py-8 ${cx.textMuted}`}>
          <Icon name="segment" className="text-4xl mb-2 opacity-30" />
          <p className="text-sm">No structural ranges defined</p>
          <p className="text-[10px] mt-1">
            Add ranges to create a table of contents for navigation
          </p>
        </div>
      )}

      {/* Edit/Create Modal */}
      <RangeEditModal
        isOpen={modalOpen}
        onClose={() => { setModalOpen(false); setEditingRange(null); }}
        onSave={handleModalSave}
        initialLabel={editingRange ? getIIIFValue(editingRange.label, settings.language) || '' : ''}
        initialCanvasIds={editingRange ? getCanvasIdsFromRange(editingRange) : []}
        availableCanvases={canvases}
        isEditing={!!editingRange}
        fieldMode={settings.fieldMode}
        language={settings.language}
      />
    </div>
  );
};

export default StructureTabPanel;
