// src/features/metadata-edit/ui/molecules/ValidationSummary.tsx
/**
 * Validation Summary Molecule
 *
 * Prominent validation feedback displayed at the top of the inspector panel.
 * Shows error/warning counts and batch fix actions.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Composes ValidationBadge atom, ActionButton molecule
 * - No domain logic
 * - Props-only API
 *
 * @module features/metadata-edit/ui/molecules/ValidationSummary
 */

import React, { useMemo } from 'react';
import { Icon } from '@/src/shared/ui/atoms';
import { ActionButton } from '@/src/shared/ui/molecules/ActionButton';
import type { ValidationIssue } from '../../model/useInspectorValidation';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';

export interface ValidationSummaryProps {
  /** Validation issues */
  issues: ValidationIssue[];
  /** Error count */
  errorCount: number;
  /** Warning count */
  warningCount: number;
  /** Info count */
  infoCount: number;
  /** Auto-fixable issue count */
  autoFixableCount: number;
  /** Called when user clicks "Fix All" */
  onFixAll: () => void;
  /** Called when user clicks "View Details" */
  onViewDetails: () => void;
  /** Contextual styles from template */
  cx?: ContextualClassNames;
  /** Field mode flag */
  fieldMode?: boolean;
}

/**
 * Validation Summary Molecule
 *
 * @example
 * <ValidationSummary
 *   issues={issues}
 *   errorCount={2}
 *   warningCount={3}
 *   onFixAll={handleFixAll}
 *   onViewDetails={handleViewDetails}
 * />
 */
export const ValidationSummary: React.FC<ValidationSummaryProps> = ({
  issues,
  errorCount,
  warningCount,
  infoCount,
  autoFixableCount,
  onFixAll,
  onViewDetails,
  cx = {},
  fieldMode = false,
}) => {
  // Determine overall status
  const status = useMemo(() => {
    if (errorCount > 0) return 'error';
    if (warningCount > 0) return 'warning';
    if (infoCount > 0) return 'info';
    return 'success';
  }, [errorCount, warningCount, infoCount]);

  // Status styles
  const statusStyles = {
    error: {
      bg: fieldMode ? 'bg-red-950/50' : 'bg-nb-red/10',
      border: fieldMode ? 'border-nb-red' : 'border-nb-red/30',
      icon: 'error',
      iconColor: 'text-nb-red',
      text: fieldMode ? 'text-nb-red/40' : 'text-nb-red',
    },
    warning: {
      bg: fieldMode ? 'bg-nb-orange/10' : 'bg-nb-orange/10',
      border: fieldMode ? 'border-nb-orange' : 'border-nb-orange/20',
      icon: 'warning',
      iconColor: 'text-nb-orange',
      text: fieldMode ? 'text-nb-orange/40' : 'text-nb-orange',
    },
    info: {
      bg: fieldMode ? 'bg-blue-950/50' : 'bg-nb-blue/10',
      border: fieldMode ? 'border-nb-blue' : 'border-nb-blue/30',
      icon: 'info',
      iconColor: 'text-nb-blue',
      text: fieldMode ? 'text-nb-blue/40' : 'text-nb-blue',
    },
    success: {
      bg: fieldMode ? 'bg-green-950/50' : 'bg-nb-green/10',
      border: fieldMode ? 'border-nb-green' : 'border-nb-green/30',
      icon: 'check_circle',
      iconColor: 'text-nb-green',
      text: fieldMode ? 'text-nb-green/40' : 'text-nb-green',
    },
  };

  const styles = statusStyles[status];

  if (issues.length === 0) {
    return (
      <div
        className={`p-3 border ${styles.bg} ${styles.border} flex items-center gap-3`}
      >
        <Icon name={styles.icon} className={`text-xl ${styles.iconColor}`} />
        <span className={`text-sm font-medium ${styles.text}`}>
          All validations passed
        </span>
      </div>
    );
  }

  return (
    <div
      className={`p-3 border ${styles.bg} ${styles.border}`}
      role="alert"
      aria-live="polite"
    >
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-center gap-3">
          <Icon name={styles.icon} className={`text-xl flex-shrink-0 ${styles.iconColor}`} />
          <div>
            <div className={`text-sm font-medium ${styles.text}`}>
              {errorCount > 0 ? (
                <>
                  {errorCount} error{errorCount !== 1 ? 's' : ''},{' '}
                  {warningCount} warning{warningCount !== 1 ? 's' : ''}
                </>
              ) : warningCount > 0 ? (
                <>
                  {warningCount} warning{warningCount !== 1 ? 's' : ''}
                </>
              ) : (
                <>
                  {infoCount} suggestion{infoCount !== 1 ? 's' : ''}
                </>
              )}
            </div>
            {autoFixableCount > 0 && (
              <div className={`text-xs mt-0.5 opacity-75 ${styles.text}`}>
                {autoFixableCount} can be auto-fixed
              </div>
            )}
          </div>
        </div>

        <div className="flex items-center gap-2 flex-shrink-0">
          {autoFixableCount > 0 && (
            <ActionButton
              onClick={onFixAll}
              label={`Fix All (${autoFixableCount})`}
              icon="auto_fix"
              size="sm"
              variant={fieldMode ? 'secondary' : 'primary'}
            />
          )}
          <ActionButton
            onClick={onViewDetails}
            label="Details"
            icon="visibility"
            size="sm"
            variant="ghost"
          />
        </div>
      </div>
    </div>
  );
};

ValidationSummary.displayName = 'ValidationSummary';

export default ValidationSummary;

// src/features/metadata-edit/ui/molecules/ValidationSummary.svelte
<!--
  ValidationSummary -- Prominent validation feedback with error/warning counts and fix actions.
  React source: src/features/metadata-edit/ui/molecules/ValidationSummary.tsx (179 lines)
  Architecture: Molecule (composes Icon atom + ActionButton molecule, Rule 5.D: cx + fieldMode)
-->
<script module lang="ts">
  import type { ValidationIssue } from '../../lib/inspectorValidation';

  export type { ValidationIssue };

  type SummaryStatus = 'error' | 'warning' | 'info' | 'success';

  interface StatusStyle {
    bg: string;
    border: string;
    icon: string;
    iconColor: string;
    text: string;
  }

  const STATUS_STYLES: Record<'normal' | 'field', Record<SummaryStatus, StatusStyle>> = {
    normal: {
      error:   { bg: 'bg-nb-red/10',   border: 'border-nb-red/30',   icon: 'error',        iconColor: 'text-nb-red',    text: 'text-nb-red' },
      warning: { bg: 'bg-nb-orange/10', border: 'border-nb-orange/20', icon: 'warning',     iconColor: 'text-nb-orange', text: 'text-nb-orange' },
      info:    { bg: 'bg-nb-blue/10',   border: 'border-nb-blue/30',  icon: 'info',         iconColor: 'text-nb-blue',   text: 'text-nb-blue' },
      success: { bg: 'bg-nb-green/10',  border: 'border-nb-green/30', icon: 'check_circle', iconColor: 'text-nb-green',  text: 'text-nb-green' },
    },
    field: {
      error:   { bg: 'bg-red-950/50',   border: 'border-nb-red',   icon: 'error',        iconColor: 'text-nb-red',    text: 'text-nb-red/40' },
      warning: { bg: 'bg-nb-orange/10',  border: 'border-nb-orange', icon: 'warning',     iconColor: 'text-nb-orange', text: 'text-nb-orange/40' },
      info:    { bg: 'bg-blue-950/50',   border: 'border-nb-blue',  icon: 'info',         iconColor: 'text-nb-blue',   text: 'text-nb-blue/40' },
      success: { bg: 'bg-green-950/50',  border: 'border-nb-green', icon: 'check_circle', iconColor: 'text-nb-green',  text: 'text-nb-green/40' },
    },
  };
</script>

<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import { cn } from '@/src/shared/lib/cn';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';
  import ActionButton from '@/src/shared/ui/molecules/ActionButton.svelte';

  interface Props {
    issues: ValidationIssue[];
    errorCount: number;
    warningCount: number;
    infoCount: number;
    autoFixableCount: number;
    onFixAll: () => void;
    onViewDetails: () => void;
    cx?: Partial<ContextualClassNames>;
    fieldMode?: boolean;
  }

  let {
    issues,
    errorCount,
    warningCount,
    infoCount,
    autoFixableCount,
    onFixAll,
    onViewDetails,
    cx = {},
    fieldMode = false,
  }: Props = $props();

  let status = $derived<SummaryStatus>(
    errorCount > 0 ? 'error' :
    warningCount > 0 ? 'warning' :
    infoCount > 0 ? 'info' :
    'success'
  );

  let styles = $derived(STATUS_STYLES[fieldMode ? 'field' : 'normal'][status]);
</script>

{#if issues.length === 0}
  <!-- Empty state: all validations passed -->
  <div class={cn('p-3 border flex items-center gap-3', styles.bg, styles.border)}>
    <Icon name={styles.icon} class={cn('text-xl', styles.iconColor)} />
    <span class={cn('text-sm font-medium', styles.text)}>
      All validations passed
    </span>
  </div>
{:else}
  <!-- Issues present -->
  <div
    class={cn('p-3 border', styles.bg, styles.border)}
    role="alert"
    aria-live="polite"
  >
    <div class="flex items-start justify-between gap-3">
      <div class="flex items-center gap-3">
        <Icon name={styles.icon} class={cn('text-xl shrink-0', styles.iconColor)} />
        <div>
          <div class={cn('text-sm font-medium', styles.text)}>
            {#if errorCount > 0}
              {errorCount} error{errorCount !== 1 ? 's' : ''},
              {warningCount} warning{warningCount !== 1 ? 's' : ''}
            {:else if warningCount > 0}
              {warningCount} warning{warningCount !== 1 ? 's' : ''}
            {:else}
              {infoCount} suggestion{infoCount !== 1 ? 's' : ''}
            {/if}
          </div>
          {#if autoFixableCount > 0}
            <div class={cn('text-xs mt-0.5 opacity-75', styles.text)}>
              {autoFixableCount} can be auto-fixed
            </div>
          {/if}
        </div>
      </div>

      <div class="flex items-center gap-2 shrink-0">
        {#if autoFixableCount > 0}
          <ActionButton
            onclick={onFixAll}
            label={`Fix All (${autoFixableCount})`}
            icon="auto_fix"
            cx={cx as ContextualClassNames}
          />
        {/if}
        <ActionButton
          onclick={onViewDetails}
          label="Details"
          icon="visibility"
          cx={cx as ContextualClassNames}
        />
      </div>
    </div>
  </div>
{/if}
