// src/shared/ui/molecules/DropdownSelect.tsx
/**
 * DropdownSelect Molecule
 *
 * Custom-styled dropdown selector with click-outside detection.
 * Alternative to native select for enhanced visual styling.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Local UI state (dropdown open/closed only)
 * - No domain logic
 * - Props-only API for data
 * - Uses design tokens
 *
 * @module shared/ui/molecules/DropdownSelect
 */

import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Button } from '@/ui/primitives/Button';
import { Icon } from '@/src/shared/ui/atoms';

export interface DropdownOption {
  value: string;
  label: string;
  description?: string;
}

export interface DropdownSelectProps {
  /** Available options */
  options: DropdownOption[];
  /** Currently selected value */
  value: string;
  /** Callback when selection changes */
  onChange: (value: string) => void;
  /** Placeholder when no value selected */
  placeholder?: string;
  /** Theme color for selected state (e.g., 'yellow', 'purple', 'blue') */
  themeColor?: 'yellow' | 'purple' | 'blue' | 'green';
  /** Field mode flag for dark theme */
  fieldMode?: boolean;
  /** Whether to show option descriptions */
  showDescriptions?: boolean;
  /** Additional CSS class */
  className?: string;
}

const THEME_COLORS = {
  yellow: {
    light: { bg: '#fefce8', text: '#a16207' },
    dark: { bg: 'rgba(250, 204, 21, 0.2)', text: '#facc15' },
  },
  purple: {
    light: { bg: '#faf5ff', text: '#7c3aed' },
    dark: { bg: 'rgba(168, 85, 247, 0.2)', text: '#c084fc' },
  },
  blue: {
    light: { bg: '#eff6ff', text: '#1d4ed8' },
    dark: { bg: 'rgba(59, 130, 246, 0.2)', text: '#60a5fa' },
  },
  green: {
    light: { bg: '#f0fdf4', text: '#15803d' },
    dark: { bg: 'rgba(34, 197, 94, 0.2)', text: '#4ade80' },
  },
};

export const DropdownSelect: React.FC<DropdownSelectProps> = ({
  options,
  value,
  onChange,
  placeholder = 'Select an option...',
  themeColor = 'blue',
  fieldMode = false,
  showDescriptions = false,
  className = '',
}) => {
  const [isOpen, setIsOpen] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  const selectedOption = options.find(o => o.value === value);
  const colorScheme = THEME_COLORS[themeColor];
  const selectedColors = fieldMode ? colorScheme.dark : colorScheme.light;

  const handleSelect = useCallback((newValue: string) => {
    onChange(newValue);
    setIsOpen(false);
  }, [onChange]);

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };

    if (isOpen) {
      document.addEventListener('mousedown', handleClickOutside);
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [isOpen]);

  const dropdownBg = fieldMode ? '#0f172a' : '#ffffff';
  const dropdownBorder = fieldMode ? '#334155' : '#e2e8f0';

  return (
    <div ref={containerRef} className={`relative ${className}`}>
      <Button
        onClick={() => setIsOpen(!isOpen)}
        variant="secondary"
        size="sm"
        fullWidth
        icon={<Icon name={isOpen ? 'expand_less' : 'expand_more'} className="text-xs" />}
        iconAfter
        style={{
          fontSize: '0.75rem',
          justifyContent: 'space-between',
          padding: '8px 12px',
        }}
        aria-haspopup="listbox"
        aria-expanded={isOpen}
      >
        {selectedOption?.label || placeholder}
      </Button>

      {isOpen && (
        <div
          style={{
            position: 'absolute',
            left: 0,
            right: 0,
            top: '100%',
            marginTop: '4px',
            backgroundColor: dropdownBg,
            border: `1px solid ${dropdownBorder}`,
            borderRadius: '6px',
            padding: '4px 0',
            zIndex: 50,
            boxShadow: fieldMode
              ? '0 10px 15px -3px rgba(0, 0, 0, 0.5)'
              : '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
          }}
          role="listbox"
        >
          {options.map(option => {
            const isSelected = option.value === value;
            const optionBg = isSelected
              ? selectedColors.bg
              : fieldMode ? '#1e293b' : '#f8fafc';
            const optionColor = isSelected
              ? selectedColors.text
              : fieldMode ? '#cbd5e1' : '#334155';

            return (
              <Button
                key={option.value}
                onClick={() => handleSelect(option.value)}
                variant="ghost"
                size="sm"
                fullWidth
                style={{
                  fontSize: '0.75rem',
                  justifyContent: 'flex-start',
                  padding: '6px 12px',
                  backgroundColor: optionBg,
                  color: optionColor,
                  borderRadius: 0,
                  borderBottom: `1px solid ${fieldMode ? '#1e293b' : '#f1f5f9'}`,
                }}
                role="option"
                aria-selected={isSelected}
              >
                <div>
                  <div style={{ fontWeight: 600 }}>{option.label}</div>
                  {showDescriptions && option.description && (
                    <div style={{ fontSize: '10px', opacity: 0.7, marginTop: '2px' }}>
                      {option.description}
                    </div>
                  )}
                </div>
              </Button>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default DropdownSelect;

// src/shared/ui/molecules/DropdownSelect.svelte
<script module lang="ts">
  export const THEME_COLORS = {
    yellow: { bg: 'bg-yellow-100', border: 'border-yellow-400', hover: 'hover:bg-yellow-200', selected: 'bg-yellow-300' },
    purple: { bg: 'bg-purple-100', border: 'border-purple-400', hover: 'hover:bg-purple-200', selected: 'bg-purple-300' },
    blue: { bg: 'bg-blue-100', border: 'border-blue-400', hover: 'hover:bg-blue-200', selected: 'bg-blue-300' },
    green: { bg: 'bg-green-100', border: 'border-green-400', hover: 'hover:bg-green-200', selected: 'bg-green-300' },
  } as const;
</script>

<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import { cn } from '@/src/shared/lib/cn';
  import Icon from '../atoms/Icon.svelte';

  interface Option {
    value: string;
    label: string;
    description?: string;
  }

  type ThemeColor = keyof typeof THEME_COLORS;

  interface Props {
    options: Option[];
    value?: string;
    placeholder?: string;
    themeColor?: ThemeColor;
    showDescriptions?: boolean;
    cx: ContextualClassNames;
    fieldMode?: boolean;
    class?: string;
  }

  let {
    options,
    value = $bindable(''),
    placeholder = 'Select an option',
    themeColor = 'blue',
    showDescriptions = false,
    cx,
    fieldMode = false,
    class: className = ''
  }: Props = $props();

  let isOpen = $state(false);
  let dropdownRef: HTMLDivElement | undefined = $state();

  const selectedOption = $derived(options.find(opt => opt.value === value));
  const displayText = $derived(selectedOption?.label || placeholder);
  const theme = $derived(THEME_COLORS[themeColor]);

  function toggleDropdown() { isOpen = !isOpen; }

  function handleSelect(optionValue: string) {
    value = optionValue;
    isOpen = false;
  }

  // Click-outside
  $effect(() => {
    if (!isOpen || !dropdownRef) return;
    function handleClickOutside(e: MouseEvent) {
      if (dropdownRef && !dropdownRef.contains(e.target as Node)) isOpen = false;
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  });

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') isOpen = false;
    else if ((e.key === 'Enter' || e.key === ' ') && !isOpen) {
      e.preventDefault();
      toggleDropdown();
    }
  }
</script>

<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
<div bind:this={dropdownRef} class={cn('relative', className)} onkeydown={handleKeydown} role="group">
  <button aria-label={displayText}
    type="button"
    class={cn(
      'w-full px-4 py-2 border-2 flex items-center justify-between cursor-pointer',
      theme.bg, theme.border
    )}
    onclick={toggleDropdown}
    aria-haspopup="listbox"
    aria-expanded={isOpen}
  >
    <span class="truncate">{displayText}</span>
    <Icon name="expand_more" class={cn('text-base transition-transform', isOpen && 'rotate-180')} />
  </button>

  {#if isOpen}
    <div
      class={cn('absolute z-50 w-full mt-1 border-2 shadow-lg max-h-60 overflow-y-auto', theme.bg, theme.border)}
      role="listbox"
    >
      {#each options as option (option.value)}
        <button aria-label={option.label}
          type="button"
          class={cn(
            'w-full px-4 py-2 text-left flex flex-col cursor-pointer border-0 bg-transparent',
            theme.hover,
            option.value === value && theme.selected
          )}
          onclick={() => handleSelect(option.value)}
          role="option"
          aria-selected={option.value === value}
        >
          <span class="font-medium">{option.label}</span>
          {#if showDescriptions && option.description}
            <span class="text-xs text-gray-600 mt-1">{option.description}</span>
          {/if}
        </button>
      {/each}
    </div>
  {/if}
</div>
