// src/shared/ui/molecules/FormInput.tsx
/**
 * FormInput Molecule
 *
 * Universal form input supporting multiple types with consistent styling.
 * Consolidates text, textarea, number, datetime, and other input patterns.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Zero state (controlled input)
 * - No domain logic
 * - Props-only API
 * - Uses design tokens via Tailwind
 *
 * @module shared/ui/molecules/FormInput
 */

import React, { ReactNode } from 'react';
import { FieldLayout } from '@/src/shared/ui/layout';

export type FormInputType ='text' |'textarea' |'number' |'datetime-local' |'date' |'time' |'email' |'url' |'password';

export interface FormInputProps {
  /** Current input value */
  value: string | number;
  /** Called when value changes */
  onChange: (value: string) => void;
  /** Input type */
  type?: FormInputType;
  /** Input label (optional) */
  label?: string;
  /** Input placeholder */
  placeholder?: string;
  /** Helper text or hint displayed below input */
  hint?: string;
  /** Error message to display */
  error?: string;
  /** Whether the input is disabled */
  disabled?: boolean;
  /** Whether the field is required */
  required?: boolean;
  /** Field mode for dark theme */
  fieldMode?: boolean;
  /** Optional action button/element (e.g., location picker) */
  actionButton?: ReactNode;
  /** Number of rows for textarea */
  rows?: number;
  /** Additional CSS class */
  className?: string;
  /** Input ID for label association */
  id?: string;
  /** Min value for number inputs */
  min?: number;
  /** Max value for number inputs */
  max?: number;
  /** Step value for number inputs */
  step?: number;
}

export const FormInput: React.FC<FormInputProps> = ({
  value,
  onChange,
  type ='text',
  label,
  placeholder ='',
  hint,
  error,
  disabled = false,
  required = false,
  fieldMode = false,
  actionButton,
  rows = 3,
  className ='',
  id,
  min,
  max,
  step,
}) => {
  const inputClass =`w-full text-xs px-2 py-1 border focus:outline-none focus:ring-2 transition-nb ${
    error
      ? fieldMode
        ?'border-nb-red bg-nb-red/20 text-nb-red/60 focus:border-nb-red focus:ring-red-500/50'
        :'border-nb-red/40 bg-nb-red/10 text-nb-red focus:border-nb-red focus:ring-red-200'
      : fieldMode
        ?'bg-nb-black text-nb-black/20 border-nb-black/80 focus:border-nb-blue focus:ring-nb-blue/50'
        :'bg-nb-white text-nb-black border-nb-black/20 focus:border-nb-blue focus:ring-nb-blue/30'
  } ${disabled ?'opacity-50 cursor-not-allowed' :''} ${className}`;

  const labelClass =`block text-xs font-bold mb-1 ${fieldMode ?'text-nb-black/30' :'text-nb-black/80'}`;
  const hintClass =`text-[10px] mt-1 ${error ? (fieldMode ?'text-nb-red' :'text-nb-red') : (fieldMode ?'text-nb-black/40' :'text-nb-black/50')}`;

  const renderInput = () => {
    if (type ==='textarea') {
      return (
        <textarea
          id={id}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          placeholder={placeholder}
          disabled={disabled}
          required={required}
          className={`${inputClass} resize-none`}
          rows={rows}
          aria-invalid={!!error}
          aria-describedby={error ?`${id}-error` : hint ?`${id}-hint` : undefined}
        />
      );
    }

    const inputElement = (
      <input
        id={id}
        type={type}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        disabled={disabled}
        required={required}
        min={min}
        max={max}
        step={step}
        className={inputClass}
        aria-invalid={!!error}
        aria-describedby={error ?`${id}-error` : hint ?`${id}-hint` : undefined}
      />
    );

    // If there's an action button, wrap input and button in a flex container
    if (actionButton) {
      return (
        <div className="flex gap-1">
          {inputElement}
          {actionButton}
        </div>
      );
    }

    return inputElement;
  };

  return (
    <FieldLayout>
      {label && (
        <FieldLayout.Label>
          <label htmlFor={id} className={labelClass}>
            {label}
            {required && <span className={fieldMode ?'text-nb-red' :'text-nb-red'}> *</span>}
          </label>
        </FieldLayout.Label>
      )}
      <FieldLayout.Control>
        {renderInput()}
      </FieldLayout.Control>
      {(error || hint) && (
        <FieldLayout.Hint>
          <div id={error ?`${id}-error` :`${id}-hint`} className={hintClass} role={error ?'alert' : undefined}>
            {error || hint}
          </div>
        </FieldLayout.Hint>
      )}
    </FieldLayout>
  );
};

export default FormInput;

// src/shared/ui/molecules/FormInput.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import { cn } from '@/src/shared/lib/cn';
  import TextArea from '../atoms/TextArea.svelte';

  interface Props {
    value?: string;
    type?: 'text' | 'textarea' | 'number' | 'datetime-local' | 'email' | 'url' | 'password';
    label?: string;
    hint?: string;
    error?: string;
    required?: boolean;
    disabled?: boolean;
    placeholder?: string;
    cx: ContextualClassNames;
    fieldMode?: boolean;
    action?: Snippet;
    min?: number;
    max?: number;
    step?: number;
    rows?: number;
    oninput?: (value: string) => void;
    onblur?: () => void;
    class?: string;
  }

  let {
    value = $bindable(''),
    type = 'text',
    label,
    hint,
    error,
    required = false,
    disabled = false,
    placeholder,
    cx,
    fieldMode = false,
    action,
    min,
    max,
    step,
    rows = 3,
    oninput,
    onblur,
    class: className = ''
  }: Props = $props();

  const id = `fi-${Math.random().toString(36).slice(2, 8)}`;
  const hasError = $derived(!!error);
  const inputClasses = $derived(cn(
    cx.input || 'w-full border-2 border-nb-black px-3 py-2 font-mono',
    hasError && 'border-red-500 bg-red-50',
    disabled && 'opacity-50 cursor-not-allowed'
  ));

  function handleInput(e: Event) {
    const target = e.target as HTMLInputElement | HTMLTextAreaElement;
    value = target.value;
    oninput?.(value);
  }

  function handleBlur() {
    onblur?.();
  }
</script>

<div class={cn('flex flex-col gap-1.5', className)}>
  {#if label}
    <label for={id} class={cn(cx.label || 'text-[11px] font-bold uppercase tracking-wider font-mono', cx.text)}>
      {label}
      {#if required}<span class="text-red-500"> *</span>{/if}
    </label>
  {/if}

  <div class="relative">
    {#if type === 'textarea'}
      <TextArea
        {id}
        {placeholder}
        {disabled}
        {rows}
        class={inputClasses}
        value={value}
        oninput={handleInput}
        onblur={handleBlur}
      />
    {:else}
      <input
        {id}
        {type}
        {placeholder}
        {disabled}
        {min}
        {max}
        {step}
        class={inputClasses}
        value={value}
        oninput={handleInput}
        onblur={handleBlur}
        aria-invalid={hasError || undefined}
        aria-required={required || undefined}
        aria-describedby={error ? `${id}-error` : hint ? `${id}-hint` : undefined}
      />
    {/if}

    {#if action}
      <div class="absolute right-2 top-1/2 -translate-y-1/2">
        {@render action()}
      </div>
    {/if}
  </div>

  {#if error}
    <span id="{id}-error" role="alert" class="text-xs font-bold text-red-600 font-mono">{error}</span>
  {:else if hint}
    <span id="{id}-hint" class={cn('text-xs', cx.textMuted || 'text-nb-black/50')}>{hint}</span>
  {/if}
</div>
