// src/shared/ui/molecules/MetadataFieldRenderer.svelte
<script lang="ts">
  import { cn } from '@/src/shared/lib/cn';
  import TextArea from '@/src/shared/ui/atoms/TextArea.svelte';
  import Select from '@/src/shared/ui/atoms/Select.svelte';

  export interface MetadataField {
    id: string;
    label: string;
    value: string | string[] | null;
    type?: 'text' | 'textarea' | 'date' | 'url' | 'select' | 'readonly';
    editable?: boolean;
    required?: boolean;
    error?: string;
    helpText?: string;
    group?: string;
    options?: Array<{ value: string; label: string }>;
  }

  interface Props {
    field: MetadataField;
    isEditing: boolean;
    onFieldChange?: (fieldId: string, value: string) => void;
    fieldMode?: boolean;
  }

  let { field, isEditing, onFieldChange, fieldMode = false }: Props = $props();

  function formatValue(value: string | string[] | null, type?: string): string {
    if (value === null || value === undefined) return '\u2014';
    if (Array.isArray(value)) return value.join(', ') || '\u2014';
    if (type === 'date' && value) {
      try {
        const d = new Date(value);
        return d.toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });
      } catch {
        return value;
      }
    }
    return value || '\u2014';
  }

  const displayValue = $derived(formatValue(field.value, field.type));
  const hasError = $derived(!!field.error);

  const inputClass = $derived(cn(
    'w-full px-3 py-2 text-sm border transition-nb',
    fieldMode
      ? 'bg-nb-black border-nb-black/80 text-white focus:border-nb-blue'
      : 'bg-nb-white border-nb-black/20 text-nb-black focus:border-nb-blue',
    hasError ? 'border-nb-red' : ''
  ));

  function getStringValue(): string {
    if (Array.isArray(field.value)) return field.value.join(', ');
    return (field.value as string) ?? '';
  }
</script>

{#if isEditing && field.editable}
  <div class="space-y-1">
    <label class={`text-xs font-medium ${fieldMode ? 'text-nb-black/40' : 'text-nb-black/60'}`}>
      {field.label}
      {#if field.required}<span class="text-nb-red ml-1">*</span>{/if}
    </label>

    {#if field.type === 'textarea'}
      <TextArea
        value={getStringValue()}
        oninput={(e) => onFieldChange?.(field.id, (e.target as HTMLTextAreaElement).value)}
        rows={3}
        class="resize-none"
        cx={{ input: inputClass }}
        placeholder={`Enter ${field.label.toLowerCase()}`}
      />
    {:else if field.type === 'select' && field.options}
      <Select
        value={getStringValue()}
        onchange={(e) => onFieldChange?.(field.id, (e.target as HTMLSelectElement).value)}
        cx={{ input: inputClass }}
      >
        {#snippet children()}
          <option value="">Select {field.label.toLowerCase()}</option>
          {#each field.options as opt}
            <option value={opt.value}>{opt.label}</option>
          {/each}
        {/snippet}
      </Select>
    {:else}
      <input
        type={field.type === 'date' ? 'date' : field.type === 'url' ? 'url' : 'text'}
        value={getStringValue()}
        oninput={(e) => onFieldChange?.(field.id, (e.target as HTMLInputElement).value)}
        class={inputClass}
        placeholder={`Enter ${field.label.toLowerCase()}`}
      />
    {/if}

    {#if hasError}
      <p class="text-xs text-nb-red flex items-center gap-1">
        <span class="material-icons text-xs">error</span>
        {field.error}
      </p>
    {/if}

    {#if field.helpText && !hasError}
      <p class={`text-xs ${fieldMode ? 'text-nb-black/50' : 'text-nb-black/40'}`}>{field.helpText}</p>
    {/if}
  </div>
{:else}
  <!-- Read-only display -->
  <div class="flex flex-col">
    <span class={`text-xs font-medium mb-1 ${fieldMode ? 'text-nb-black/50' : 'text-nb-black/50'}`}>{field.label}</span>
    <span class={`text-sm ${fieldMode ? 'text-white' : 'text-nb-black'}`}>{displayValue}</span>
  </div>
{/if}

// src/shared/ui/molecules/MetadataFieldRenderer.tsx
/**
 * MetadataFieldRenderer Molecule
 *
 * Renders a single metadata field in either edit or read-only mode.
 * Supports text, textarea, date, url, select, and readonly field types.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - No local state
 * - No domain logic
 * - Props-only API
 * - Uses design tokens
 *
 * @module shared/ui/molecules/MetadataFieldRenderer
 */

import React from 'react';
import { Icon } from '../atoms';
import type { MetadataField } from './metadataTypes';

export interface MetadataFieldRendererProps {
  /** Field definition */
  field: MetadataField;
  /** Whether in edit mode */
  isEditing: boolean;
  /** Callback when field changes */
  onFieldChange?: (fieldId: string, value: string) => void;
  /** Field mode flag for dark theme */
  fieldMode?: boolean;
}

/**
 * Format a field value for display
 */
export const formatFieldValue = (value: string | string[] | null, type?: string): string => {
  if (value === null || value === undefined) return'\u2014';

  if (Array.isArray(value)) {
    return value.join(',') ||'\u2014';
  }

  if (type ==='date' && value) {
    try {
      const date = new Date(value);
      return date.toLocaleDateString(undefined, {
        year:'numeric',
        month:'long',
        day:'numeric',
      });
    } catch {
      return value;
    }
  }

  return value ||'\u2014';
};

export const MetadataFieldRenderer: React.FC<MetadataFieldRendererProps> = ({
  field,
  isEditing,
  onFieldChange,
  fieldMode = false,
}) => {
  const displayValue = formatFieldValue(field.value, field.type);
  const hasError = field.error;

  if (isEditing && field.editable) {
    const inputClass =`
      w-full px-3 py-2  text-sm
      border transition-nb
      ${fieldMode
        ?'bg-nb-black border-nb-black/80 text-white focus:border-nb-blue'
        :'bg-nb-white border-nb-black/20 text-nb-black focus:border-nb-blue'
      }
      ${hasError ?'border-nb-red' :''}
`;

    return (
      <div key={field.id} className="space-y-1">
        <label className={`text-xs font-medium ${fieldMode ?'text-nb-black/40' :'text-nb-black/60'}`}>
          {field.label}
          {field.required && <span className="text-nb-red ml-1">*</span>}
        </label>

        {field.type ==='textarea' ? (
          <textarea
            value={(field.value as string) ||''}
            onChange={(e) => onFieldChange?.(field.id, e.target.value)}
            rows={3}
            className={`${inputClass} resize-none`}
            placeholder={`Enter ${field.label.toLowerCase()}`}
          />
        ) : field.type ==='select' && field.options ? (
          <select
            value={(field.value as string) ||''}
            onChange={(e) => onFieldChange?.(field.id, e.target.value)}
            className={inputClass}
          >
            <option value="">Select {field.label.toLowerCase()}</option>
            {field.options.map(opt => (
              <option key={opt.value} value={opt.value}>{opt.label}</option>
            ))}
          </select>
        ) : (
          <input
            type={field.type ==='date' ?'date' : field.type ==='url' ?'url' :'text'}
            value={(field.value as string) ||''}
            onChange={(e) => onFieldChange?.(field.id, e.target.value)}
            className={inputClass}
            placeholder={`Enter ${field.label.toLowerCase()}`}
          />
        )}

        {hasError && (
          <p className="text-xs text-nb-red flex items-center gap-1">
            <Icon name="error" className="text-xs" />
            {field.error}
          </p>
        )}

        {field.helpText && !hasError && (
          <p className={`text-xs ${fieldMode ?'text-nb-black/50' :'text-nb-black/40'}`}>
            {field.helpText}
          </p>
        )}
      </div>
    );
  }

  // Read-only display
  return (
    <div key={field.id} className="flex flex-col">
      <span className={`text-xs font-medium mb-1 ${fieldMode ?'text-nb-black/50' :'text-nb-black/50'}`}>
        {field.label}
      </span>
      <span className={`text-sm ${fieldMode ?'text-white' :'text-nb-black'}`}>
        {displayValue}
      </span>
    </div>
  );
};

export default MetadataFieldRenderer;
