// components/MuseumLabel.tsx

import React from 'react';
import { Icon } from '@/src/shared/ui/atoms/Icon';

interface MuseumLabelProps {
  title: string;
  subtitle?: string;
  children: React.ReactNode;
  type?: 'field-note' | 'exhibit' | 'spec';
}

export const MuseumLabel: React.FC<MuseumLabelProps> = ({ title, subtitle, children, type = 'field-note' }) => {
  const styles = {
    'field-note': 'bg-amber-50 border-amber-200 text-amber-900',
    'exhibit': 'bg-blue-50 border-blue-200 text-blue-900',
    'spec': 'bg-slate-900 border-slate-700 text-slate-100',
  };

  return (
    <div className={`p-4 rounded-xl border-l-4 shadow-sm my-4 animate-in fade-in slide-in-from-left-2 ${styles[type]}`}>
      <div className="flex items-center gap-2 mb-2">
        <Icon name={type === 'field-note' ? 'history_edu' : type === 'exhibit' ? 'account_balance' : 'terminal'} className="text-sm opacity-60" />
        <h4 className="text-[10px] font-black uppercase tracking-widest opacity-70">{title}</h4>
      </div>
      {subtitle && <p className="text-xs font-bold mb-2">{subtitle}</p>}
      <div className="text-xs leading-relaxed opacity-90 italic">
        {children}
      </div>
    </div>
  );
};

// src/shared/ui/molecules/MuseumLabel.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import { cn } from '@/src/shared/lib/cn';

  interface Props {
    title: string;
    date?: string;
    description?: string;
    attribution?: string;
    class?: string;
    type?: string;
    cx?: ContextualClassNames;
    fieldMode?: boolean;
    children?: Snippet;
  }

  let { title, date, description, attribution, class: className = '', type: _type, cx = {} as ContextualClassNames, fieldMode = false, children }: Props = $props();
</script>

<div class={cn('bg-nb-cream border-4 border-nb-black shadow-brutal p-6', className)}>
  <h3 class="text-lg font-bold uppercase font-mono tracking-wide mb-1">{title}</h3>

  {#if date}
    <p class="text-xs font-mono text-nb-black/60 mb-3">{date}</p>
  {/if}

  {#if description}
    <p class="text-sm leading-relaxed mb-3 font-serif">{description}</p>
  {/if}

  {#if attribution}
    <p class="text-xs font-mono text-nb-black/50 border-t-2 border-nb-black/20 pt-2 mt-2">{attribution}</p>
  {/if}

  {#if children}
    <div class="mt-2">{@render children()}</div>
  {/if}
</div>
