// src/shared/ui/molecules/RangeSelector.svelte
<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import { cn } from '@/src/shared/lib/cn';
  import Button from '../atoms/Button.svelte';
  import Icon from '../atoms/Icon.svelte';

  interface Preset {
    label: string;
    start: string;
    end: string;
  }

  interface Props {
    start: string;
    end: string;
    onApply: (range: { start: string; end: string }) => void;
    presets?: Preset[];
    minDate?: string;
    maxDate?: string;
    showPresets?: boolean;
    disabled?: boolean;
    cx: ContextualClassNames;
    fieldMode?: boolean;
  }

  let {
    start = $bindable(''),
    end = $bindable(''),
    onApply,
    presets = [],
    minDate,
    maxDate,
    showPresets = true,
    disabled = false,
    cx,
    fieldMode = false
  }: Props = $props();

  let localStart = $state(start);
  let localEnd = $state(end);
  let showPresetMenu = $state(false);
  let validationError = $state('');
  let presetRef: HTMLDivElement | undefined = $state();

  $effect(() => { if (start !== localStart) localStart = start; });
  $effect(() => { if (end !== localEnd) localEnd = end; });

  // Date API calls (getTime) — not external services, safe for reactive context
   
  function validateRange(s: string, e: string): boolean {
    if (!s || !e) { validationError = 'Both start and end dates are required'; return false; }
    const st = new Date(s).getTime();
    const et = new Date(e).getTime();
    if (st > et) { validationError = 'Start date must be before end date'; return false; }
    if (minDate && st < new Date(minDate).getTime()) { validationError = `Start date cannot be before ${minDate}`; return false; }
    if (maxDate && et > new Date(maxDate).getTime()) { validationError = `End date cannot be after ${maxDate}`; return false; }
    validationError = '';
    return true;
  }
   

  const isValid = $derived(validateRange(localStart, localEnd));

  function handleApply() {
    if (!isValid) return;
    start = localStart;
    end = localEnd;
    onApply({ start: localStart, end: localEnd });
  }

  function handlePresetSelect(preset: Preset) {
    localStart = preset.start;
    localEnd = preset.end;
    showPresetMenu = false;
    if (validateRange(preset.start, preset.end)) {
      start = preset.start;
      end = preset.end;
      onApply({ start: preset.start, end: preset.end });
    }
  }

  function handleReset() {
    localStart = '';
    localEnd = '';
    validationError = '';
  }

  // Click-outside for presets
  $effect(() => {
    if (!showPresetMenu || !presetRef) return;
    function handleClickOutside(e: MouseEvent) {
      if (presetRef && !presetRef.contains(e.target as Node)) showPresetMenu = false;
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  });
</script>

<div class="flex flex-col gap-4">
  <div class="flex gap-4 items-end">
    <div class="flex-1">
      <label for="field-start-date" class={cn(cx.label || 'text-[11px] font-bold uppercase tracking-wider font-mono', 'block mb-2')}>Start Date</label>
      <input id="field-start-date"
        type="date"
        bind:value={localStart}
        min={minDate}
        max={maxDate}
        {disabled}
        class={cx.input || 'w-full border-2 border-nb-black px-3 py-2 font-mono'}
      />
    </div>

    <div class="flex-1">
      <label for="field-end-date" class={cn(cx.label || 'text-[11px] font-bold uppercase tracking-wider font-mono', 'block mb-2')}>End Date</label>
      <input id="field-end-date"
        type="date"
        bind:value={localEnd}
        min={minDate}
        max={maxDate}
        {disabled}
        class={cx.input || 'w-full border-2 border-nb-black px-3 py-2 font-mono'}
      />
    </div>

    {#if showPresets && presets.length > 0}
      <div class="relative" bind:this={presetRef}>
        <Button variant="ghost" onclick={() => showPresetMenu = !showPresetMenu} {disabled}>
          {#snippet children()}
            <Icon name="date_range" class="text-base" />
            <span>Presets</span>
          {/snippet}
        </Button>

        {#if showPresetMenu}
          <div class={cn('absolute right-0 mt-1 w-48 border-2 shadow-lg z-50 py-1', cx.surface || 'bg-nb-white border-nb-black')}>
            {#each presets as preset (preset.label)}
              <button
                type="button"
                class="w-full px-4 py-2 text-left text-sm hover:bg-nb-cream cursor-pointer border-0 bg-transparent"
                onclick={() => handlePresetSelect(preset)}
              >{preset.label}</button>
            {/each}
          </div>
        {/if}
      </div>
    {/if}
  </div>

  {#if validationError}
    <div class="text-sm text-red-600 font-mono">{validationError}</div>
  {/if}

  <div class="flex gap-2 justify-end">
    <Button variant="ghost" onclick={handleReset} {disabled}>
      {#snippet children()}<span>Reset</span>{/snippet}
    </Button>
    <Button variant="primary" onclick={handleApply} disabled={disabled || !isValid}>
      {#snippet children()}<span>Apply Range</span>{/snippet}
    </Button>
  </div>
</div>

// src/shared/ui/molecules/RangeSelector.tsx
/**
 * RangeSelector Molecule
 *
 * A date/time range selector for filtering timeline or temporal views.
 * Composes input atoms with range validation.
 *
 * ATOMIC DESIGN:
 * - Composes: Input atom, Button atom
 * - Has local state: start, end inputs
 * - No domain logic (filtering managed by parent)
 *
 * IDEAL OUTCOME: Easy selection of temporal ranges with validation
 * FAILURE PREVENTED: Invalid date ranges, ambiguous date formats
 *
 * @example
 * <RangeSelector
 *   start="2023-01-01"
 *   end="2023-12-31"
 *   onChange={({ start, end }) => setRange({ start, end })}
 *   presets={[
 *     { label:'Last 30 days', start:'2023-11-01', end:'2023-12-01' },
 *     { label:'This year', start:'2023-01-01', end:'2023-12-31' },
 *   ]}
 * />
 */

import React, { useCallback, useEffect, useState } from 'react';
import { Button } from '../atoms';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';

export interface RangePreset {
  label: string;
  start: string;
  end: string;
}

export interface RangeSelectorProps {
  /** Start date (ISO format: YYYY-MM-DD) */
  start: string;
  /** End date (ISO format: YYYY-MM-DD) */
  end: string;
  /** Called when range changes */
  onChange: (range: { start: string; end: string }) => void;
  /** Optional presets for quick selection */
  presets?: RangePreset[];
  /** Minimum allowed date */
  minDate?: string;
  /** Maximum allowed date */
  maxDate?: string;
  /** Show presets dropdown */
  showPresets?: boolean;
  /** Disabled state */
  disabled?: boolean;
  /** Contextual styles from template (required for theming) */
  cx: ContextualClassNames;
  fieldMode?: boolean;
}

/**
 * RangeSelector Component
 *
 * Date range input with validation and presets.
 */
export const RangeSelector: React.FC<RangeSelectorProps> = ({
  start,
  end,
  onChange,
  presets = [],
  minDate,
  maxDate,
  showPresets = true,
  disabled = false,
  cx,
}) => {

  // Local state for inputs
  const [startInput, setStartInput] = useState(start);
  const [endInput, setEndInput] = useState(end);
  const [showPresetMenu, setShowPresetMenu] = useState(false);

  // Sync with props
  useEffect(() => {
    setStartInput(start);
  }, [start]);

  useEffect(() => {
    setEndInput(end);
  }, [end]);

  // Validation
  const validateRange = useCallback(
    (startVal: string, endVal: string): boolean => {
      if (!startVal || !endVal) return false;

      const startDate = new Date(startVal);
      const endDate = new Date(endVal);

      // Start must be before end
      if (startDate > endDate) return false;

      // Check min/max constraints
      if (minDate && startDate < new Date(minDate)) return false;
      if (maxDate && endDate > new Date(maxDate)) return false;

      return true;
    },
    [minDate, maxDate]
  );

  const isValid = validateRange(startInput, endInput);

  // Apply range
  const handleApply = useCallback(() => {
    if (isValid) {
      onChange({ start: startInput, end: endInput });
    }
  }, [startInput, endInput, isValid, onChange]);

  // Apply preset
  const handlePreset = useCallback(
    (preset: RangePreset) => {
      setStartInput(preset.start);
      setEndInput(preset.end);
      onChange({ start: preset.start, end: preset.end });
      setShowPresetMenu(false);
    },
    [onChange]
  );

  // Clear range
  const handleClear = useCallback(() => {
    setStartInput('');
    setEndInput('');
    onChange({ start:'', end:'' });
  }, [onChange]);

  return (
    <div className="space-y-3">
      {/* Date inputs */}
      <div className="flex items-center gap-2">
        <div className="flex-1">
          <label className={`block text-xs ${cx.textMuted} mb-1`}>Start</label>
          <input
            type="date"
            value={startInput}
            onChange={(e) => setStartInput(e.target.value)}
            min={minDate}
            max={maxDate}
            disabled={disabled}
            className={`
              w-full px-3 py-2 border text-sm
              ${cx.input} ${cx.border}
              focus:ring-2 focus:ring-inset focus:${cx.accent}
              ${disabled ?'opacity-50 cursor-not-allowed' :''}
`}
          />
        </div>

        <span className={`${cx.textMuted} pt-5`}>to</span>

        <div className="flex-1">
          <label className={`block text-xs ${cx.textMuted} mb-1`}>End</label>
          <input
            type="date"
            value={endInput}
            onChange={(e) => setEndInput(e.target.value)}
            min={minDate || startInput}
            max={maxDate}
            disabled={disabled}
            className={`
              w-full px-3 py-2 border text-sm
              ${cx.input} ${cx.border}
              focus:ring-2 focus:ring-inset focus:${cx.accent}
              ${disabled ?'opacity-50 cursor-not-allowed' :''}
`}
          />
        </div>
      </div>

      {/* Validation message */}
      {!isValid && startInput && endInput && (
        <p className="text-xs text-nb-red">
          Invalid range: Start date must be before end date
        </p>
      )}

      {/* Actions */}
      <div className="flex items-center gap-2">
        <Button
          variant="primary"
          size="sm"
          onClick={handleApply}
          disabled={disabled || !isValid}
        >
          Apply
        </Button>

        {(start || end) && (
          <Button
            variant="secondary"
            size="sm"
            onClick={handleClear}
            disabled={disabled}
          >
            Clear
          </Button>
        )}

        {/* Presets dropdown */}
        {showPresets && presets.length > 0 && (
          <div className="relative ml-auto">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setShowPresetMenu(!showPresetMenu)}
              disabled={disabled}
            >
              Presets
              <span className="material-icons text-sm ml-1">
                {showPresetMenu ?'expand_less' :'expand_more'}
              </span>
            </Button>

            {showPresetMenu && (
              <div
                className={`
                  absolute right-0 top-full mt-1 w-48
                   shadow-brutal border ${cx.border} ${cx.surface}
                  z-50 overflow-hidden
`}
              >
                {presets.map((preset) => (
                  <Button
                    key={preset.label}
                    onClick={() => handlePreset(preset)}
                    variant="ghost"
                    size="sm"
                    className={`
                      w-full px-3 py-2 text-left text-sm
                      hover:${cx.headerBg} ${cx.text}
                      justify-start
`}
                  >
                    {preset.label}
                  </Button>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default RangeSelector;
