// src/shared/ui/molecules/StackedThumbnail.tsx
/**
 * StackedThumbnail Molecule
 *
 * Displays a single thumbnail or a grid of up to 4 thumbnails.
 * Used for showing collection/manifest previews.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Props-driven, no context
 * - Local state only (failed image tracking)
 * - Uses Icon atom
 */

import React, { useCallback, useState } from 'react';
import { Icon } from '../atoms';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';

export interface StackedThumbnailProps {
  /** URLs of images to display */
  urls: string[];
  /** Size preset */
  size?:'xs' |'sm' |'md' |'lg' |'xl';
  /** Additional CSS classes */
  className?: string;
  /** Icon to show when no images */
  icon?: string;
  /** Background class for placeholder */
  placeholderBg?: string;
  /** Contextual styles from template (optional, for theming) */
  cx?: ContextualClassNames;
  /** Current field mode */
  fieldMode?: boolean;
}

const containerSizes = {
  xs:'w-6 h-6 rounded',
  sm:'w-10 h-10',
  md:'w-16 h-16',
  lg:'w-full h-full',
  xl:'w-40 h-40',
};

export const StackedThumbnail: React.FC<StackedThumbnailProps> = ({
  urls,
  size ='md',
  className ='',
  icon ='image',
  placeholderBg,
  cx,
  fieldMode: _fieldMode,
}) => {
  const [failedUrls, setFailedUrls] = useState<Set<string>>(new Set());

  const handleImageError = useCallback((url: string) => {
    setFailedUrls((prev) => new Set([...prev, url]));
  }, []);

  const bgClass = placeholderBg || cx?.subtleBg ||'bg-nb-cream';
  const iconColor = cx?.textMuted ||'text-nb-black/30';

  // Filter out failed URLs
  const validUrls = urls.filter((url) => url && !failedUrls.has(url));
  const urlCount = validUrls.length;

  // Show placeholder if no valid URLs
  if (urlCount === 0) {
    return (
      <div
        className={`${containerSizes[size]} ${bgClass} flex items-center justify-center shrink-0 overflow-hidden border ${cx?.border ||'border-nb-black/20'} ${className}`}
      >
        <Icon name={icon} className={iconColor} />
      </div>
    );
  }

  // Single image
  if (urlCount === 1) {
    return (
      <div
        className={`${containerSizes[size]} bg-nb-black shrink-0 overflow-hidden border ${cx?.border ||'border-nb-black/20'} ${className}`}
      >
        <img
          src={validUrls[0]}
          alt=""
          className="w-full h-full object-cover"
          loading="lazy"
          onError={() => handleImageError(validUrls[0])}
        />
      </div>
    );
  }

  // Grid layout for 2-4 images
  return (
    <div
      className={`${containerSizes[size]} ${cx?.separator ||'bg-nb-cream'} shrink-0 overflow-hidden ${cx?.border ||'border-nb-black/20'} grid grid-cols-2 grid-rows-2 gap-0.5 ${className}`}
    >
      {validUrls.slice(0, 4).map((url, i) => (
        <div
          key={i}
          className={`bg-nb-black ${
            urlCount === 2 && i === 0 ?'col-span-1 row-span-2' :''
          } ${
            urlCount === 2 && i === 1 ?'col-span-1 row-span-2' :''
          } ${urlCount === 3 && i === 0 ?'col-span-2 row-span-1' :''}`}
        >
          <img
            src={url}
            alt=""
            className="w-full h-full object-cover"
            loading="lazy"
            onError={() => handleImageError(url)}
          />
        </div>
      ))}
      {/* Fill empty cells if we have 3 images */}
      {urlCount === 3 && (
        <div className={`${cx?.subtleBg ||'bg-nb-black'} flex items-center justify-center`}>
          <Icon name={icon} className={`text-[10px] ${cx?.textMuted ||'text-nb-black/50'}`} />
        </div>
      )}
    </div>
  );
};

// src/shared/ui/molecules/StackedThumbnail.svelte
<script lang="ts">
  import type { ContextualClassNames } from './ViewHeader/types';

  interface Props {
    urls: string[];
    size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
    class?: string;
    icon?: string;
    placeholderBg?: string;
    cx?: ContextualClassNames;
    fieldMode?: boolean;
  }

  let {
    urls,
    size = 'md',
    class: className = '',
    icon = 'image',
    placeholderBg,
    cx,
    fieldMode: _fieldMode,
  }: Props = $props();

  const containerSizes: Record<string, string> = {
    xs: 'w-6 h-6 rounded',
    sm: 'w-10 h-10',
    md: 'w-16 h-16',
    lg: 'w-full h-full',
    xl: 'w-40 h-40',
  };

  let failedUrls = $state<Set<string>>(new Set());

  function handleImageError(url: string) {
    failedUrls = new Set([...failedUrls, url]);
  }

  const bgClass = $derived(placeholderBg ?? cx?.subtleBg ?? 'bg-nb-cream');
  const iconColor = $derived(cx?.textMuted ?? 'text-nb-black/30');
  const borderClass = $derived(cx?.border ?? 'border-nb-black/20');
  const containerSize = $derived(containerSizes[size]);
  const validUrls = $derived(urls.filter(u => u && !failedUrls.has(u)));
  const urlCount = $derived(validUrls.length);
</script>

{#if urlCount === 0}
  <div class={`${containerSize} ${bgClass} flex items-center justify-center shrink-0 overflow-hidden border ${borderClass} ${className}`}>
    <span class={`material-icons ${iconColor}`}>{icon}</span>
  </div>
{:else if urlCount === 1}
  <div class={`${containerSize} bg-nb-black shrink-0 overflow-hidden border ${borderClass} ${className}`}>
    <img
      src={validUrls[0]}
      alt=""
      class="w-full h-full object-cover"
      loading="lazy"
      onerror={() => handleImageError(validUrls[0])}
    />
  </div>
{:else}
  <div class={`${containerSize} ${cx?.separator ?? 'bg-nb-cream'} shrink-0 overflow-hidden ${borderClass} grid grid-cols-2 grid-rows-2 gap-0.5 ${className}`}>
    {#each validUrls.slice(0, 4) as url, i}
      <div
        class={`bg-nb-black
          ${urlCount === 2 ? 'col-span-1 row-span-2' : ''}
          ${urlCount === 3 && i === 0 ? 'col-span-2 row-span-1' : ''}
        `}
      >
        <img src={url} alt="" class="w-full h-full object-cover" loading="lazy" onerror={() => handleImageError(url)} />
      </div>
    {/each}
    {#if urlCount === 3}
      <div class={`${cx?.subtleBg ?? 'bg-nb-black'} flex items-center justify-center`}>
        <span class={`material-icons text-[10px] ${cx?.textMuted ?? 'text-nb-black/50'}`}>{icon}</span>
      </div>
    {/if}
  </div>
{/if}
