// src/shared/ui/molecules/TimelineTick.svelte
<script lang="ts">
  import type { ContextualClassNames } from './ViewHeader/types';

  export interface TimelineItem {
    id: string;
    title: string;
    type: string;
    thumbnail?: string;
    timestamp: string;
  }

  interface Props {
    timestamp: string;
    label: string;
    items: TimelineItem[];
    position: number;
    onSelectItem: (id: string) => void;
    selected?: boolean;
    size?: 'sm' | 'md' | 'lg';
    disabled?: boolean;
    cx: ContextualClassNames;
    fieldMode?: boolean;
  }

  let {
    timestamp: _timestamp,
    label,
    items,
    position,
    onSelectItem,
    selected = false,
    size = 'md',
    disabled = false,
    cx,
    fieldMode: _fieldMode,
  }: Props = $props();

  let isHovered = $state(false);
  let isExpanded = $state(false);

  const count = $derived(items.length);

  const sizeConfig = {
    sm: { dot: 'w-2 h-2', label: 'text-[10px]', badge: 'text-[8px]' },
    md: { dot: 'w-3 h-3', label: 'text-xs', badge: 'text-[10px]' },
    lg: { dot: 'w-4 h-4', label: 'text-sm', badge: 'text-xs' },
  };

  // Intensity thresholds for color: > 10 items = high, > 3 = med, else low
  const intensity = $derived(
    count > 10 ? 'bg-nb-red' : count > 3 ? 'bg-nb-blue' : 'bg-nb-black/50'
  );

  const config = $derived(sizeConfig[size]);

  function handleTickClick() {
    if (count === 1) {
      onSelectItem(items[0].id);
    } else {
      isExpanded = !isExpanded;
    }
  }
</script>

<div
  class="absolute flex flex-col items-center"
  style={`left: ${position * 100}%`}
  onmouseenter={() => { isHovered = true; }}
  onmouseleave={() => { isHovered = false; }}
>
  <!-- Label above tick -->
  <span class={`${config.label} ${cx.textMuted ?? 'text-nb-black/40'} whitespace-nowrap mb-1 transition-nb ${isHovered || selected ? 'opacity-100' : 'opacity-60'}`}>
    {label}
  </span>

  <!-- Tick dot -->
  <button
    onclick={handleTickClick}
    {disabled}
    class={`
      ${config.dot} relative transition-nb p-0
      ${intensity}
      ${selected ? 'ring-2 ring-offset-2 ring-current scale-150' : 'hover:scale-125'}
      ${disabled ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}
      ${isHovered ? 'shadow-brutal' : ''}
    `}
    aria-label={`${label}: ${count} items`}
    aria-expanded={isExpanded}
  >
    <!-- Count badge for multiple items -->
    {#if count > 1}
      <span class={`absolute -top-2 -right-2 min-w-[14px] h-3.5 px-1 bg-current text-white font-bold flex items-center justify-center ${config.badge}`}>
        {count > 9 ? '9+' : count}
      </span>
    {/if}
  </button>

  <!-- Expanded item popup -->
  {#if isExpanded && count > 1}
    <div class={`absolute top-full left-1/2 -translate-x-1/2 mt-3 w-56 shadow-brutal border ${cx.border ?? 'border-nb-black/20'} ${cx.surface ?? 'bg-nb-white'} z-50 overflow-hidden`}>
      <!-- Header -->
      <div class={`px-3 py-2 border-b ${cx.border ?? 'border-nb-black/20'} ${cx.headerBg ?? 'bg-nb-cream'} flex justify-between items-center`}>
        <span class={`text-sm font-medium ${cx.text ?? 'text-nb-black'}`}>{label} ({count} items)</span>
        <button onclick={() => { isExpanded = false; }} class="p-1 hover:opacity-70" aria-label="Close">
          <span class={`material-icons text-sm ${cx.textMuted ?? 'text-nb-black/40'}`}>close</span>
        </button>
      </div>

      <!-- Item list -->
      <div class="p-2 space-y-1 max-h-48 overflow-auto">
        {#each items as item}
          <button
            onclick={() => { onSelectItem(item.id); isExpanded = false; }}
            class={`w-full flex items-center gap-2 p-2 text-left transition-nb hover:${cx.headerBg ?? 'bg-nb-cream'}`}
          >
            {#if item.thumbnail}
              <img src={item.thumbnail} alt="" class="w-8 h-8 object-cover" />
            {:else}
              <div class={`w-8 h-8 flex items-center justify-center ${cx.headerBg ?? 'bg-nb-cream'}`}>
                <span class={`material-icons text-sm ${cx.textMuted ?? 'text-nb-black/40'}`}>image</span>
              </div>
            {/if}
            <div class="flex-1 min-w-0">
              <p class={`text-sm truncate ${cx.text ?? 'text-nb-black'}`}>{item.title}</p>
              <p class={`text-xs ${cx.textMuted ?? 'text-nb-black/40'}`}>{item.type}</p>
            </div>
          </button>
        {/each}
      </div>
    </div>
  {/if}
</div>

// src/shared/ui/molecules/TimelineTick.tsx
/**
 * TimelineTick Molecule
 *
 * A tick marker for temporal timelines showing IIIF resources.
 * Supports single items and clustered items at the same time point.
 *
 * ATOMIC DESIGN:
 * - Composes: Icon atom, Badge atom
 * - Has local state: hover, expanded
 * - No domain logic (timeline state managed by parent)
 *
 * IDEAL OUTCOME: Clear temporal representation of resource distribution
 * FAILURE PREVENTED: Timeline overcrowding, unclear temporal relationships
 *
 * @example
 * <TimelineTick
 *   timestamp="2023-01-15"
 *   label="Jan 15"
 *   items={[{ id:'1', title:'Photo 1', type:'Canvas' }]}
 *   position={0.5}
 *   onSelectItem={(id) => openItem(id)}
 * />
 */

import React, { useState } from 'react';
import { Button } from '../atoms';
import { IconButton } from './IconButton';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';
import { TIMELINE_DENSITY } from '../../config/tokens';

export interface TimelineItem {
  id: string;
  title: string;
  type: string;
  thumbnail?: string;
  timestamp: string;
}

export interface TimelineTickProps {
  /** ISO timestamp for this tick */
  timestamp: string;
  /** Display label (e.g.,"Jan 15" or"2023") */
  label: string;
  /** Items at this time point */
  items: TimelineItem[];
  /** Position along timeline (0-1) */
  position: number;
  /** Called when an item is selected */
  onSelectItem: (id: string) => void;
  /** Whether this tick is currently selected */
  selected?: boolean;
  /** Size variant */
  size?:'sm' |'md' |'lg';
  /** Disabled state */
  disabled?: boolean;
  /** Contextual styles from template (required for theming) */
  cx: ContextualClassNames;
  fieldMode?: boolean;
}

/**
 * TimelineTick Component
 *
 * Temporal marker with expandable item preview.
 */
export const TimelineTick: React.FC<TimelineTickProps> = ({
  timestamp: _timestamp,
  label,
  items,
  position,
  onSelectItem,
  selected = false,
  size ='md',
  disabled = false,
  cx,
}) => {
  const [isHovered, setIsHovered] = useState(false);
  const [isExpanded, setIsExpanded] = useState(false);

  const count = items.length;

  // Size configurations
  const sizeConfig = {
    sm: { dot:'w-2 h-2', label:'text-[10px]', badge:'text-[8px]' },
    md: { dot:'w-3 h-3', label:'text-xs', badge:'text-[10px]' },
    lg: { dot:'w-4 h-4', label:'text-sm', badge:'text-xs' },
  };

  const config = sizeConfig[size];

  // Determine tick intensity based on item count — from design tokens
  const getIntensity = () => {
    const match = TIMELINE_DENSITY.thresholds.find(t => count >= t.min);
    return match ? match.color : TIMELINE_DENSITY.single;
  };

  return (
    <div
      className="absolute flex flex-col items-center"
      style={{ left:`${position * 100}%` }}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
    >
      {/* Label above tick */}
      <span
        className={`
          ${config.label} ${cx.textMuted} whitespace-nowrap mb-1
          transition-nb ${isHovered || selected ?'opacity-100' :'opacity-60'}
`}
      >
        {label}
      </span>

      {/* Tick dot */}
      <Button
        onClick={() => {
          if (count === 1) {
            onSelectItem(items[0].id);
          } else {
            setIsExpanded(!isExpanded);
          }
        }}
        disabled={disabled}
        variant="ghost"
        size="sm"
        className={`
          ${config.dot}  transition-nb  p-0
          ${getIntensity()}
          ${selected ?'ring-2 ring-offset-2 ring-current scale-150' :'hover:scale-125'}
          ${disabled ?'opacity-50 cursor-not-allowed' :'cursor-pointer'}
          ${isHovered ?'shadow-brutal' :''}
`}
        aria-label={`${label}: ${count} items`}
        aria-expanded={isExpanded}
      >
        {/* Count badge for multiple items */}
        {count > 1 && (
          <span
            className={`
              absolute -top-2 -right-2 min-w-[14px] h-3.5 px-1
               bg-current text-white font-bold
              flex items-center justify-center ${config.badge}
`}
          >
            {count > 9 ?'9+' : count}
          </span>
        )}
      </Button>

      {/* Expanded item popup */}
      {isExpanded && count > 1 && (
        <div
          className={`
            absolute top-full left-1/2 -translate-x-1/2 mt-3 w-56
             shadow-brutal border ${cx.border} ${cx.surface}
            z-50 overflow-hidden
`}
        >
          {/* Header */}
          <div
            className={`
              px-3 py-2 border-b ${cx.border} ${cx.headerBg}
              flex justify-between items-center
`}
          >
            <span className={`text-sm font-medium ${cx.text}`}>
              {label} ({count} items)
            </span>
            <IconButton
              icon="close"
              ariaLabel="Close"
              onClick={() => setIsExpanded(false)}
              variant="ghost"
              size="sm"
              className={cx.textMuted}
              cx={cx}
            />
          </div>

          {/* Item list */}
          <div className="p-2 space-y-1 max-h-48 overflow-auto">
            {items.map((item) => (
              <Button
                key={item.id}
                onClick={() => {
                  onSelectItem(item.id);
                  setIsExpanded(false);
                }}
                variant="ghost"
                size="sm"
                className={`
                  w-full flex items-center gap-2 p-2 rounded
                  text-left transition-nb hover:${cx.headerBg}
                  justify-start
`}
              >
                {item.thumbnail ? (
                  <img
                    src={item.thumbnail}
                    alt=""
                    className="w-8 h-8 object-cover"
                  />
                ) : (
                  <div
                    className={`
                      w-8 h-8 flex items-center justify-center
                      ${cx.headerBg}
`}
                  >
                    <span className={`material-icons text-sm ${cx.textMuted}`}>
                      image
                    </span>
                  </div>
                )}
                <div className="flex-1 min-w-0">
                  <p className={`text-sm truncate ${cx.text}`}>{item.title}</p>
                  <p className={`text-xs ${cx.textMuted}`}>{item.type}</p>
                </div>
              </Button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default TimelineTick;
