// src/features/structure-view/ui/atoms/ExpandButton.tsx
/**
 * Expand Button Atom
 *
 * Simple toggle button for expanding/collapsing tree nodes.
 * Zero business logic - just visual state.
 */

import React from 'react';
import { Button } from '@/src/shared/ui/atoms';
import { cn } from '@/src/shared/lib/cn';

interface ExpandButtonProps {
  isExpanded: boolean;
  onClick: (e: React.MouseEvent) => void;
  hasChildren: boolean;
  className?: string;
  /** Field mode flag */
  fieldMode?: boolean;
}

export const ExpandButton: React.FC<ExpandButtonProps> = ({
  isExpanded,
  onClick,
  hasChildren,
  className = '',
  fieldMode,
}) => {
  if (!hasChildren) {
    return <span className="w-5 h-5 inline-block" />;
  }

  return (
    <Button variant="ghost" size="bare"
      type="button"
      onClick={onClick}
      className={cn('w-5 h-5 inline-flex items-center justify-center transition-nb', fieldMode ? 'hover:bg-nb-yellow/20' : 'hover:bg-nb-black/10', className)}
      aria-label={isExpanded ? 'Collapse' : 'Expand'}
    >
      <svg
        className={`w-3 h-3 transition-transform ${isExpanded ? 'rotate-90' : ''}`}
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
      >
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
      </svg>
    </Button>
  );
};

ExpandButton.displayName = 'ExpandButton';

// src/features/structure-view/ui/atoms/ExpandButton.svelte
<!--
  ExpandButton.svelte — Chevron toggle for tree nodes
  React source: ExpandButton.tsx (52L)
  Pure presentational: expand/collapse chevron
-->
<script lang="ts">
  import { cn } from '@/src/shared/lib/cn';
  import Button from '@/src/shared/ui/atoms/Button.svelte';

  interface Props {
    isExpanded: boolean;
    onclick: (e: MouseEvent) => void;
    hasChildren: boolean;
    class?: string;
    fieldMode?: boolean;
  }

  let { isExpanded, onclick, hasChildren, class: className = '', fieldMode = false }: Props = $props();
</script>

{#if !hasChildren}
  <span class="w-5 h-5 inline-block"></span>
{:else}
  <Button variant="ghost" size="bare"
    type="button"
    {onclick}
    class={cn('w-5 h-5 inline-flex items-center justify-center transition-nb', fieldMode ? 'hover:bg-nb-yellow/20' : 'hover:bg-nb-black/10', className)}
    aria-label={isExpanded ? 'Collapse' : 'Expand'}
  >
    <svg
      class={cn('w-3 h-3 transition-transform', isExpanded && 'rotate-90')}
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
    >
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
    </svg>
  </Button>
{/if}
