// src/features/structure-view/ui/atoms/NodeLabel.svelte
<!--
  NodeLabel.svelte — Styled tree node label
  React source: NodeLabel.tsx (47L)
  Pure presentational: label text with selection/drag styling
-->
<script lang="ts">
  import { cn } from '@/src/shared/lib/cn';
  import type { ContextualClassNames } from '@/src/shared/ui/molecules/ViewHeader/types';

  interface Props {
    label: string;
    type: string;
    isSelected: boolean;
    isDragging: boolean;
    class?: string;
    cx?: Partial<ContextualClassNames>;
  }

  let { label, type, isSelected, isDragging, class: className = '', cx }: Props = $props();

  const stateClasses = $derived(
    isSelected
      ? cn('font-semibold', cx?.accent ?? 'text-nb-blue')
      : cn(cx?.textMuted ?? 'text-nb-black/70')
  );
</script>

<span
  class={cn('truncate text-sm', stateClasses, isDragging && 'opacity-50', className)}
  title={label}
>
  {label}
</span>

// src/features/structure-view/ui/atoms/NodeLabel.tsx
/**
 * Node Label Atom
 *
 * Displays a tree node label with appropriate styling.
 * Zero business logic - pure presentation.
 */

import React from 'react';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';
import { cn } from '@/src/shared/lib/cn';

interface NodeLabelProps {
  label: string;
  type: string;
  isSelected: boolean;
  isDragging: boolean;
  className?: string;
  /** Contextual class names from parent */
  cx?: Partial<ContextualClassNames>;
}

export const NodeLabel: React.FC<NodeLabelProps> = ({
  label,
  type,
  isSelected,
  isDragging,
  className = '',
  cx,
}) => {
  const baseClasses = 'truncate text-sm';
  const stateClasses = isSelected
    ? cn('font-semibold', cx?.accent ?? 'text-nb-blue')
    : cn(cx?.textMuted ?? 'text-nb-black/70');
  const dragClasses = isDragging ? 'opacity-50' : '';

  return (
    <span
      className={cn(baseClasses, stateClasses, dragClasses, className)}
      title={label}
    >
      {label}
    </span>
  );
};

NodeLabel.displayName = 'NodeLabel';
