// src/features/timeline/ui/organisms/TimelineView.svelte
<!--
  TimelineView.svelte — Chronological Timeline View
  ====================================================
  React source: src/features/timeline/ui/organisms/TimelineView.tsx

  ARCHITECTURE:
  - Feature organism: Date-grouped canvas display with zoom levels
  - Uses PaneLayout with variant="default" (scrollable body)
  - SubBar shows date range minimap
  - Pure Svelte rendering (no external lib)

  PROPS:
  - root: IIIFItem — IIIF tree
  - cx: ContextualClassNames
  - fieldMode: boolean
  - t: TerminologyFn
  - onSelect: (item: IIIFItem) => void
  - onSwitchView: (mode: string) => void
-->

<script lang="ts">
  import { PaneLayout, Row } from '@/src/shared/ui/layout';
  import ViewHeader from '@/src/shared/ui/molecules/ViewHeader/ViewHeader.svelte';
  import type { ContextualClassNames } from '@/src/shared/ui/molecules/ViewHeader/types';
  import Center from '@/src/shared/ui/layout/primitives/Center.svelte';
  import Button from '@/src/shared/ui/atoms/Button.svelte';
  import { cn } from '@/src/shared/lib/cn';
  import { TimelineStore } from '@/src/features/timeline/stores/timeline.svelte';
  import type { ZoomLevel, TimelineGroup, TimelineItem } from '@/src/features/timeline/stores/timeline.svelte';
  import type { IIIFItem } from '@/src/shared/types';
  import { getIIIFValue } from '@/src/shared/types';

  interface Props {
    root: IIIFItem;
    cx: ContextualClassNames;
    fieldMode: boolean;
    t: (key: string, fallback?: string) => string;
    onSelect: (item: IIIFItem) => void;
    onSwitchView: (mode: string) => void;
  }

  let { root, cx, fieldMode, t, onSelect, onSwitchView }: Props = $props();

  // ── Feature Store ──
  const timeline = new TimelineStore();

  // ── Derived ──
  const groups = $derived(timeline.groups);
  const hasItems = $derived(timeline.hasData);
  const zoomLevel = $derived(timeline.zoomLevel);
  const totalItems = $derived(timeline.totalItems);
  const selectedDate = $derived(timeline.selectedDate);

  const gridColumnsClass = $derived(
    zoomLevel === 'day' ? 'grid-cols-7' :
    zoomLevel === 'month' ? 'grid-cols-4' : 'grid-cols-3'
  );

  const zoomLevels: ZoomLevel[] = ['day', 'month', 'year'];

  // ── Effects ──

  // Initialize timeline store from root's canvases (items with navDate)
  $effect(() => {
    // @migration: root.items may be canvases or manifests; extract canvas-level navDate
    const items = root.items ?? [];
    const canvases = items
      .filter((item: IIIFItem) => item.type === 'Canvas' || item.type === 'Manifest')
      .flatMap((item: IIIFItem) => {
        if (item.type === 'Canvas') return [item];
        return item.items ?? [];
      })
      .map((canvas: IIIFItem) => ({
        id: canvas.id,
        label: getIIIFValue(canvas.label) || canvas.id,
        navDate: canvas.navDate,
      }));

    timeline.loadFromCanvases(canvases);
  });

  // ── Handlers ──
  function handleDotClick(dateKey: string): void {
    timeline.toggleDate(dateKey);
  }

  function handleItemClick(item: TimelineItem): void {
    onSelect({ id: item.canvasId, type: 'Canvas' } as IIIFItem);
  }

  function handleZoomChange(level: ZoomLevel): void {
    timeline.setZoomLevel(level);
  }

  // ── Minimap helpers ──
  // Position dots proportionally across the minimap bar
  function getMinimapPosition(group: TimelineGroup): number {
    return timeline.getTimelinePosition(group.date) * 100;
  }
</script>

<PaneLayout variant="default">
  {#snippet header()}
    <ViewHeader {cx}>
      {#snippet title()}
        <span class={cn('font-mono uppercase text-sm font-semibold', cx.text)}>
          {t('timeline', 'Timeline')}
        </span>
        {#if hasItems}
          <span class={cn(
            'ml-2 px-1.5 py-0.5 rounded text-xs font-bold',
            cx.accent || 'bg-nb-black text-nb-white'
          )}>
            {totalItems}
          </span>
        {/if}
      {/snippet}

      {#snippet actions()}
        <div class="flex items-center gap-1" role="radiogroup" aria-label={t('zoomLevel', 'Zoom level')}>
          {#each zoomLevels as level}
            <Button
              variant={zoomLevel === level ? 'primary' : 'ghost'}
              size="sm"
              onclick={() => handleZoomChange(level)}
              aria-checked={zoomLevel === level ? 'true' : 'false'}
              role="radio"
            >
              {t(level, level)}
            </Button>
          {/each}
        </div>
      {/snippet}

      <!-- Date range minimap in subbar -->
      {#snippet subbar()}
        {#if hasItems}
          <div class="relative flex items-center w-full h-6">
            <!-- Base line -->
            <div class={cn(
              'absolute left-0 right-0 top-1/2 h-px -translate-y-1/2',
              cx.border || 'bg-nb-black/20'
            )}></div>
            <!-- Date dots -->
            {#each groups as group (group.key)}
              {@const pct = getMinimapPosition(group)}
              <button
                class={cn(
                  'absolute w-2 h-2 rounded-full -translate-x-1/2 -translate-y-1/2 top-1/2',
                  'transition-all hover:scale-150',
                  selectedDate === group.key
                    ? cn('w-3 h-3', cx.accent || 'bg-nb-black')
                    : cn(cx.textMuted || 'bg-nb-black/30')
                )}
                style="left: {pct}%;"
                onclick={() => handleDotClick(group.key)}
                title="{group.displayDate}: {group.items.length} {t('items', 'items')}"
                aria-label="{group.displayDate}, {group.items.length} {t('items', 'items')}"
              ></button>
            {/each}
            <!-- Min date label -->
            {#if timeline.minDate}
              <span class={cn('absolute left-0 -bottom-0.5 text-[9px] font-mono', cx.textMuted || 'text-nb-black/40')}>
                {timeline.formatShortDate(timeline.minDate)}
              </span>
            {/if}
            <!-- Max date label -->
            {#if timeline.maxDate}
              <span class={cn('absolute right-0 -bottom-0.5 text-[9px] font-mono', cx.textMuted || 'text-nb-black/40')}>
                {timeline.formatShortDate(timeline.maxDate)}
              </span>
            {/if}
          </div>
        {/if}
      {/snippet}
    </ViewHeader>
  {/snippet}

  {#snippet body()}
    {#if !hasItems}
      <Center flex class="h-full">
        <div class={cn('text-center p-8', cx.textMuted || 'text-nb-black/50')}>
          <div class="text-4xl mb-4" aria-hidden="true">&#x1f4c5;</div>
          <p class="text-lg font-medium">{t('noDatedItems', 'No dated items')}</p>
          <p class="text-sm mt-2">
            {t('noDatedItemsHint', 'Add navDate to canvases to see them on the timeline.')}
          </p>
        </div>
      </Center>
    {:else}
      <div class="relative pl-10 pr-4 py-6" role="list" aria-label={t('timeline', 'Timeline')}>
        <!-- Vertical connector line -->
        <div
          class={cn('absolute left-[22px] top-0 bottom-0 w-0.5', cx.border || 'bg-nb-black/15')}
          aria-hidden="true"
        ></div>

        {#each groups as group (group.key)}
          {@const isExpanded = selectedDate === null || selectedDate === group.key}
          {@const isSelected = selectedDate === group.key}

          <div class="relative mb-8" aria-expanded={isExpanded}>
            <!-- Timeline dot -->
            <button
              class={cn(
                'absolute left-[-22px] top-1 w-4 h-4 rounded-full border-2',
                'transition-all hover:scale-125 -translate-x-1/2',
                isSelected
                  ? cn('scale-110', cx.accent || 'bg-nb-black border-nb-black')
                  : cn(cx.surface || 'bg-nb-white', cx.border || 'border-nb-black/40')
              )}
              onclick={() => handleDotClick(group.key)}
              aria-pressed={isSelected}
              aria-label="{t('toggle', 'Toggle')} {group.displayDate} ({group.items.length} {t('items', 'items')})"
            ></button>

            <!-- Date header -->
            <div class={cn('mb-3 flex items-baseline gap-2', cx.text || 'text-nb-black')}>
              <span class="font-semibold text-sm font-mono uppercase">
                {group.displayDate}
              </span>
              <span class={cn('text-xs', cx.textMuted || 'text-nb-black/50')}>
                {group.items.length} {group.items.length === 1 ? t('item', 'item') : t('items', 'items')}
              </span>
            </div>

            <!-- Items grid (visible when group is expanded) -->
            {#if isExpanded}
              <div class={cn('grid gap-2', gridColumnsClass)}>
                {#each group.items as item (item.id)}
                  <button
                    class={cn(
                      'rounded overflow-hidden border-2 text-left',
                      'transition-all hover:shadow-md hover:-translate-y-0.5',
                      cx.surface || 'bg-nb-white',
                      cx.border || 'border-nb-black/20',
                      'hover:border-nb-black/50'
                    )}
                    onclick={() => handleItemClick(item)}
                    aria-label="{item.label} — {timeline.formatShortDate(item.date)}"
                  >
                    <!-- @migration: thumbnail would come from canvas thumbnail resolution -->
                    <div
                      class={cn(
                        'w-full aspect-square flex items-center justify-center',
                        'text-lg font-bold',
                        cx.accent || 'bg-nb-cream text-nb-black/30'
                      )}
                      aria-hidden="true"
                    >
                      {item.label.charAt(0).toUpperCase()}
                    </div>
                    <div class="p-1.5">
                      {#if zoomLevel === 'day'}
                        <p class={cn('text-[10px] font-mono', cx.textMuted || 'text-nb-black/50')}>
                          {timeline.formatTime(item.date)}
                        </p>
                      {/if}
                      <p class={cn('text-xs truncate', cx.text || 'text-nb-black')}>
                        {item.label}
                      </p>
                      {#if zoomLevel !== 'day'}
                        <p class={cn('text-[10px]', cx.textMuted || 'text-nb-black/40')}>
                          {timeline.formatShortDate(item.date)}
                        </p>
                      {/if}
                    </div>
                  </button>
                {/each}
              </div>
            {/if}
          </div>
        {/each}
      </div>
    {/if}
  {/snippet}
</PaneLayout>

// components/views/TimelineView.tsx

import React, { useMemo, useState } from 'react';
import { IIIFItem, IIIFCanvas, isCanvas, getIIIFValue } from '../../types';
import { Icon } from '../Icon';
import { useAppSettings } from '../../hooks/useAppSettings';
import { useContextualStyles } from '../../hooks/useContextualStyles';
import { useTerminology } from '../../hooks/useTerminology';

interface TimelineViewProps {
  root: IIIFItem | null;
  onSelect: (item: IIIFItem) => void;
}

interface TimelineGroup {
  date: string;
  displayDate: string;
  items: IIIFCanvas[];
}

export const TimelineView: React.FC<TimelineViewProps> = ({ root, onSelect }) => {
  const [zoomLevel, setZoomLevel] = useState<'day' | 'month' | 'year'>('day');
  const [selectedDate, setSelectedDate] = useState<string | null>(null);

  const { settings } = useAppSettings();
  const fieldMode = settings.fieldMode;
  const cx = useContextualStyles(fieldMode);
  const { t, isAdvanced } = useTerminology({ level: settings.abstractionLevel });

  const { groups, minDate, maxDate } = useMemo(() => {
    if (!root) return { groups: [], minDate: null, maxDate: null };

    const items: IIIFCanvas[] = [];
    const traverse = (item: IIIFItem) => {
      if (isCanvas(item) && (item as IIIFCanvas).navDate) {
        items.push(item as IIIFCanvas);
      }
      if (item.items) {
        item.items.forEach(traverse);
      }
    };
    traverse(root);

    if (items.length === 0) return { groups: [], minDate: null, maxDate: null };

    // Sort by date
    items.sort((a, b) => {
      const dateA = new Date(a.navDate!).getTime();
      const dateB = new Date(b.navDate!).getTime();
      return dateA - dateB;
    });

    // Group by zoom level
    const groupMap = new Map<string, IIIFCanvas[]>();

    items.forEach(item => {
      const date = new Date(item.navDate!);
      let key: string;
      let displayDate: string;

      switch (zoomLevel) {
        case 'year':
          key = date.getFullYear().toString();
          displayDate = key;
          break;
        case 'month':
          key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
          displayDate = date.toLocaleDateString('en-US', { year: 'numeric', month: 'long' });
          break;
        case 'day':
        default:
          key = date.toISOString().split('T')[0];
          displayDate = date.toLocaleDateString('en-US', { weekday: 'short', year: 'numeric', month: 'short', day: 'numeric' });
          break;
      }

      if (!groupMap.has(key)) {
        groupMap.set(key, []);
      }
      groupMap.get(key)!.push(item);
    });

    const groups: TimelineGroup[] = Array.from(groupMap.entries()).map(([date, items]) => ({
      date,
      displayDate: items[0] ? formatDisplayDate(new Date(items[0].navDate!), zoomLevel) : date,
      items
    }));

    const minDate = items[0]?.navDate ? new Date(items[0].navDate) : null;
    const maxDate = items[items.length - 1]?.navDate ? new Date(items[items.length - 1].navDate) : null;

    return { groups, minDate, maxDate };
  }, [root, zoomLevel]);

  const totalItems = groups.reduce((sum, g) => sum + g.items.length, 0);

  if (!root || groups.length === 0) {
    return (
      <div className={`flex-1 flex flex-col items-center justify-center ${cx.surface} ${cx.textMuted} p-8`}>
        <Icon name="event" className="text-6xl mb-4 opacity-50" />
        <p className="text-lg font-medium">No Dated Items</p>
        <p className="text-sm mt-2">Items need a navDate property to appear in the timeline.</p>
      </div>
    );
  }

  return (
    <div className={`flex flex-col h-full ${cx.surface}`}>
      {/* Header */}
      <div className={`h-14 ${cx.headerBg} border-b flex items-center justify-between px-6 shadow-sm`}>
        <div className="flex items-center gap-4">
          <h2 className={`font-bold ${cx.text} flex items-center gap-2`}>
            <Icon name="timeline" className="text-purple-500" />
            Timeline
          </h2>
          <span className={`text-sm ${cx.textMuted}`}>{totalItems} dated items</span>
        </div>

        <div className={`flex items-center gap-2 ${cx.surface} p-1 rounded`}>
          <button
            onClick={() => setZoomLevel('day')}
            className={`px-3 py-1 text-xs font-bold rounded ${zoomLevel === 'day' ? `${cx.active} shadow` : cx.textMuted}`}
          >
            Day
          </button>
          <button
            onClick={() => setZoomLevel('month')}
            className={`px-3 py-1 text-xs font-bold rounded ${zoomLevel === 'month' ? `${cx.active} shadow` : cx.textMuted}`}
          >
            Month
          </button>
          <button
            onClick={() => setZoomLevel('year')}
            className={`px-3 py-1 text-xs font-bold rounded ${zoomLevel === 'year' ? `${cx.active} shadow` : cx.textMuted}`}
          >
            Year
          </button>
        </div>
      </div>

      {/* Date Range Bar */}
      {minDate && maxDate && (
        <div className={`h-10 ${cx.surface} flex items-center px-6 text-xs ${cx.textMuted}`}>
          <span>{minDate.toLocaleDateString()}</span>
          <div className={`flex-1 mx-4 h-1 ${cx.border} rounded relative`}>
            {groups.map((g, i) => {
              const startTime = minDate.getTime();
              const endTime = maxDate.getTime();
              const groupDate = new Date(g.items[0].navDate!).getTime();
              const percent = endTime > startTime ? ((groupDate - startTime) / (endTime - startTime)) * 100 : 0;
              return (
                <div
                  key={g.date}
                  className="absolute w-2 h-2 bg-purple-500 rounded-full -top-0.5 cursor-pointer hover:scale-150 transition-transform"
                  style={{ left: `${percent}%` }}
                  title={`${g.displayDate}: ${g.items.length} items`}
                  onClick={() => setSelectedDate(selectedDate === g.date ? null : g.date)}
                />
              );
            })}
          </div>
          <span>{maxDate.toLocaleDateString()}</span>
        </div>
      )}

      {/* Timeline Content */}
      <div className="flex-1 overflow-y-auto p-6">
        <div className="max-w-4xl mx-auto">
          {groups.map((group, groupIdx) => (
            <div key={group.date} className="relative pl-8 pb-8">
              {/* Timeline line */}
              {groupIdx < groups.length - 1 && (
                <div className="absolute left-3 top-6 bottom-0 w-0.5 bg-slate-300" />
              )}

              {/* Timeline dot */}
              <div
                className={`absolute left-0 top-1 w-6 h-6 rounded-full flex items-center justify-center ${
                  selectedDate === group.date ? 'bg-purple-500' : 'bg-slate-400'
                }`}
              >
                <div className="w-2 h-2 bg-white rounded-full" />
              </div>

              {/* Date header */}
              <div
                className="flex items-center gap-3 mb-3 cursor-pointer group"
                onClick={() => setSelectedDate(selectedDate === group.date ? null : group.date)}
              >
                <h3 className="font-bold text-slate-800 group-hover:text-purple-600">
                  {group.displayDate}
                </h3>
                <span className="text-xs text-slate-400 bg-slate-200 px-2 py-0.5 rounded">
                  {group.items.length} item{group.items.length !== 1 ? 's' : ''}
                </span>
              </div>

              {/* Items grid */}
              <div className={`grid gap-3 ${
                zoomLevel === 'day' ? 'grid-cols-4 md:grid-cols-6' :
                zoomLevel === 'month' ? 'grid-cols-6 md:grid-cols-8' :
                'grid-cols-8 md:grid-cols-12'
              }`}>
                {group.items.map(item => (
                  <div
                    key={item.id}
                    className="bg-white rounded-lg shadow-sm border hover:shadow-md hover:border-purple-300 cursor-pointer transition-all group overflow-hidden"
                    onClick={() => onSelect(item)}
                  >
                    <div className="aspect-square bg-slate-100 relative overflow-hidden">
                      {item._blobUrl ? (
                        <img src={item._blobUrl} className="w-full h-full object-cover" loading="lazy" />
                      ) : (
                        <div className="w-full h-full flex items-center justify-center">
                          <Icon name="image" className="text-slate-300 text-2xl" />
                        </div>
                      )}
                      {zoomLevel !== 'day' && (
                        <div className="absolute bottom-0 left-0 right-0 bg-black/60 text-white text-[8px] px-1 py-0.5 truncate">
                          {new Date(item.navDate!).toLocaleDateString()}
                        </div>
                      )}
                    </div>
                    {zoomLevel === 'day' && (
                      <div className="p-1.5">
                        <div className="text-[10px] text-slate-600 truncate">
                          {getIIIFValue(item.label, 'none') || 'Untitled'}
                        </div>
                        <div className="text-[9px] text-slate-400">
                          {new Date(item.navDate!).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                        </div>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

function formatDisplayDate(date: Date, zoomLevel: 'day' | 'month' | 'year'): string {
  switch (zoomLevel) {
    case 'year':
      return date.getFullYear().toString();
    case 'month':
      return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long' });
    case 'day':
    default:
      return date.toLocaleDateString('en-US', { weekday: 'short', year: 'numeric', month: 'short', day: 'numeric' });
  }
}
