// src/features/structure-view/ui/molecules/TreeNodeItem.svelte
<!--
  TreeNodeItem.svelte — Single tree row with drag-drop
  React source: TreeNodeItem.tsx (195L)
  Composes: ExpandButton, StructureNodeIcon, NodeLabel, DropIndicator
  Local state: localDropPosition, isDraggingOver
-->
<script lang="ts">
  import { cn } from '@/src/shared/lib/cn';
  import ExpandButton from '../atoms/ExpandButton.svelte';
  import StructureNodeIcon from '../atoms/StructureNodeIcon.svelte';
  import NodeLabel from '../atoms/NodeLabel.svelte';
  import DropIndicator from '../atoms/DropIndicator.svelte';
  import type { DropPosition } from '../atoms/types';
  import type { StructureNode } from '../../stores/structureTree.svelte';

  interface Props {
    node: StructureNode;
    onSelect: (id: string, additive: boolean) => void;
    onToggleExpand: (id: string) => void;
    onDragStart: (id: string) => void;
    onDragEnd: () => void;
    onDrop: (targetId: string, position?: DropPosition) => void;
    style?: string;
    canDrop?: boolean;
    dropPosition?: DropPosition | null;
    isDropOver?: boolean;
  }

  let {
    node,
    onSelect,
    onToggleExpand,
    onDragStart,
    onDragEnd,
    onDrop,
    style = '',
    canDrop = false,
    dropPosition = null,
    isDropOver = false,
  }: Props = $props();

  let localDropPosition = $state<DropPosition | null>(null);
  let isDraggingOver = $state(false);

  function calculateDropPosition(e: DragEvent): DropPosition {
    const target = e.currentTarget as HTMLElement;
    const rect = target.getBoundingClientRect();
    const y = e.clientY - rect.top;
    const height = rect.height;

    if (y < height * 0.25) return 'before';
    if (y > height * 0.75) return 'after';
    return 'inside';
  }

  function handleClick(e: MouseEvent) {
    e.stopPropagation();
    onSelect(node.id, e.metaKey || e.ctrlKey);
  }

  function handleExpandClick(e: MouseEvent) {
    e.stopPropagation();
    onToggleExpand(node.id);
  }

  function handleDragStart(e: DragEvent) {
    if (!e.dataTransfer) return;
    e.dataTransfer.setData('text/plain', node.id);
    e.dataTransfer.effectAllowed = 'move';
    onDragStart(node.id);
  }

  function handleDragEnd() {
    onDragEnd();
  }

  function handleDragOver(e: DragEvent) {
    e.preventDefault();
    if (e.dataTransfer) {
      e.dataTransfer.dropEffect = canDrop ? 'move' : 'none';
    }
    if (canDrop) {
      localDropPosition = calculateDropPosition(e);
      isDraggingOver = true;
    }
  }

  function handleDragLeave() {
    isDraggingOver = false;
    localDropPosition = null;
  }

  function handleDrop(e: DragEvent) {
    e.preventDefault();
    e.stopPropagation();
    const position = localDropPosition || 'inside';
    onDrop(node.id, position);
    isDraggingOver = false;
    localDropPosition = null;
  }

  const indentWidth = $derived(node.depth * 16);
  const effectiveDropPosition = $derived(dropPosition || localDropPosition);
  const effectiveIsDropOver = $derived(isDropOver || isDraggingOver);

  const typeColorClass = $derived(
    node.type === 'Collection' ? 'text-nb-blue' :
    node.type === 'Manifest' ? 'text-nb-green' :
    node.type === 'Canvas' ? 'text-nb-purple' :
    node.type === 'Range' ? 'text-nb-orange' : ''
  );
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
  role="treeitem"
  aria-level={node.depth + 1}
  aria-expanded={node.childCount > 0 ? node.isExpanded : undefined}
  aria-selected={node.isSelected}
  tabindex={node.isSelected ? 0 : -1}
  {style}
  class={cn(
    'relative flex items-center gap-1 px-2 py-1.5 cursor-pointer',
    'border-b border-nb-black/10',
    'hover:bg-nb-cream',
    'transition-nb',
    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-nb-blue focus-visible:ring-inset',
    node.isSelected && 'bg-nb-blue/10',
    effectiveIsDropOver && canDrop && 'bg-nb-blue/10',
  )}
  onclick={handleClick}
  draggable="true"
  ondragstart={handleDragStart}
  ondragend={handleDragEnd}
  ondragover={handleDragOver}
  ondragleave={handleDragLeave}
  ondrop={handleDrop}
>
  {#if effectiveIsDropOver && canDrop && effectiveDropPosition}
    <DropIndicator position={effectiveDropPosition} isValid={canDrop} />
  {/if}

  <span style="width: {indentWidth}px" class="flex-shrink-0"></span>

  <ExpandButton
    isExpanded={node.isExpanded}
    onclick={handleExpandClick}
    hasChildren={node.childCount > 0}
  />

  <StructureNodeIcon
    type={node.type}
    class={cn('flex-shrink-0 ml-1', typeColorClass)}
  />

  <NodeLabel
    label={node.label}
    type={node.type}
    isSelected={node.isSelected}
    isDragging={false}
    class="flex-1 ml-2"
  />

  {#if node.childCount > 0}
    <span class="text-xs text-nb-black/40 px-1.5 py-0.5 bg-nb-cream">
      {node.childCount}
    </span>
  {/if}
</div>

// src/features/structure-view/ui/molecules/TreeNodeItem.tsx
/**
 * Tree Node Item Molecule
 *
 * A single row in the structure tree.
 * Composes atoms: StructureNodeIcon, ExpandButton, NodeLabel, DropIndicator
 * Handles selection, expansion, and drag-drop interactions.
 */

import React, { useCallback, useState } from 'react';
import { DropIndicator, ExpandButton, NodeLabel, StructureNodeIcon } from '../atoms';
import type { StructureNode } from '../../model/useStructureTree';
import type { DropPosition } from '../atoms/DropIndicator';

export interface TreeNodeItemProps {
  node: StructureNode;
  onSelect: (id: string, additive: boolean) => void;
  onToggleExpand: (id: string) => void;
  onDragStart: (id: string) => void;
  onDragEnd: () => void;
  onDrop: (targetId: string, position?: DropPosition) => void;
  style?: React.CSSProperties;
  canDrop?: boolean;
  dropPosition?: DropPosition | null;
  isDropOver?: boolean;
}

export const TreeNodeItem: React.FC<TreeNodeItemProps> = ({
  node,
  onSelect,
  onToggleExpand,
  onDragStart,
  onDragEnd,
  onDrop,
  style,
  canDrop = false,
  dropPosition = null,
  isDropOver = false,
}) => {
  const [localDropPosition, setLocalDropPosition] = useState<DropPosition | null>(null);
  const [isDraggingOver, setIsDraggingOver] = useState(false);

  const calculateDropPosition = useCallback((e: React.DragEvent<HTMLDivElement>): DropPosition => {
    const rect = e.currentTarget.getBoundingClientRect();
    const y = e.clientY - rect.top;
    const {height} = rect;

    if (y < height * 0.25) return 'before';
    if (y > height * 0.75) return 'after';
    return 'inside';
  }, []);

  const handleClick = useCallback(
    (e: React.MouseEvent) => {
      e.stopPropagation();
      onSelect(node.id, e.metaKey || e.ctrlKey);
    },
    [node.id, onSelect]
  );

  const handleExpandClick = useCallback(
    (e: React.MouseEvent) => {
      e.stopPropagation();
      onToggleExpand(node.id);
    },
    [node.id, onToggleExpand]
  );

  const handleDragStart = useCallback(
    (e: React.DragEvent) => {
      e.dataTransfer.setData('text/plain', node.id);
      e.dataTransfer.effectAllowed = 'move';
      onDragStart(node.id);
    },
    [node.id, onDragStart]
  );

  const handleDragEnd = useCallback(() => {
    onDragEnd();
  }, [onDragEnd]);

  const handleDragOver = useCallback(
    (e: React.DragEvent<HTMLDivElement>) => {
      e.preventDefault();
      e.dataTransfer.dropEffect = canDrop ? 'move' : 'none';

      if (canDrop) {
        const position = calculateDropPosition(e);
        setLocalDropPosition(position);
        setIsDraggingOver(true);
      }
    },
    [canDrop, calculateDropPosition]
  );

  const handleDragLeave = useCallback(() => {
    setIsDraggingOver(false);
    setLocalDropPosition(null);
  }, []);

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      e.stopPropagation();
      const position = localDropPosition || 'inside';
      onDrop(node.id, position);
      setIsDraggingOver(false);
      setLocalDropPosition(null);
    },
    [node.id, onDrop, localDropPosition]
  );

  const indentWidth = node.depth * 16;
  const effectiveDropPosition = dropPosition || localDropPosition;
  const effectiveIsDropOver = isDropOver || isDraggingOver;

  return (
    <div
      role="treeitem"
      aria-level={node.depth + 1}
      aria-expanded={node.childCount > 0 ? node.isExpanded : undefined}
      aria-selected={node.isSelected}
      tabIndex={node.isSelected ? 0 : -1}
      style={style}
      className={`
        relative flex items-center gap-1 px-2 py-1.5 cursor-pointer
        border-b border-nb-black/10
        hover:bg-nb-cream
        ${node.isSelected ? 'bg-nb-blue/10' : ''}
        ${node.relationship === 'reference' ? 'italic' : ''}
        ${node.isDragging ? 'opacity-40' : ''}
        ${effectiveIsDropOver && canDrop ? 'bg-nb-blue/10' : ''}
        transition-nb 
        focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-nb-blue focus-visible:ring-inset
      `}
      onClick={handleClick}
      draggable
      onDragStart={handleDragStart}
      onDragEnd={handleDragEnd}
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
    >
      {effectiveIsDropOver && canDrop && effectiveDropPosition && (
        <DropIndicator position={effectiveDropPosition} isValid={canDrop} />
      )}

      <span style={{ width: indentWidth }} className="flex-shrink-0" />

      <ExpandButton
        isExpanded={node.isExpanded}
        onClick={handleExpandClick}
        hasChildren={node.childCount > 0}
      />

      <StructureNodeIcon
        type={node.type}
        className={`
          flex-shrink-0 ml-1
          ${node.type === 'Collection' ? 'text-nb-blue' : ''}
          ${node.type === 'Manifest' ? 'text-nb-green' : ''}
          ${node.type === 'Canvas' ? 'text-nb-purple' : ''}
          ${node.type === 'Range' ? 'text-nb-orange' : ''}
        `}
      />

      <NodeLabel
        label={node.label}
        type={node.type}
        isSelected={node.isSelected}
        isDragging={node.isDragging}
        className="flex-1 ml-2"
      />

      {node.childCount > 0 && (
        <span className="text-xs text-nb-black/40 px-1.5 py-0.5 bg-nb-cream ">
          {node.childCount}
        </span>
      )}

      {node.relationship === 'reference' && (
        <span
          className="text-xs text-nb-black/40 ml-1"
          title="Reference (not owned)"
        >
          ↗
        </span>
      )}
    </div>
  );
};

TreeNodeItem.displayName = 'TreeNodeItem';

export default TreeNodeItem;
