// src/features/viewer/ui/molecules/AnnotationToolbar.svelte
<!--
  AnnotationToolbar.svelte — Drawing mode selector for spatial annotations

  LAYER: molecule (receives cx + fieldMode props)
  FSD: features/viewer/ui/molecules

  Button group for polygon / rectangle / freehand / select drawing modes.
  Keyboard shortcuts: P=polygon, R=rectangle, F=freehand, S=select.
-->
<script lang="ts">
  import { cn } from '@/src/shared/lib/cn';
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import { onMount, onDestroy } from 'svelte';

  type DrawingMode = 'polygon' | 'rectangle' | 'freehand' | 'select';

  interface Props {
    activeMode: DrawingMode;
    onModeChange: (mode: DrawingMode) => void;
    disabled?: boolean;
    fieldMode: boolean;
    cx: ContextualClassNames;
  }

  let {
    activeMode,
    onModeChange,
    disabled = false,
    fieldMode,
    cx,
  }: Props = $props();

  const modes: Array<{ value: DrawingMode; label: string; shortcut: string; icon: string }> = [
    { value: 'polygon', label: 'Polygon', shortcut: 'P', icon: 'pentagon' },
    { value: 'rectangle', label: 'Rectangle', shortcut: 'R', icon: 'crop_square' },
    { value: 'freehand', label: 'Freehand', shortcut: 'F', icon: 'gesture' },
    { value: 'select', label: 'Select', shortcut: 'S', icon: 'near_me' },
  ];

  let activeBtnClass = $derived(fieldMode
    ? 'bg-nb-yellow text-nb-black border-nb-yellow font-bold'
    : 'bg-nb-black text-nb-white border-nb-black font-bold'
  );

  function handleKeyDown(e: KeyboardEvent) {
    if (disabled) return;
    if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return;
    switch (e.key.toUpperCase()) {
      case 'P': onModeChange('polygon'); break;
      case 'R': onModeChange('rectangle'); break;
      case 'F': onModeChange('freehand'); break;
      case 'S': onModeChange('select'); break;
    }
  }

  onMount(() => {
    window.addEventListener('keydown', handleKeyDown);
  });

  onDestroy(() => {
    window.removeEventListener('keydown', handleKeyDown);
  });
</script>

<div
  class="flex gap-1"
  role="toolbar"
  aria-label="Drawing tools"
>
  {#each modes as mode}
    <button
      class={cn(
        'flex items-center gap-1.5 px-2.5 py-1.5 text-xs font-mono border-2 transition-nb',
        activeMode === mode.value ? activeBtnClass : cx.iconButton,
        disabled && 'opacity-40 cursor-not-allowed pointer-events-none'
      )}
      onclick={() => !disabled && onModeChange(mode.value)}
      aria-pressed={activeMode === mode.value}
      aria-label="{mode.label} ({mode.shortcut})"
      title="{mode.label} ({mode.shortcut})"
      {disabled}
    >
      <span class="material-symbols-outlined text-sm leading-none">{mode.icon}</span>
      <span class="hidden md:inline">{mode.label}</span>
      <span class={cn(
        'text-[10px] font-bold hidden md:inline',
        activeMode === mode.value ? 'opacity-60' : 'opacity-40'
      )}>{mode.shortcut}</span>
    </button>
  {/each}
</div>

// src/features/viewer/ui/molecules/AnnotationToolbar.tsx
/**
 * AnnotationToolbar Molecule
 *
 * Toolbar for the annotation tool with mode selection and controls.
 */

import React from 'react';
import { Icon } from '@/src/shared/ui/atoms';
import { Button } from '@/ui/primitives/Button';
import type { DrawingMode } from '../../model/annotation';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';

export interface AnnotationToolbarProps {
  currentMode: DrawingMode;
  existingCount: number;
  showExisting: boolean;
  onModeChange: (mode: DrawingMode) => void;
  onToggleExisting: () => void;
  onClose: () => void;
  cx?: ContextualClassNames;
  fieldMode?: boolean;
}

const MODES: { mode: DrawingMode; icon: string; label: string }[] = [
  { mode: 'polygon', icon: 'pentagon', label: 'Polygon' },
  { mode: 'rectangle', icon: 'crop_square', label: 'Rectangle' },
  { mode: 'freehand', icon: 'gesture', label: 'Freehand' },
  { mode: 'select', icon: 'pan_tool', label: 'Pan' },
];

export const AnnotationToolbar: React.FC<AnnotationToolbarProps> = ({
  currentMode,
  existingCount,
  showExisting,
  onModeChange,
  onToggleExisting,
  onClose,
}) => {
  return (
    <div className="h-12 bg-nb-black border-b border-white/10 flex items-center justify-between px-4 shrink-0">
      <div className="flex items-center gap-4">
        <h2 className="text-white font-bold flex items-center gap-2 text-sm">
          <Icon name="pentagon" className="text-nb-green" />
          Annotation Tool
        </h2>

        <div className="flex bg-nb-white/5 border border-white/10 p-0.5">
          {MODES.map((m) => (
            <Button
              key={m.mode}
              onClick={() => onModeChange(m.mode)}
              variant={currentMode === m.mode ? 'primary' : 'ghost'}
              size="sm"
              icon={<Icon name={m.icon} className="text-xs" />}
              className="text-[10px] font-bold uppercase"
            >
              {m.label}
            </Button>
          ))}
        </div>
      </div>

      <div className="flex items-center gap-3">
        <Button
          onClick={onToggleExisting}
          variant={showExisting ? 'primary' : 'ghost'}
          size="sm"
          className="text-[10px] font-bold uppercase"
        >
          {existingCount} Existing
        </Button>
        <Button
          onClick={onClose}
          variant="ghost"
          size="sm"
          className="font-bold text-sm"
        >
          Done
        </Button>
      </div>
    </div>
  );
};
