// src/features/viewer/ui/molecules/AnnotationOverlay.svelte
<!--
  AnnotationOverlay.svelte — SVG overlay rendering existing IIIF annotations as visual shapes

  LAYER: molecule (receives fieldMode props)
  FSD: features/viewer/ui/molecules

  Scales annotation coordinates from canvas space to container space and
  renders SvgSelector annotations as polygon/rect SVG shapes. Individual
  shapes are interactive (pointer-events: all); the SVG root is passive.
-->
<script lang="ts">
  import { cn } from '@/src/shared/lib/cn';
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import type { IIIFAnnotation } from '@/src/shared/types';
  import { parseSvgSelector } from '@/src/features/viewer/model/annotation';

  interface Props {
    annotations: IIIFAnnotation[];
    canvasWidth: number;
    canvasHeight: number;
    containerWidth: number;
    containerHeight: number;
    selectedId?: string;
    onSelect?: (id: string) => void;
    fieldMode: boolean;
    cx?: ContextualClassNames;
  }

  let {
    annotations,
    canvasWidth,
    canvasHeight,
    containerWidth,
    containerHeight,
    selectedId,
    onSelect,
    fieldMode,
    cx = {} as ContextualClassNames,
  }: Props = $props();

  // Scale factors from canvas space to container space
  let scaleX = $derived(canvasWidth > 0 ? containerWidth / canvasWidth : 1);
  let scaleY = $derived(canvasHeight > 0 ? containerHeight / canvasHeight : 1);

  type ShapeData =
    | { type: 'polygon'; points: string; id: string }
    | { type: 'rect'; x: number; y: number; width: number; height: number; id: string }
    | null;

  function extractShape(anno: IIIFAnnotation): ShapeData {
    const target = anno.target as any;
    const selector = target?.selector;
    if (!selector) return null;

    const selectorType = selector.type;
    const selectorValue = selector.value;

    if (selectorType === 'SvgSelector' && selectorValue) {
      const pts = parseSvgSelector(selectorValue);
      if (pts.length < 2) return null;
      const scaled = pts.map(p => `${(p.x * scaleX).toFixed(1)},${(p.y * scaleY).toFixed(1)}`).join(' ');
      return { type: 'polygon', points: scaled, id: anno.id };
    }

    // FragmentSelector with xywh=
    if (selectorType === 'FragmentSelector' && selectorValue) {
      const match = String(selectorValue).match(/xywh=(\d+),(\d+),(\d+),(\d+)/);
      if (match) {
        return {
          type: 'rect',
          x: parseInt(match[1]) * scaleX,
          y: parseInt(match[2]) * scaleY,
          width: parseInt(match[3]) * scaleX,
          height: parseInt(match[4]) * scaleY,
          id: anno.id,
        };
      }
    }

    return null;
  }

  let shapes = $derived(
    annotations.map(a => ({ anno: a, shape: extractShape(a) })).filter(s => s.shape !== null)
  );

  let strokeColor = $derived(fieldMode ? '#FFE500' : '#0055FF');
  let selectedStrokeColor = $derived(fieldMode ? '#FF6B00' : '#FF4444');
</script>

<svg
  class="absolute inset-0 w-full h-full"
  style:pointer-events="none"
  aria-label="Annotation overlay"
  role="img"
>
  {#each shapes as { anno, shape }}
    {#if shape}
      {@const isSelected = selectedId === anno.id}
      {@const stroke = isSelected ? selectedStrokeColor : strokeColor}
      {@const fill = isSelected ? `${stroke}33` : `${stroke}1A`}

      {#if shape.type === 'polygon'}
        <polygon
          points={shape.points}
          fill={fill}
          stroke={stroke}
          stroke-width={isSelected ? 3 : 2}
          style:pointer-events="all"
          style:cursor="pointer"
          role="button"
          tabindex="0"
          aria-label="Annotation"
          aria-pressed={isSelected}
          onclick={() => onSelect?.(anno.id)}
          onkeydown={(e) => e.key === 'Enter' && onSelect?.(anno.id)}
        />
      {:else if shape.type === 'rect'}
        <rect
          x={shape.x}
          y={shape.y}
          width={shape.width}
          height={shape.height}
          fill={fill}
          stroke={stroke}
          stroke-width={isSelected ? 3 : 2}
          style:pointer-events="all"
          style:cursor="pointer"
          role="button"
          tabindex="0"
          aria-label="Annotation"
          aria-pressed={isSelected}
          onclick={() => onSelect?.(anno.id)}
          onkeydown={(e) => e.key === 'Enter' && onSelect?.(anno.id)}
        />
      {/if}
    {/if}
  {/each}
</svg>

// src/features/viewer/ui/molecules/AnnotationOverlay.tsx
/**
 * AnnotationOverlay Molecule
 *
 * Composes: SVG elements for annotation rendering
 *
 * Renders IIIF annotations as SVG overlays on the viewer canvas.
 * Supports W3C Media Fragments and SVG selectors.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Receives cx and fieldMode via props (no hook calls)
 * - Renders SVG annotations
 * - Local UI state only
 * - No domain logic
 *
 * IDEAL OUTCOME: Visual annotation overlay synchronized with viewer
 * FAILURE PREVENTED: Annotation misalignment, rendering errors
 *
 * @module features/viewer/ui/molecules/AnnotationOverlay
 */

import React, { useMemo } from 'react';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';

/** IIIF Annotation structure */
export interface IIIFAnnotation {
  id: string;
  type: 'Annotation';
  motivation?: string;
  body?: {
    type: string;
    value?: string;
    format?: string;
  } | Array<{
    type: string;
    value?: string;
    format?: string;
  }>;
  target?: string | {
    id?: string;
    selector?: {
      type: string;
      value?: string;
      region?: string;
    };
  };
}

export interface AnnotationOverlayProps {
  /** Annotations to render */
  annotations: IIIFAnnotation[];
  /** Canvas dimensions */
  canvasWidth: number;
  /** Canvas height */
  canvasHeight: number;
  /** Currently selected annotation ID */
  selectedId?: string | null;
  /** Called when annotation is clicked */
  onAnnotationClick?: (annotation: IIIFAnnotation) => void;
  /** Whether annotations are visible */
  visible?: boolean;
  /** Contextual styles from template */
  cx?: ContextualClassNames;
  /** Current field mode */
  fieldMode?: boolean;
}

/**
 * Parse W3C Media Fragment region (xywh format)
 */
const parseRegion = (region: string): { x: number; y: number; w: number; h: number } | null => {
  const match = region.match(/xywh=(\d+),(\d+),(\d+),(\d+)/);
  if (!match) return null;
  return {
    x: parseInt(match[1], 10),
    y: parseInt(match[2], 10),
    w: parseInt(match[3], 10),
    h: parseInt(match[4], 10),
  };
};

/**
 * Parse SVG path from selector
 */
const parseSvgPath = (value: string): string | null => {
  // Extract path from SVG <path> element
  const match = value.match(/<path[^>]*d="([^"]*)"/);
  return match ? match[1] : value;
};

/**
 * AnnotationOverlay Molecule
 *
 * @example
 * <AnnotationOverlay
 *   annotations={annotations}
 *   canvasWidth={1000}
 *   canvasHeight={1500}
 *   selectedId={selectedAnnotationId}
 *   onAnnotationClick={handleAnnotationClick}
 *   cx={cx}
 *   fieldMode={fieldMode}
 * />
 */
export const AnnotationOverlay: React.FC<AnnotationOverlayProps> = ({
  annotations,
  canvasWidth,
  canvasHeight,
  selectedId,
  onAnnotationClick,
  visible = true,
  fieldMode = false,
}) => {
  const renderedAnnotations = useMemo(() => {
    return annotations.map((annotation) => {
      const isSelected = annotation.id === selectedId;
      const {target} = annotation;

      // Extract region from target
      let region: { x: number; y: number; w: number; h: number } | null = null;
      let path: string | null = null;

      if (typeof target === 'string') {
        // Parse URL with fragment
        const [, fragment] = target.split('#');
        if (fragment) {
          region = parseRegion(fragment);
        }
      } else if (target?.selector) {
        const { selector } = target;
        if (selector.type === 'FragmentSelector' && selector.value) {
          region = parseRegion(selector.value);
        } else if (selector.type === 'SvgSelector' && selector.value) {
          path = parseSvgPath(selector.value);
        }
      }

      return {
        annotation,
        isSelected,
        region,
        path,
      };
    });
  }, [annotations, selectedId]);

  if (!visible || annotations.length === 0) return null;

  const strokeColor = fieldMode ? '#4ade80' : '#22c55e';
  const fillColor = fieldMode ? 'rgba(74, 222, 128, 0.1)' : 'rgba(34, 197, 94, 0.1)';
  const selectedStrokeColor = fieldMode ? '#fbbf24' : '#f59e0b';
  const selectedFillColor = fieldMode ? 'rgba(251, 191, 36, 0.2)' : 'rgba(245, 158, 11, 0.2)';

  return (
    <svg
      className="absolute inset-0 pointer-events-auto"
      viewBox={`0 0 ${canvasWidth} ${canvasHeight}`}
      preserveAspectRatio="xMidYMid meet"
      style={{ width: '100%', height: '100%' }}
    >
      {renderedAnnotations.map(({ annotation, isSelected, region, path }) => {
        const commonProps = {
          key: annotation.id,
          onClick: () => onAnnotationClick?.(annotation),
          style: { cursor: onAnnotationClick ? 'pointer' : 'default' },
          stroke: isSelected ? selectedStrokeColor : strokeColor,
          strokeWidth: isSelected ? 3 : 2,
          fill: isSelected ? selectedFillColor : fillColor,
        };

        if (region) {
          return (
            <rect
              {...commonProps}
              x={region.x}
              y={region.y}
              width={region.w}
              height={region.h}
            />
          );
        }

        if (path) {
          return <path {...commonProps} d={path} />;
        }

        return null;
      })}
    </svg>
  );
};

export default AnnotationOverlay;
