// src/features/viewer/ui/molecules/ComposerToolbar.svelte
<!--
  ComposerToolbar.svelte — Save / Undo / Redo for board design

  LAYER: molecule (receives cx + fieldMode props)
  FSD: features/viewer/ui/molecules

  Toolbar with Save (disabled when not dirty), Undo/Redo (disabled when
  !canUndo/!canRedo), unsaved changes indicator, and Close button.
-->
<script lang="ts">
  import { cn } from '@/src/shared/lib/cn';
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';

  interface Props {
    canUndo: boolean;
    canRedo: boolean;
    isDirty: boolean;
    onSave: () => void;
    onUndo: () => void;
    onRedo: () => void;
    onClose: () => void;
    fieldMode: boolean;
    cx: ContextualClassNames;
  }

  let {
    canUndo,
    canRedo,
    isDirty,
    onSave,
    onUndo,
    onRedo,
    onClose,
    fieldMode,
    cx,
  }: Props = $props();
</script>

<div
  class={cn(
    'flex items-center gap-2 px-3 py-2 border-b shrink-0',
    cx.headerBg,
    cx.text
  )}
  role="toolbar"
  aria-label="Composer tools"
>
  <!-- Save -->
  <button
    class={cn(
      'flex items-center gap-1.5 px-3 py-1.5 text-xs font-mono font-bold uppercase border-2 transition-nb',
      isDirty
        ? fieldMode
          ? 'bg-nb-yellow text-nb-black border-nb-yellow hover:bg-nb-yellow/80'
          : 'bg-nb-black text-nb-white border-nb-black hover:bg-nb-black/80'
        : 'opacity-40 cursor-not-allowed border-current',
      cx.text
    )}
    onclick={onSave}
    disabled={!isDirty}
    aria-label="Save composition"
    title="Save (Ctrl+S)"
  >
    <span class="material-symbols-outlined text-sm leading-none">save</span>
    Save
  </button>

  <!-- Unsaved indicator -->
  {#if isDirty}
    <span class={cn(
      'text-xs font-mono animate-pulse',
      fieldMode ? 'text-nb-yellow/70' : 'text-nb-black/50'
    )}>
      Unsaved changes
    </span>
  {/if}

  <!-- Separator -->
  <div class={cn('w-px h-5 mx-1', fieldMode ? 'bg-nb-yellow/30' : 'bg-nb-black/20')} aria-hidden="true"></div>

  <!-- Undo -->
  <button
    class={cn(
      'flex items-center gap-1 px-2 py-1.5 text-xs font-mono border-2 transition-nb',
      canUndo ? cx.iconButton : 'opacity-40 cursor-not-allowed border-current'
    )}
    onclick={onUndo}
    disabled={!canUndo}
    aria-label="Undo"
    title="Undo (Ctrl+Z)"
  >
    <span class="material-symbols-outlined text-sm leading-none">undo</span>
    <span class="hidden sm:inline">Undo</span>
  </button>

  <!-- Redo -->
  <button
    class={cn(
      'flex items-center gap-1 px-2 py-1.5 text-xs font-mono border-2 transition-nb',
      canRedo ? cx.iconButton : 'opacity-40 cursor-not-allowed border-current'
    )}
    onclick={onRedo}
    disabled={!canRedo}
    aria-label="Redo"
    title="Redo (Ctrl+Shift+Z)"
  >
    <span class="material-symbols-outlined text-sm leading-none">redo</span>
    <span class="hidden sm:inline">Redo</span>
  </button>

  <!-- Spacer -->
  <div class="flex-1"></div>

  <!-- Close -->
  <button
    class={cn('flex items-center gap-1 px-2 py-1.5 text-xs font-mono border-2 transition-nb', cx.iconButton)}
    onclick={onClose}
    aria-label="Close composer"
    title="Close"
  >
    <span class="material-symbols-outlined text-sm leading-none">close</span>
    <span class="hidden sm:inline">Close</span>
  </button>
</div>

// src/features/viewer/ui/molecules/ComposerToolbar.tsx
/**
 * ComposerToolbar Molecule
 *
 * Toolbar for the canvas composer with dimensions, bg mode, zoom, undo/redo.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Composes atoms (Button, Input)
 * - No domain logic, only UI state
 * - Props-driven, no hooks
 */

import React from 'react';
import { Icon } from '@/components/Icon';

export type BackgroundMode = 'grid' | 'dark' | 'light';

export interface ComposerToolbarProps {
  /** Canvas width */
  width: number;
  /** Canvas height */
  height: number;
  /** Current background mode */
  bgMode: BackgroundMode;
  /** Current zoom percentage */
  zoomPercent: number;
  /** Whether undo is available */
  canUndo: boolean;
  /** Whether redo is available */
  canRedo: boolean;
  /** Callback when width changes */
  onWidthChange: (w: number) => void;
  /** Callback when height changes */
  onHeightChange: (h: number) => void;
  /** Callback when bg mode changes */
  onBgModeChange: (mode: BackgroundMode) => void;
  /** Callback when zoom in clicked */
  onZoomIn: () => void;
  /** Callback when zoom out clicked */
  onZoomOut: () => void;
  /** Callback when undo clicked */
  onUndo: () => void;
  /** Callback when redo clicked */
  onRedo: () => void;
  /** Callback when add text clicked */
  onAddText: () => void;
  /** Callback when save clicked */
  onSave: () => void;
  /** Callback when cancel clicked */
  onCancel: () => void;
  /** Contextual styles - currently unused but reserved for future fieldMode support */
  cx?: {
    text: string;
    textMuted: string;
    active: string;
    surface: string;
  };
}

const BG_MODES: BackgroundMode[] = ['grid', 'dark', 'light'];

/**
 * ComposerToolbar Molecule
 *
 * @example
 * <ComposerToolbar
 *   width={1920}
 *   height={1080}
 *   bgMode="grid"
 *   zoomPercent={100}
 *   canUndo={true}
 *   canRedo={false}
 *   onWidthChange={setWidth}
 *   onHeightChange={setHeight}
 *   onBgModeChange={setBgMode}
 *   onZoomIn={zoomIn}
 *   onZoomOut={zoomOut}
 *   onUndo={undo}
 *   onRedo={redo}
 *   onAddText={addTextLayer}
 *   onSave={handleSave}
 *   onCancel={onClose}
 *   cx={cx}
 * />
 */
export const ComposerToolbar: React.FC<ComposerToolbarProps> = ({
  width,
  height,
  bgMode,
  zoomPercent,
  canUndo,
  canRedo,
  onWidthChange,
  onHeightChange,
  onBgModeChange,
  onZoomIn,
  onZoomOut,
  onUndo,
  onRedo,
  onAddText,
  onSave,
  onCancel,
  cx,
}) => {
  return (
    <div className="h-14 bg-slate-900 border-b border-white/10 flex items-center justify-between px-6 shrink-0 shadow-2xl">
      {/* Left: Title & Dimensions */}
      <div className="flex items-center gap-6">
        <h2 className="text-white font-bold flex items-center gap-2">
          <Icon name="auto_awesome_motion" className="text-indigo-400" />
          Synthesis Workspace
        </h2>
        <div className="h-6 w-px bg-white/10" />
        <div className="flex items-center gap-2">
          <span className="text-[10px] font-black text-white/40 uppercase tracking-widest">
            Dimensions
          </span>
          <input
            type="number"
            aria-label="Canvas Width"
            value={width}
            onChange={(e) => onWidthChange(Number(e.target.value))}
            className="w-16 bg-white/5 text-white text-[10px] border border-white/10 rounded px-1 outline-none"
          />
          <span className="text-white/20">×</span>
          <input
            type="number"
            aria-label="Canvas Height"
            value={height}
            onChange={(e) => onHeightChange(Number(e.target.value))}
            className="w-16 bg-white/5 text-white text-[10px] border border-white/10 rounded px-1 outline-none"
          />
        </div>
        <div className="h-6 w-px bg-white/10" />
        <div
          className="flex bg-white/5 border border-white/10 rounded p-1"
          role="group"
          aria-label="Background Mode"
        >
          {BG_MODES.map((m) => (
            <button
              key={m}
              onClick={() => onBgModeChange(m)}
              aria-pressed={bgMode === m}
              className={`px-2 py-0.5 text-[9px] font-black uppercase rounded ${
                bgMode === m ? 'bg-indigo-600 text-white' : 'text-slate-500'
              }`}
            >
              {m}
            </button>
          ))}
        </div>
        <button
          onClick={onAddText}
          className="bg-white/10 hover:bg-white/20 text-white px-3 py-1 rounded text-[10px] font-black uppercase flex items-center gap-1"
        >
          <Icon name="title" className="text-xs" /> Add Text
        </button>
      </div>

      {/* Right: Actions */}
      <div className="flex items-center gap-3">
        {/* Undo/Redo */}
        <div
          className="flex bg-white/5 border border-white/10 rounded p-1"
          role="group"
          aria-label="Undo/Redo"
        >
          <button
            onClick={onUndo}
            disabled={!canUndo}
            aria-label="Undo (Ctrl+Z)"
            title="Undo (Ctrl+Z)"
            className={`p-1 ${
              canUndo ? 'text-white/40 hover:text-white' : 'text-white/10 cursor-not-allowed'
            }`}
          >
            <Icon name="undo" />
          </button>
          <button
            onClick={onRedo}
            disabled={!canRedo}
            aria-label="Redo (Ctrl+Shift+Z)"
            title="Redo (Ctrl+Shift+Z)"
            className={`p-1 ${
              canRedo ? 'text-white/40 hover:text-white' : 'text-white/10 cursor-not-allowed'
            }`}
          >
            <Icon name="redo" />
          </button>
        </div>

        {/* Zoom */}
        <div className="flex bg-white/5 border border-white/10 rounded p-1">
          <button
            onClick={onZoomOut}
            aria-label="Zoom Out"
            className="p-1 text-white/40 hover:text-white"
          >
            <Icon name="remove" />
          </button>
          <span
            className="px-3 py-1 text-[10px] font-bold text-white/60 min-w-[60px] text-center"
            aria-live="polite"
          >
            {zoomPercent}%
          </span>
          <button
            onClick={onZoomIn}
            aria-label="Zoom In"
            className="p-1 text-white/40 hover:text-white"
          >
            <Icon name="add" />
          </button>
        </div>

        {/* Cancel/Save */}
        <button
          onClick={onCancel}
          aria-label="Cancel and close workspace"
          className="px-4 py-2 text-white/40 hover:text-white font-bold text-sm"
        >
          Cancel
        </button>
        <button
          onClick={onSave}
          aria-label="Apply composition to canvas"
          className="bg-indigo-600 text-white px-6 py-2 rounded-lg font-black uppercase tracking-widest text-xs hover:bg-indigo-500 shadow-xl transition-all"
        >
          Apply Composition
        </button>
      </div>
    </div>
  );
};
