// src/features/viewer/ui/molecules/ContinuousViewer.svelte
<!--
  ContinuousViewer.svelte — Virtualized scroll viewer using IntersectionObserver

  LAYER: molecule (receives cx + fieldMode props)
  FSD: features/viewer/ui/molecules

  Each canvas is rendered as a div with the correct aspect ratio. An
  IntersectionObserver tracks which canvas is in the viewport and calls
  onCanvasInView. Scrolls to activeCanvasId when it changes.
-->
<script lang="ts">
  import { cn } from '@/src/shared/lib/cn';
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import type { IIIFCanvas } from '@/src/shared/types';
  import { getIIIFValue } from '@/src/shared/types';
  import { onMount, tick } from 'svelte';

  interface Props {
    canvases: IIIFCanvas[];
    activeCanvasId?: string;
    gap?: number;
    horizontal?: boolean;
    fieldMode: boolean;
    cx: ContextualClassNames;
    onCanvasInView?: (canvasId: string) => void;
  }

  let {
    canvases,
    activeCanvasId,
    gap = 16,
    horizontal = false,
    fieldMode,
    cx,
    onCanvasInView,
  }: Props = $props();

  let containerEl: HTMLDivElement | undefined = $state(undefined);
  // Plain object from canvasId -> element, managed via Svelte action
  const canvasElements: Record<string, HTMLDivElement> = {};
  let intersectionObserver: IntersectionObserver | null = null;

  // Extract thumbnail URL from canvas
  function getThumbnailUrl(canvas: IIIFCanvas): string | null {
    const anyCanvas = canvas as any;
    if (anyCanvas.thumbnail) {
      const thumb = anyCanvas.thumbnail;
      if (Array.isArray(thumb) && thumb[0]?.id) return thumb[0].id;
      if (typeof thumb === 'string') return thumb;
    }
    const body = canvas.items?.[0]?.items?.[0]?.body as any;
    if (body?.id) return body.id;
    return null;
  }

  function getAspectRatio(canvas: IIIFCanvas): number {
    const w = canvas.width ?? 4;
    const h = canvas.height ?? 3;
    return w / h;
  }

  onMount(() => {
    if (onCanvasInView) {
      intersectionObserver = new IntersectionObserver(
        (entries) => {
          for (const entry of entries) {
            if (entry.isIntersecting) {
              const canvasId = (entry.target as HTMLElement).dataset.canvasId;
              if (canvasId) onCanvasInView!(canvasId);
            }
          }
        },
        { threshold: 0.5 }
      );
    }

    return () => {
      if (intersectionObserver) {
        intersectionObserver.disconnect();
        intersectionObserver = null;
      }
    };
  });

  // Scroll to active canvas when it changes
  $effect(() => {
    const id = activeCanvasId;
    if (!id) return;
    tick().then(() => {
      const el = canvasElements[id];
      if (el) el.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    });
  });

  // Svelte action: register/unregister canvas element with IntersectionObserver
  function canvasItem(el: HTMLDivElement, canvasId: string) {
    canvasElements[canvasId] = el;
    if (intersectionObserver) intersectionObserver.observe(el);

    return {
      update(newCanvasId: string) {
        delete canvasElements[canvasId];
        canvasElements[newCanvasId] = el;
      },
      destroy() {
        if (intersectionObserver) intersectionObserver.unobserve(el);
        delete canvasElements[canvasId];
      },
    };
  }
</script>

<div
  bind:this={containerEl}
  class={cn(
    'flex overflow-auto',
    horizontal ? 'flex-row items-center' : 'flex-col items-center',
    fieldMode ? 'bg-nb-black' : 'bg-nb-cream',
    'w-full h-full'
  )}
  style:gap="{gap}px"
  style:padding="{gap}px"
  role="list"
  aria-label="Canvas list"
>
  {#each canvases as canvas (canvas.id)}
    {@const ratio = getAspectRatio(canvas)}
    {@const thumb = getThumbnailUrl(canvas)}
    {@const isActive = canvas.id === activeCanvasId}
    {@const label = getIIIFValue(canvas.label) ?? 'Canvas'}

    <div
      use:canvasItem={canvas.id}
      data-canvas-id={canvas.id}
      class={cn(
        'relative shrink-0 overflow-hidden border-4 transition-nb',
        isActive
          ? fieldMode ? 'border-nb-yellow shadow-brutal' : 'border-nb-black shadow-brutal'
          : fieldMode ? 'border-nb-yellow/30' : 'border-nb-black/20',
        horizontal ? 'h-full' : 'w-full max-w-2xl'
      )}
      style:aspect-ratio={String(ratio)}
      role="listitem"
      aria-label={label}
    >
      {#if thumb}
        <img
          src={thumb}
          alt={label}
          class="w-full h-full object-contain"
          loading="lazy"
        />
      {:else}
        <div class={cn(
          'w-full h-full flex items-center justify-center',
          fieldMode ? 'bg-nb-yellow/10' : 'bg-nb-black/10'
        )}>
          <span class="material-symbols-outlined text-4xl opacity-30">image</span>
        </div>
      {/if}

      <!-- Canvas label overlay -->
      <div class={cn(
        'absolute bottom-0 left-0 right-0 px-2 py-1 text-xs font-mono truncate',
        fieldMode ? 'bg-nb-black/80 text-nb-yellow' : 'bg-nb-white/80 text-nb-black'
      )}>
        {label}
      </div>
    </div>
  {/each}
</div>

// src/features/viewer/ui/molecules/ContinuousViewer.tsx
/**
 * ContinuousViewer Molecule
 *
 * Vertically stitched scroll of all canvases for `behavior: ['continuous']`.
 * Virtualized rendering — only renders canvases in/near viewport.
 * Respects viewingDirection for axis (vertical by default, horizontal for LTR/RTL).
 *
 * @module features/viewer/ui/molecules/ContinuousViewer
 */

import React, { useRef, useCallback, useEffect, useState, useMemo } from 'react';
import type { IIIFCanvas } from '@/src/shared/types';
import { getIIIFValue } from '@/src/shared/types';
import { resolveImageSource } from '@/src/entities/canvas/model/imageSourceResolver';

export interface ContinuousViewerProps {
  /** All canvases in the manifest */
  canvases: IIIFCanvas[];
  /** Currently active canvas ID (scroll target) */
  activeCanvasId?: string;
  /** Callback when a canvas scrolls into view */
  onCanvasInView?: (canvasId: string) => void;
  /** Gap between canvases in pixels */
  gap?: number;
  /** Whether to layout horizontally (for LTR/RTL viewingDirection) */
  horizontal?: boolean;
  /** Field mode styling */
  fieldMode?: boolean;
}

const OVERSCAN = 2; // number of canvases to render beyond viewport

export const ContinuousViewer: React.FC<ContinuousViewerProps> = ({
  canvases,
  activeCanvasId,
  onCanvasInView,
  gap = 4,
  horizontal = false,
  fieldMode = false,
}) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [visibleRange, setVisibleRange] = useState({ start: 0, end: Math.min(5, canvases.length) });
  const observerRef = useRef<IntersectionObserver | null>(null);
  const canvasRefs = useRef<Map<string, HTMLDivElement>>(new Map());

  // Track which canvases are visible for virtualization
  useEffect(() => {
    if (!containerRef.current) return;

    observerRef.current = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            const canvasId = entry.target.getAttribute('data-canvas-id');
            if (canvasId && onCanvasInView) {
              onCanvasInView(canvasId);
            }
          }
        }

        // Update visible range for virtualization
        const visibleIds = entries
          .filter(e => e.isIntersecting)
          .map(e => e.target.getAttribute('data-canvas-id'))
          .filter(Boolean) as string[];

        if (visibleIds.length > 0) {
          const indices = visibleIds.map(id =>
            canvases.findIndex(c => c.id === id)
          ).filter(i => i >= 0);

          if (indices.length > 0) {
            const minIdx = Math.max(0, Math.min(...indices) - OVERSCAN);
            const maxIdx = Math.min(canvases.length, Math.max(...indices) + OVERSCAN + 1);
            setVisibleRange({ start: minIdx, end: maxIdx });
          }
        }
      },
      {
        root: containerRef.current,
        rootMargin: '200px',
        threshold: 0.1,
      }
    );

    return () => {
      observerRef.current?.disconnect();
    };
  }, [canvases, onCanvasInView]);

  // Observe canvas elements
  const setCanvasRef = useCallback((id: string, el: HTMLDivElement | null) => {
    if (el) {
      canvasRefs.current.set(id, el);
      observerRef.current?.observe(el);
    } else {
      const existing = canvasRefs.current.get(id);
      if (existing) observerRef.current?.unobserve(existing);
      canvasRefs.current.delete(id);
    }
  }, []);

  // Scroll to active canvas
  useEffect(() => {
    if (!activeCanvasId) return;
    const el = canvasRefs.current.get(activeCanvasId);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'center' });
    }
  }, [activeCanvasId]);

  // Resolve thumbnail URLs
  const resolvedUrls = useMemo(() => {
    const map: Record<string, string> = {};
    for (const canvas of canvases) {
      try {
        const resolved = resolveImageSource(canvas);
        if (resolved?.url) map[canvas.id] = resolved.url;
      } catch {
        // Skip
      }
    }
    return map;
  }, [canvases]);

  return (
    <div
      ref={containerRef}
      className={`flex-1 overflow-auto ${
        horizontal ? 'flex flex-row' : 'flex flex-col'
      } ${fieldMode ? 'bg-nb-black' : 'bg-nb-cream'}`}
      style={{ gap: `${gap}px` }}
    >
      {canvases.map((canvas, index) => {
        const isInRange = index >= visibleRange.start && index < visibleRange.end;
        const isActive = canvas.id === activeCanvasId;
        const url = resolvedUrls[canvas.id];

        // Estimate dimensions based on canvas aspect ratio
        const aspect = canvas.width && canvas.height ? canvas.width / canvas.height : 1;

        return (
          <div
            key={canvas.id}
            ref={(el) => setCanvasRef(canvas.id, el)}
            data-canvas-id={canvas.id}
            className={`shrink-0 relative ${
              isActive
                ? fieldMode
                  ? 'ring-2 ring-nb-yellow/50'
                  : 'ring-2 ring-nb-blue/50'
                : ''
            }`}
            style={horizontal
              ? { height: '100%', width: `${100 * aspect}%`, maxWidth: '90vw' }
              : { width: '100%', aspectRatio: `${aspect}` }
            }
          >
            {isInRange && url ? (
              <img
                src={url}
                alt={getIIIFValue(canvas.label) || `Canvas ${index + 1}`}
                className="w-full h-full object-contain"
                loading="lazy"
              />
            ) : (
              <div className={`w-full h-full flex items-center justify-center ${
                fieldMode ? 'bg-nb-black' : 'bg-nb-cream'
              }`}>
                <span className={`text-xs ${fieldMode ? 'text-nb-black/60' : 'text-nb-black/40'}`}>
                  {getIIIFValue(canvas.label) || `Canvas ${index + 1}`}
                </span>
              </div>
            )}

            {/* Canvas label overlay */}
            <div className={`absolute bottom-0 left-0 right-0 px-2 py-1 text-[10px] ${
              fieldMode
                ? 'bg-nb-black/60 text-nb-black/40'
                : 'bg-nb-white/60 text-nb-black/50'
            }`}>
              {index + 1}. {getIIIFValue(canvas.label) || 'Untitled'}
            </div>
          </div>
        );
      })}
    </div>
  );
};

export default ContinuousViewer;
