// src/features/viewer/ui/molecules/TimeAnnotationOverlay.tsx
/**
 * TimeAnnotationOverlay Molecule
 *
 * Time-based annotation tool for audio/video content.
 * Allows users to mark time ranges on the progress bar and add annotations.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Receives cx and fieldMode via props
 * - Uses useTimeAnnotation hook for annotation logic
 * - Integrates with MediaPlayer progress bar
 *
 * @see https://www.w3.org/TR/media-frags/ - W3C Media Fragments
 * @module features/viewer/ui/molecules/TimeAnnotationOverlay
 */

import React, { useCallback, useRef, useState } from 'react';
import { Button, Icon } from '@/src/shared/ui/atoms';
import { IconButton } from '@/src/shared/ui/molecules/IconButton';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';
import type { IIIFAnnotation } from '@/src/shared/types';
import {
  formatTimeForDisplay,
  getAnnotationTimeRange,
  isTimeBasedAnnotation,
  type TimeRange,
  useTimeAnnotation,
} from '../../model/annotation';

export interface TimeAnnotationOverlayProps {
  /** Canvas ID for creating annotations */
  canvasId: string;
  /** Total duration in seconds */
  duration: number;
  /** Current playback time in seconds */
  currentTime: number;
  /** Callback to seek to a specific time */
  onSeek: (time: number) => void;
  /** Whether annotation mode is active */
  isActive: boolean;
  /** Callback to toggle annotation mode */
  onToggle: (active: boolean) => void;
  /** Callback when annotation is created */
  onCreateAnnotation: (annotation: IIIFAnnotation) => void;
  /** Existing annotations to display */
  existingAnnotations: IIIFAnnotation[];
  /** Callback to expose save function to parent */
  onSaveRef?: (fn: () => void) => void;
  /** Callback to expose clear function to parent */
  onClearRef?: (fn: () => void) => void;
  /** Contextual styles */
  cx?: ContextualClassNames | Record<string, string>;
  /** Field mode flag */
  fieldMode?: boolean;
}

/**
 * TimeAnnotationOverlay
 *
 * Renders time-based annotation controls for audio/video content
 */
export const TimeAnnotationOverlay: React.FC<TimeAnnotationOverlayProps> = ({
  canvasId,
  duration,
  currentTime,
  onSeek,
  isActive,
  onToggle,
  onCreateAnnotation,
  existingAnnotations,
  onSaveRef,
  onClearRef,
  cx,
  fieldMode = false,
}) => {
  const progressRef = useRef<HTMLDivElement>(null);
  const [hoveredAnnotation, setHoveredAnnotation] = useState<IIIFAnnotation | null>(null);

  const {
    timeRange,
    isSelecting,
    hasStart,
    annotationText,
    motivation,
    canSave,
    existingTimeAnnotations,
    setStartTime,
    setEndTime,
    setTimeRange,
    setAnnotationText,
    setMotivation,
    handleClear,
    handleSave,
  } = useTimeAnnotation(canvasId, duration, existingAnnotations, onCreateAnnotation);

  // Expose save/clear to parent
  React.useEffect(() => {
    onSaveRef?.(handleSave);
  }, [onSaveRef, handleSave]);

  React.useEffect(() => {
    onClearRef?.(handleClear);
  }, [onClearRef, handleClear]);

  // Convert click position to time
  const getTimeFromPosition = useCallback((clientX: number): number => {
    if (!progressRef.current || duration === 0) return 0;

    const rect = progressRef.current.getBoundingClientRect();
    const percentage = Math.max(0, Math.min(1, (clientX - rect.left) / rect.width));
    return percentage * duration;
  }, [duration]);

  // Handle clicks on the annotation progress bar
  const handleProgressClick = useCallback((e: React.MouseEvent) => {
    if (!isActive) return;

    const time = getTimeFromPosition(e.clientX);

    if (!hasStart) {
      // Set start time
      setStartTime(time);
    } else if (isSelecting) {
      // Set end time
      setEndTime(time);
    }
  }, [isActive, hasStart, isSelecting, getTimeFromPosition, setStartTime, setEndTime]);

  // Handle "Use Current Time" buttons
  const handleSetStartFromCurrent = useCallback(() => {
    setStartTime(currentTime);
  }, [currentTime, setStartTime]);

  const handleSetEndFromCurrent = useCallback(() => {
    if (hasStart) {
      setEndTime(currentTime);
    }
  }, [currentTime, hasStart, setEndTime]);

  // Calculate percentage for display
  const timeToPercent = (time: number) => (time / duration) * 100;

  const accentColor = fieldMode ? 'rgb(234, 179, 8)' : 'rgb(34, 197, 94)';
  const accentBg = fieldMode ? 'bg-nb-yellow' : 'bg-nb-green';
  const accentBgFaded = fieldMode ? 'bg-nb-yellow/30' : 'bg-nb-green/30';
  const textColor = fieldMode ? 'text-nb-yellow' : 'text-nb-green';

  if (!isActive) {
    return (
      <IconButton
        icon="add_comment"
        ariaLabel="Add time annotation"
        onClick={() => onToggle(true)}
        variant="ghost"
        size="md"
        className="!text-white hover:!text-nb-blue"
        fieldMode={fieldMode}
      />
    );
  }

  return (
    <div className="relative">
      {/* Annotation Progress Bar */}
      <div
        ref={progressRef}
        className={`
          relative h-8 cursor-crosshair
          ${fieldMode ? 'bg-nb-black' : 'bg-nb-black/80'}
          border ${fieldMode ? 'border-nb-yellow/50' : 'border-nb-black/60'}
        `}
        onClick={handleProgressClick}
      >
        {/* Existing time annotations */}
        {existingTimeAnnotations.map((anno) => {
          const range = getAnnotationTimeRange(anno);
          if (!range) return null;

          const startPercent = timeToPercent(range.start);
          const endPercent = range.end !== undefined ? timeToPercent(range.end) : startPercent + 0.5;
          const width = Math.max(0.5, endPercent - startPercent);

          return (
            <div
              key={anno.id}
              className={`
                absolute top-1 bottom-1  cursor-pointer transition-nb
                ${hoveredAnnotation?.id === anno.id ? 'opacity-100 ring-2 ring-nb-blue' : 'opacity-70'}
                bg-nb-blue/50 hover:bg-nb-blue/70
              `}
              style={{
                left: `${startPercent}%`,
                width: `${width}%`,
              }}
              onMouseEnter={() => setHoveredAnnotation(anno)}
              onMouseLeave={() => setHoveredAnnotation(null)}
              onClick={(e) => {
                e.stopPropagation();
                onSeek(range.start);
              }}
              title={`${formatTimeForDisplay(range.start)}${range.end !== undefined ? ` - ${formatTimeForDisplay(range.end)}` : ''}`}
            />
          );
        })}

        {/* Current selection */}
        {timeRange && (
          <div
            className={`absolute top-1 bottom-1 ${accentBgFaded} border-2 ${fieldMode ? 'border-nb-yellow' : 'border-nb-green'}`}
            style={{
              left: `${timeToPercent(timeRange.start)}%`,
              width: `${timeRange.end !== undefined ? timeToPercent(timeRange.end) - timeToPercent(timeRange.start) : 0.5}%`,
            }}
          />
        )}

        {/* Current playback position indicator */}
        <div
          className="absolute top-0 bottom-0 w-0.5 bg-nb-white/80"
          style={{ left: `${timeToPercent(currentTime)}%` }}
        />

        {/* Instructions */}
        <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
          <span className={`text-xs font-medium ${fieldMode ? 'text-nb-yellow/70' : 'text-white/50'}`}>
            {!hasStart ? 'Click to set start time' :
             isSelecting ? 'Click to set end time' :
             'Range selected'}
          </span>
        </div>
      </div>

      {/* Annotation Form */}
      {timeRange && (
        <div className={`
          mt-3 p-3 
          ${fieldMode ? 'bg-nb-black border border-nb-yellow/50' : 'bg-nb-black/80 border border-nb-black/60'}
        `}>
          {/* Time Range Display */}
          <div className="flex items-center gap-3 mb-3">
            <div className="flex items-center gap-2">
              <span className={`text-xs font-medium ${fieldMode ? 'text-nb-yellow' : 'text-nb-green'}`}>
                Start:
              </span>
              <span className="text-sm text-white font-mono">
                {formatTimeForDisplay(timeRange.start)}
              </span>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleSetStartFromCurrent}
                className={`text-xs ${fieldMode ? 'text-nb-yellow hover:text-nb-yellow' : 'text-nb-blue hover:text-nb-blue/60'}`}
              >
                Use current
              </Button>
            </div>
            {timeRange.end !== undefined && (
              <>
                <span className="text-nb-black/40">→</span>
                <div className="flex items-center gap-2">
                  <span className={`text-xs font-medium ${fieldMode ? 'text-nb-yellow' : 'text-nb-green'}`}>
                    End:
                  </span>
                  <span className="text-sm text-white font-mono">
                    {formatTimeForDisplay(timeRange.end)}
                  </span>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={handleSetEndFromCurrent}
                    className={`text-xs ${fieldMode ? 'text-nb-yellow hover:text-nb-yellow' : 'text-nb-blue hover:text-nb-blue/60'}`}
                  >
                    Use current
                  </Button>
                </div>
              </>
            )}
          </div>

          {/* Motivation Selector */}
          <div className="flex items-center gap-2 mb-3">
            <span className="text-xs text-nb-black/40">Purpose:</span>
            {(['commenting', 'tagging', 'describing'] as const).map((mot) => (
              <Button
                key={mot}
                variant={motivation === mot ? 'primary' : 'ghost'}
                size="sm"
                onClick={() => setMotivation(mot)}
                className={motivation === mot ? '' : 'text-nb-black/40'}
              >
                {mot}
              </Button>
            ))}
          </div>

          {/* Annotation Text */}
          <textarea
            value={annotationText}
            onChange={(e) => setAnnotationText(e.target.value)}
            placeholder="Enter your annotation..."
            rows={2}
            className={`
              w-full text-sm p-2 border
              ${fieldMode ? 'bg-nb-black border-nb-yellow/50 text-white placeholder-yellow-400/30' : 'bg-nb-black border-nb-black/60 text-white placeholder-nb-black/50'}
              focus:outline-none focus:ring-2 ${fieldMode ? 'focus:ring-nb-yellow/50' : 'focus:ring-nb-blue/50'}
            `}
          />

          {/* Action Buttons */}
          <div className="flex items-center justify-between mt-3">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => {
                handleClear();
                onToggle(false);
              }}
              className="text-nb-black/40 hover:text-white"
            >
              <Icon name="close" className="mr-1" />
              Cancel
            </Button>

            <div className="flex items-center gap-2">
              <Button
                variant="ghost"
                size="sm"
                onClick={handleClear}
                className="text-nb-black/40 hover:text-white"
              >
                <Icon name="refresh" className="mr-1" />
                Clear
              </Button>

              <Button
                variant="primary"
                size="sm"
                onClick={() => {
                  handleSave();
                }}
                disabled={!canSave}
                className={!canSave ? 'opacity-50 cursor-not-allowed' : ''}
              >
                <Icon name="check" className="mr-1" />
                Save Annotation
              </Button>
            </div>
          </div>
        </div>
      )}

      {/* Hovered Annotation Tooltip */}
      {hoveredAnnotation && (
        <div className={`
          absolute -top-20 left-1/2 -translate-x-1/2 z-50
          max-w-xs p-2  shadow-brutal
          ${fieldMode ? 'bg-nb-black border border-nb-yellow/50' : 'bg-nb-black border border-nb-black/60'}
        `}>
          <p className="text-sm text-white">
            {(hoveredAnnotation.body as { value?: string })?.value || 'Annotation'}
          </p>
          <p className={`text-xs mt-1 ${fieldMode ? 'text-nb-yellow/70' : 'text-nb-black/40'}`}>
            {(() => {
              const range = getAnnotationTimeRange(hoveredAnnotation);
              if (!range) return '';
              return range.end !== undefined
                ? `${formatTimeForDisplay(range.start)} - ${formatTimeForDisplay(range.end)}`
                : formatTimeForDisplay(range.start);
            })()}
          </p>
        </div>
      )}
    </div>
  );
};

export default TimeAnnotationOverlay;

// src/features/viewer/ui/molecules/TimeAnnotationOverlay.svelte
<!--
  TimeAnnotationOverlay.svelte — Time range selection UI overlay on progress bar

  LAYER: molecule (receives fieldMode prop)
  FSD: features/viewer/ui/molecules

  Visual overlay showing a selected time range as a highlighted band on top of
  a progress bar. Click to start range, click again to end range. Shows a
  clear (X) button for an existing range and start/end time labels.
-->
<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import { cn } from '@/src/shared/lib/cn';
  import { formatTimeForDisplay } from '@/src/features/viewer/model/annotation';

  interface TimeRange {
    start: number;
    end?: number;
  }

  interface Props {
    currentTime: number;
    duration: number;
    timeRange: TimeRange | null;
    isSelecting: boolean;
    onRangeStart: (time: number) => void;
    onRangeEnd: (time: number) => void;
    onRangeClear: () => void;
    fieldMode: boolean;
    cx?: ContextualClassNames;
  }

  let {
    currentTime,
    duration,
    timeRange,
    isSelecting,
    onRangeStart,
    onRangeEnd,
    onRangeClear,
    fieldMode,
    cx = {} as ContextualClassNames,
  }: Props = $props();

  let trackEl: HTMLDivElement | undefined = $state(undefined);
  let hoveredTime = $state<number | null>(null);

  let accentColor = $derived(fieldMode ? '#FFE500' : '#22c55e');
  let accentBg = $derived(fieldMode ? 'bg-nb-yellow/30' : 'bg-green-500/30');
  let accentBorder = $derived(fieldMode ? 'border-nb-yellow' : 'border-green-500');
  let accentText = $derived(fieldMode ? 'text-nb-yellow' : 'text-green-500');

  // Percentage positions
  let rangeStartPct = $derived(
    timeRange && duration > 0 ? (timeRange.start / duration) * 100 : 0
  );
  let rangeEndPct = $derived(
    timeRange?.end !== undefined && duration > 0
      ? (timeRange.end / duration) * 100
      : rangeStartPct
  );
  let currentPct = $derived(duration > 0 ? (currentTime / duration) * 100 : 0);
  let hoveredPct = $derived(
    hoveredTime !== null && duration > 0 ? (hoveredTime / duration) * 100 : null
  );

  function getTimeFromMouseX(clientX: number): number {
    if (!trackEl || duration === 0) return 0;
    const rect = trackEl.getBoundingClientRect();
    const pct = Math.max(0, Math.min(1, (clientX - rect.left) / rect.width));
    return pct * duration;
  }

  function handleClick(e: MouseEvent) {
    const time = getTimeFromMouseX(e.clientX);
    if (!timeRange || timeRange.end !== undefined) {
      onRangeStart(time);
    } else {
      const start = Math.min(timeRange.start, time);
      const end = Math.max(timeRange.start, time);
      onRangeEnd(end);
    }
  }

  function handleMouseMove(e: MouseEvent) {
    hoveredTime = getTimeFromMouseX(e.clientX);
  }

  function handleMouseLeave() {
    hoveredTime = null;
  }
</script>

<div class="relative flex flex-col gap-1 select-none" aria-label="Time annotation range selector">
  <!-- Status text -->
  <div class={cn('text-xs font-mono flex items-center justify-between', accentText)}>
    <span>
      {#if !timeRange}
        Click to set start point
      {:else if timeRange.end === undefined}
        Click to set end point &mdash; start: {formatTimeForDisplay(timeRange.start)}
      {:else}
        Range: {formatTimeForDisplay(timeRange.start)} &ndash; {formatTimeForDisplay(timeRange.end)}
      {/if}
    </span>

    {#if timeRange}
      <button
        class={cn(
          'ml-2 flex items-center gap-0.5 px-1 py-0.5 border text-xs font-mono',
          fieldMode
            ? 'border-nb-yellow/60 text-nb-yellow hover:bg-nb-yellow/20'
            : 'border-green-500/60 text-green-600 hover:bg-green-500/10'
        )}
        onclick={onRangeClear}
        aria-label="Clear time range"
        title="Clear selection"
      >
        <span class="material-symbols-outlined text-xs leading-none">close</span>
        Clear
      </button>
    {/if}
  </div>

  <!-- Progress track -->
  <div
    bind:this={trackEl}
    class={cn(
      'relative h-4 cursor-pointer',
      isSelecting && cn('ring-2 ring-offset-1', fieldMode ? 'ring-nb-yellow ring-offset-black' : 'ring-green-500 ring-offset-white')
    )}
    style:background={fieldMode ? '#1e293b' : '#e2e8f0'}
    onclick={handleClick}
    onkeydown={(e) => {
      if (e.key === 'Enter' || e.key === ' ') {
        e.preventDefault();
        // Use midpoint of track as fallback for keyboard activation
        if (!timeRange || timeRange.end !== undefined) {
          onRangeStart(duration / 2);
        } else {
          onRangeEnd(Math.min(duration, (timeRange.start + duration) / 2));
        }
      }
    }}
    onmousemove={handleMouseMove}
    onmouseleave={handleMouseLeave}
    role="slider"
    aria-label="Time range track"
    aria-valuemin={0}
    aria-valuemax={duration}
    aria-valuenow={timeRange?.start ?? currentTime}
    tabindex="0"
  >
    <!-- Current playback progress -->
    <div
      class={cn('absolute top-0 bottom-0 left-0 opacity-30', fieldMode ? 'bg-nb-yellow' : 'bg-blue-500')}
      style:width="{currentPct}%"
    ></div>

    <!-- Selected range band -->
    {#if timeRange}
      <div
        class={cn('absolute top-0 bottom-0', accentBg)}
        style:left="{rangeStartPct}%"
        style:width="{Math.max(0.5, rangeEndPct - rangeStartPct)}%"
      ></div>

      <!-- Start handle -->
      <div
        class={cn('absolute top-0 bottom-0 w-0.5', fieldMode ? 'bg-nb-yellow' : 'bg-green-500')}
        style:left="{rangeStartPct}%"
      ></div>

      <!-- End handle (if set) -->
      {#if timeRange.end !== undefined}
        <div
          class={cn('absolute top-0 bottom-0 w-0.5', fieldMode ? 'bg-nb-yellow' : 'bg-green-500')}
          style:left="{rangeEndPct}%"
        ></div>
      {/if}
    {/if}

    <!-- Playhead -->
    <div
      class={cn('absolute top-1/2 -translate-y-1/2 w-2.5 h-2.5', fieldMode ? 'bg-nb-yellow' : 'bg-nb-blue')}
      style:left="calc({currentPct}% - 5px)"
    ></div>

    <!-- Hover time tooltip -->
    {#if hoveredTime !== null && hoveredPct !== null}
      <div
        class={cn(
          'absolute -top-7 transform -translate-x-1/2 px-1.5 py-0.5 text-[10px] font-mono pointer-events-none',
          fieldMode ? 'bg-nb-black text-nb-yellow border border-nb-yellow/40' : 'bg-nb-black/80 text-nb-white'
        )}
        style:left="{hoveredPct}%"
      >
        {formatTimeForDisplay(hoveredTime)}
      </div>
    {/if}
  </div>

  <!-- Time labels -->
  {#if timeRange && timeRange.end !== undefined}
    <div class="flex justify-between text-[10px] font-mono tabular-nums" style:color={accentColor}>
      <span>Start: {formatTimeForDisplay(timeRange.start)}</span>
      <span>Duration: {formatTimeForDisplay(timeRange.end - timeRange.start)}</span>
      <span>End: {formatTimeForDisplay(timeRange.end)}</span>
    </div>
  {/if}
</div>
