// src/features/viewer/ui/molecules/ViewerEmptyState.tsx
/**
 * ViewerEmptyState Molecule
 *
 * Composes: GuidedEmptyState + terminology adaptation
 *
 * Displays when no canvas is selected in the viewer.
 * Uses user-friendly terminology and provides clear guidance
 * on how to select content.
 *
 * COMMUNICATIVE DESIGN:
 * - Uses terminology appropriate to user's abstraction level
 * - Shows visual example of what to do
 * - Provides direct navigation to content
 * - Explains what will happen after selection
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Receives cx and fieldMode via props (no hook calls)
 * - Composes molecules: GuidedEmptyState
 * - Local UI state only
 * - No domain logic
 *
 * IDEAL OUTCOME: Clear guidance when no canvas is selected
 * FAILURE PREVENTED: User confusion about empty viewer state
 */

import React from 'react';
import { GuidedEmptyState } from '@/src/shared/ui/molecules';
import type { ContextualClassNames } from '@/hooks/useContextualStyles';

export interface ViewerEmptyStateProps {
  /** Terminology function for localized strings */
  t: (key: string) => string;
  /** Optional custom message */
  message?: string;
  /** Contextual styles from template */
  cx: ContextualClassNames;
  /** Current field mode */
  fieldMode: boolean;
  /** Callback to navigate to archive */
  onGoToArchive?: () => void;
  /** Callback to import content */
  onImport?: () => void;
  /** Whether archive has any content */
  hasContent?: boolean;
}

/**
 * ViewerEmptyState Molecule
 *
 * @example
 * <ViewerEmptyState
 *   t={(key) => translations[key]}
 *   cx={cx}
 *   fieldMode={fieldMode}
 *   onGoToArchive={() => navigate('/archive')}
 *   hasContent={true}
 * />
 */
export const ViewerEmptyState: React.FC<ViewerEmptyStateProps> = ({
  t,
  message,
  cx,
  fieldMode,
  onGoToArchive,
  onImport,
  hasContent = false,
}) => {
  // Get user-friendly term for Canvas based on abstraction level
  const canvasTerm = t('Canvas');
  const archiveTerm = t('Archive');

  // Define workflow steps based on whether archive has content
  const steps = hasContent
    ? [
        {
          id: 'navigate',
          number: 1,
          title: `Go to ${archiveTerm}`,
          description: `Switch to the ${archiveTerm} view to see your content`,
          icon: 'folder_open' as const,
          active: true,
          action: onGoToArchive ? {
            label: `Open ${archiveTerm}`,
            onClick: onGoToArchive,
          } : undefined,
        },
        {
          id: 'select',
          number: 2,
          title: `Select a ${canvasTerm}`,
          description: `Click any ${canvasTerm.toLowerCase()} to view it`,
          icon: 'touch_app' as const,
        },
        {
          id: 'view',
          number: 3,
          title: 'View Details',
          description: `See the full image and metadata here`,
          icon: 'visibility' as const,
        },
      ]
    : [
        {
          id: 'import',
          number: 1,
          title: 'Import Content',
          description: 'Add photos, videos, or documents',
          icon: 'upload' as const,
          active: true,
          action: onImport ? {
            label: 'Import Files',
            onClick: onImport,
          } : undefined,
        },
        {
          id: 'organize',
          number: 2,
          title: 'Organize',
          description: 'Arrange into albums and groups',
          icon: 'folder' as const,
        },
        {
          id: 'view',
          number: 3,
          title: 'View',
          description: 'Open items in the viewer',
          icon: 'visibility' as const,
        },
      ];

  const primaryAction = hasContent && onGoToArchive
    ? {
        label: `Browse ${archiveTerm}`,
        icon: 'folder_open' as const,
        onClick: onGoToArchive,
      }
    : onImport
    ? {
        label: 'Import Your First Files',
        icon: 'upload' as const,
        onClick: onImport,
      }
    : {
        label: 'Get Started',
        icon: 'arrow_forward' as const,
        onClick: () => {},
      };

  const secondaryAction = hasContent && onImport
    ? {
        label: 'Import More',
        icon: 'add' as const,
        onClick: onImport,
      }
    : undefined;

  return (
    <GuidedEmptyState
      icon="image"
      title={message || `Select a ${canvasTerm}`}
      subtitle={
        hasContent
          ? `Choose a ${canvasTerm.toLowerCase()} from the ${archiveTerm.toLowerCase()} to view it here`
          : `Your ${archiveTerm.toLowerCase()} is empty. Import files to get started.`
      }
      steps={steps}
      primaryAction={primaryAction}
      secondaryAction={secondaryAction}
      cx={cx}
      fieldMode={fieldMode}
      tip={hasContent
        ? `Tip: You can also double-click any ${canvasTerm.toLowerCase()} to open it directly`
        : `Tip: Drag and drop a folder to quickly import multiple files`
      }
    />
  );
};

export default ViewerEmptyState;

// src/features/viewer/ui/molecules/ViewerEmptyState.svelte
<!--
  ViewerEmptyState.svelte -- Guided empty state for the viewer
  React source: src/features/viewer/ui/molecules/ViewerEmptyState.tsx
  Layer: molecule (FSD features/viewer/ui/molecules)

  Displays when no canvas is selected. Provides workflow guidance based on
  whether the project has content loaded. Uses GuidanceEmptyState pattern.
-->
<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import { cn } from '@/src/shared/lib/cn';
  import Button from '@/src/shared/ui/atoms/Button.svelte';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';
  import GuidanceEmptyState from '@/src/shared/ui/molecules/GuidanceEmptyState.svelte';

  interface Props {
    t: (key: string) => string;
    hasContent?: boolean;
    message?: string;
    onGoToArchive?: () => void;
    onImport?: () => void;
    cx: ContextualClassNames;
    fieldMode: boolean;
  }

  let {
    t,
    hasContent = false,
    message,
    onGoToArchive,
    onImport,
    cx,
    fieldMode,
  }: Props = $props();

  let canvasTerm = $derived(t('Canvas'));
  let archiveTerm = $derived(t('Archive'));

  let title = $derived(
    message || `Select a ${canvasTerm}`
  );

  let description = $derived(
    hasContent
      ? `Choose a ${canvasTerm.toLowerCase()} from the ${archiveTerm.toLowerCase()} to view it here`
      : `Your ${archiveTerm.toLowerCase()} is empty. Import files to get started.`
  );

  let steps = $derived.by(() => {
    if (hasContent) {
      return [
        { icon: 'folder_open', text: `Go to ${archiveTerm} to see your content` },
        { icon: 'touch_app', text: `Select a ${canvasTerm.toLowerCase()} to view it` },
        { icon: 'visibility', text: 'See the full image and metadata here' },
      ];
    }
    return [
      { icon: 'upload', text: 'Add photos, videos, or documents' },
      { icon: 'folder', text: 'Arrange into albums and groups' },
      { icon: 'visibility', text: 'Open items in the viewer' },
    ];
  });

  let tip = $derived(
    hasContent
      ? `Tip: You can also double-click any ${canvasTerm.toLowerCase()} to open it directly`
      : 'Tip: Drag and drop a folder to quickly import multiple files'
  );
</script>

<GuidanceEmptyState
  icon="image"
  {title}
  {description}
  {steps}
  {cx}
>
  {#snippet action()}
    <div class="flex flex-col items-center gap-3">
      <!-- Action buttons -->
      <div class="flex items-center gap-3">
        {#if !hasContent && onImport}
          <Button variant="primary" onclick={onImport}>
            {#snippet icon()}
              <Icon name="upload" class="text-base" />
            {/snippet}
            {#snippet children()}
              Import Your First Files
            {/snippet}
          </Button>
        {/if}

        {#if onGoToArchive}
          <Button
            variant={hasContent ? 'primary' : 'ghost'}
            onclick={onGoToArchive}
          >
            {#snippet icon()}
              <Icon name="folder_open" class="text-base" />
            {/snippet}
            {#snippet children()}
              {hasContent ? `Browse ${archiveTerm}` : `Go to ${archiveTerm}`}
            {/snippet}
          </Button>
        {/if}

        {#if hasContent && onImport}
          <Button variant="ghost" onclick={onImport}>
            {#snippet icon()}
              <Icon name="add" class="text-base" />
            {/snippet}
            {#snippet children()}
              Import More
            {/snippet}
          </Button>
        {/if}
      </div>

      <!-- Tip -->
      <p class={cn(
        'text-xs font-mono mt-2 max-w-sm text-center',
        fieldMode ? 'text-nb-yellow/40' : 'text-nb-black/40'
      )}>
        {tip}
      </p>
    </div>
  {/snippet}
</GuidanceEmptyState>
