// src/features/viewer/ui/molecules/ViewerSearchPanel.svelte
<!--
  ViewerSearchPanel — IIIF Content Search 2.0 UI
  React source: src/features/viewer/ui/molecules/ViewerSearchPanel.tsx (464 lines)
  Layer: molecule (FSD features/viewer/ui/molecules)

  Search form with autocomplete, debounced suggestions, grouped results by
  canvas, keyboard navigation (arrow keys, enter, escape).
-->

<script module lang="ts">
  export interface SearchResult {
    id: string;
    canvasId: string;
    text: string;
    selector?: {
      prefix?: string;
      exact: string;
      suffix?: string;
    };
    region?: {
      x: number;
      y: number;
      width: number;
      height: number;
    };
    time?: {
      start: number;
      end?: number;
    };
  }

  export interface SearchService {
    id: string;
    type: string;
    profile?: string;
  }

  /** Format seconds to MM:SS */
  function formatTime(seconds: number): string {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  }
</script>

<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/ui/molecules/ViewHeader/types';
  import type { IIIFManifest } from '@/src/shared/types';
  import { cn } from '@/src/shared/lib/cn';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';
  import Button from '@/src/shared/ui/atoms/Button.svelte';

  interface Props {
    manifest: IIIFManifest | null;
    searchService: SearchService | null;
    onResultSelect: (result: SearchResult) => void;
    onResultsChange?: (results: SearchResult[]) => void;
    currentCanvasId?: string;
    cx?: ContextualClassNames | Record<string, string>;
    fieldMode?: boolean;
    onSearch: (query: string) => Promise<SearchResult[]>;
    onFetchSuggestions?: (input: string) => Promise<Array<{ value: string; count?: number }>>;
  }

  let {
    manifest: _manifest,
    searchService,
    onResultSelect,
    onResultsChange,
    currentCanvasId,
    cx: _cx,
    fieldMode = false,
    onSearch,
    onFetchSuggestions,
  }: Props = $props();

  // Internal state
  let query = $state('');
  let localQuery = $state('');
  let results = $state<SearchResult[]>([]);
  let suggestions = $state<Array<{ value: string; count?: number }>>([]);
  let loading = $state(false);
  let error = $state<string | null>(null);
  let total = $state(0);
  let showSuggestions = $state(false);
  let selectedIndex = $state(-1);
  let suggestionTimeoutId: ReturnType<typeof setTimeout> | undefined;

  // Derived styling
  let bgClass = $derived(fieldMode ? 'bg-nb-black' : 'bg-nb-white');
  let textClass = $derived(fieldMode ? 'text-white' : 'text-nb-black');
  let borderClass = $derived(fieldMode ? 'border-nb-black' : 'border-nb-black/20');
  let mutedTextClass = $derived(fieldMode ? 'text-nb-black/40' : 'text-nb-black/50');

  // Group results by canvas
  let groupedResults = $derived.by(() => {
    const groups: Record<string, SearchResult[]> = {};
    for (const result of results) {
      if (!groups[result.canvasId]) {
        groups[result.canvasId] = [];
      }
      groups[result.canvasId].push(result);
    }
    return groups;
  });

  // Perform search
  async function performSearch(searchQuery: string) {
    if (!searchService || !searchQuery.trim()) {
      results = [];
      total = 0;
      onResultsChange?.([]);
      return;
    }

    loading = true;
    error = null;

    try {
      const searchResults = await onSearch(searchQuery);
      results = searchResults;
      total = searchResults.length;
      onResultsChange?.(searchResults);
    } catch (e: unknown) {
      const errorMessage = e instanceof Error ? e.message : 'Search failed';
      error = errorMessage;
      results = [];
      total = 0;
    } finally {
      loading = false;
    }
  }

  // Fetch autocomplete suggestions
  async function fetchSuggestions(input: string) {
    if (!onFetchSuggestions || input.length < 2) {
      suggestions = [];
      return;
    }

    try {
      const response = await onFetchSuggestions(input);
      suggestions = response;
      showSuggestions = true;
    } catch {
      suggestions = [];
    }
  }

  // Handle input changes with debounced suggestions
  function handleInputChange(e: Event) {
    const value = (e.target as HTMLInputElement).value;
    localQuery = value;
    query = value;
    selectedIndex = -1;

    // Debounce suggestions
    if (suggestionTimeoutId) clearTimeout(suggestionTimeoutId);
    suggestionTimeoutId = setTimeout(() => {
      fetchSuggestions(value);
    }, 200);
  }

  // Handle form submission
  function handleSubmit(e: Event) {
    e.preventDefault();
    showSuggestions = false;
    performSearch(query);
  }

  // Select a suggestion
  function selectSuggestion(term: { value: string }) {
    localQuery = term.value;
    query = term.value;
    showSuggestions = false;
    performSearch(term.value);
  }

  // Keyboard navigation for autocomplete
  function handleKeyDown(e: KeyboardEvent) {
    if (!showSuggestions || suggestions.length === 0) return;

    if (e.key === 'ArrowDown') {
      e.preventDefault();
      selectedIndex = Math.min(selectedIndex + 1, suggestions.length - 1);
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      selectedIndex = Math.max(selectedIndex - 1, -1);
    } else if (e.key === 'Enter' && selectedIndex >= 0) {
      e.preventDefault();
      selectSuggestion(suggestions[selectedIndex]);
    } else if (e.key === 'Escape') {
      showSuggestions = false;
    }
  }

  // Clear search
  function clearSearch() {
    query = '';
    localQuery = '';
    results = [];
    suggestions = [];
    total = 0;
    error = null;
    onResultsChange?.([]);
  }

  // Highlight query matches in text
  function highlightParts(text: string, searchQuery: string): Array<{ text: string; isMatch: boolean }> {
    if (!searchQuery) return [{ text, isMatch: false }];
    const escapedQuery = searchQuery.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const parts = text.split(new RegExp(`(${escapedQuery})`, 'gi'));
    return parts.map(part => ({
      text: part,
      isMatch: part.toLowerCase() === searchQuery.toLowerCase(),
    }));
  }
</script>

{#snippet highlightMatch(text: string, searchQuery: string)}
  {#each highlightParts(text, searchQuery) as segment}
    {#if segment.isMatch}
      <mark class={cn(
        'px-0.5 rounded',
        fieldMode ? 'bg-nb-yellow/20 text-nb-yellow' : 'bg-nb-yellow/60 text-nb-yellow'
      )}>{segment.text}</mark>
    {:else}
      {segment.text}
    {/if}
  {/each}
{/snippet}

{#snippet searchResultItem(result: SearchResult, searchQuery: string)}
  <div>
    <p class={cn('text-sm leading-relaxed', fieldMode ? 'text-nb-black/30' : 'text-nb-black/80')}>
      {#if result.selector}
        {#if result.selector.prefix}
          <span class={fieldMode ? 'text-nb-black/50' : 'text-nb-black/40'}>...{result.selector.prefix}</span>
        {/if}
        <mark class={cn(
          'px-0.5 font-medium',
          fieldMode ? 'bg-nb-yellow/20 text-nb-yellow' : 'bg-nb-yellow/60 text-nb-yellow'
        )}>{result.selector.exact}</mark>
        {#if result.selector.suffix}
          <span class={fieldMode ? 'text-nb-black/50' : 'text-nb-black/40'}>{result.selector.suffix}...</span>
        {/if}
      {:else}
        {@render highlightMatch(result.text.substring(0, 200), searchQuery)}
      {/if}
    </p>

    <!-- Location info -->
    <div class={cn('flex items-center gap-3 mt-1.5 text-xs', fieldMode ? 'text-nb-black/50' : 'text-nb-black/40')}>
      {#if result.region}
        <span class="flex items-center gap-1">
          <Icon name="crop" class="text-sm" />
          {result.region.x},{result.region.y}
        </span>
      {/if}
      {#if result.time}
        <span class="flex items-center gap-1">
          <Icon name="schedule" class="text-sm" />
          {formatTime(result.time.start)}
          {#if result.time.end}
            {' '}- {formatTime(result.time.end)}
          {/if}
        </span>
      {/if}
      <Icon
        name="arrow_forward"
        class={cn('text-sm ml-auto opacity-0 group-hover:opacity-100 transition-nb', fieldMode ? 'text-nb-black/40' : '')}
      />
    </div>
  </div>
{/snippet}

{#if !searchService}
  <div class={cn('p-4 text-center', mutedTextClass)}>
    <Icon name="search_off" class="text-4xl mb-2 opacity-50" />
    <p class="text-sm">No search service available for this manifest.</p>
  </div>
{:else}
  <div class={cn('flex flex-col h-full', bgClass)}>
    <!-- Search Input -->
    <form onsubmit={handleSubmit} class={cn('p-3 border-b sticky top-0 z-10', borderClass, bgClass)}>
      <div class="relative">
        <div class="absolute left-3 top-1/2 -translate-y-1/2">
          <Icon name="search" class={mutedTextClass} />
        </div>
        <input
          type="text"
          value={localQuery}
          oninput={handleInputChange}
          onkeydown={handleKeyDown}
          onfocus={() => { if (suggestions.length > 0) showSuggestions = true; }}
          placeholder="Search within manifest..."
          class={cn(
            'w-full pl-10 pr-10 py-2 text-sm border font-mono',
            fieldMode ? 'bg-nb-black border-nb-black/80 text-white' : 'bg-nb-white border-nb-black/20 text-nb-black'
          )}
          aria-label="Search within manifest"
          aria-autocomplete={onFetchSuggestions ? 'list' : 'none'}
          aria-controls="search-suggestions"
          aria-expanded={showSuggestions}
        />
        {#if query}
          <div class="absolute right-2 top-1/2 -translate-y-1/2">
            <Button variant="ghost" size="bare" onclick={clearSearch} aria-label="Clear search">
              <Icon name="close" class={cn('text-sm', mutedTextClass)} />
            </Button>
          </div>
        {/if}

        <!-- Autocomplete Suggestions -->
        {#if showSuggestions && suggestions.length > 0}
          <ul
            id="search-suggestions"
            role="listbox"
            class={cn(
              'absolute top-full left-0 right-0 mt-1 border shadow-brutal z-20 max-h-60 overflow-auto',
              fieldMode ? 'bg-nb-black border-nb-black/80' : 'bg-nb-white border-nb-black/20'
            )}
          >
            {#each suggestions as term, index}
              <!-- svelte-ignore a11y_click_events_have_key_events -->
              <li
                role="option"
                aria-selected={index === selectedIndex}
                onclick={() => selectSuggestion(term)}
                class={cn(
                  'px-4 py-2 cursor-pointer flex items-center justify-between',
                  index === selectedIndex
                    ? fieldMode ? 'bg-nb-blue text-nb-blue/60' : 'bg-nb-blue/10 text-nb-blue'
                    : fieldMode ? 'hover:bg-nb-black text-nb-black/30' : 'hover:bg-nb-white'
                )}
              >
                <span class="text-sm">{term.value}</span>
                {#if term.count}
                  <span class={cn('text-xs', mutedTextClass)}>{term.count}</span>
                {/if}
              </li>
            {/each}
          </ul>
        {/if}
      </div>
    </form>

    <!-- Results -->
    <div class="flex-1 overflow-auto">
      {#if loading}
        <div class="flex items-center justify-center py-8">
          <div class="w-6 h-6 border-2 border-nb-black/20 border-t-nb-blue animate-spin"></div>
        </div>
      {/if}

      {#if error}
        <div class={cn(
          'p-4 m-3 border text-sm',
          fieldMode ? 'bg-nb-red/30 border-nb-red text-nb-red/60' : 'bg-nb-red/10 border-nb-red/30 text-nb-red'
        )}>
          <Icon name="error" class="inline mr-2" />
          {error}
        </div>
      {/if}

      {#if !loading && !error && results.length === 0 && query}
        <div class={cn('p-8 text-center', mutedTextClass)}>
          <Icon name="search_off" class="text-4xl mb-2 opacity-50" />
          <p class="text-sm">No results found for "{query}"</p>
        </div>
      {/if}

      {#if !loading && results.length > 0}
        <!-- Results Header -->
        <div class={cn(
          'px-4 py-2 border-b text-xs font-medium sticky top-0',
          fieldMode ? 'bg-nb-black border-nb-black' : 'bg-nb-white',
          mutedTextClass
        )}>
          {total} result{total !== 1 ? 's' : ''} for "{query}"
        </div>

        <!-- Grouped Results -->
        <div class="divide-y">
          {#each Object.entries(groupedResults) as [canvasId, canvasResults]}
            <div class={currentCanvasId === canvasId
              ? fieldMode ? 'bg-nb-blue/30' : 'bg-nb-blue/10'
              : ''
            }>
              <!-- Canvas Header -->
              <div class={cn(
                'px-4 py-2 text-xs font-medium flex items-center gap-2',
                fieldMode ? 'bg-nb-black/50' : 'bg-nb-cream/50',
                mutedTextClass
              )}>
                <Icon name="image" class="text-sm" />
                <span class="truncate flex-1">
                  {canvasId.split('/').pop()}
                </span>
                <span class={mutedTextClass}>
                  {canvasResults.length} hit{canvasResults.length !== 1 ? 's' : ''}
                </span>
              </div>

              <!-- Results for this canvas -->
              {#each canvasResults as result, index}
                <!-- svelte-ignore a11y_no_static_element_interactions -->
                <div
                  onclick={() => onResultSelect(result)}
                  onkeydown={(e) => { if (e.key === 'Enter' || e.key === ' ') onResultSelect(result); }}
                  class={cn(
                    'w-full px-4 py-3 text-left transition-nb group cursor-pointer',
                    fieldMode
                      ? 'hover:bg-nb-black text-nb-black/30'
                      : 'hover:bg-nb-white text-nb-black/80'
                  )}
                  role="button"
                  tabindex="0"
                >
                  {@render searchResultItem(result, query)}
                </div>
              {/each}
            </div>
          {/each}
        </div>
      {/if}
    </div>
  </div>
{/if}

// src/features/viewer/ui/molecules/ViewerSearchPanel.tsx
/**
 * ViewerSearchPanel Molecule
 *
 * Composes: Icon atom + Input atom + IconButton molecule
 *
 * IIIF Content Search 2.0 UI for searching within manifests.
 * Provides search input with autocomplete and result list.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Receives cx and fieldMode via props (no hook calls)
 * - Composes atoms: Icon, Input
 * - Composes molecules: IconButton
 * - Local UI state only (useState, useCallback, useEffect)
 * - No domain logic - search service passed as prop
 *
 * IDEAL OUTCOME: Users can search within IIIF manifests
 * FAILURE PREVENTED: Search timeouts, result overflow, focus loss
 */

import React, { useCallback, useEffect, useState } from 'react';
import { Icon, Input } from '@/src/shared/ui/atoms';
import { IconButton } from '@/src/shared/ui/molecules/IconButton';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';
import type { IIIFManifest } from '@/src/shared/types';

export interface SearchResult {
  id: string;
  canvasId: string;
  text: string;
  selector?: {
    prefix?: string;
    exact: string;
    suffix?: string;
  };
  region?: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
  time?: {
    start: number;
    end?: number;
  };
}

export interface SearchService {
  id: string;
  type: string;
  profile?: string;
}

export interface ViewerSearchPanelProps {
  /** The manifest to search within */
  manifest: IIIFManifest | null;
  /** Search service extracted from manifest */
  searchService: SearchService | null;
  /** Callback when a result is selected */
  onResultSelect: (result: SearchResult) => void;
  /** Callback when results change (for overlay rendering) */
  onResultsChange?: (results: SearchResult[]) => void;
  /** Currently selected canvas ID (to highlight relevant results) */
  currentCanvasId?: string;
  /** Contextual styles from template (unused but passed for consistency) */
  cx?: ContextualClassNames | Record<string, string>;
  /** Current field mode */
  fieldMode?: boolean;
  /** Callback to perform search - delegates to service */
  onSearch: (query: string) => Promise<SearchResult[]>;
  /** Callback to fetch autocomplete suggestions */
  onFetchSuggestions?: (input: string) => Promise<Array<{ value: string; count?: number }>>;
}

/**
 * ViewerSearchPanel Molecule
 *
 * @example
 * <ViewerSearchPanel
 *   manifest={manifest}
 *   searchService={searchService}
 *   onResultSelect={handleResultSelect}
 *   onSearch={searchFn}
 *   cx={cx}
 *   fieldMode={fieldMode}
 * />
 */
export const ViewerSearchPanel: React.FC<ViewerSearchPanelProps> = ({
  manifest: _manifest,
  searchService,
  onResultSelect,
  onResultsChange,
  currentCanvasId,
  cx: _cx,
  fieldMode = false,
  onSearch,
  onFetchSuggestions,
}) => {
  const [query, setQuery] = useState('');
  const [localQuery, setLocalQuery] = useState('');
  const [results, setResults] = useState<SearchResult[]>([]);
  const [suggestions, setSuggestions] = useState<Array<{ value: string; count?: number }>>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [total, setTotal] = useState(0);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [selectedIndex, setSelectedIndex] = useState(-1);

  // Sync local query with external query
  useEffect(() => {
    setLocalQuery(query);
  }, [query]);

  // Handle search
  const performSearch = useCallback(async (searchQuery: string) => {
    if (!searchService || !searchQuery.trim()) {
      setResults([]);
      setTotal(0);
      onResultsChange?.([]);
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const searchResults = await onSearch(searchQuery);
      setResults(searchResults);
      setTotal(searchResults.length);
      onResultsChange?.(searchResults);
    } catch (e: unknown) {
      const errorMessage = e instanceof Error ? e.message : 'Search failed';
      setError(errorMessage);
      setResults([]);
      setTotal(0);
    } finally {
      setLoading(false);
    }
  }, [searchService, onSearch, onResultsChange]);

  // Handle autocomplete
  const fetchSuggestions = useCallback(async (input: string) => {
    if (!onFetchSuggestions || input.length < 2) {
      setSuggestions([]);
      return;
    }

    try {
      const response = await onFetchSuggestions(input);
      setSuggestions(response);
      setShowSuggestions(true);
    } catch {
      setSuggestions([]);
    }
  }, [onFetchSuggestions]);

  // Debounced input handler
  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const {value} = e.target;
    setLocalQuery(value);
    setQuery(value);
    setSelectedIndex(-1);

    // Debounce suggestions
    setTimeout(() => {
      fetchSuggestions(value);
    }, 200);
  };

  // Handle form submit
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setShowSuggestions(false);
    performSearch(query);
  };

  // Handle suggestion selection
  const selectSuggestion = (term: { value: string }) => {
    setLocalQuery(term.value);
    setQuery(term.value);
    setShowSuggestions(false);
    performSearch(term.value);
  };

  // Keyboard navigation
  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (!showSuggestions || suggestions.length === 0) return;

    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setSelectedIndex(prev => Math.min(prev + 1, suggestions.length - 1));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setSelectedIndex(prev => Math.max(prev - 1, -1));
    } else if (e.key === 'Enter' && selectedIndex >= 0) {
      e.preventDefault();
      selectSuggestion(suggestions[selectedIndex]);
    } else if (e.key === 'Escape') {
      setShowSuggestions(false);
    }
  };

  // Clear search
  const clearSearch = () => {
    setQuery('');
    setLocalQuery('');
    setResults([]);
    setSuggestions([]);
    setTotal(0);
    setError(null);
    onResultsChange?.([]);
  };

  // Group results by canvas
  const groupedResults = results.reduce((acc, result) => {
    if (!acc[result.canvasId]) {
      acc[result.canvasId] = [];
    }
    acc[result.canvasId].push(result);
    return acc;
  }, {} as Record<string, SearchResult[]>);

  // Styling based on field mode
  const bgClass = fieldMode ? 'bg-nb-black' : 'bg-nb-white';
  const textClass = fieldMode ? 'text-white' : 'text-nb-black';
  const borderClass = fieldMode ? 'border-nb-black' : 'border-nb-black/20';
  const mutedTextClass = fieldMode ? 'text-nb-black/40' : 'text-nb-black/50';

  if (!searchService) {
    return (
      <div className={`p-4 text-center ${mutedTextClass}`}>
        <Icon name="search_off" className="text-4xl mb-2 opacity-50" />
        <p className="text-sm">No search service available for this manifest.</p>
      </div>
    );
  }

  return (
    <div className={`flex flex-col h-full ${bgClass}`}>
      {/* Search Input */}
      <form onSubmit={handleSubmit} className={`p-3 border-b ${borderClass} sticky top-0 z-10 ${bgClass}`}>
        <div className="relative">
          <div className="absolute left-3 top-1/2 -translate-y-1/2">
            <Icon name="search" className={mutedTextClass} />
          </div>
          <Input
            value={localQuery}
            onChange={handleInputChange}
            onKeyDown={handleKeyDown}
            onFocus={() => suggestions.length > 0 && setShowSuggestions(true)}
            placeholder="Search within manifest..."
            className={`w-full pl-10 pr-10 ${fieldMode ? '!bg-nb-black !border-nb-black/80 !text-white' : '!bg-nb-white !border-nb-black/20'}`}
            aria-label="Search within manifest"
            aria-autocomplete="list"
            aria-controls="search-suggestions"
            aria-expanded={showSuggestions}
          />
          {query && (
            <div className="absolute right-2 top-1/2 -translate-y-1/2">
              <IconButton
                icon="close"
                ariaLabel="Clear search"
                onClick={clearSearch}
                variant="ghost"
                size="sm"
                className={`${mutedTextClass} hover:${textClass}`}
              />
            </div>
          )}

          {/* Autocomplete Suggestions */}
          {showSuggestions && suggestions.length > 0 && (
            <ul
              id="search-suggestions"
              role="listbox"
              className={`absolute top-full left-0 right-0 mt-1 ${fieldMode ? 'bg-nb-black border-nb-black/80' : 'bg-nb-white border-nb-black/20'} border  shadow-brutal z-20 max-h-60 overflow-auto`}
            >
              {suggestions.map((term, index) => (
                <li
                  key={term.value}
                  role="option"
                  aria-selected={index === selectedIndex}
                  onClick={() => selectSuggestion(term)}
                  className={`px-4 py-2 cursor-pointer flex items-center justify-between ${
                    index === selectedIndex
                      ? fieldMode ? 'bg-nb-blue text-nb-blue/60' : 'bg-nb-blue/10 text-nb-blue'
                      : fieldMode ? 'hover:bg-nb-black text-nb-black/30' : 'hover:bg-nb-white'
                  }`}
                >
                  <span className="text-sm">{term.value}</span>
                  {term.count && (
                    <span className={`text-xs ${mutedTextClass}`}>{term.count}</span>
                  )}
                </li>
              ))}
            </ul>
          )}
        </div>
      </form>

      {/* Results */}
      <div className="flex-1 overflow-auto">
        {loading && (
          <div className="flex items-center justify-center py-8">
            <div className="w-6 h-6 border-2 border-nb-black/20 border-t-nb-blue animate-spin"></div>
          </div>
        )}

        {error && (
          <div className={`p-4 m-3 ${fieldMode ? 'bg-nb-red/30 border-nb-red text-nb-red/60' : 'bg-nb-red/10 border-nb-red/30 text-nb-red'} border  text-sm`}>
            <Icon name="error" className="inline mr-2" />
            {error}
          </div>
        )}

        {!loading && !error && results.length === 0 && query && (
          <div className={`p-8 text-center ${mutedTextClass}`}>
            <Icon name="search_off" className="text-4xl mb-2 opacity-50" />
            <p className="text-sm">No results found for "{query}"</p>
          </div>
        )}

        {!loading && results.length > 0 && (
          <>
            {/* Results Header */}
            <div className={`px-4 py-2 ${fieldMode ? 'bg-nb-black border-nb-black' : 'bg-nb-white'} border-b text-xs font-medium ${mutedTextClass} sticky top-0`}>
              {total} result{total !== 1 ? 's' : ''} for "{query}"
            </div>

            {/* Grouped Results */}
            <div className="divide-y">
              {Object.entries(groupedResults).map(([canvasId, canvasResults]) => (
                <div
                  key={canvasId}
                  className={`${
                    currentCanvasId === canvasId
                      ? fieldMode ? 'bg-nb-blue/30' : 'bg-nb-blue/10'
                      : ''
                  }`}
                >
                  {/* Canvas Header */}
                  <div className={`px-4 py-2 ${fieldMode ? 'bg-nb-black/50' : 'bg-nb-cream/50'} text-xs font-medium ${mutedTextClass} flex items-center gap-2`}>
                    <Icon name="image" className="text-sm" />
                    <span className="truncate flex-1">
                      {canvasId.split('/').pop()}
                    </span>
                    <span className={mutedTextClass}>
                      {canvasResults.length} hit{canvasResults.length !== 1 ? 's' : ''}
                    </span>
                  </div>

                  {/* Results for this canvas */}
                  {canvasResults.map((result, index) => (
                    <div
                      key={`${result.canvasId}-${index}`}
                      onClick={() => onResultSelect(result)}
                      onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') onResultSelect(result); }}
                      className={`w-full px-4 py-3 text-left transition-nb group cursor-pointer ${
                        fieldMode
                          ? 'hover:bg-nb-black text-nb-black/30'
                          : 'hover:bg-nb-white text-nb-black/80'
                      }`}
                      role="button"
                      tabIndex={0}
                    >
                      <SearchResultItem result={result} query={query} fieldMode={fieldMode} />
                    </div>
                  ))}
                </div>
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  );
};

/**
 * Individual search result item with highlighting
 */
const SearchResultItem: React.FC<{
  result: SearchResult;
  query: string;
  fieldMode?: boolean;
}> = ({
  result,
  query,
  fieldMode = false,
}) => {
  // Highlight the query in the text
  const highlightText = (text: string, searchQuery: string): React.ReactNode => {
    if (!searchQuery) return text;

    const escapedQuery = searchQuery.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const parts = text.split(new RegExp(`(${escapedQuery})`, 'gi'));

    return parts.map((part, i) =>
      part.toLowerCase() === searchQuery.toLowerCase() ? (
        <mark
          key={i}
          className={`${fieldMode ? 'bg-nb-yellow/20 text-nb-yellow' : 'bg-nb-yellow/60 text-nb-yellow'} px-0.5 rounded`}
        >
          {part}
        </mark>
      ) : (
        part
      )
    );
  };

  return (
    <div>
      <p className={`text-sm leading-relaxed ${fieldMode ? 'text-nb-black/30' : 'text-nb-black/80'}`}>
        {result.selector ? (
          <>
            {result.selector.prefix && (
              <span className={fieldMode ? 'text-nb-black/50' : 'text-nb-black/40'}>...{result.selector.prefix}</span>
            )}
            <mark className={`${fieldMode ? 'bg-nb-yellow/20 text-nb-yellow' : 'bg-nb-yellow/60 text-nb-yellow'} px-0.5 font-medium`}>
              {result.selector.exact}
            </mark>
            {result.selector.suffix && (
              <span className={fieldMode ? 'text-nb-black/50' : 'text-nb-black/40'}>{result.selector.suffix}...</span>
            )}
          </>
        ) : (
          highlightText(result.text.substring(0, 200), query)
        )}
      </p>

      {/* Location info */}
      <div className={`flex items-center gap-3 mt-1.5 text-xs ${fieldMode ? 'text-nb-black/50' : 'text-nb-black/40'}`}>
        {result.region && (
          <span className="flex items-center gap-1">
            <Icon name="crop" className="text-sm" />
            {result.region.x},{result.region.y}
          </span>
        )}
        {result.time && (
          <span className="flex items-center gap-1">
            <Icon name="schedule" className="text-sm" />
            {formatTime(result.time.start)}
            {result.time.end && ` - ${formatTime(result.time.end)}`}
          </span>
        )}
        <Icon
          name="arrow_forward"
          className={`text-sm ml-auto opacity-0 group-hover:opacity-100 transition-nb ${fieldMode ? 'text-nb-black/40' : ''}`}
        />
      </div>
    </div>
  );
};

/**
 * Format seconds to MM:SS
 */
const formatTime = (seconds: number): string => {
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}:${secs.toString().padStart(2, '0')}`;
};

export default ViewerSearchPanel;
