// src/features/viewer/ui/molecules/ViewerToolbar.svelte
<!--
  ViewerToolbar — Viewer header bar with tools in SubBar
  React source: src/features/viewer/ui/molecules/ViewerToolbar.tsx (377 lines)
  Layer: molecule (FSD features/viewer/ui/molecules)

  Uses ViewHeader shell with named snippet slots. SubBar adapts
  tool groups based on media type. Annotation drawing mode expands
  inline color/stroke pickers.
-->

<script module lang="ts">
  export type AnnotationDrawingMode = 'polygon' | 'rectangle' | 'freehand' | 'select';

  export interface AnnotationStyleOptions {
    color: string;
    strokeWidth: number;
    fillOpacity?: number;
  }

  export type ScreenshotFormat = 'png' | 'jpeg' | 'webp';
</script>

<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { ContextualClassNames } from '@/src/shared/ui/molecules/ViewHeader/types';
  import { cn } from '@/src/shared/lib/cn';
  import { ViewHeader } from '@/src/shared/ui/molecules/ViewHeader';
  import Button from '@/src/shared/ui/atoms/Button.svelte';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';
  import Divider from '@/src/shared/ui/atoms/Divider.svelte';
  import ZoomControl from '@/src/shared/ui/atoms/ZoomControl.svelte';
  import AnnotationColorPicker from '../atoms/AnnotationColorPicker.svelte';
  import StrokeWidthSelect from '../atoms/StrokeWidthSelect.svelte';

  interface Props {
    label: string;
    mediaType: 'image' | 'video' | 'audio' | 'other';
    zoomLevel: number;
    rotation?: number;
    isFlipped?: boolean;
    showNavigator?: boolean;
    annotationCount: number;
    hasSearchService: boolean;
    canDownload: boolean;
    isFullscreen: boolean;
    showSearchPanel: boolean;
    showWorkbench: boolean;
    showComposer: boolean;
    showAnnotationTool: boolean;
    annotationDrawingMode?: AnnotationDrawingMode;
    hasMultipleCanvases: boolean;
    showFilmstrip: boolean;
    viewerReady: boolean;
    onZoomIn: () => void;
    onZoomOut: () => void;
    onResetView: () => void;
    onRotateCW?: () => void;
    onRotateCCW?: () => void;
    onFlipHorizontal?: () => void;
    onTakeScreenshot?: (format: ScreenshotFormat, action: 'download' | 'clipboard') => void;
    onToggleNavigator?: () => void;
    onToggleKeyboardHelp?: () => void;
    onToggleSearch: () => void;
    onToggleWorkbench: () => void;
    onToggleComposer: () => void;
    onToggleAnnotationTool: () => void;
    onAnnotationModeChange?: (mode: AnnotationDrawingMode) => void;
    onAnnotationUndo?: () => void;
    onAnnotationRedo?: () => void;
    onAnnotationClear?: () => void;
    annotationStyle?: AnnotationStyleOptions;
    onAnnotationStyleChange?: (style: AnnotationStyleOptions) => void;
    onToggleMetadata: () => void;
    onDownload?: () => void;
    onToggleFullscreen: () => void;
    onToggleFilmstrip: () => void;
    showFilterPanel?: boolean;
    filtersActive?: boolean;
    onToggleFilterPanel?: () => void;
    showMeasurement?: boolean;
    onToggleMeasurement?: () => void;
    showComparison?: boolean;
    onToggleComparison?: () => void;
    showLayers?: boolean;
    onToggleLayers?: () => void;
    layerCount?: number;
    onShareLink?: () => void;
    onSwitchView?: (mode: string) => void;
    cx: ContextualClassNames;
    fieldMode: boolean;
  }

  let {
    label,
    mediaType,
    zoomLevel,
    rotation = 0,
    isFlipped = false,
    showNavigator = true,
    annotationCount,
    hasSearchService,
    canDownload,
    isFullscreen,
    showSearchPanel,
    showWorkbench,
    showComposer,
    showAnnotationTool,
    hasMultipleCanvases,
    showFilmstrip,
    viewerReady,
    onZoomIn,
    onZoomOut,
    onResetView,
    onRotateCW,
    onRotateCCW,
    onFlipHorizontal,
    onTakeScreenshot,
    onToggleNavigator,
    onToggleKeyboardHelp,
    onToggleSearch,
    onToggleWorkbench,
    onToggleComposer,
    onToggleAnnotationTool,
    onAnnotationModeChange,
    onAnnotationUndo,
    onAnnotationRedo,
    onAnnotationClear,
    onToggleMetadata,
    onDownload,
    onToggleFullscreen,
    onToggleFilmstrip,
    cx,
    fieldMode,
    annotationDrawingMode,
    annotationStyle,
    onAnnotationStyleChange,
    showFilterPanel,
    filtersActive,
    onToggleFilterPanel,
    showMeasurement,
    onToggleMeasurement,
    showComparison,
    onToggleComparison,
    showLayers,
    onToggleLayers,
    layerCount,
    onShareLink,
    onSwitchView,
  }: Props = $props();

  let iconName = $derived(
    mediaType === 'video' ? 'movie' : mediaType === 'audio' ? 'audiotrack' : 'image'
  );
  let isAV = $derived(mediaType === 'audio' || mediaType === 'video');
  let hasTools = $derived(mediaType === 'image' || showAnnotationTool);

  /** Icon button helper for consistent toolbar buttons */
  function ibClass(active: boolean): string {
    return cn(
      'p-1.5 transition-nb',
      active
        ? fieldMode ? 'bg-nb-yellow text-black' : 'bg-nb-blue text-white'
        : fieldMode ? 'text-nb-yellow/70 hover:bg-nb-yellow/10' : 'text-nb-black/60 hover:bg-nb-black/5'
    );
  }
</script>

{#snippet iconBtn(icon: string, ariaLabel: string, onclick: (() => void) | undefined, active: boolean, disabled?: boolean, title?: string)}
  <button
    type="button"
    class={ibClass(active)}
    {onclick}
    disabled={disabled ?? false}
    aria-label={ariaLabel}
    aria-pressed={active || undefined}
    title={title ?? ariaLabel}
  >
    <Icon name={icon} class="text-base" />
  </button>
{/snippet}

<ViewHeader {cx} zIndex="z-20" class="viewer-chrome">
  {#snippet title()}
    <Icon name={iconName} class={cn('text-base', fieldMode ? 'text-nb-yellow/60' : 'text-nb-black/50')} />
    <span class={cn('text-xs font-bold font-mono uppercase tracking-wider truncate', cx.text)}>
      {label}
    </span>
    {#if annotationCount > 0}
      <div class={cn('h-4 w-px', fieldMode ? 'bg-nb-yellow/40' : 'bg-nb-black/20')}></div>
      <span class={cn('text-[10px] font-bold font-mono', fieldMode ? 'text-nb-yellow/60' : 'text-nb-black/40')}>
        {annotationCount} annotation{annotationCount !== 1 ? 's' : ''}
      </span>
    {/if}
  {/snippet}

  {#snippet actions()}
    <div class="flex items-center gap-0.5">
      {#if onSwitchView}
        {@render iconBtn('inventory_2', 'Open in Archive', () => onSwitchView('archive'), false)}
        {@render iconBtn('table_chart', 'Open in Metadata', () => onSwitchView('metadata'), false)}
        <div class={cn('w-px h-6 mx-1', cx.divider)}></div>
      {/if}
      {@render iconBtn(
        isFullscreen ? 'fullscreen_exit' : 'fullscreen',
        'Fullscreen',
        onToggleFullscreen,
        false,
        false,
        'Toggle fullscreen (Esc to exit)'
      )}
      {#if hasMultipleCanvases}
        {@render iconBtn('view_carousel', 'Filmstrip', onToggleFilmstrip, showFilmstrip)}
      {/if}
    </div>
  {/snippet}

  {#snippet subbar()}
    <!-- Zoom and rotation - images only -->
    {#if mediaType === 'image'}
      <div class="flex items-center gap-0.5" role="group" aria-label="Zoom controls">
        <ZoomControl
          zoom={zoomLevel / 100}
          onZoomChange={(z) => {
            const pct = Math.round(z * 100);
            if (pct > zoomLevel) onZoomIn();
            else if (pct < zoomLevel) onZoomOut();
          }}
          onReset={onResetView}
          disabled={!viewerReady}
          {cx}
        />
      </div>

      <Divider direction="vertical" cx={cx} class="h-6 mx-1" />

      <div class="flex items-center gap-0.5" role="group" aria-label="Orientation">
        {#if onRotateCCW}
          {@render iconBtn('rotate_left', 'Rotate left', onRotateCCW, false, !viewerReady, 'Rotate counter-clockwise (Shift+R)')}
        {/if}
        {#if rotation !== 0}
          <span class={cn('text-[10px] font-mono px-1', fieldMode ? 'text-nb-yellow' : 'text-nb-blue')}>
            {rotation}&deg;
          </span>
        {/if}
        {#if onRotateCW}
          {@render iconBtn('rotate_right', 'Rotate right', onRotateCW, false, !viewerReady, 'Rotate clockwise (R)')}
        {/if}
        {#if onFlipHorizontal}
          {@render iconBtn('flip', 'Flip', onFlipHorizontal, isFlipped, !viewerReady, 'Flip horizontally (F)')}
        {/if}
      </div>

      <Divider direction="vertical" cx={cx} class="h-6 mx-1" />
    {/if}

    <!-- Annotate button -->
    <button
      aria-label="Toggle annotation tool"
      type="button"
      onclick={onToggleAnnotationTool}
      title="Toggle annotation tool (A)"
      class={cn(
        'flex items-center gap-1.5 text-xs font-semibold px-3 py-1 transition-nb',
        showAnnotationTool
          ? fieldMode ? 'bg-nb-yellow text-black' : 'bg-nb-green text-white'
          : fieldMode ? 'bg-nb-yellow/20 text-nb-yellow hover:bg-nb-yellow/30' : 'bg-nb-black/80 text-nb-black/20 hover:bg-nb-black/60'
      )}
    >
      <Icon name={isAV ? 'timer' : 'gesture'} class="text-base" />
      <span>Annotate</span>
    </button>

    <!-- Layers toggle -->
    {#if layerCount != null && layerCount > 0 && onToggleLayers}
      {@render iconBtn('layers', 'Annotation layers', onToggleLayers, showLayers ?? false, false, `Annotation layers (${layerCount})`)}
    {/if}

    <!-- Drawing mode buttons - images only when annotation active -->
    {#if showAnnotationTool && mediaType === 'image' && onAnnotationModeChange}
      <Divider direction="vertical" cx={cx} class="h-6 mx-1" />
      <div class="flex items-center gap-0.5" role="group" aria-label="Drawing mode">
        {@render iconBtn('pentagon', 'Polygon', () => onAnnotationModeChange('polygon'), annotationDrawingMode === 'polygon')}
        {@render iconBtn('crop_square', 'Rectangle', () => onAnnotationModeChange('rectangle'), annotationDrawingMode === 'rectangle')}
        {@render iconBtn('draw', 'Freehand', () => onAnnotationModeChange('freehand'), annotationDrawingMode === 'freehand')}
      </div>
      {#if onAnnotationStyleChange && annotationStyle}
        <Divider direction="vertical" cx={cx} class="h-6 mx-1" />
        <AnnotationColorPicker
          value={annotationStyle.color || '#22c55e'}
          onChange={(color) => onAnnotationStyleChange({ ...annotationStyle, color })}
          {fieldMode}
        />
        <StrokeWidthSelect
          value={annotationStyle.strokeWidth ?? 2}
          onChange={(strokeWidth) => onAnnotationStyleChange({ ...annotationStyle, strokeWidth })}
          color={annotationStyle.color || '#22c55e'}
          {fieldMode}
        />
      {/if}
      <div class="flex items-center gap-0.5" role="group" aria-label="Annotation actions">
        {#if onAnnotationUndo}
          {@render iconBtn('undo', 'Undo', onAnnotationUndo, false, false, 'Undo (Ctrl+Z)')}
        {/if}
        {#if onAnnotationRedo}
          {@render iconBtn('redo', 'Redo', onAnnotationRedo, false, false, 'Redo (Ctrl+Shift+Z)')}
        {/if}
        {#if onAnnotationClear}
          {@render iconBtn('delete_outline', 'Clear', onAnnotationClear, false)}
        {/if}
      </div>
    {/if}

    <!-- Image tools: filter, measurement, comparison, screenshot -->
    {#if mediaType === 'image' && onToggleFilterPanel}
      {@render iconBtn('tune', 'Image filters', onToggleFilterPanel, (showFilterPanel ?? false) || (filtersActive ?? false), false, 'Image filters')}
    {/if}
    {#if mediaType === 'image' && onToggleMeasurement}
      {@render iconBtn('straighten', 'Measure', onToggleMeasurement, showMeasurement ?? false, false, 'Measurement tool (M)')}
    {/if}
    {#if mediaType === 'image' && hasMultipleCanvases && onToggleComparison}
      {@render iconBtn('compare', 'Compare', onToggleComparison, showComparison ?? false, false, 'Compare canvases')}
    {/if}
    {#if mediaType === 'image' && onTakeScreenshot}
      <Divider direction="vertical" cx={cx} class="h-6 mx-1" />
      <!-- Screenshot button - simplified from ScreenshotMenu -->
      {@render iconBtn('photo_camera', 'Screenshot', () => onTakeScreenshot('png', 'download'), false, !viewerReady, 'Take screenshot')}
    {/if}

    <div class="flex-1"></div>

    <!-- Secondary actions -->
    <div class="flex items-center gap-0.5">
      {#if hasSearchService}
        {@render iconBtn('search', 'Search', onToggleSearch, showSearchPanel)}
      {/if}
      {#if mediaType === 'image' && onToggleNavigator}
        {@render iconBtn('picture_in_picture', 'Navigator', onToggleNavigator, showNavigator, false, 'Toggle navigator (N)')}
      {/if}
      {#if onShareLink}
        {@render iconBtn('share', 'Share link', onShareLink, false, false, 'Copy shareable link')}
      {/if}
    </div>
  {/snippet}
</ViewHeader>

// src/features/viewer/ui/molecules/ViewerToolbar.tsx
/**
 * ViewerToolbar Molecule
 *
 * Simplified toolbar for IIIF viewer with clear groupings:
 * - Left: Title
 * - Center: View controls (zoom, rotation for images)
 * - Right: Actions (annotate, metadata, fullscreen)
 *
 * @module features/viewer/ui/molecules/ViewerToolbar
 */

import React from 'react';
import { Icon } from '@/src/shared/ui/atoms';
import { IconButton } from '@/src/shared/ui/molecules/IconButton';
import {
  ViewHeader,
  ViewHeaderTitle,
  ViewHeaderCenter,
  ViewHeaderActions,
  ViewHeaderSubBar,
  ViewHeaderDivider,
} from '@/src/shared/ui/molecules/ViewHeader';
import { ZoomControl, ScreenshotMenu, AnnotationColorPicker, StrokeWidthSelect } from '@/src/features/viewer/ui/atoms';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';
import type { ScreenshotFormat } from '../../model';
import type { AnnotationStyleOptions } from '../../model/useAnnotorious';

export type AnnotationDrawingMode = 'polygon' | 'rectangle' | 'freehand' | 'select';

/** Toolbar button group with label */
const ToolbarGroup: React.FC<{
  label?: string;
  children: React.ReactNode;
  fieldMode?: boolean;
}> = ({ label, children, fieldMode }) => (
  <div className="flex items-center gap-0.5">
    {label && (
      <span className={`nb-label-sm mr-1 ${fieldMode ? 'text-nb-yellow/60' : 'text-nb-black/50'}`}>
        {label}
      </span>
    )}
    {children}
  </div>
);

/** Vertical divider */
const ToolbarDivider: React.FC<{ cx: ContextualClassNames }> = ({ cx }) => (
  <div className={`w-px h-6 mx-1 ${cx.divider}`} />
);

export interface ViewerToolbarProps {
  /** Canvas label/title to display */
  label: string;
  /** Media type for icon display */
  mediaType: 'image' | 'video' | 'audio' | 'other';
  /** Current zoom level (percentage) */
  zoomLevel: number;
  /** Current rotation in degrees */
  rotation?: number;
  /** Whether image is flipped */
  isFlipped?: boolean;
  /** Whether navigator is visible */
  showNavigator?: boolean;
  /** Number of annotations */
  annotationCount: number;
  /** Whether search service is available */
  hasSearchService: boolean;
  /** Whether image can be downloaded */
  canDownload: boolean;
  /** Whether viewer is in fullscreen */
  isFullscreen: boolean;
  /** Whether search panel is open */
  showSearchPanel: boolean;
  /** Whether workbench is open */
  showWorkbench: boolean;
  /** Whether composer is open */
  showComposer: boolean;
  /** Whether annotation tool is open */
  showAnnotationTool: boolean;
  /** Current drawing mode when annotation tool is active */
  annotationDrawingMode?: AnnotationDrawingMode;
  /** Whether there are multiple canvases */
  hasMultipleCanvases: boolean;
  /** Whether filmstrip is visible */
  showFilmstrip: boolean;
  /** Whether OSD viewer is ready */
  viewerReady: boolean;
  /** Zoom in handler */
  onZoomIn: () => void;
  /** Zoom out handler */
  onZoomOut: () => void;
  /** Reset view handler */
  onResetView: () => void;
  /** Rotate clockwise handler */
  onRotateCW?: () => void;
  /** Rotate counter-clockwise handler */
  onRotateCCW?: () => void;
  /** Flip horizontal handler */
  onFlipHorizontal?: () => void;
  /** Screenshot handler (format, action) */
  onTakeScreenshot?: (format: ScreenshotFormat, action: 'download' | 'clipboard') => void;
  /** Navigator toggle */
  onToggleNavigator?: () => void;
  /** Keyboard help toggle */
  onToggleKeyboardHelp?: () => void;
  /** Search panel toggle */
  onToggleSearch: () => void;
  /** Workbench toggle */
  onToggleWorkbench: () => void;
  /** Composer toggle */
  onToggleComposer: () => void;
  /** Annotation tool toggle */
  onToggleAnnotationTool: () => void;
  /** Change annotation drawing mode */
  onAnnotationModeChange?: (mode: AnnotationDrawingMode) => void;
  /** Undo annotation drawing */
  onAnnotationUndo?: () => void;
  /** Redo annotation drawing */
  onAnnotationRedo?: () => void;
  /** Clear annotation drawing */
  onAnnotationClear?: () => void;
  /** Current annotation style */
  annotationStyle?: AnnotationStyleOptions;
  /** Change annotation style */
  onAnnotationStyleChange?: (style: AnnotationStyleOptions) => void;
  /** Metadata panel toggle */
  onToggleMetadata: () => void;
  /** Download handler */
  onDownload?: () => void;
  /** Fullscreen toggle */
  onToggleFullscreen: () => void;
  /** Filmstrip toggle */
  onToggleFilmstrip: () => void;
  /** Whether filter panel is open */
  showFilterPanel?: boolean;
  /** Whether any filters are active */
  filtersActive?: boolean;
  /** Filter panel toggle */
  onToggleFilterPanel?: () => void;
  /** Whether measurement mode is active */
  showMeasurement?: boolean;
  /** Measurement toggle */
  onToggleMeasurement?: () => void;
  /** Whether comparison mode is active */
  showComparison?: boolean;
  /** Comparison toggle */
  onToggleComparison?: () => void;
  /** Whether layers panel is open */
  showLayers?: boolean;
  /** Layers panel toggle */
  onToggleLayers?: () => void;
  /** Number of annotation layers */
  layerCount?: number;
  /** Share link handler */
  onShareLink?: () => void;
  /** Switch to another view mode (standalone viewer only) */
  onSwitchView?: (mode: string) => void;
  /** Contextual styles from template */
  cx: ContextualClassNames;
  /** Current field mode */
  fieldMode: boolean;
}

export const ViewerToolbar: React.FC<ViewerToolbarProps> = ({
  label,
  mediaType,
  zoomLevel,
  rotation = 0,
  isFlipped = false,
  showNavigator = true,
  annotationCount,
  hasSearchService,
  canDownload,
  isFullscreen,
  showSearchPanel,
  showWorkbench,
  showComposer,
  showAnnotationTool,
  hasMultipleCanvases,
  showFilmstrip,
  viewerReady,
  onZoomIn,
  onZoomOut,
  onResetView,
  onRotateCW,
  onRotateCCW,
  onFlipHorizontal,
  onTakeScreenshot,
  onToggleNavigator,
  onToggleKeyboardHelp,
  onToggleSearch,
  onToggleWorkbench,
  onToggleComposer,
  onToggleAnnotationTool,
  onAnnotationModeChange,
  onAnnotationUndo,
  onAnnotationRedo,
  onAnnotationClear,
  onToggleMetadata,
  onDownload,
  onToggleFullscreen,
  onToggleFilmstrip,
  cx,
  fieldMode,
  annotationDrawingMode,
  annotationStyle,
  onAnnotationStyleChange,
  showFilterPanel,
  filtersActive,
  onToggleFilterPanel,
  showMeasurement,
  onToggleMeasurement,
  showComparison,
  onToggleComparison,
  showLayers,
  onToggleLayers,
  layerCount,
  onShareLink,
  onSwitchView,
}) => {
  const iconName = mediaType === 'video' ? 'movie' : mediaType === 'audio' ? 'audiotrack' : 'image';
  const isAV = mediaType === 'audio' || mediaType === 'video';

  const hasTools = mediaType === 'image' || showAnnotationTool;

  return (
    <ViewHeader cx={cx} fieldMode={fieldMode} zIndex="z-20" className="viewer-chrome">
      {/* Header: Title + minimal actions */}
      <ViewHeaderTitle icon={iconName} title={label}>
        {annotationCount > 0 && (
          <>
            <div className={`h-4 w-px ${fieldMode ? 'bg-nb-yellow/40' : 'bg-nb-black/20'}`} />
            <span className={`text-[10px] font-bold font-mono ${fieldMode ? 'text-nb-yellow/60' : 'text-nb-black/40'}`}>
              {annotationCount} annotation{annotationCount !== 1 ? 's' : ''}
            </span>
          </>
        )}
      </ViewHeaderTitle>

      <ViewHeaderActions>
        <div className="flex items-center gap-0.5">
          {onSwitchView && (
            <>
              <IconButton icon="inventory_2" ariaLabel="Open in Archive" title="Open in Archive" onClick={() => onSwitchView('archive')} variant="ghost" size="sm" cx={cx} fieldMode={fieldMode} />
              <IconButton icon="table_chart" ariaLabel="Open in Metadata" title="Open in Metadata" onClick={() => onSwitchView('metadata')} variant="ghost" size="sm" cx={cx} fieldMode={fieldMode} />
              <ToolbarDivider cx={cx} />
            </>
          )}
          <IconButton icon={isFullscreen ? 'fullscreen_exit' : 'fullscreen'} ariaLabel="Fullscreen" title="Toggle fullscreen (Esc to exit)" onClick={onToggleFullscreen} variant="ghost" size="sm" cx={cx} fieldMode={fieldMode} />
          {hasMultipleCanvases && (
            <IconButton icon="view_carousel" ariaLabel="Filmstrip" onClick={onToggleFilmstrip} variant={showFilmstrip ? 'primary' : 'ghost'} size="sm" cx={cx} fieldMode={fieldMode} />
          )}
        </div>
      </ViewHeaderActions>

      {/* Sub-header: All tools */}
      <ViewHeaderSubBar visible={hasTools}>
        {/* Zoom & rotation - images only */}
        {mediaType === 'image' && (
          <>
            <ToolbarGroup fieldMode={fieldMode}>
              <ZoomControl
                zoom={zoomLevel / 100}
                onZoomChange={(z) => {
                  const pct = Math.round(z * 100);
                  if (pct > zoomLevel) onZoomIn();
                  else if (pct < zoomLevel) onZoomOut();
                }}
                onReset={onResetView}
                disabled={!viewerReady}
                cx={cx}
              />
            </ToolbarGroup>

            <ToolbarDivider cx={cx} />

            <ToolbarGroup fieldMode={fieldMode}>
              {onRotateCCW && (
                <IconButton icon="rotate_left" ariaLabel="Rotate left" title="Rotate counter-clockwise (Shift+R)" onClick={onRotateCCW} disabled={!viewerReady} variant="ghost" size="sm" cx={cx} fieldMode={fieldMode} />
              )}
              {rotation !== 0 && (
                <span className={`text-[10px] font-mono px-1 ${fieldMode ? 'text-nb-yellow' : 'text-nb-blue'}`}>
                  {rotation}°
                </span>
              )}
              {onRotateCW && (
                <IconButton icon="rotate_right" ariaLabel="Rotate right" title="Rotate clockwise (R)" onClick={onRotateCW} disabled={!viewerReady} variant="ghost" size="sm" cx={cx} fieldMode={fieldMode} />
              )}
              {onFlipHorizontal && (
                <IconButton icon="flip" ariaLabel="Flip" title="Flip horizontally (F)" onClick={onFlipHorizontal} disabled={!viewerReady} variant={isFlipped ? 'primary' : 'ghost'} size="sm" cx={cx} fieldMode={fieldMode} />
              )}
            </ToolbarGroup>

            <ToolbarDivider cx={cx} />
          </>
        )}

        {/* Annotate Button */}
        <button
          onClick={onToggleAnnotationTool}
          title="Toggle annotation tool (A)"
          className={`flex items-center gap-1.5 text-xs font-semibold px-3 py-1 transition-nb ${
            showAnnotationTool
              ? fieldMode ? 'bg-nb-yellow text-black' : 'bg-nb-green text-white'
              : fieldMode ? 'bg-nb-yellow/20 text-nb-yellow hover:bg-nb-yellow/30' : 'bg-nb-black/80 text-nb-black/20 hover:bg-nb-black/60'
          }`}
        >
          <Icon name={isAV ? 'timer' : 'gesture'} className="text-base" />
          <span>Annotate</span>
        </button>

        {/* Layers toggle */}
        {layerCount != null && layerCount > 0 && onToggleLayers && (
          <IconButton icon="layers" ariaLabel="Annotation layers" title={`Annotation layers (${layerCount})`} onClick={onToggleLayers} variant={showLayers ? 'primary' : 'ghost'} size="sm" cx={cx} fieldMode={fieldMode} />
        )}

        {/* Drawing mode buttons - only for images when annotation active */}
        {showAnnotationTool && mediaType === 'image' && onAnnotationModeChange && (
          <>
            <ToolbarDivider cx={cx} />
            <ToolbarGroup fieldMode={fieldMode}>
              <IconButton icon="pentagon" ariaLabel="Polygon" onClick={() => onAnnotationModeChange('polygon')} variant={annotationDrawingMode === 'polygon' ? 'primary' : 'ghost'} size="sm" cx={cx} fieldMode={fieldMode} />
              <IconButton icon="crop_square" ariaLabel="Rectangle" onClick={() => onAnnotationModeChange('rectangle')} variant={annotationDrawingMode === 'rectangle' ? 'primary' : 'ghost'} size="sm" cx={cx} fieldMode={fieldMode} />
              <IconButton icon="draw" ariaLabel="Freehand" onClick={() => onAnnotationModeChange('freehand')} variant={annotationDrawingMode === 'freehand' ? 'primary' : 'ghost'} size="sm" cx={cx} fieldMode={fieldMode} />
            </ToolbarGroup>
            {onAnnotationStyleChange && annotationStyle && (
              <>
                <ToolbarDivider cx={cx} />
                <AnnotationColorPicker value={annotationStyle.color || '#22c55e'} onChange={(color) => onAnnotationStyleChange({ ...annotationStyle, color })} fieldMode={fieldMode} />
                <StrokeWidthSelect value={annotationStyle.strokeWidth ?? 2} onChange={(strokeWidth) => onAnnotationStyleChange({ ...annotationStyle, strokeWidth })} color={annotationStyle.color || '#22c55e'} fieldMode={fieldMode} />
              </>
            )}
            <ToolbarGroup fieldMode={fieldMode}>
              {onAnnotationUndo && <IconButton icon="undo" ariaLabel="Undo" title="Undo (Ctrl+Z)" onClick={onAnnotationUndo} variant="ghost" size="sm" cx={cx} fieldMode={fieldMode} />}
              {onAnnotationRedo && <IconButton icon="redo" ariaLabel="Redo" title="Redo (Ctrl+Shift+Z)" onClick={onAnnotationRedo} variant="ghost" size="sm" cx={cx} fieldMode={fieldMode} />}
              {onAnnotationClear && <IconButton icon="delete_outline" ariaLabel="Clear" onClick={onAnnotationClear} variant="ghost" size="sm" cx={cx} fieldMode={fieldMode} />}
            </ToolbarGroup>
          </>
        )}

        {/* Image tools: filter, measurement, comparison */}
        {mediaType === 'image' && onToggleFilterPanel && (
          <IconButton icon="tune" ariaLabel="Image filters" title="Image filters" onClick={onToggleFilterPanel} variant={showFilterPanel || filtersActive ? 'primary' : 'ghost'} size="sm" cx={cx} fieldMode={fieldMode} />
        )}
        {mediaType === 'image' && onToggleMeasurement && (
          <IconButton icon="straighten" ariaLabel="Measure" title="Measurement tool (M)" onClick={onToggleMeasurement} variant={showMeasurement ? 'primary' : 'ghost'} size="sm" cx={cx} fieldMode={fieldMode} />
        )}
        {mediaType === 'image' && hasMultipleCanvases && onToggleComparison && (
          <IconButton icon="compare" ariaLabel="Compare" title="Compare canvases" onClick={onToggleComparison} variant={showComparison ? 'primary' : 'ghost'} size="sm" cx={cx} fieldMode={fieldMode} />
        )}
        {mediaType === 'image' && onTakeScreenshot && (
          <>
            <ToolbarDivider cx={cx} />
            <ScreenshotMenu onScreenshot={onTakeScreenshot} disabled={!viewerReady} fieldMode={fieldMode} />
          </>
        )}

        <div className="flex-1" />

        {/* Secondary actions */}
        <div className="flex items-center gap-0.5">
          {hasSearchService && (
            <IconButton icon="search" ariaLabel="Search" onClick={onToggleSearch} variant={showSearchPanel ? 'primary' : 'ghost'} size="sm" cx={cx} fieldMode={fieldMode} />
          )}
          {mediaType === 'image' && onToggleNavigator && (
            <IconButton icon="picture_in_picture" ariaLabel="Navigator" title="Toggle navigator (N)" onClick={onToggleNavigator} variant={showNavigator ? 'primary' : 'ghost'} size="sm" cx={cx} fieldMode={fieldMode} />
          )}
          {onShareLink && (
            <IconButton icon="share" ariaLabel="Share link" title="Copy shareable link" onClick={onShareLink} variant="ghost" size="sm" cx={cx} fieldMode={fieldMode} />
          )}
        </div>
      </ViewHeaderSubBar>
    </ViewHeader>
  );
};

export default ViewerToolbar;
