// src/features/viewer/ui/molecules/ViewerPanels.tsx
/**
 * ViewerPanels Molecule
 *
 * Composes: ViewerSearchPanel + IconButton + Panel containers
 *
 * Side panel container for search, metadata, and transcription panels.
 * Manages panel visibility and layout.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Receives cx and fieldMode via props (no hook calls)
 * - Composes molecules: ViewerSearchPanel, IconButton
 * - Local UI state only
 * - No domain logic
 *
 * IDEAL OUTCOME: Consistent side panel experience
 * FAILURE PREVENTED: Panel layout conflicts, accessibility issues
 *
 * @module features/viewer/ui/molecules/ViewerPanels
 */

import React from 'react';
import { IconButton } from '@/src/shared/ui/molecules/IconButton';
import { type SearchResult, type SearchService, ViewerSearchPanel } from './ViewerSearchPanel';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';
import type { IIIFManifest } from '@/src/shared/types';

export interface ViewerPanelsProps {
  /** Currently selected canvas ID */
  currentCanvasId?: string;
  /** Manifest for search context */
  manifest: IIIFManifest | null;
  /** Search service extracted from manifest */
  searchService: SearchService | null;
  /** Whether search panel is visible */
  showSearchPanel: boolean;
  /** Called when search panel should close */
  onCloseSearchPanel: () => void;
  /** Called when a search result is selected */
  onSearchResultSelect?: (result: SearchResult) => void;
  /** Called when search results change */
  onSearchResultsChange?: (results: SearchResult[]) => void;
  /** Search callback */
  onSearch?: (query: string) => Promise<SearchResult[]>;
  /** Contextual styles from template */
  cx: ContextualClassNames;
  /** Current field mode */
  fieldMode: boolean;
}

/**
 * ViewerPanels Molecule
 *
 * @example
 * <ViewerPanels
 *   manifest={manifest}
 *   searchService={searchService}
 *   showSearchPanel={showSearchPanel}
 *   onCloseSearchPanel={() => setShowSearchPanel(false)}
 *   cx={cx}
 *   fieldMode={fieldMode}
 * />
 */
export const ViewerPanels: React.FC<ViewerPanelsProps> = ({
  currentCanvasId,
  manifest,
  searchService,
  showSearchPanel,
  onCloseSearchPanel,
  onSearchResultSelect,
  onSearchResultsChange,
  onSearch,
  cx,
  fieldMode,
}) => {
  if (!showSearchPanel) return null;

  return (
    <div
      className={`fixed inset-y-0 right-0 w-96 shadow-brutal z-50 flex flex-col ${
        fieldMode ? 'bg-nb-black' : 'bg-nb-white'
      }`}
    >
      {/* Panel Header */}
      <div
        className={`flex items-center justify-between p-4 border-b ${
          fieldMode ? 'border-nb-black' : 'border-nb-black/20'
        }`}
      >
        <h3 className={`font-bold ${fieldMode ? 'text-white' : 'text-nb-black'}`}>
          Search Manifest
        </h3>
        <IconButton
          icon="close"
          ariaLabel="Close search panel"
          onClick={onCloseSearchPanel}
          variant="ghost"
          size="sm"
          cx={cx}
          fieldMode={fieldMode}
        />
      </div>

      {/* Panel Content */}
      <div className="flex-1 overflow-hidden">
        {showSearchPanel && manifest && (
          <ViewerSearchPanel
            manifest={manifest}
            searchService={searchService}
            onResultSelect={onSearchResultSelect || (() => {})}
            onResultsChange={onSearchResultsChange}
            currentCanvasId={currentCanvasId}
            cx={cx}
            fieldMode={fieldMode}
            onSearch={onSearch || (async () => [])}
          />
        )}
      </div>
    </div>
  );
};

export default ViewerPanels;

// src/features/viewer/ui/molecules/ViewerPanels.svelte
<!--
  ViewerPanels.svelte -- Side panel container for IIIF Content Search
  React source: src/features/viewer/ui/molecules/ViewerPanels.tsx
  Layer: molecule (FSD features/viewer/ui/molecules)

  Fixed right-side drawer panel over the viewer canvas area.
  Contains ViewerSearchPanel. Slides in/out with transition.
  Panel DOM is removed when hidden ({#if}), resetting search state on close.
-->
<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import type { IIIFManifest } from '@/src/shared/types';
  import { cn } from '@/src/shared/lib/cn';
  import { slide } from 'svelte/transition';
  import Button from '@/src/shared/ui/atoms/Button.svelte';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';
  import ViewerSearchPanel from './ViewerSearchPanel.svelte';
  import type { SearchResult } from './ViewerSearchPanel.svelte';

  interface SearchService {
    id: string;
    type: string;
  }

  interface Props {
    currentCanvasId?: string;
    manifest: IIIFManifest | null;
    searchService: SearchService | null;
    showSearchPanel: boolean;
    onCloseSearchPanel: () => void;
    onSearchResultSelect?: (result: SearchResult) => void;
    onSearchResultsChange?: (results: SearchResult[]) => void;
    onSearch?: (query: string) => Promise<SearchResult[]>;
    cx: ContextualClassNames;
    fieldMode: boolean;
  }

  let {
    currentCanvasId,
    manifest,
    searchService,
    showSearchPanel,
    onCloseSearchPanel,
    onSearchResultSelect,
    onSearchResultsChange,
    onSearch,
    cx,
    fieldMode,
  }: Props = $props();

  function handleClose() {
    onCloseSearchPanel();
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') {
      e.stopPropagation();
      handleClose();
    }
  }

  function handleSearchResultSelect(result: SearchResult) {
    onSearchResultSelect?.(result);
  }

  function handleSearchResultsChange(results: SearchResult[]) {
    onSearchResultsChange?.(results);
  }

  function handleSearch(query: string) {
    return onSearch?.(query) ?? Promise.resolve([]);
  }
</script>

{#if showSearchPanel}
  <div
    class={cn(
      'absolute right-0 top-0 bottom-0 w-96 z-30',
      'border-l shadow-brutal flex flex-col',
      fieldMode ? 'bg-nb-black border-nb-yellow' : 'bg-nb-white border-nb-black/20'
    )}
    role="complementary"
    aria-label="Search panel"
    onkeydown={handleKeydown}
    transition:slide={{ axis: 'x', duration: 200 }}
  >
    <!-- Panel Header -->
    <div class={cn(
      'flex items-center justify-between px-4 h-12 border-b shrink-0',
      cx.headerBg,
      fieldMode ? 'border-nb-yellow' : 'border-nb-black/20'
    )}>
      <h3 class={cn(
        'text-sm font-mono uppercase tracking-wide font-bold',
        fieldMode ? 'text-nb-yellow' : 'text-nb-black'
      )}>
        Search
      </h3>
      <Button
        variant="ghost"
        size="bare"
        onclick={handleClose}
        aria-label="Close search panel"
      >
        {#snippet children()}
          <Icon name="close" class="text-base" />
        {/snippet}
      </Button>
    </div>

    <!-- Panel Body -->
    <div class="flex-1 overflow-y-auto">
      {#if manifest}
        <ViewerSearchPanel
          {manifest}
          {searchService}
          onResultSelect={handleSearchResultSelect}
          onResultsChange={handleSearchResultsChange}
          {currentCanvasId}
          {cx}
          {fieldMode}
          onSearch={handleSearch}
        />
      {/if}
    </div>
  </div>
{/if}
