// src/app/ui/BaseTemplate.svelte
<!--
  BaseTemplate — App shell layout template.
  React source: src/app/templates/BaseTemplate.tsx (112 lines)
  Architecture: Template (layout-only, no business logic, snippet slots)

  Structure:
  ┌─────────────────────────────────────────┐
  │ Header (optional)                       │
  ├──────────────────────────────────────────┤
  │ Body                                    │
  │  ├── Sidebar (optional, 256px)          │
  │  └── Main content area                 │
  └──────────────────────────────────────────┘

  All slots are Svelte 5 snippets (not named slots).
-->
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { cn } from '@/src/shared/lib/cn';
  import Button from '@/src/shared/ui/atoms/Button.svelte';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';

  interface Props {
    /** Main content area */
    children: Snippet;
    /** Whether to show the sidebar */
    showSidebar?: boolean;
    /** Callback when sidebar toggle is clicked */
    onSidebarToggle?: () => void;
    /** Optional header content snippet */
    headerContent?: Snippet;
    /** Optional sidebar content snippet */
    sidebarContent?: Snippet;
  }

  let {
    children,
    showSidebar = true,
    onSidebarToggle,
    headerContent,
    sidebarContent,
  }: Props = $props();
</script>

<div class="flex flex-col h-screen bg-nb-black">
  <!-- Header -->
  <header
    class="flex items-center justify-between h-16 px-4 border-b border-nb-black/20 bg-nb-black shrink-0"
  >
    <!-- Sidebar toggle -->
    <Button
      variant="ghost"
      size="bare"
      onclick={onSidebarToggle}
      aria-label={showSidebar ? 'Hide sidebar' : 'Show sidebar'}
      title={showSidebar ? 'Hide sidebar (Cmd+\\)' : 'Show sidebar (Cmd+\\)'}
      class="p-2"
    >
      <Icon name="menu" class="w-5 h-5" />
    </Button>

    <!-- Custom header content (flex-1 centred area) -->
    <div class="flex-1 mx-4">
      {#if headerContent}
        {@render headerContent()}
      {/if}
    </div>
  </header>

  <!-- Main layout: sidebar + content -->
  <div class="flex flex-1 overflow-hidden">
    <!-- Sidebar -->
    {#if showSidebar && sidebarContent}
      <aside
        class="w-64 border-r border-nb-black/20 bg-nb-black overflow-y-auto shrink-0"
        role="navigation"
        aria-label="Main navigation"
      >
        {@render sidebarContent()}
      </aside>
    {/if}

    <!-- Main content area -->
    <main
      id="main-content"
      class={cn(
        'flex-1 min-h-0 flex flex-col',
        !showSidebar && 'w-full'
      )}
    >
      {@render children()}
    </main>
  </div>
</div>

// src/app/templates/BaseTemplate.tsx
/**
 * BaseTemplate
 *
 * Provides the base layout structure with sidebar, header, and main content area.
 * All app routes are wrapped with this template for consistent layout.
 *
 * Structure:
 * ┌─────────────────────────────────────────┐
 * │ Header                                  │
 * ├──────────┬──────────────────────────────┤
 * │ Sidebar  │ Main Content                 │
 * │          │                              │
 * │          │ (FieldModeTemplate wraps here)
 * │          │                              │
 * └──────────┴──────────────────────────────┘
 *
 * Usage:
 *   <BaseTemplate
 *     showSidebar={true}
 *     onSidebarToggle={() => setShowSidebar(!show)}
 *   >
 *     [Main content goes here]
 *   </BaseTemplate>
 */

import React, { ReactNode } from 'react';
import { Button } from '@/ui/primitives/Button';

export interface BaseTemplateProps {
  /** Main content */
  children: ReactNode;
  /** Whether to show sidebar */
  showSidebar?: boolean;
  /** Callback when sidebar toggle is clicked */
  onSidebarToggle?: () => void;
  /** Optional header content (defaults to standard header) */
  headerContent?: ReactNode;
  /** Optional sidebar content (defaults to standard sidebar) */
  sidebarContent?: ReactNode;
}

/**
 * Base layout template providing sidebar, header, main structure
 *
 * This template establishes the overall app structure that all views use.
 */
export const BaseTemplate: React.FC<BaseTemplateProps> = ({
  children,
  showSidebar = true,
  onSidebarToggle,
  headerContent,
  sidebarContent
}) => {
  return (
    <div className="flex flex-col h-screen bg-nb-black">
      {/* Header */}
      <header
        className="flex items-center justify-between h-16 px-4 border-b border-nb-black bg-nb-black"
        role="banner"
      >
        {/* Sidebar toggle button */}
        <Button
          onClick={onSidebarToggle}
          variant="ghost"
          size="sm"
          aria-label={showSidebar ? 'Hide sidebar' : 'Show sidebar'}
          title={showSidebar ? 'Hide sidebar (Cmd+\\)' : 'Show sidebar (Cmd+\\)'}
          icon={
            <svg
              className="w-5 h-5"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M4 6h16M4 12h16M4 18h16"
              />
            </svg>
          }
        />

        {/* Custom header content */}
        <div className="flex-1 mx-4">
          {headerContent}
        </div>
      </header>

      {/* Main layout: sidebar + content */}
      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar */}
        {showSidebar && (
          <aside
            className="w-64 border-r border-nb-black bg-nb-black overflow-y-auto"
            role="navigation"
          >
            {sidebarContent}
          </aside>
        )}

        {/* Main content area */}
        <main className="flex-1 min-h-0 flex flex-col" role="main">
          {children}
        </main>
      </div>
    </div>
  );
};

export default BaseTemplate;
