// src/app/ui/FieldModeTemplate.svelte
<!--
  FieldModeTemplate — Field mode variant of BaseTemplate.
  React source: src/app/templates/FieldModeTemplate.tsx (82 lines)
  Architecture: Template (injects cx, fieldMode, terminology into child organisms via snippet)

  Philosophy:
  - Organisms are context-agnostic; templates provide context.
  - No fieldMode prop-drilling. Children receive props via snippet parameters.
  - cx (contextual styles) is always available, never undefined.
  - Terminology is resolved at template level.

  Usage:
    <FieldModeTemplate>
      {#snippet children({ cx, fieldMode, t, isAdvanced })}
        <ArchiveView {cx} {fieldMode} {t} {isAdvanced} />
      {/snippet}
    </FieldModeTemplate>
-->
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { appSettings } from '@/src/shared/stores/appSettings.svelte';
  import { terminology } from '@/src/shared/stores/terminology.svelte';
  import { getContextualClasses } from '@/src/shared/lib/contextual-styles';
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';

  // ---------------------------------------------------------------------------
  // Types
  // ---------------------------------------------------------------------------

  export interface FieldModeTemplateRenderProps {
    /** Contextual class names for current fieldMode (light/field/dark/custom) */
    cx: ContextualClassNames;
    /** Current field mode state (true = high-contrast dark mode) */
    fieldMode: boolean;
    /** Terminology function for IIIF resource labels */
    t: (key: string) => string;
    /** Whether user is in advanced mode (shows technical details) */
    isAdvanced: boolean;
  }

  interface Props {
    /** Render snippet receives cx, fieldMode, t, isAdvanced */
    children: Snippet<[FieldModeTemplateRenderProps]>;
  }

  let { children }: Props = $props();

  // ---------------------------------------------------------------------------
  // Reactive derived values
  // ---------------------------------------------------------------------------

  /** Current field mode from app settings */
  let fieldMode = $derived(appSettings.fieldMode);

  /** Contextual class names derived from current theme name */
  let cx = $derived(getContextualClasses(appSettings.themeName));

  /** Terminology translation function + isAdvanced flag */
  let t = $derived((key: string) => terminology.t(key));
  let isAdvanced = $derived(terminology.isAdvanced);

  /** Combined props to pass to children snippet */
  let renderProps = $derived<FieldModeTemplateRenderProps>({
    cx,
    fieldMode,
    t,
    isAdvanced,
  });
</script>

{@render children(renderProps)}

// src/app/templates/FieldModeTemplate.tsx
/**
 * FieldModeTemplate
 *
 * Provides fieldMode context, design tokens (cx), and terminology (t) to child organisms.
 * This template ensures that organisms don't need to call useAppSettings,
 * useContextualStyles, or useTerminology directly - they receive these via render props.
 *
 * Philosophy:
 * - Organisms are context-agnostic. App provides context via templates.
 * - No fieldMode prop-drilling. Use render props instead.
 * - cx (contextual styles) is always available, never undefined.
 * - Terminology is provided at template level to avoid hook calls in organisms.
 *
 * Usage:
 *   <FieldModeTemplate>
 *     {({ cx, fieldMode, t, isAdvanced }) => (
 *       <ArchiveView cx={cx} fieldMode={fieldMode} t={t} isAdvanced={isAdvanced} />
 *     )}
 *   </FieldModeTemplate>
 */

import React, { ReactNode } from 'react';
import { useAppSettings, useTerminology } from '@/src/app/providers';
import { ContextualClassNames, useContextualStyles } from '@/src/shared/lib/hooks/useContextualStyles';

export interface FieldModeTemplateRenderProps {
  /** Contextual class names for current fieldMode (light/dark) */
  cx: ContextualClassNames;
  /** Current field mode state (true = high-contrast dark mode) */
  fieldMode: boolean;
  /** Terminology function for IIIF resource labels */
  t: (key: string) => string;
  /** Whether user is in advanced mode (shows technical details) */
  isAdvanced: boolean;
}

export interface FieldModeTemplateProps {
  /** Render function receives cx and fieldMode */
  children: (props: FieldModeTemplateRenderProps) => ReactNode;
}

/**
 * Template that injects fieldMode context to child organisms
 *
 * This is the primary way organisms receive styling and mode information.
 * Organisms wrapped in this template don't need to know about useAppSettings.
 */
/**
 * Memoized FieldModeTemplate for performance
 *
 * Prevents re-renders when settings haven't changed.
 * Critical for <50ms paint time after context changes.
 */
export const FieldModeTemplate: React.FC<FieldModeTemplateProps> = React.memo(({ children }) => {
  // Get current app settings (fieldMode, abstractionLevel, etc.)
  const { settings } = useAppSettings();

  // Get contextual styles based on current fieldMode
  const cx = useContextualStyles();

  // Get terminology based on abstraction level
  const { t, isAdvanced } = useTerminology({ level: settings.abstractionLevel });

  // Memoize the context object to prevent unnecessary re-renders
  const contextValue = React.useMemo(() => ({
    cx,
    fieldMode: settings.fieldMode,
    t,
    isAdvanced,
  }), [cx, settings.fieldMode, t, isAdvanced]);

  // Pass all context to children via render prop
  return (
    <>
      {children(contextValue)}
    </>
  );
});

FieldModeTemplate.displayName = 'FieldModeTemplate';

export default FieldModeTemplate;
