// src/shared/ui/layout/composites/SectionLayout.svelte
<script module lang="ts">
  type SectionGap = 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl';

  const sectionGapClasses: Record<SectionGap, string> = {
    none: '',
    xs: 'gap-1',
    sm: 'gap-2',
    md: 'gap-4',
    lg: 'gap-6',
    xl: 'gap-8',
  };
</script>

<script lang="ts">
  import type { Snippet } from 'svelte';
  import { cn } from '@/src/shared/lib/cn';

  interface Props {
    class?: string;
    title?: Snippet;
    body: Snippet;
    bodyGap?: SectionGap;
  }

  let { class: className = '', title, body, bodyGap = 'md' }: Props = $props();
</script>

<div class={cn('flex flex-col', className)}>
  {#if title}<div class="shrink-0">{@render title()}</div>{/if}
  <div class={cn('flex-1', sectionGapClasses[bodyGap])}>
    {@render body()}
  </div>
</div>

// src/shared/ui/layout/composites/SectionLayout.tsx
import React from 'react';
import { gapClasses } from '../types';
import type { GapSize } from '../types';
import { cn } from '@/src/shared/lib/cn';

/* ── SectionLayout (Level 4 — Content grouping) ── */

interface SectionLayoutProps {
  className?: string;
  children: React.ReactNode;
}

export function SectionLayout({ className, children }: SectionLayoutProps) {
  const classes = cn('flex flex-col', className);
  return <div className={classes}>{children}</div>;
}

/* ── Sub-components ── */

interface TitleProps {
  className?: string;
  children: React.ReactNode;
}

function Title({ className, children }: TitleProps) {
  return <div className={cn('shrink-0', className)}>{children}</div>;
}

interface BodyProps {
  gap?: GapSize;
  className?: string;
  children: React.ReactNode;
}

function Body({ gap = 'none', className, children }: BodyProps) {
  const classes = cn('flex flex-col', gapClasses[gap], className);
  return <div className={classes}>{children}</div>;
}

SectionLayout.Title = Title;
SectionLayout.Body = Body;
