// src/widgets/OnboardingModal/ui/OnboardingModal.svelte
<!--
  OnboardingModal - Two-screen wizard for first-time users.
  Screen 1: Welcome with feature highlights + "Get Started" (defaults to 'simple').
  Screen 2: ExperienceSelector widget for customizing experience level.

  React source: 189 lines -> ~160 lines Svelte
-->
<script lang="ts">
  import { cn } from '@/src/shared/lib/cn';
  import { Button } from '@/src/shared/ui/atoms';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';
  import type { AbstractionLevel } from '@/src/shared/types';
  import ExperienceSelector from '@/src/widgets/ExperienceSelector/ExperienceSelector.svelte';

  // --- Props ---
  interface Props {
    onComplete: (level: AbstractionLevel) => void;
  }

  let { onComplete }: Props = $props();

  // --- Local State ---
  let showExpertise: boolean = $state(false);
  let selectedLevel: AbstractionLevel = $state('standard');

  // --- Derived ---
  let selectedLabel = $derived.by(() => {
    const level = selectedLevel as AbstractionLevel;
    return level === 'simple' ? 'Essential' : level === 'standard' ? 'Complete' : 'Expert';
  });

  // --- Handlers ---
  function handleQuickStart() {
    onComplete('simple');
  }

  function handleSelectLevel(level: AbstractionLevel) {
    selectedLevel = level;
  }

  function handleConfirmSelection() {
    onComplete(selectedLevel);
  }

  function handleSkipSelection() {
    onComplete('standard');
  }

  // --- Feature list data (static) ---
  const features = [
    { icon: 'folder', color: 'nb-green', title: 'Drag folders to import', desc: 'Structure is preserved automatically' },
    { icon: 'photo_camera', color: 'nb-blue', title: 'Metadata extracted', desc: 'GPS, dates, and camera info captured' },
    { icon: 'public', color: 'nb-purple', title: 'Export to web', desc: 'One-click shareable websites' },
  ] as const;
</script>

<!-- Fullscreen overlay backdrop -->
<div class="fixed inset-0 bg-nb-black/80 z-[200] flex items-center justify-center p-4 backdrop-blur-sm animate-in fade-in">
  <div class="bg-nb-white max-w-4xl w-full shadow-brutal-lg overflow-hidden border border-nb-black/20">

    {#if !showExpertise}
      <!-- SCREEN 1: Welcome -->
      <div class="p-8 animate-in fade-in">
        <!-- Hero icon + heading -->
        <div class="text-center mb-8">
          <div class="inline-flex items-center justify-center w-14 h-14 bg-gradient-to-br from-nb-blue/100 to-nb-blue mb-4 text-white shadow-brutal">
            <Icon name="auto_awesome" class="text-2xl" />
          </div>
          <h1 class="text-2xl font-bold text-nb-black mb-2">Welcome to Field Studio</h1>
          <p class="text-nb-black/50 text-sm leading-relaxed">
            Turn your files into organized, shareable digital archives.
          </p>
        </div>

        <!-- Feature highlights -->
        <div class="space-y-3 mb-8">
          {#each features as feat}
            <div class="flex items-start gap-3 p-3 bg-nb-white">
              <div class={cn('w-8 h-8 flex items-center justify-center shrink-0', `bg-${feat.color}/20`)}>
                <Icon name={feat.icon} class={cn('text-sm', `text-${feat.color}`)} />
              </div>
              <div>
                <p class="text-sm font-medium text-nb-black/80">{feat.title}</p>
                <p class="text-xs text-nb-black/40">{feat.desc}</p>
              </div>
            </div>
          {/each}
        </div>

        <!-- Actions -->
        <div class="space-y-3">
          <Button variant="ghost" size="bare"
            onclick={handleQuickStart}
            class="w-full bg-gradient-to-r from-emerald-500 to-emerald-600 text-white px-6 py-3 font-semibold hover:from-emerald-600 hover:to-emerald-700 transition-nb flex items-center justify-center gap-2 shadow-brutal hover:shadow-brutal"
          >
            Get Started (Essential Mode)
            <Icon name="arrow_forward" />
          </Button>
          <Button variant="ghost" size="bare"
            onclick={() => showExpertise = true}
            class="w-full text-nb-black/60 px-6 py-3 text-sm hover:text-nb-black hover:bg-nb-white transition-nb border border-nb-black/20 hover:border-nb-black/20"
          >
            <div class="flex items-center justify-center gap-2">
              <Icon name="tune" class="text-nb-black/40" />
              Customize my experience level
            </div>
          </Button>
        </div>

        <!-- Help hint -->
        <p class="text-center text-[10px] text-nb-black/40 mt-6">
          Press <kbd class="px-1.5 py-0.5 bg-nb-cream text-[9px] font-mono">?</kbd> anytime for help
        </p>
      </div>

    {:else}
      <!-- SCREEN 2: Experience Selection -->
      <div class="p-8 animate-in slide-in-from-right-4">
        <!-- Back + step indicator -->
        <div class="flex items-center justify-between mb-6">
          <Button variant="ghost" size="bare"
            onclick={() => showExpertise = false}
            class="flex items-center gap-2 text-nb-black/50 hover:text-nb-black/80 text-sm px-3 py-1.5 hover:bg-nb-white transition-nb"
          >
            <Icon name="arrow_back" class="text-sm" />
            Back to welcome
          </Button>
          <div class="text-sm text-nb-black/50">Step 2 of 2</div>
        </div>

        <!-- ExperienceSelector widget -->
        <div class="mb-8">
          <ExperienceSelector
            selectedLevel={selectedLevel}
            onSelect={handleSelectLevel}
            showSkipOption={true}
            onSkip={handleSkipSelection}
            showFeatureComparison={true}
          />
        </div>

        <!-- Confirmation footer -->
        <div class="flex items-center justify-between pt-6 border-t border-nb-black/20">
          <div class="text-sm text-nb-black/50">
            Selected: <span class="font-semibold text-nb-black/80">{selectedLabel}</span>
          </div>
          <div class="flex items-center gap-3">
            <Button variant="ghost" size="bare"
              onclick={handleSkipSelection}
              class="px-4 py-2 text-sm text-nb-black/50 hover:text-nb-black/80 hover:bg-nb-white transition-nb"
            >
              Skip for now
            </Button>
            <Button variant="ghost" size="bare"
              onclick={handleConfirmSelection}
              class="px-6 py-2.5 bg-gradient-to-r from-nb-blue/100 to-nb-blue text-white font-semibold hover:from-nb-blue hover:to-nb-blue transition-nb shadow-brutal-sm hover:shadow-brutal"
            >
              Continue with {selectedLabel}
            </Button>
          </div>
        </div>

        <!-- Guidance box -->
        <div class="mt-6 p-4 bg-nb-blue/10 border border-nb-blue/20">
          <div class="flex items-start gap-3">
            <Icon name="lightbulb" class="text-nb-blue text-lg mt-0.5" />
            <div>
              <p class="text-sm font-medium text-nb-blue mb-1">Not sure which to choose?</p>
              <p class="text-xs text-nb-blue">
                <strong>Essential</strong> is perfect for quick organization.
                <strong>Complete</strong> adds full metadata control.
                <strong>Expert</strong> is for IIIF specialists. You can change this anytime in Settings.
              </p>
            </div>
          </div>
        </div>
      </div>
    {/if}

  </div>
</div>

// components/OnboardingModal.tsx
/**
 * OnboardingModal - Updated with Enhanced Experience Selector
 * 
 * Uses the new ExperienceSelector widget to solve all UX problems:
 * 1. No Context for Decision
 * 2. Arrow Icons Suggest Navigation
 * 3. Condescending Descriptions
 * 4. No Visual Differentiation
 * 5. Ambiguous Back Button
 */

import React, { useState } from 'react';
import { Icon } from './Icon';
import { AbstractionLevel } from '../types';
import { ExperienceSelector } from '../src/widgets/ExperienceSelector';

interface OnboardingModalProps {
  onComplete: (level: AbstractionLevel) => void;
}

export const OnboardingModal: React.FC<OnboardingModalProps> = ({ onComplete }) => {
  const [showExpertise, setShowExpertise] = useState(false);
  const [selectedLevel, setSelectedLevel] = useState<AbstractionLevel>('standard');

  // Quick start with default settings
  const handleQuickStart = () => {
    onComplete('simple');
  };

  // Choose expertise level
  const handleSelectLevel = (level: AbstractionLevel) => {
    setSelectedLevel(level);
  };

  const handleConfirmSelection = () => {
    onComplete(selectedLevel);
  };

  const handleSkipSelection = () => {
    onComplete('standard'); // Default to Complete
  };

  return (
    <div className="fixed inset-0 bg-slate-900/80 z-[200] flex items-center justify-center p-4 backdrop-blur-sm animate-in fade-in duration-300">
      <div className="bg-white max-w-4xl w-full rounded-2xl shadow-2xl overflow-hidden border border-slate-200">

        {!showExpertise ? (
          // Welcome Screen - Simple and Quick
          <div className="p-8 animate-in fade-in duration-300">
            <div className="text-center mb-8">
              <div className="inline-flex items-center justify-center w-14 h-14 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-2xl mb-4 text-white shadow-lg">
                <Icon name="auto_awesome" className="text-2xl" />
              </div>
              <h1 className="text-2xl font-bold text-slate-900 mb-2">Welcome to Field Studio</h1>
              <p className="text-slate-500 text-sm leading-relaxed">
                Turn your files into organized, shareable digital archives.
              </p>
            </div>

            {/* Quick Start Features */}
            <div className="space-y-3 mb-8">
              <div className="flex items-start gap-3 p-3 bg-slate-50 rounded-xl">
                <div className="w-8 h-8 rounded-lg bg-emerald-100 flex items-center justify-center shrink-0">
                  <Icon name="folder" className="text-emerald-600 text-sm" />
                </div>
                <div>
                  <p className="text-sm font-medium text-slate-700">Drag folders to import</p>
                  <p className="text-xs text-slate-400">Structure is preserved automatically</p>
                </div>
              </div>
              <div className="flex items-start gap-3 p-3 bg-slate-50 rounded-xl">
                <div className="w-8 h-8 rounded-lg bg-blue-100 flex items-center justify-center shrink-0">
                  <Icon name="photo_camera" className="text-blue-600 text-sm" />
                </div>
                <div>
                  <p className="text-sm font-medium text-slate-700">Metadata extracted</p>
                  <p className="text-xs text-slate-400">GPS, dates, and camera info captured</p>
                </div>
              </div>
              <div className="flex items-start gap-3 p-3 bg-slate-50 rounded-xl">
                <div className="w-8 h-8 rounded-lg bg-violet-100 flex items-center justify-center shrink-0">
                  <Icon name="public" className="text-violet-600 text-sm" />
                </div>
                <div>
                  <p className="text-sm font-medium text-slate-700">Export to web</p>
                  <p className="text-xs text-slate-400">One-click shareable websites</p>
                </div>
              </div>
            </div>

            {/* Actions */}
            <div className="space-y-3">
              <button
                onClick={handleQuickStart}
                className="w-full bg-gradient-to-r from-emerald-500 to-emerald-600 text-white px-6 py-3 rounded-xl font-semibold hover:from-emerald-600 hover:to-emerald-700 transition-all flex items-center justify-center gap-2 shadow-lg hover:shadow-xl"
              >
                Get Started (Essential Mode)
                <Icon name="arrow_forward" />
              </button>
              <button
                onClick={() => setShowExpertise(true)}
                className="w-full text-slate-600 px-6 py-3 rounded-xl text-sm hover:text-slate-800 hover:bg-slate-50 transition-colors border border-slate-200 hover:border-slate-300"
              >
                <div className="flex items-center justify-center gap-2">
                  <Icon name="tune" className="text-slate-400" />
                  Customize my experience level
                </div>
              </button>
            </div>

            {/* Help hint */}
            <p className="text-center text-[10px] text-slate-400 mt-6">
              Press <kbd className="px-1.5 py-0.5 bg-slate-100 rounded text-[9px] font-mono">?</kbd> anytime for help
            </p>
          </div>
        ) : (
          // Expertise Selection with Enhanced ExperienceSelector
          <div className="p-8 animate-in slide-in-from-right-4 duration-300">
            {/* Back Button - Clearer navigation */}
            <div className="flex items-center justify-between mb-6">
              <button
                onClick={() => setShowExpertise(false)}
                className="flex items-center gap-2 text-slate-500 hover:text-slate-700 text-sm px-3 py-1.5 hover:bg-slate-50 rounded-lg transition-colors"
              >
                <Icon name="arrow_back" className="text-sm" />
                Back to welcome
              </button>
              <div className="text-sm text-slate-500">
                Step 2 of 2
              </div>
            </div>

            {/* Enhanced Experience Selector */}
            <div className="mb-8">
              <ExperienceSelector
                selectedLevel={selectedLevel}
                onSelect={handleSelectLevel}
                showSkipOption={true}
                onSkip={handleSkipSelection}
                showFeatureComparison={true}
              />
            </div>

            {/* Confirmation Actions */}
            <div className="flex items-center justify-between pt-6 border-t border-slate-200">
              <div className="text-sm text-slate-500">
                Selected: <span className="font-semibold text-slate-700">
                  {selectedLevel === 'simple' ? 'Essential' : 
                   selectedLevel === 'standard' ? 'Complete' : 'Expert'}
                </span>
              </div>
              <div className="flex items-center gap-3">
                <button
                  onClick={handleSkipSelection}
                  className="px-4 py-2 text-sm text-slate-500 hover:text-slate-700 hover:bg-slate-50 rounded-lg transition-colors"
                >
                  Skip for now
                </button>
                <button
                  onClick={handleConfirmSelection}
                  className="px-6 py-2.5 bg-gradient-to-r from-blue-500 to-blue-600 text-white font-semibold rounded-lg hover:from-blue-600 hover:to-blue-700 transition-all shadow-md hover:shadow-lg"
                >
                  Continue with {selectedLevel === 'simple' ? 'Essential' : 
                                selectedLevel === 'standard' ? 'Complete' : 'Expert'}
                </button>
              </div>
            </div>

            {/* Additional Guidance */}
            <div className="mt-6 p-4 bg-blue-50/50 rounded-xl border border-blue-100">
              <div className="flex items-start gap-3">
                <Icon name="lightbulb" className="text-blue-500 text-lg mt-0.5" />
                <div>
                  <p className="text-sm font-medium text-blue-800 mb-1">
                    Not sure which to choose?
                  </p>
                  <p className="text-xs text-blue-600">
                    <strong>Essential</strong> is perfect for quick organization. <strong>Complete</strong> adds full metadata control. 
                    <strong>Expert</strong> is for IIIF specialists. You can change this anytime in Settings.
                  </p>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
