// src/features/metadata-edit/ui/atoms/ValidatedInput.svelte
<!--
  ValidatedInput — Input/textarea with live validation feedback, debounce, and auto-fix.
  React source: src/features/metadata-edit/ui/atoms/ValidatedInput.tsx (278 lines)
  Architecture: Atom (internal debounce + focus state, Rule 5.D: fieldMode, Rule 2.F: static types)
-->
<script module lang="ts">
  export type ValidationStatus = 'pristine' | 'valid' | 'invalid' | 'validating';

  export interface FieldValidation {
    status: ValidationStatus;
    message?: string;
    fix?: () => void;
    fixDescription?: string;
  }
</script>

<script lang="ts">
  import Button from '@/src/shared/ui/atoms/Button.svelte';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';
  import { cn } from '@/src/shared/lib/cn';

  interface Props {
    value: string;
    onchange: (value: string) => void;
    validation: FieldValidation;
    label: string;
    id: string;
    type?: 'text' | 'textarea' | 'url';
    placeholder?: string;
    disabled?: boolean;
    rows?: number;
    fieldMode?: boolean;
    onfocus?: (e: FocusEvent) => void;
    onblur?: (e: FocusEvent) => void;
  }

  let {
    value,
    onchange,
    validation,
    label,
    id,
    type = 'text',
    placeholder = '',
    disabled = false,
    rows = 3,
    fieldMode = false,
    onfocus,
    onblur,
  }: Props = $props();

  // --- Internal state ---
  let innerValue = $state(value ?? '');
  let isFocused = $state(false);
  let showSuccess = $state(false);
  let debounceTimer: ReturnType<typeof setTimeout> | undefined;
  let successTimer: ReturnType<typeof setTimeout> | undefined;

  // Sync external value when not focused (parent-driven updates)
  $effect(() => {
    if (!isFocused) {
      innerValue = value ?? '';
    }
  });

  // Success fade: show checkmark for 2s when status becomes 'valid'
  $effect(() => {
    if (validation.status === 'valid') {
      showSuccess = true;
      clearTimeout(successTimer);
      successTimer = setTimeout(() => {
        showSuccess = false;
      }, 2000);
    } else {
      showSuccess = false;
    }

    return () => clearTimeout(successTimer);
  });

  // --- Debounced change handler ---
  function handleInput(newValue: string) {
    innerValue = newValue;
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => {
      onchange(innerValue);
    }, 300);
  }

  function flushDebounce() {
    clearTimeout(debounceTimer);
    if (innerValue !== value) {
      onchange(innerValue);
    }
  }

  function handleFocus(e: FocusEvent) {
    isFocused = true;
    onfocus?.(e);
  }

  function handleBlur(e: FocusEvent) {
    isFocused = false;
    flushDebounce();
    onblur?.(e);
  }

  // --- Derived styles ---
  let borderColor = $derived.by(() => {
    switch (validation.status) {
      case 'invalid':
        return fieldMode ? 'border-nb-red' : 'border-nb-red';
      case 'valid':
        return fieldMode ? 'border-nb-green' : 'border-nb-green';
      case 'validating':
        return fieldMode ? 'border-nb-yellow/50' : 'border-nb-blue/50';
      default:
        return fieldMode ? 'border-nb-yellow/30' : 'border-nb-black/20';
    }
  });

  let statusIcon = $derived.by(() => {
    switch (validation.status) {
      case 'invalid':  return 'error';
      case 'valid':    return 'check_circle';
      case 'validating': return 'hourglass_empty';
      default:         return '';
    }
  });

  let statusIconColor = $derived.by(() => {
    switch (validation.status) {
      case 'invalid':    return 'text-nb-red';
      case 'valid':      return 'text-nb-green';
      case 'validating': return fieldMode ? 'text-nb-yellow/50' : 'text-nb-blue/50';
      default:           return '';
    }
  });

  let inputClasses = $derived(
    cn(
      'w-full px-3 py-2 text-sm border-2 outline-none font-mono transition-colors duration-100',
      'focus:ring-2',
      fieldMode
        ? 'bg-nb-black text-nb-yellow focus:ring-nb-yellow'
        : 'bg-nb-white text-nb-black focus:ring-nb-blue',
      borderColor,
      disabled && 'opacity-50 cursor-not-allowed'
    )
  );

  let labelClasses = $derived(
    cn(
      'flex items-center gap-1.5 text-xs font-bold font-mono uppercase tracking-wider mb-1.5',
      fieldMode ? 'text-nb-yellow' : 'text-nb-black'
    )
  );

  let messageId = $derived(`${id}-message`);
  let isInvalid = $derived(validation.status === 'invalid');
</script>

<!-- Label row with status icon -->
<div class="flex flex-col gap-0.5">
  <label for={id} class={labelClasses}>
    <span>{label}</span>
    {#if statusIcon}
      <Icon
        name={statusIcon}
        class={cn('text-sm', statusIconColor)}
      />
    {/if}
  </label>

  <!-- Input / Textarea -->
  {#if type === 'textarea'}
    <textarea
      {id}
      value={innerValue}
      oninput={(e) => handleInput(e.currentTarget.value)}
      onfocus={handleFocus}
      onblur={handleBlur}
      {placeholder}
      {disabled}
      {rows}
      class={inputClasses}
      aria-invalid={isInvalid || undefined}
      aria-describedby={validation.message ? messageId : undefined}
      aria-errormessage={isInvalid ? messageId : undefined}
    ></textarea>
  {:else}
    <input
      {id}
      type={type === 'url' ? 'url' : 'text'}
      value={innerValue}
      oninput={(e) => handleInput(e.currentTarget.value)}
      onfocus={handleFocus}
      onblur={handleBlur}
      {placeholder}
      {disabled}
      class={inputClasses}
      aria-invalid={isInvalid || undefined}
      aria-describedby={validation.message ? messageId : undefined}
      aria-errormessage={isInvalid ? messageId : undefined}
    />
  {/if}

  <!-- Validation message area -->
  <div
    id={messageId}
    class="min-h-[20px] mt-1"
    aria-live="polite"
  >
    {#if validation.status === 'invalid' && validation.message}
      <div class={cn(
        'flex items-start gap-1.5 text-xs font-bold',
        fieldMode ? 'text-nb-red' : 'text-nb-red'
      )}>
        <Icon name="error" class="text-sm shrink-0 mt-px" />
        <span class="flex-1">{validation.message}</span>
        {#if validation.fix}
          <Button
            variant="ghost"
            size="bare"
            onclick={validation.fix}
            class={cn(
              'text-xs font-bold underline shrink-0',
              fieldMode ? 'text-nb-yellow' : 'text-nb-blue'
            )}
          >
            {#snippet children()}
              {validation.fixDescription ?? 'Fix'}
            {/snippet}
          </Button>
        {/if}
      </div>
    {:else if validation.status === 'validating'}
      <div class={cn(
        'flex items-center gap-1.5 text-xs',
        fieldMode ? 'text-nb-yellow/50' : 'text-nb-black/40'
      )}>
        <Icon name="hourglass_empty" class="text-sm animate-spin" />
        <span>Validating...</span>
      </div>
    {:else if validation.status === 'valid' && showSuccess}
      <div class={cn(
        'flex items-center gap-1.5 text-xs transition-opacity duration-500',
        'text-nb-green'
      )}>
        <Icon name="check_circle" class="text-sm" />
        <span>Valid</span>
      </div>
    {/if}
  </div>
</div>

// components/ValidatedInput.tsx
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Icon } from '@/src/shared/ui/atoms/Icon';

export type ValidationStatus = 'pristine' | 'valid' | 'invalid' | 'validating';

export interface FieldValidation {
  status: ValidationStatus;
  message?: string;
  fix?: () => void;
  fixDescription?: string;
}

export interface ValidatedInputProps {
  value: string;
  onChange: (value: string) => void;
  validation: FieldValidation;
  label: string;
  id: string;
  type?: 'text' | 'textarea' | 'url';
  placeholder?: string;
  disabled?: boolean;
  rows?: number;
  fieldMode?: boolean;
  onFocus?: (e: React.FocusEvent<HTMLInputElement | HTMLTextAreaElement>) => void;
  onBlur?: (e: React.FocusEvent<HTMLInputElement | HTMLTextAreaElement>) => void;
}

/**
 * ValidatedInput - Field-level validation component for IIIF Inspector
 * 
 * Visual States:
 * - Pristine: border-slate-300 (default)
 * - Validating: border-amber-400 with spinner icon
 * - Valid: border-green-500 with checkmark (fades after 2s)
 * - Invalid: border-red-500 with exclamation, error message below, fix button if available
 * 
 * Accessibility:
 * - Screen reader announcements via aria-live
 * - Proper ARIA attributes for validation state
 * - Keyboard navigation support
 */
export const ValidatedInput: React.FC<ValidatedInputProps> = ({
  value,
  onChange,
  validation,
  label,
  id,
  type = 'text',
  placeholder,
  disabled = false,
  rows = 3,
  fieldMode = false,
  onFocus,
  onBlur,
}) => {
  const [innerValue, setInnerValue] = useState(value ?? '');
  const [showSuccess, setShowSuccess] = useState(false);
  const timeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const isTyping = useRef<boolean>(false);
  const isFocused = useRef<boolean>(false);
  const onChangeRef = useRef<(val: string) => void>(onChange);

  onChangeRef.current = onChange;

  // Sync with external value when not typing/focused
  useEffect(() => {
    if (!isTyping.current && !isFocused.current) {
      setInnerValue(value ?? '');
    }
  }, [value]);

  // Handle success state fade after 2 seconds
  useEffect(() => {
    if (validation.status === 'valid') {
      setShowSuccess(true);
      if (timeoutRef.current) clearTimeout(timeoutRef.current);
      timeoutRef.current = setTimeout(() => {
        setShowSuccess(false);
      }, 2000);
    } else {
      setShowSuccess(false);
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
        timeoutRef.current = null;
      }
    }

    return () => {
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
      }
    };
  }, [validation.status]);

  const handleChange = useCallback((e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const newVal = e.target.value;
    isTyping.current = true;
    setInnerValue(newVal);

    if (timeoutRef.current) clearTimeout(timeoutRef.current);
    timeoutRef.current = setTimeout(() => {
      onChangeRef.current(newVal);
      isTyping.current = false;
    }, 300);
  }, []);

  const handleFocus = useCallback((e: React.FocusEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    isFocused.current = true;
    onFocus?.(e as React.FocusEvent<HTMLInputElement>);
  }, [onFocus]);

  const handleBlur = useCallback((e: React.FocusEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    isFocused.current = false;
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current);
      onChangeRef.current(innerValue);
      isTyping.current = false;
    }
    onBlur?.(e as React.FocusEvent<HTMLInputElement>);
  }, [onBlur, innerValue]);

  // Determine border color based on validation state
  const getBorderColor = () => {
    if (disabled) return fieldMode ? 'border-slate-700' : 'border-slate-200';
    
    switch (validation.status) {
      case 'invalid':
        return 'border-red-500 focus:border-red-500 focus:ring-2 focus:ring-red-200';
      case 'valid':
        return showSuccess
          ? 'border-green-500 focus:border-green-500 focus:ring-2 focus:ring-green-200'
          : (fieldMode ? 'border-slate-800 focus:border-yellow-400' : 'border-slate-300 focus:ring-2 focus:ring-blue-500');
      case 'validating':
        return 'border-amber-400 focus:border-amber-400 focus:ring-2 focus:ring-amber-200';
      case 'pristine':
      default:
        return fieldMode
          ? 'border-slate-800 focus:border-yellow-400'
          : 'border-slate-300 focus:ring-2 focus:ring-blue-500';
    }
  };

  // Get status icon
  const getStatusIcon = () => {
    switch (validation.status) {
      case 'invalid':
        return <Icon name="error" className="text-red-500 text-sm" />;
      case 'valid':
        return showSuccess ? <Icon name="check_circle" className="text-green-500 text-sm" /> : null;
      case 'validating':
        return (
          <span className="inline-block animate-spin">
            <Icon name="sync" className="text-amber-400 text-sm" />
          </span>
        );
      case 'pristine':
      default:
        return null;
    }
  };

  // Get ARIA attributes for accessibility
  const getAriaAttributes = () => {
    const attrs: Record<string, string> = {
      'aria-describedby': `${id}-help`,
    };

    if (validation.status === 'invalid') {
      attrs['aria-invalid'] = 'true';
      attrs['aria-errormessage'] = `${id}-error`;
    } else if (validation.status === 'valid') {
      attrs['aria-invalid'] = 'false';
    }

    return attrs;
  };

  const baseInputClass = `w-full text-sm p-3 rounded-lg outline-none border transition-colors duration-200 ${getBorderColor()} ${
    fieldMode ? 'bg-slate-900 text-white placeholder-slate-600' : 'bg-white placeholder-slate-400'
  } ${disabled ? 'opacity-50 cursor-not-allowed' : ''}`;

  const InputComponent = type === 'textarea' ? 'textarea' : 'input';
  const inputType = type === 'url' ? 'url' : 'text';

  return (
    <div className="space-y-1.5">
      {/* Label with status indicator */}
      <label 
        htmlFor={id}
        className={`block text-[10px] font-bold uppercase tracking-wider flex items-center gap-1.5 ${
          fieldMode ? 'text-slate-500' : 'text-slate-400'
        }`}
      >
        {label}
        {getStatusIcon()}
      </label>

      {/* Input field */}
      <div className="relative">
        {type === 'textarea' ? (
          <textarea
            id={id}
            value={innerValue}
            onChange={handleChange}
            onFocus={handleFocus}
            onBlur={handleBlur}
            disabled={disabled}
            placeholder={placeholder}
            rows={rows}
            className={`${baseInputClass} resize-none`}
            {...getAriaAttributes()}
          />
        ) : (
          <input
            id={id}
            type={inputType}
            value={innerValue}
            onChange={handleChange}
            onFocus={handleFocus}
            onBlur={handleBlur}
            disabled={disabled}
            placeholder={placeholder}
            className={baseInputClass}
            {...getAriaAttributes()}
          />
        )}
      </div>

      {/* Validation message area with aria-live for screen readers */}
      <div 
        id={`${id}-help`}
        className="min-h-[20px]"
        aria-live="polite"
        aria-atomic="true"
      >
        {validation.status === 'invalid' && validation.message && (
          <div 
            id={`${id}-error`}
            className="flex items-start gap-1.5 text-[10px] text-red-500"
            role="alert"
          >
            <Icon name="error" className="text-[10px] mt-0.5 shrink-0" />
            <span className="flex-1">{validation.message}</span>
            {validation.fix && (
              <button
                onClick={validation.fix}
                className="shrink-0 ml-1 px-2 py-0.5 bg-green-100 text-green-700 rounded text-[9px] font-bold uppercase hover:bg-green-200 transition-colors"
                aria-label={`Fix: ${validation.fixDescription || 'Auto-fix this issue'}`}
                title={validation.fixDescription || 'Auto-fix this issue'}
              >
                Fix
              </button>
            )}
          </div>
        )}

        {validation.status === 'validating' && (
          <div className="flex items-center gap-1.5 text-[10px] text-amber-600">
            <span className="inline-block animate-spin">
              <Icon name="sync" className="text-[10px]" />
            </span>
            <span>Validating...</span>
          </div>
        )}

        {validation.status === 'valid' && showSuccess && (
          <div className="flex items-center gap-1.5 text-[10px] text-green-600">
            <Icon name="check_circle" className="text-[10px]" />
            <span>Valid</span>
          </div>
        )}
      </div>
    </div>
  );
};

export default ValidatedInput;
