// src/features/archive/ui/molecules/GroupedArchiveGrid.svelte
<!--
  GroupedArchiveGrid.svelte — Grouped archive grid by manifest
  =============================================================
  Groups canvases by parent manifest with collapsible sections.
  Each section has a header (chevron, book icon, label, count) and
  a responsive grid of canvas thumbnail cards with selection support.
  React source: src/features/archive/ui/molecules/GroupedArchiveGrid.tsx
-->
<script lang="ts">
  import type { IIIFCanvas } from '@/src/shared/types';
  import { getIIIFValue } from '@/src/shared/types';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';
  import Button from '@/src/shared/ui/atoms/Button.svelte';
  import BlurUpThumbnail from './BlurUpThumbnail.svelte';
  import { cn } from '@/src/shared/lib/cn';

  interface ManifestGroup {
    manifestId: string;
    manifestLabel: string;
    canvases: IIIFCanvas[];
  }

  type GridDensity = 'compact' | 'comfortable' | 'spacious';

  interface Props {
    groups: ManifestGroup[];
    isSelected: (id: string) => boolean;
    onItemClick: (e: MouseEvent, canvas: IIIFCanvas) => void;
    onToggleSelect: (canvas: IIIFCanvas) => void;
    onContextMenu: (e: MouseEvent, canvas: IIIFCanvas) => void;
    validationIssues?: Map<string, unknown[]>;
    cx: { surface?: string; text?: string; textMuted?: string; divider?: string; thumbnailBg?: string; selected?: string; [key: string]: string | undefined };
    fieldMode: boolean;
    density?: GridDensity;
    class?: string;
  }

  let {
    groups,
    isSelected,
    onItemClick,
    onToggleSelect,
    onContextMenu,
    validationIssues,
    cx,
    fieldMode,
    density = 'comfortable',
    class: className = '',
  }: Props = $props();

  let collapsed = $state<Set<string>>(new Set());

  function toggleCollapse(manifestId: string) {
    const next = new Set(collapsed);
    if (next.has(manifestId)) {
      next.delete(manifestId);
    } else {
      next.add(manifestId);
    }
    collapsed = next;
  }

  const gridColsClass = $derived(
    fieldMode
      ? 'grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5'
      : 'grid-cols-2 md:grid-cols-4 lg:grid-cols-6 xl:grid-cols-8'
  );

  const DENSITY_CLASSES: Record<GridDensity, string> = {
    compact: 'gap-2',
    comfortable: 'gap-4',
    spacious: 'gap-6',
  };

  const PADDING_CLASSES: Record<GridDensity, string> = {
    compact: 'p-1',
    comfortable: 'p-2',
    spacious: 'p-3',
  };

  /** Get thumbnail URLs for a canvas (low-res + high-res) */
  function resolveThumbs(canvas: IIIFCanvas): { low: string; high: string } {
    const thumb = canvas.thumbnail?.[0];
    const id = thumb?.id || '';
    if (!id) return { low: '', high: '' };
    // Low-res: append size hint for a small version
    // High-res: the original thumbnail URL
    return { low: id, high: id };
  }

  /** Get the label for a canvas */
  function getLabel(canvas: IIIFCanvas): string {
    return getIIIFValue(canvas.label) || canvas._filename || 'Untitled';
  }

  /** Handle checkbox click without propagating to item click */
  function handleCheckboxClick(e: MouseEvent, canvas: IIIFCanvas) {
    e.stopPropagation();
    onToggleSelect(canvas);
  }
</script>

{#if groups.length === 0}
  <!-- Empty state -->
  <div class="flex flex-col items-center justify-center py-16">
    <Icon
      name="inventory_2"
      class={cn('text-4xl mb-3 opacity-40', cx.textMuted || 'text-nb-black/30')}
    />
    <p class={cn('text-sm', cx.textMuted || 'text-nb-black/50')}>
      No manifest groups to display
    </p>
  </div>
{:else}
  <div class={cn('space-y-6', className)}>
    {#each groups as group (group.manifestId)}
      {@const isCollapsed = collapsed.has(group.manifestId)}
      <div class="group/section">
        <!-- Section header -->
        <button
          type="button"
          class={cn(
            'flex items-center gap-2 w-full text-left px-3 py-2 cursor-pointer transition-nb',
            fieldMode ? 'hover:bg-nb-yellow/10' : 'hover:bg-nb-black/5',
            cx.divider ? `border-b ${cx.divider}` : 'border-b border-nb-black/10'
          )}
          onclick={() => toggleCollapse(group.manifestId)}
          aria-expanded={!isCollapsed}
          aria-controls="group-{group.manifestId}"
        >
          <!-- Chevron toggle -->
          <Icon
            name="expand_more"
            class={cn(
              'text-lg transition-transform duration-200',
              isCollapsed && '-rotate-90',
              cx.textMuted || 'text-nb-black/40'
            )}
          />

          <!-- Book icon -->
          <Icon
            name="auto_stories"
            class={cn('text-base', fieldMode ? 'text-nb-yellow/70' : 'text-nb-blue/60')}
          />

          <!-- Manifest label -->
          <span class={cn(
            'font-mono text-xs font-bold uppercase tracking-wider flex-1 truncate',
            cx.text || 'text-nb-black'
          )}>
            {group.manifestLabel}
          </span>

          <!-- Canvas count -->
          <span class={cn(
            'text-xs font-mono tabular-nums shrink-0',
            cx.textMuted || 'text-nb-black/40'
          )}>
            {group.canvases.length}
          </span>
        </button>

        <!-- Grid of canvas items -->
        {#if !isCollapsed}
          <div
            id="group-{group.manifestId}"
            class={cn('grid', gridColsClass, DENSITY_CLASSES[density], 'p-4')}
            role="grid"
            aria-label="{group.manifestLabel} canvases"
          >
            {#each group.canvases as canvas (canvas.id)}
              {@const selected = isSelected(canvas.id)}
              {@const thumbs = resolveThumbs(canvas)}
              {@const label = getLabel(canvas)}
              {@const hasIssues = validationIssues?.has(canvas.id)}
              <div
                role="gridcell"
                aria-selected={selected}
                class={cn(
                  'group relative flex flex-col overflow-hidden cursor-pointer transition-nb',
                  cx.thumbnailBg || 'bg-nb-cream border-2 border-nb-black',
                  selected && (cx.selected || 'ring-2 ring-nb-blue'),
                  PADDING_CLASSES[density]
                )}
                onclick={(e) => onItemClick(e, canvas)}
                oncontextmenu={(e) => onContextMenu(e, canvas)}
                onkeydown={(e) => {
                  if (e.key === ' ') {
                    e.preventDefault();
                    onToggleSelect(canvas);
                  }
                }}
                tabindex="0"
              >
                <!-- Thumbnail -->
                <div class={cn(
                  'aspect-square overflow-hidden',
                  fieldMode ? 'bg-nb-black' : 'bg-nb-cream'
                )}>
                  <BlurUpThumbnail
                    lowResUrl={thumbs.low}
                    highResUrl={thumbs.high}
                    {cx}
                    {fieldMode}
                  />
                </div>

                <!-- Label bar -->
                <div class="px-1.5 py-1 min-h-[1.75rem] flex items-center gap-1">
                  <span class={cn('text-xs truncate flex-1', cx.text || 'text-nb-black')}>
                    {label}
                  </span>

                  <!-- Validation dot -->
                  {#if hasIssues}
                    <span
                      class="w-2 h-2 rounded-full bg-nb-red shrink-0"
                      title="Has validation issues"
                    ></span>
                  {/if}
                </div>

                <!-- Selection checkmark overlay -->
                {#if selected}
                  <div class={cn(
                    'absolute top-1.5 left-1.5 w-5 h-5 flex items-center justify-center rounded-sm',
                    fieldMode ? 'bg-nb-yellow text-nb-black' : 'bg-nb-blue text-nb-white'
                  )}>
                    <Icon name="check" class="text-sm" />
                  </div>
                {/if}

                <!-- Hover checkbox (non-selected items) -->
                {#if !selected}
                  <button
                    type="button"
                    class={cn(
                      'absolute top-1.5 left-1.5 w-5 h-5 flex items-center justify-center rounded-sm',
                      'opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer',
                      fieldMode
                        ? 'bg-nb-black/50 text-nb-yellow border border-nb-yellow/40'
                        : 'bg-nb-white/80 text-nb-black/40 border border-nb-black/20'
                    )}
                    onclick={(e) => handleCheckboxClick(e, canvas)}
                    aria-label="Select {label}"
                  >
                    <Icon name="check_box_outline_blank" class="text-xs" />
                  </button>
                {/if}
              </div>
            {/each}
          </div>
        {/if}
      </div>
    {/each}
  </div>
{/if}

// src/features/archive/ui/molecules/GroupedArchiveGrid.tsx
/**
 * GroupedArchiveGrid Molecule
 *
 * Renders canvases grouped by parent manifest with collapsible sections.
 * Each section has a manifest header with collapse toggle and item count.
 *
 * @module features/archive/ui/molecules/GroupedArchiveGrid
 */

import React, { useCallback, useState } from 'react';
import { getIIIFValue, type IIIFCanvas } from '@/src/shared/types';
import { type ValidationIssue } from '@/src/entities/manifest/model/validation/validator';
import { Icon } from '@/src/shared/ui/atoms';
import { Button } from '@/ui/primitives/Button';
import { RESOURCE_TYPE_CONFIG } from '@/src/shared/constants';
import { resolveHierarchicalThumbs } from '@/utils/imageSourceResolver';
import { type ManifestGroup, getFileDNA } from '../../model';
import { BlurUpThumbnail } from './BlurUpThumbnail';
import type { GridDensity } from '../organisms/ArchiveGrid';

export interface GroupedArchiveGridProps {
  groups: ManifestGroup[];
  isSelected: (id: string) => boolean;
  onItemClick: (e: React.MouseEvent, asset: IIIFCanvas) => void;
  onToggleSelect?: (id: string) => void;
  onContextMenu: (e: React.MouseEvent, id: string) => void;
  validationIssues?: Record<string, ValidationIssue[]>;
  cx: {
    surface: string;
    text: string;
    accent: string;
    border: string;
    textMuted: string;
    [key: string]: string | undefined;
  };
  fieldMode: boolean;
  density?: GridDensity;
}

export const GroupedArchiveGrid: React.FC<GroupedArchiveGridProps> = ({
  groups,
  isSelected,
  onItemClick,
  onToggleSelect,
  onContextMenu,
  validationIssues,
  cx,
  fieldMode,
  density = 'comfortable',
}) => {
  const [collapsed, setCollapsed] = useState<Set<string>>(new Set());

  const toggleCollapse = useCallback((manifestId: string) => {
    setCollapsed(prev => {
      const next = new Set(prev);
      if (next.has(manifestId)) next.delete(manifestId);
      else next.add(manifestId);
      return next;
    });
  }, []);

  const gridColsClass = fieldMode
    ? 'grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5'
    : 'grid-cols-2 md:grid-cols-4 lg:grid-cols-6 xl:grid-cols-8';

  const densityClasses = {
    compact: 'gap-2',
    comfortable: 'gap-4',
    spacious: 'gap-6',
  };

  const paddingClasses = {
    compact: 'p-1',
    comfortable: 'p-2',
    spacious: 'p-3',
  };

  if (groups.length === 0) {
    return (
      <div className="p-12 text-center">
        <div className={`text-lg font-medium ${cx.text} mb-2`}>No groups found</div>
        <p className={`text-sm ${cx.textMuted}`}>Your archive has no manifests to group by.</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {groups.map((group) => {
        const isCollapsed = collapsed.has(group.manifestId);

        return (
          <div key={group.manifestId}>
            {/* Section header */}
            <Button
              variant="ghost"
              size="bare"
              onClick={() => toggleCollapse(group.manifestId)}
              className={`w-full flex items-center gap-2 px-3 py-2.5 mb-3 border transition-nb ${
                fieldMode
                  ? 'bg-nb-yellow/10 border-nb-yellow/30 hover:bg-nb-yellow/20'
                  : 'bg-nb-cream/50 border-nb-black/10 hover:bg-nb-cream'
              }`}
            >
              <Icon
                name={isCollapsed ? 'chevron_right' : 'expand_more'}
                className={`text-lg transition-transform ${
                  fieldMode ? 'text-nb-yellow' : 'text-nb-black/50'
                }`}
              />
              <Icon
                name="auto_stories"
                className={`text-sm ${fieldMode ? 'text-nb-yellow/70' : 'text-nb-black/40'}`}
              />
              <span className={`text-sm font-bold flex-1 text-left truncate ${
                fieldMode ? 'text-nb-yellow' : cx.text
              }`}>
                {group.manifestLabel}
              </span>
              <span className={`text-xs font-mono px-2 py-0.5 ${
                fieldMode ? 'bg-nb-yellow/20 text-nb-yellow' : 'bg-nb-black/5 text-nb-black/50'
              }`}>
                {group.canvases.length}
              </span>
            </Button>

            {/* Grid content */}
            {!isCollapsed && (
              <div className={`grid ${densityClasses[density]} ${gridColsClass}`}>
                {group.canvases.map((asset) => {
                  const selected = isSelected(asset.id);
                  const thumbUrls = resolveHierarchicalThumbs(asset, 200);
                  const config = RESOURCE_TYPE_CONFIG['Canvas'];

                  return (
                    <div
                      key={asset.id}
                      data-grid-item
                      data-item-id={asset.id}
                      onClick={(e) => onItemClick(e, asset)}
                      onContextMenu={(e) => onContextMenu(e, asset.id)}
                      className={`
                        group relative transition-nb cursor-pointer
                        ${paddingClasses[density]}
                        ${selected
                          ? 'bg-nb-orange/20 border-2 border-nb-orange shadow-brutal-sm'
                          : 'bg-nb-black border border-nb-black/20 hover:shadow-brutal hover:border-nb-black/20'
                        }
                      `}
                    >
                      <div className="aspect-square overflow-hidden flex items-center justify-center mb-2 relative bg-nb-black">
                        {selected && (
                          <div className="absolute inset-0 bg-nb-orange/10 z-10 pointer-events-none" />
                        )}
                        {/* Validation dot */}
                        {validationIssues?.[asset.id] && (
                          <div className="absolute top-2 left-2 z-20" title={`${validationIssues[asset.id].length} issue(s)`}>
                            <div className={`w-2.5 h-2.5 rounded-full shadow-brutal-sm ${
                              validationIssues[asset.id].some(i => i.level === 'error') ? 'bg-nb-red' : 'bg-nb-orange'
                            }`} />
                          </div>
                        )}
                        {/* Checkmark */}
                        <Button variant="ghost" size="bare"
                          onClick={(e) => { e.stopPropagation(); onToggleSelect?.(asset.id); }}
                          className={`absolute top-2 right-2 z-20 w-6 h-6 flex items-center justify-center transition-nb shadow-brutal-sm cursor-pointer ${
                            selected
                              ? fieldMode ? 'bg-nb-yellow text-white scale-100' : 'bg-nb-orange text-white scale-100'
                              : 'bg-nb-white/90 text-nb-black/40 scale-0 group-hover:scale-100 hover:bg-nb-cream'
                          }`}
                        >
                          <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                            <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                          </svg>
                        </Button>

                        {thumbUrls.length <= 1 ? (
                          <BlurUpThumbnail
                            lowResUrl={resolveHierarchicalThumbs(asset, 50)[0] || ''}
                            highResUrl={thumbUrls[0] || ''}
                            fallbackIcon={config.icon}
                            cx={cx}
                            fieldMode={fieldMode}
                          />
                        ) : (
                          <img
                            src={thumbUrls[0]}
                            alt=""
                            className="w-full h-full object-cover"
                            loading="lazy"
                          />
                        )}
                      </div>

                      <div className="px-1 min-w-0 h-6 flex items-center">
                        <div className={`text-nb-xs font-medium truncate ${cx.text ?? 'text-nb-black'}`} title={getIIIFValue(asset.label)}>
                          {getIIIFValue(asset.label)}
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
};

export default GroupedArchiveGrid;
