// components/AuthDialog.tsx
/**
 * AuthDialog - IIIF Authorization Flow 2.0 UI Component
 *
 * Displays authentication prompts for restricted IIIF content.
 * Supports active, kiosk, and external authentication profiles.
 */

import React, { useEffect, useState } from 'react';
import { authService, AuthService, AuthState, ProbeResponse } from '../services/authService';
import { Icon } from './Icon';

interface AuthDialogProps {
  /** The auth services extracted from the IIIF resource */
  authServices: AuthService[];
  /** Resource ID being accessed */
  resourceId: string;
  /** Callback when authentication completes */
  onComplete: (state: AuthState) => void;
  /** Callback to close dialog */
  onClose: () => void;
  /** Preferred language for labels */
  preferredLang?: string;
}

export const AuthDialog: React.FC<AuthDialogProps> = ({
  authServices,
  resourceId,
  onComplete,
  onClose,
  preferredLang = 'en'
}) => {
  const [state, setState] = useState<AuthState>({ status: 'probing' });
  const [probeResult, setProbeResult] = useState<ProbeResponse | null>(null);
  const [isLoggingIn, setIsLoggingIn] = useState(false);

  const accessService = authService.findAccessService(authServices);
  const probeService = authService.findProbeService(authServices);
  const tokenService = authService.findTokenService(authServices);

  // Auto-probe on mount
  useEffect(() => {
    if (probeService) {
      probeForAccess();
    }
  }, []);

  const probeForAccess = async () => {
    if (!probeService) return;

    setState({ status: 'probing' });

    const result = await authService.probe(probeService, resourceId);
    setProbeResult(result);

    if (result.status === 200) {
      setState({ status: 'authenticated' });
      onComplete({ status: 'authenticated', probeResult: result });
    } else if (result.status === 401) {
      if (result.substitute) {
        setState({
          status: 'degraded',
          substitute: result.substitute,
          probeResult: result
        });
      } else {
        setState({
          status: 'unauthenticated',
          probeResult: result
        });
      }
    } else {
      setState({
        status: 'error',
        errorMessage: `Access denied (${result.status})`
      });
    }
  };

  const handleLogin = () => {
    if (!accessService) return;

    setIsLoggingIn(true);

    authService.openLoginWindow(accessService, {
      onComplete: async (windowClosed) => {
        setIsLoggingIn(false);

        // Try to get token after login window closes
        if (tokenService) {
          try {
            const tokenResponse = await authService.requestToken(tokenService);
            // Check if we got a valid token response (not an error)
            if (tokenResponse.type === 'AuthAccessToken2' && 'accessToken' in tokenResponse) {
              authService.storeToken(resourceId, tokenResponse.accessToken, tokenResponse.expiresIn);
            } else {
              throw new Error('Invalid token response');
            }

            // Re-probe to verify access
            await probeForAccess();
          } catch (error) {
            console.error('Token request failed:', error);
            setState({
              status: 'error',
              errorMessage: 'Failed to retrieve access token'
            });
          }
        } else {
          // No token service, just re-probe
          await probeForAccess();
        }
      }
    });
  };

  const handleUseDegraded = () => {
    if (state.substitute) {
      onComplete({
        status: 'degraded',
        substitute: state.substitute,
        probeResult: probeResult || undefined
      });
    }
  };

  // Get display texts
  const heading = probeResult?.heading
    ? authService.getLabel(probeResult.heading, preferredLang)
    : accessService?.header
      ? authService.getLabel(accessService.header, preferredLang)
      : 'Authentication Required';

  const description = probeResult?.note
    ? authService.getLabel(probeResult.note, preferredLang)
    : accessService?.description
      ? authService.getLabel(accessService.description, preferredLang)
      : 'This resource requires authentication to access.';

  const loginLabel = accessService?.confirmLabel
    ? authService.getLabel(accessService.confirmLabel, preferredLang)
    : 'Login';

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[100] flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full overflow-hidden">
        {/* Header */}
        <div className="p-6 border-b bg-slate-50">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-amber-100 rounded-xl flex items-center justify-center text-amber-600">
              <Icon name="lock" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-800">{heading}</h2>
              <p className="text-xs text-slate-500">IIIF Authorization Flow 2.0</p>
            </div>
          </div>
        </div>

        {/* Content */}
        <div className="p-6">
          {state.status === 'probing' && (
            <div className="flex flex-col items-center py-8">
              <div className="w-12 h-12 border-4 border-slate-100 border-t-iiif-blue rounded-full animate-spin mb-4"></div>
              <p className="text-sm text-slate-500">Checking access...</p>
            </div>
          )}

          {state.status === 'unauthenticated' && (
            <>
              <p className="text-slate-600 mb-6">{description}</p>

              {accessService?.profile === 'active' && (
                <div className="bg-blue-50 border border-blue-100 rounded-xl p-4 mb-4">
                  <div className="flex items-start gap-3">
                    <Icon name="info" className="text-blue-600 mt-0.5" />
                    <div className="text-sm text-blue-800">
                      You will be redirected to a login page. After logging in, return here to continue.
                    </div>
                  </div>
                </div>
              )}

              {accessService?.profile === 'kiosk' && (
                <div className="bg-green-50 border border-green-100 rounded-xl p-4 mb-4">
                  <div className="flex items-start gap-3">
                    <Icon name="verified_user" className="text-green-600 mt-0.5" />
                    <div className="text-sm text-green-800">
                      Access will be granted automatically based on your network location.
                    </div>
                  </div>
                </div>
              )}

              {accessService?.profile === 'external' && (
                <div className="bg-purple-50 border border-purple-100 rounded-xl p-4 mb-4">
                  <div className="flex items-start gap-3">
                    <Icon name="open_in_new" className="text-purple-600 mt-0.5" />
                    <div className="text-sm text-purple-800">
                      Authentication is handled by an external service. You may need to log in separately.
                    </div>
                  </div>
                </div>
              )}
            </>
          )}

          {state.status === 'degraded' && (
            <>
              <p className="text-slate-600 mb-4">{description}</p>

              <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-4">
                <div className="flex items-start gap-3">
                  <Icon name="warning" className="text-amber-600 mt-0.5" />
                  <div>
                    <p className="text-sm font-medium text-amber-900 mb-1">
                      Restricted Access
                    </p>
                    <p className="text-xs text-amber-700">
                      Full access requires authentication. A lower-quality substitute is available.
                    </p>
                  </div>
                </div>
              </div>

              {state.substitute && (
                <div className="border rounded-lg p-3 mb-4">
                  <p className="text-xs font-medium text-slate-500 mb-1">Available substitute:</p>
                  <p className="text-sm text-slate-700 font-mono truncate">
                    {state.substitute.id}
                  </p>
                  {state.substitute.width && state.substitute.height && (
                    <p className="text-xs text-slate-500 mt-1">
                      {state.substitute.width} x {state.substitute.height}
                    </p>
                  )}
                </div>
              )}
            </>
          )}

          {state.status === 'authenticated' && (
            <div className="flex flex-col items-center py-8">
              <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center text-green-600 mb-4">
                <Icon name="check_circle" className="text-3xl" />
              </div>
              <p className="text-lg font-semibold text-green-800">Access Granted</p>
              <p className="text-sm text-slate-500 mt-1">You can now view this resource.</p>
            </div>
          )}

          {state.status === 'error' && (
            <div className="bg-red-50 border border-red-200 rounded-xl p-4">
              <div className="flex items-start gap-3">
                <Icon name="error" className="text-red-600 mt-0.5" />
                <div>
                  <p className="text-sm font-medium text-red-900 mb-1">
                    Authentication Error
                  </p>
                  <p className="text-xs text-red-700">
                    {state.errorMessage || 'An error occurred during authentication.'}
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Actions */}
        <div className="p-4 border-t bg-slate-50 flex gap-3 justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 text-slate-600 hover:text-slate-800 font-medium text-sm"
          >
            Cancel
          </button>

          {state.status === 'unauthenticated' && accessService && (
            <button
              onClick={handleLogin}
              disabled={isLoggingIn}
              className="px-6 py-2 bg-iiif-blue text-white rounded-lg font-semibold text-sm hover:bg-blue-700 disabled:opacity-50 flex items-center gap-2"
            >
              {isLoggingIn ? (
                <>
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                  Logging in...
                </>
              ) : (
                <>
                  <Icon name="login" />
                  {loginLabel}
                </>
              )}
            </button>
          )}

          {state.status === 'degraded' && (
            <>
              <button
                onClick={handleUseDegraded}
                className="px-4 py-2 border border-slate-300 text-slate-700 rounded-lg font-medium text-sm hover:bg-slate-100"
              >
                Use Substitute
              </button>
              {accessService && (
                <button
                  onClick={handleLogin}
                  disabled={isLoggingIn}
                  className="px-6 py-2 bg-iiif-blue text-white rounded-lg font-semibold text-sm hover:bg-blue-700 disabled:opacity-50 flex items-center gap-2"
                >
                  {isLoggingIn ? (
                    <>
                      <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                      Logging in...
                    </>
                  ) : (
                    <>
                      <Icon name="login" />
                      {loginLabel}
                    </>
                  )}
                </button>
              )}
            </>
          )}

          {state.status === 'authenticated' && (
            <button
              onClick={() => onComplete(state)}
              className="px-6 py-2 bg-green-600 text-white rounded-lg font-semibold text-sm hover:bg-green-700"
            >
              Continue
            </button>
          )}

          {state.status === 'error' && (
            <button
              onClick={probeForAccess}
              className="px-4 py-2 border border-slate-300 text-slate-700 rounded-lg font-medium text-sm hover:bg-slate-100"
            >
              Retry
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

/**
 * Hook for handling auth in viewers/components
 */
export const useIIIFAuth = (resourceId: string, authServices: AuthService[]) => {
  const [authState, setAuthState] = useState<AuthState>({ status: 'unknown' });
  const [showDialog, setShowDialog] = useState(false);

  const checkAuth = async () => {
    const result = await authService.authenticateResource(
      resourceId,
      authServices,
      setAuthState
    );
    setAuthState(result);
    return result;
  };

  const getAuthHeaders = (): HeadersInit => {
    const token = authService.getValidToken(resourceId);
    if (token) {
      return { Authorization: `Bearer ${token}` };
    }
    return {};
  };

  return {
    authState,
    showDialog,
    setShowDialog,
    checkAuth,
    getAuthHeaders,
    needsAuth: authState.status === 'unauthenticated' || authState.status === 'degraded'
  };
};

export default AuthDialog;

// src/widgets/AuthDialog/ui/AuthDialog.svelte
<!--
  AuthDialog.svelte
  IIIF Authorization Flow 2.0 dialog widget.
  Migrated from React AuthDialog.tsx (369 lines).

  Handles three auth profiles: active (login window), kiosk (auto-token), external (redirect).
  Flow: auto-probe on mount -> login prompt -> logging in -> result.
-->

<script lang="ts">
  // ---------------------------------------------------------------------------
  // Imports
  // ---------------------------------------------------------------------------
  import { cn } from '@/src/shared/lib/cn';
  import { Button } from '@/src/shared/ui/atoms';
  import { Icon } from '@/src/shared/ui/atoms';
  import { ModalDialog } from '@/src/shared/ui/molecules';
  import { toast } from '@/src/shared/stores/toast.svelte';

  import type { AuthAccessService2 } from '@/src/shared/types/auth-api';
  import {
    detectProbeService,
    findTokenService,
    openAccessService,
    requestToken,
    probeResource,
    authStatusFromProbe,
  } from '@/src/shared/services/authFlowService';
  // AuthService is the general union; AuthDialog specifically handles access services
  type AuthService = AuthAccessService2;

  // ---------------------------------------------------------------------------
  // Types
  // ---------------------------------------------------------------------------
  type AuthState = 'authenticated' | 'degraded' | 'failed';

  type AuthFlowState =
    | 'idle'
    | 'probing'
    | 'prompt'
    | 'loggingIn'
    | 'complete'
    | 'error';

  type AuthProfile = 'active' | 'kiosk' | 'external';

  interface ProbeResult {
    status: number;
    contentLocation?: string;
    errorMessage?: string;
    substitute?: { id: string; width?: number; height?: number };
  }

  // ---------------------------------------------------------------------------
  // Props
  // ---------------------------------------------------------------------------
  interface Props {
    authServices: AuthService[];
    resourceId: string;
    onComplete: (state: AuthState) => void;
    onClose: () => void;
    preferredLang?: string;
  }

  let {
    authServices,
    resourceId,
    onComplete,
    onClose,
    preferredLang = 'en',
  }: Props = $props();

  // ---------------------------------------------------------------------------
  // State
  // ---------------------------------------------------------------------------
  let flowState: AuthFlowState = $state('idle');
  let probeResult: ProbeResult | null = $state(null);
  let isLoggingIn: boolean = $state(false);
  let activeServiceIndex: number = $state(0);
  let loginWindowRef: Window | null = $state(null);
  let errorMessage: string = $state('');

  // ---------------------------------------------------------------------------
  // Derived
  // ---------------------------------------------------------------------------
  const activeService = $derived(authServices[activeServiceIndex] ?? null);

  const authProfile = $derived.by((): AuthProfile => {
    if (!activeService) return 'active';
    const profile = activeService.profile ?? '';
    if (profile.includes('kiosk')) return 'kiosk';
    if (profile.includes('external')) return 'external';
    return 'active';
  });

  const serviceLabel = $derived(
    activeService
      ? getLocalizedValue(activeService.label, preferredLang)
      : 'Authentication Required'
  );

  const serviceDescription = $derived(
    activeService
      ? getLocalizedValue(activeService.description, preferredLang)
      : 'This resource requires authentication to access.'
  );

  const confirmLabel = $derived(
    activeService
      ? getLocalizedValue(activeService.confirmLabel, preferredLang)
      : 'Login'
  );

  const isComplete = $derived((flowState as AuthFlowState) === 'complete');
  const isError = $derived((flowState as AuthFlowState) === 'error');
  const isProbing = $derived((flowState as AuthFlowState) === 'probing');
  const showLoginPrompt = $derived((flowState as AuthFlowState) === 'prompt');
  const hasDegradedSubstitute = $derived.by(() => {
    const pr = probeResult as ProbeResult | null;
    return pr != null && pr.substitute != null && (flowState as AuthFlowState) === 'prompt';
  });

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  /** Extract localized string from IIIF language map or plain string */
  function getLocalizedValue(
    value: string | Record<string, string[]> | undefined,
    lang: string
  ): string {
    if (!value) return '';
    if (typeof value === 'string') return value;
    return value[lang]?.[0] ?? value['en']?.[0] ?? value['none']?.[0] ?? '';
  }

  /**
   * Probe the auth service to determine current auth status.
   * Sends a HEAD/GET request to the probe service endpoint.
   */
  async function probeService(service: AuthService): Promise<ProbeResult> {
    const probeSvc = detectProbeService(service.service);
    if (!probeSvc) {
      return { status: 401, errorMessage: 'No probe service found' };
    }

    try {
      const response = await probeResource(probeSvc.id);
      const sub = response.substitute?.[0];
      return {
        status: response.status,
        contentLocation: response.location?.id,
        errorMessage: response.note?.en?.[0],
        substitute: sub
          ? { id: sub.id, width: sub.width, height: sub.height }
          : undefined,
      };
    } catch (e: unknown) {
      return { status: 0, errorMessage: e instanceof Error ? e.message : 'Probe request failed' };
    }
  }

  /**
   * Exchange the auth cookie/token for an access token
   * by hitting the token service endpoint.
   */
  async function fetchAccessToken(
    service: AuthService
  ): Promise<{ accessToken?: string; error?: string }> {
    const tokenSvc = findTokenService(service);
    if (!tokenSvc) {
      return { error: 'No token service found' };
    }

    try {
      const tokenResp = await requestToken(tokenSvc);
      return { accessToken: tokenResp.accessToken };
    } catch (e: unknown) {
      const message = e instanceof Error ? e.message : 'Token exchange failed';
      return { error: message };
    }
  }

  /** Open a login window for the active auth profile */
  function openLoginWindow(service: AuthService): void {
    const handle = openAccessService(service);
    // openAccessService returns { close, type } -- for 'window' type we need the
    // actual window ref for polling. Fall back to window.open directly.
    const w = window.open(service.id, '_blank', 'width=600,height=700');
    loginWindowRef = w;
  }

  // ---------------------------------------------------------------------------
  // Handlers
  // ---------------------------------------------------------------------------

  async function handleProbe(): Promise<void> {
    if (!activeService) return;
    flowState = 'probing';
    errorMessage = '';

    try {
      const result = await probeService(activeService);
      probeResult = result;

      if (result.status === 200) {
        // Already authenticated
        flowState = 'complete';
        onComplete('authenticated');
      } else if (authProfile === 'kiosk') {
        // Kiosk: auto-fetch token without user interaction
        await handleKioskFlow();
      } else {
        // Active/External: show login prompt
        flowState = 'prompt';
      }
    } catch (e: unknown) {
      flowState = 'error';
      errorMessage = e instanceof Error ? e.message : 'Probe failed';
    }
  }

  async function handleKioskFlow(): Promise<void> {
    if (!activeService) return;
    flowState = 'loggingIn';

    try {
      const tokenResult = await fetchAccessToken(activeService);
      if (tokenResult.accessToken) {
        flowState = 'complete';
        onComplete('authenticated');
      } else {
        flowState = 'error';
        errorMessage = tokenResult.error ?? 'Token exchange failed';
        onComplete('failed');
      }
    } catch (e: unknown) {
      flowState = 'error';
      errorMessage = e instanceof Error ? e.message : 'Kiosk auth failed';
      onComplete('failed');
    }
  }

  async function handleLogin(): Promise<void> {
    if (!activeService) return;
    isLoggingIn = true;
    flowState = 'loggingIn';

    openLoginWindow(activeService);

    // Poll for login window close + listen for postMessage completion
    await new Promise<void>((resolve) => {
      const pollInterval = setInterval(() => {
        if (loginWindowRef?.closed) {
          clearInterval(pollInterval);
          resolve();
        }
      }, 500);

      // TODO(loop): Add postMessage listener for token exchange when auth
      // service sends token directly via postMessage instead of cookie flow.
      // For now, rely on window close detection followed by token exchange.
    });

    await handlePostLogin();
  }

  async function handlePostLogin(): Promise<void> {
    if (!activeService) return;

    try {
      const tokenResult = await fetchAccessToken(activeService);
      isLoggingIn = false;

      if (tokenResult.accessToken) {
        flowState = 'complete';
        onComplete('authenticated');
        toast.success('Authentication successful');
      } else if (tokenResult.error === 'missingCredentials') {
        flowState = 'complete';
        onComplete('degraded');
        toast.warning('Access granted with limited permissions');
      } else {
        flowState = 'error';
        errorMessage = tokenResult.error ?? 'Authentication failed';
        onComplete('failed');
      }
    } catch (e: unknown) {
      isLoggingIn = false;
      flowState = 'error';
      errorMessage = e instanceof Error ? e.message : 'Post-login failed';
      onComplete('failed');
    }
  }

  function handleUseDegraded(): void {
    onComplete('degraded');
    onClose();
  }

  function handleTryNextService(): void {
    if (activeServiceIndex < authServices.length - 1) {
      activeServiceIndex++;
      flowState = 'idle';
      probeResult = null;
      errorMessage = '';
      // Will re-trigger probe via effect
    } else {
      onComplete('failed');
      onClose();
    }
  }

  function handleDismiss(): void {
    if (loginWindowRef && !loginWindowRef.closed) {
      loginWindowRef.close();
    }
    onClose();
  }

  // ---------------------------------------------------------------------------
  // Effects
  // ---------------------------------------------------------------------------

  // Auto-probe on mount and when activeServiceIndex changes
  $effect(() => {
    // Track dependency
    const _idx = activeServiceIndex;
    const _services = authServices;

    if (_services.length > 0) {
      handleProbe();
    }

    return () => {
      // Cleanup: close any open login window
      if (loginWindowRef && !loginWindowRef.closed) {
        loginWindowRef.close();
      }
    };
  });
</script>

<!-- ======================================================================= -->
<!-- TEMPLATE                                                                -->
<!-- ======================================================================= -->

<div class="fixed inset-0 bg-nb-black/60 backdrop-blur-sm z-[100] flex items-center justify-center p-4">
  <div class="bg-nb-white shadow-brutal-lg max-w-md w-full overflow-hidden border border-nb-black/20">

    <!-- Header -->
    <div class="p-6 border-b">
      <div class="flex items-center gap-3">
        <div class="w-10 h-10 bg-nb-orange/20 flex items-center justify-center text-nb-orange">
          <Icon name="lock" />
        </div>
        <div>
          <h2 class="text-lg font-bold text-nb-black">{serviceLabel}</h2>
          <p class="text-[10px] font-bold uppercase tracking-widest text-nb-black/40">IIIF Authorization Flow 2.0</p>
        </div>
      </div>
    </div>

    <!-- Content -->
    <div class="p-6">

      {#if isProbing}
        <!-- Probing state: CSS spinner + checking message -->
        <div class="flex flex-col items-center py-8">
          <div class="w-12 h-12 border-4 border-nb-black/10 border-t-iiif-blue rounded-full animate-spin mb-4"></div>
          <p class="text-sm text-nb-black/50">Checking access...</p>
        </div>

      {:else if showLoginPrompt && !hasDegradedSubstitute}
        <!-- Unauthenticated prompt state: description + profile-specific instructions -->
        <p class="mb-6 text-nb-black/50">{serviceDescription}</p>

        {#if authProfile === 'active'}
          <div class="bg-nb-blue/10 border border-nb-blue/20 p-4 mb-4">
            <div class="flex items-start gap-3">
              <Icon name="info" class="text-nb-blue mt-0.5" />
              <div class="text-sm text-nb-blue">
                You will be redirected to a login page. After logging in, return here to continue.
              </div>
            </div>
          </div>
        {:else if authProfile === 'kiosk'}
          <div class="bg-nb-green/10 border border-nb-green/20 p-4 mb-4">
            <div class="flex items-start gap-3">
              <Icon name="verified_user" class="text-nb-green mt-0.5" />
              <div class="text-sm text-nb-green">
                Access will be granted automatically based on your network location.
              </div>
            </div>
          </div>
        {:else if authProfile === 'external'}
          <div class="bg-nb-purple/5 border border-nb-purple/10 p-4 mb-4">
            <div class="flex items-start gap-3">
              <Icon name="open_in_new" class="text-nb-purple mt-0.5" />
              <div class="text-sm text-nb-purple">
                Authentication is handled by an external service. You may need to log in separately.
              </div>
            </div>
          </div>
        {/if}

      {:else if showLoginPrompt && hasDegradedSubstitute}
        <!-- Degraded state: restricted access with substitute available -->
        <p class="mb-4 text-nb-black/50">{serviceDescription}</p>

        <div class="bg-nb-orange/10 border border-nb-orange/20 p-4 mb-4">
          <div class="flex items-start gap-3">
            <Icon name="warning" class="text-nb-orange mt-0.5" />
            <div>
              <p class="text-sm font-medium text-nb-orange mb-1">
                Restricted Access
              </p>
              <p class="text-xs text-nb-orange">
                Full access requires authentication. A lower-quality substitute is available.
              </p>
            </div>
          </div>
        </div>

        {#if probeResult?.substitute}
          <div class="border p-3 mb-4">
            <p class="text-xs font-medium mb-1 text-nb-black/50">Available substitute:</p>
            <p class="text-sm font-mono truncate text-nb-black">
              {probeResult.substitute.id}
            </p>
            {#if probeResult.substitute.width && probeResult.substitute.height}
              <p class="text-xs mt-1 text-nb-black/50">
                {probeResult.substitute.width} x {probeResult.substitute.height}
              </p>
            {/if}
          </div>
        {/if}

      {:else if flowState === 'loggingIn'}
        <!-- Logging in state: spinner + waiting message -->
        <div class="flex flex-col items-center py-8">
          <div class="w-12 h-12 border-4 border-nb-black/10 border-t-iiif-blue rounded-full animate-spin mb-4"></div>
          <p class="text-sm text-nb-black/50">
            {authProfile === 'kiosk'
              ? 'Obtaining access...'
              : 'Waiting for authentication...'}
          </p>
        </div>

      {:else if isComplete}
        <!-- Complete state: success icon + message -->
        <div class="flex flex-col items-center py-8">
          <div class="w-16 h-16 bg-nb-green/20 flex items-center justify-center text-nb-green mb-4">
            <Icon name="check_circle" class="text-3xl" />
          </div>
          <p class="text-lg font-semibold text-nb-green">Access Granted</p>
          <p class="text-sm mt-1 text-nb-black/50">You can now view this resource.</p>
        </div>

      {:else if isError}
        <!-- Error state: error details -->
        <div class="bg-nb-red/10 border border-nb-red/30 p-4">
          <div class="flex items-start gap-3">
            <Icon name="error" class="text-nb-red mt-0.5" />
            <div>
              <p class="text-sm font-medium text-nb-red mb-1">
                Authentication Error
              </p>
              <p class="text-xs text-nb-red">
                {errorMessage || 'An error occurred during authentication.'}
              </p>
            </div>
          </div>
        </div>
      {/if}
    </div>

    <!-- Actions -->
    <div class="p-4 border-t flex gap-3 justify-end">
      <Button variant="ghost" size="sm" onclick={handleDismiss}>
        Cancel
      </Button>

      {#if showLoginPrompt && !hasDegradedSubstitute}
        <Button
          variant="primary"
          size="sm"
          onclick={handleLogin}
          disabled={isLoggingIn}
        >
          {#if isLoggingIn}
            Logging in...
          {:else}
            <Icon name="login" class="mr-1" />
            {confirmLabel}
          {/if}
        </Button>
      {/if}

      {#if showLoginPrompt && hasDegradedSubstitute}
        <Button variant="secondary" size="sm" onclick={handleUseDegraded}>
          Use Substitute
        </Button>
        <Button
          variant="primary"
          size="sm"
          onclick={handleLogin}
          disabled={isLoggingIn}
        >
          {#if isLoggingIn}
            Logging in...
          {:else}
            <Icon name="login" class="mr-1" />
            {confirmLabel}
          {/if}
        </Button>
      {/if}

      {#if isComplete}
        <Button variant="primary" size="sm" onclick={() => { onComplete('authenticated'); handleDismiss(); }}>
          Continue
        </Button>
      {/if}

      {#if isError}
        {#if activeServiceIndex < authServices.length - 1}
          <Button variant="secondary" size="sm" onclick={handleTryNextService}>
            Try Another Method
          </Button>
        {/if}
        <Button variant="primary" size="sm" onclick={handleProbe}>
          Retry
        </Button>
      {/if}
    </div>

    <!-- Resource ID reference (subtle) -->
    <div class="px-4 pb-3 text-xs text-nb-black/30 truncate">
      Resource: {resourceId}
    </div>
  </div>
</div>
