// components/PersonaSettings.tsx

import React, { useEffect, useState } from 'react';
import { AbstractionLevel, AppSettings } from '../types';
import { Icon } from './Icon';
import { getFieldsByCategory, getVisibleFields, METADATA_TEMPLATES, MetadataComplexity } from '../constants';
import { guidance } from '../services/guidanceService';

interface PersonaSettingsProps {
  settings: AppSettings;
  onUpdate: (s: Partial<AppSettings>) => void;
  onClose: () => void;
}

export const PersonaSettings: React.FC<PersonaSettingsProps> = ({ settings, onUpdate, onClose }) => {
  // Escape key to close
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose();
      }
    };
    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [onClose]);
  const handlePersonaSelect = (lvl: AbstractionLevel) => {
      let template = METADATA_TEMPLATES.ARCHIVIST;
      let showTechnical = true;
      let fieldMode = false;
      let complexity: MetadataComplexity = 'standard';

      if (lvl === 'simple') {
          template = METADATA_TEMPLATES.RESEARCHER;
          showTechnical = false;
          fieldMode = true;
          complexity = 'simple';
      } else if (lvl === 'advanced') {
          template = METADATA_TEMPLATES.DEVELOPER;
          showTechnical = true;
          fieldMode = false;
          complexity = 'advanced';
      }

      onUpdate({
          abstractionLevel: lvl,
          metadataTemplate: template,
          showTechnicalIds: showTechnical,
          fieldMode,
          metadataComplexity: complexity
      });
  };

  const complexityLevels: { level: MetadataComplexity; label: string; desc: string }[] = [
      { level: 'simple', label: 'Essential', desc: 'Label, summary, thumbnail only' },
      { level: 'standard', label: 'Standard', desc: '+ metadata, rights, navDate' },
      { level: 'advanced', label: 'Full Spec', desc: '+ behaviors, services, structures' }
  ];

  const currentComplexityIndex = complexityLevels.findIndex(c => c.level === settings.metadataComplexity);
  const visibleFieldCount = getVisibleFields(settings.metadataComplexity).length;

  return (
    <div className="fixed inset-0 z-[700] flex items-center justify-center p-4 bg-black/60 backdrop-blur-md">
      <div className="bg-white w-full max-w-xl rounded-2xl shadow-2xl overflow-hidden border border-slate-200 animate-in zoom-in-95 duration-200">
        <div className="p-6 border-b flex justify-between items-center bg-slate-50">
          <div className="flex items-center gap-3">
             <div className="w-10 h-10 bg-slate-800 rounded-xl flex items-center justify-center text-white shadow-xl"><Icon name="psychology"/></div>
             <div>
                <h2 className="text-lg font-black text-slate-800 uppercase tracking-tighter">Studio Persona</h2>
                <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Global Workbench Configuration</p>
             </div>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-slate-200 rounded-full text-slate-400"><Icon name="close"/></button>
        </div>

        <div className="p-8 space-y-8 overflow-y-auto max-h-[70vh] custom-scrollbar">
            <section>
                <label className="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-4">Select Your Role</label>
                <div className="grid grid-cols-1 gap-3">
                    <PersonaOption 
                        icon="travel_explore" title="Field Researcher" 
                        desc="Simplified UI. Focus on GPS, high-contrast field modes, and quick capture." 
                        active={settings.abstractionLevel === 'simple'}
                        onClick={() => handlePersonaSelect('simple')}
                    />
                    <PersonaOption 
                        icon="inventory" title="Digital Archivist" 
                        desc="Standard UI. Emphasis on metadata precision, validation, and batching." 
                        active={settings.abstractionLevel === 'standard'}
                        onClick={() => handlePersonaSelect('standard')}
                    />
                    <PersonaOption 
                        icon="terminal" title="IIIF Developer" 
                        desc="Advanced UI. Raw JSON-LD access, direct ID editing, and Image API workbenches." 
                        active={settings.abstractionLevel === 'advanced'}
                        onClick={() => handlePersonaSelect('advanced')}
                    />
                </div>
            </section>

            <section className="pt-6 border-t border-slate-100">
                <label className="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-4">Affordance Overrides</label>
                <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-1">
                        <span className="text-[9px] font-bold text-slate-500 uppercase">Auto-Save Frequency</span>
                        <select value={settings.autoSaveInterval} onChange={e => onUpdate({ autoSaveInterval: parseInt(e.target.value) })} className="w-full text-xs font-bold p-2 bg-slate-50 border rounded-lg">
                            <option value={30}>Every 30 seconds</option>
                            <option value={60}>Every minute</option>
                            <option value={300}>Every 5 minutes</option>
                        </select>
                    </div>
                    <div className="space-y-1">
                        <span className="text-[9px] font-bold text-slate-500 uppercase">Base Hosting URL</span>
                        <input value={settings.defaultBaseUrl} onChange={e => onUpdate({ defaultBaseUrl: e.target.value })} className="w-full text-xs font-bold p-2 bg-slate-50 border rounded-lg font-mono" placeholder="http://localhost" />
                    </div>
                </div>
            </section>

            <section className="pt-6 border-t border-slate-100">
                <label className="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-4">Metadata Complexity</label>
                <div className="bg-slate-50 rounded-xl border p-4 space-y-4">
                    <div className="flex items-center justify-between">
                        <span className="text-xs font-bold text-slate-700">Field Visibility Level</span>
                        <span className="text-[9px] font-mono bg-iiif-blue/10 text-iiif-blue px-2 py-0.5 rounded-full">{visibleFieldCount} fields</span>
                    </div>

                    {/* Slider Track */}
                    <div className="relative pt-2">
                        <div className="flex justify-between mb-2">
                            {complexityLevels.map((c, idx) => (
                                <button
                                    key={c.level}
                                    onClick={() => onUpdate({ metadataComplexity: c.level })}
                                    className={`text-[9px] font-black uppercase tracking-tight transition-colors ${
                                        settings.metadataComplexity === c.level
                                            ? 'text-iiif-blue'
                                            : 'text-slate-400 hover:text-slate-600'
                                    }`}
                                >
                                    {c.label}
                                </button>
                            ))}
                        </div>

                        {/* Custom Slider */}
                        <div className="relative h-2 bg-slate-200 rounded-full">
                            <div
                                className="absolute h-2 bg-gradient-to-r from-iiif-blue to-blue-400 rounded-full transition-all"
                                style={{ width: `${((currentComplexityIndex + 1) / complexityLevels.length) * 100}%` }}
                            />
                            <input
                                type="range"
                                min="0"
                                max="2"
                                value={currentComplexityIndex}
                                onChange={e => onUpdate({ metadataComplexity: complexityLevels[parseInt(e.target.value)].level })}
                                className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                                aria-label="Metadata complexity level"
                            />
                            {/* Slider Thumb */}
                            <div
                                className="absolute top-1/2 -translate-y-1/2 w-4 h-4 bg-white border-2 border-iiif-blue rounded-full shadow-md transition-all pointer-events-none"
                                style={{ left: `calc(${(currentComplexityIndex / 2) * 100}% - 8px)` }}
                            />
                        </div>

                        {/* Current Level Description */}
                        <p className="text-[10px] text-slate-500 mt-3 text-center">
                            {complexityLevels[currentComplexityIndex]?.desc}
                        </p>
                    </div>

                    {/* Field Preview */}
                    <div className="pt-3 border-t border-slate-200">
                        <span className="text-[9px] font-black text-slate-400 uppercase block mb-2">Visible Fields Preview</span>
                        <div className="flex flex-wrap gap-1">
                            {getVisibleFields(settings.metadataComplexity).slice(0, 8).map(field => (
                                <span key={field.key} className="text-[8px] font-bold bg-white border px-1.5 py-0.5 rounded text-slate-600">
                                    {field.label}
                                </span>
                            ))}
                            {visibleFieldCount > 8 && (
                                <span className="text-[8px] font-bold text-slate-400">+{visibleFieldCount - 8} more</span>
                            )}
                        </div>
                    </div>
                </div>
            </section>

            <section className="pt-6 border-t border-slate-100 space-y-3">
                <div className="flex items-center justify-between p-3 bg-slate-50 rounded-xl border">
                    <div>
                        <span className="text-xs font-bold text-slate-700 block">Technical Transparency</span>
                        <span className="text-[9px] text-slate-400 uppercase font-black">IDs & JSON-LD Visible</span>
                    </div>
                    <input type="checkbox" checked={settings.showTechnicalIds} onChange={e => onUpdate({ showTechnicalIds: e.target.checked })} className="rounded text-iiif-blue w-5 h-5"/>
                </div>
                <div className="flex items-center justify-between p-3 bg-slate-50 rounded-xl border">
                    <div>
                        <span className="text-xs font-bold text-slate-700 block">Field Contrast Mode</span>
                        <span className="text-[9px] text-slate-400 uppercase font-black">Optimized for outdoor use</span>
                    </div>
                    <input type="checkbox" checked={settings.fieldMode} onChange={e => onUpdate({ fieldMode: e.target.checked })} className="rounded text-iiif-blue w-5 h-5"/>
                </div>
            </section>

            <HelpResetSection />
        </div>

        <div className="p-6 bg-slate-50 border-t flex justify-end">
            <button onClick={onClose} className="bg-slate-800 text-white px-10 py-3 rounded-xl font-black uppercase tracking-widest text-xs hover:bg-black transition-all shadow-xl">Commit Environment Profile</button>
        </div>
      </div>
    </div>
  );
};

const PersonaOption: React.FC<{ icon: string, title: string, desc: string, active: boolean, onClick: () => void }> = ({ icon, title, desc, active, onClick }) => (
    <button onClick={onClick} className={`w-full p-4 rounded-xl border-2 text-left transition-all flex items-start gap-4 ${active ? 'border-iiif-blue bg-blue-50 shadow-md' : 'border-slate-100 hover:border-slate-200'}`}>
        <div className={`p-3 rounded-xl ${active ? 'bg-iiif-blue text-white shadow-lg' : 'bg-slate-100 text-slate-400'}`}><Icon name={icon}/></div>
        <div className="flex-1">
            <h4 className={`font-black uppercase tracking-tighter text-sm ${active ? 'text-iiif-blue' : 'text-slate-700'}`}>{title}</h4>
            <p className="text-[10px] text-slate-500 leading-tight mt-1">{desc}</p>
        </div>
        {active && <Icon name="check_circle" className="text-iiif-blue"/>}
    </button>
);

const HelpResetSection: React.FC = () => {
    const [tipCount, setTipCount] = useState(guidance.getSeenCount());
    const [resetConfirm, setResetConfirm] = useState(false);

    const handleReset = () => {
        if (resetConfirm) {
            guidance.reset();
            setTipCount(0);
            setResetConfirm(false);
        } else {
            setResetConfirm(true);
            setTimeout(() => setResetConfirm(false), 3000);
        }
    };

    const handleResetTooltips = () => {
        guidance.resetTooltips();
        setTipCount(guidance.getSeenCount());
    };

    return (
        <section className="pt-6 border-t border-slate-100">
            <label className="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-4">Help & Tooltips</label>
            <div className="bg-slate-50 rounded-xl border p-4 space-y-4">
                <div className="flex items-center justify-between">
                    <div>
                        <span className="text-xs font-bold text-slate-700 block">Contextual Help</span>
                        <span className="text-[9px] text-slate-400">{tipCount} tips dismissed</span>
                    </div>
                    <div className="flex gap-2">
                        <button
                            onClick={handleResetTooltips}
                            className="text-[10px] font-bold text-slate-500 hover:text-slate-700 px-3 py-1.5 rounded-lg hover:bg-slate-100 transition-colors"
                        >
                            Reset Tooltips
                        </button>
                        <button
                            onClick={handleReset}
                            className={`text-[10px] font-bold px-3 py-1.5 rounded-lg transition-colors ${
                                resetConfirm
                                    ? 'bg-red-500 text-white'
                                    : 'text-slate-500 hover:text-slate-700 hover:bg-slate-100'
                            }`}
                        >
                            {resetConfirm ? 'Click to Confirm' : 'Reset All Help'}
                        </button>
                    </div>
                </div>
                <p className="text-[10px] text-slate-400 leading-relaxed">
                    Show all help tooltips and welcome messages again. Useful if you want a refresher on features.
                </p>
            </div>
        </section>
    );
};

// src/widgets/PersonaSettings/ui/PersonaSettings.svelte
<!--
  PersonaSettings - Settings modal with persona/workbench configuration.
  Sections: affordance overrides (autoSave, baseUrl), metadata complexity slider (3 levels),
  technical transparency toggles (IDs, field contrast), admin mode toggle (localStorage),
  help reset section.

  React source: 276 lines -> ~310 lines Svelte (includes inline HelpResetSection)
-->
<script lang="ts">
  import { cn } from '@/src/shared/lib/cn';
  import { Button } from '@/src/shared/ui/atoms';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';
  import { ModalDialog } from '@/src/shared/ui/molecules';
  import type { AppSettings } from '@/src/shared/stores';
  import type { AbstractionLevel as MetadataComplexity } from '@/src/shared/types';
  // STUB: These will be real imports in final implementation
  // import { getVisibleFields, type MetadataComplexity } from '@/src/shared/constants';
  // import { guidance } from '@/src/shared/services/guidanceService';

  // --- Props ---
  interface Props {
    settings: AppSettings;
    onUpdate: (s: Partial<AppSettings>) => void;
    onClose: () => void;
  }

  let { settings, onUpdate, onClose }: Props = $props();

  // --- Types ---
  interface ComplexityLevel {
    level: MetadataComplexity;
    label: string;
    desc: string;
  }

  // --- Static Data ---
  const complexityLevels: ComplexityLevel[] = [
    { level: 'simple', label: 'Essential', desc: 'Label, summary, thumbnail only' },
    { level: 'standard', label: 'Standard', desc: '+ metadata, rights, navDate' },
    { level: 'advanced', label: 'Full Spec', desc: '+ behaviors, services, structures' },
  ];

  // --- Local State ---
  let adminMode: boolean = $state(
    typeof window !== 'undefined'
      ? localStorage.getItem('adminMode') === 'true'
      : false
  );

  // Help reset section state
  let resetConfirm: boolean = $state(false);
  let tipCount: number = $state(0); // STUB: guidance.getSeenCount()

  // --- Derived ---
  let currentComplexityIndex = $derived(
    complexityLevels.findIndex(c => c.level === settings.abstractionLevel)
  );

  // STUB: Replace with real getVisibleFields() call
  let visibleFieldCount = $derived(
    settings.abstractionLevel === 'simple' ? 3 :
    settings.abstractionLevel === 'standard' ? 8 : 15
  );

  // STUB: Replace with real getVisibleFields() call
  let visibleFieldsPreview = $derived<{ key: string; label: string }[]>(
    settings.abstractionLevel === 'simple'
      ? [{ key: 'label', label: 'Label' }, { key: 'summary', label: 'Summary' }, { key: 'thumbnail', label: 'Thumbnail' }]
      : settings.abstractionLevel === 'standard'
        ? [{ key: 'label', label: 'Label' }, { key: 'summary', label: 'Summary' }, { key: 'thumbnail', label: 'Thumbnail' }, { key: 'metadata', label: 'Metadata' }, { key: 'rights', label: 'Rights' }, { key: 'navDate', label: 'NavDate' }, { key: 'requiredStatement', label: 'Required Statement' }, { key: 'provider', label: 'Provider' }]
        : [{ key: 'label', label: 'Label' }, { key: 'summary', label: 'Summary' }, { key: 'thumbnail', label: 'Thumbnail' }, { key: 'metadata', label: 'Metadata' }, { key: 'rights', label: 'Rights' }, { key: 'navDate', label: 'NavDate' }, { key: 'requiredStatement', label: 'Required Statement' }, { key: 'provider', label: 'Provider' }, { key: 'behavior', label: 'Behavior' }]
  );

  let sliderFillWidth = $derived(
    `${((currentComplexityIndex + 1) / complexityLevels.length) * 100}%`
  );

  let sliderThumbLeft = $derived(
    `calc(${(currentComplexityIndex / 2) * 100}% - 8px)`
  );

  // --- Effects ---
  // Escape key to close
  $effect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === 'Escape') {
        onClose();
      }
    }
    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  });

  // --- Handlers ---
  function toggleAdminMode() {
    adminMode = !adminMode;
    if (typeof window !== 'undefined') {
      localStorage.setItem('adminMode', adminMode ? 'true' : 'false');
    }
  }

  function handleComplexitySlider(e: Event) {
    const target = e.target as HTMLInputElement;
    const idx = parseInt(target.value);
    onUpdate({ abstractionLevel: complexityLevels[idx].level });
  }

  function handleHelpReset() {
    if (resetConfirm) {
      // STUB: guidance.reset();
      tipCount = 0;
      resetConfirm = false;
    } else {
      resetConfirm = true;
      setTimeout(() => { resetConfirm = false; }, 3000);
    }
  }

  function handleResetTooltips() {
    // STUB: guidance.resetTooltips();
    // tipCount = guidance.getSeenCount();
    tipCount = 0;
  }
</script>

<!-- Fullscreen modal overlay -->
<div class="fixed inset-0 z-[700] flex items-center justify-center p-4 bg-nb-black/60 backdrop-blur-md">
  <div class="bg-nb-white w-full max-w-xl shadow-brutal-lg overflow-hidden border border-nb-black/20 animate-in zoom-in-95">

    <!-- Header -->
    <div class="p-6 border-b flex justify-between items-center bg-nb-white">
      <div class="flex items-center gap-3">
        <div class="w-10 h-10 bg-nb-black flex items-center justify-center text-white shadow-brutal">
          <Icon name="psychology" />
        </div>
        <div>
          <h2 class="text-lg font-black text-nb-black uppercase tracking-tighter">Studio Persona</h2>
          <p class="text-[10px] font-bold text-nb-black/40 uppercase tracking-widest">Global Workbench Configuration</p>
        </div>
      </div>
      <Button variant="ghost" size="bare" onclick={onClose} class="p-2 hover:bg-nb-cream text-nb-black/40">
        <Icon name="close" />
      </Button>
    </div>

    <!-- Scrollable body -->
    <div class="p-8 space-y-8 overflow-y-auto max-h-[70vh] custom-scrollbar">

      <!-- Section: Affordance Overrides -->
      <section>
        <label class="block text-[10px] font-black text-nb-black/40 uppercase tracking-widest mb-4">Affordance Overrides</label>
        <div class="grid grid-cols-2 gap-4">
          <div class="space-y-1">
            <span class="text-[9px] font-bold text-nb-black/50 uppercase">Auto-Save Frequency</span>
            <select
              value={settings.autoSaveInterval}
              onchange={(e) => onUpdate({ autoSaveInterval: parseInt((e.target as HTMLSelectElement).value) })}
              class="w-full text-xs font-bold p-2 bg-nb-white border"
            >
              <option value={30}>Every 30 seconds</option>
              <option value={60}>Every minute</option>
              <option value={300}>Every 5 minutes</option>
            </select>
          </div>
          <div class="space-y-1">
            <span class="text-[9px] font-bold text-nb-black/50 uppercase">Base Hosting URL</span>
            <input
              value={settings.defaultBaseUrl}
              oninput={(e) => onUpdate({ defaultBaseUrl: (e.target as HTMLInputElement).value })}
              class="w-full text-xs font-bold p-2 bg-nb-white border font-mono"
              placeholder="http://localhost"
            />
          </div>
        </div>
      </section>

      <!-- Section: Metadata Complexity -->
      <section class="pt-6 border-t border-nb-black/10">
        <label class="block text-[10px] font-black text-nb-black/40 uppercase tracking-widest mb-4">Metadata Complexity</label>
        <div class="bg-nb-white border p-4 space-y-4">
          <div class="flex items-center justify-between">
            <span class="text-xs font-bold text-nb-black/80">Field Visibility Level</span>
            <span class="text-[9px] font-mono bg-iiif-blue/10 text-iiif-blue px-2 py-0.5">{visibleFieldCount} fields</span>
          </div>

          <!-- Slider track -->
          <div class="relative pt-2">
            <!-- Level labels -->
            <div class="flex justify-between mb-2">
              {#each complexityLevels as c}
                <Button variant="ghost" size="bare"
                  onclick={() => onUpdate({ abstractionLevel: c.level })}
                  class={cn(
                    'text-[9px] font-black uppercase tracking-tight transition-nb',
                    settings.abstractionLevel === c.level
                      ? 'text-iiif-blue'
                      : 'text-nb-black/40 hover:text-nb-black/60'
                  )}
                >
                  {c.label}
                </Button>
              {/each}
            </div>

            <!-- Custom slider visual -->
            <div class="relative h-2 bg-nb-cream">
              <div
                class="absolute h-2 bg-gradient-to-r from-iiif-blue to-blue-400 transition-nb"
                style:width={sliderFillWidth}
              ></div>
              <input
                type="range"
                min="0"
                max="2"
                value={currentComplexityIndex}
                oninput={handleComplexitySlider}
                class="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                aria-label="Metadata complexity level"
              />
              <!-- Thumb indicator -->
              <div
                class="absolute top-1/2 -translate-y-1/2 w-4 h-4 bg-nb-white border-2 border-iiif-blue shadow-brutal-sm transition-nb pointer-events-none"
                style:left={sliderThumbLeft}
              ></div>
            </div>

            <!-- Level description -->
            <p class="text-[10px] text-nb-black/50 mt-3 text-center">
              {complexityLevels[currentComplexityIndex]?.desc}
            </p>
          </div>

          <!-- Field preview tags -->
          <div class="pt-3 border-t border-nb-black/20">
            <span class="text-[9px] font-black text-nb-black/40 uppercase block mb-2">Visible Fields Preview</span>
            <div class="flex flex-wrap gap-1">
              {#each visibleFieldsPreview.slice(0, 8) as field (field.key)}
                <span class="text-[8px] font-bold bg-nb-white border px-1.5 py-0.5 text-nb-black/60">
                  {field.label}
                </span>
              {/each}
              {#if visibleFieldCount > 8}
                <span class="text-[8px] font-bold text-nb-black/40">+{visibleFieldCount - 8} more</span>
              {/if}
            </div>
          </div>
        </div>
      </section>

      <!-- Section: Technical Transparency Toggles -->
      <section class="pt-6 border-t border-nb-black/10 space-y-3">
        <div class="flex items-center justify-between p-3 bg-nb-white border">
          <div>
            <span class="text-xs font-bold text-nb-black/80 block">Technical Transparency</span>
            <span class="text-[9px] text-nb-black/40 uppercase font-black">IDs & JSON-LD Visible</span>
          </div>
          <input
            type="checkbox"
            checked={settings.showTechnicalIds}
            onchange={(e) => onUpdate({ showTechnicalIds: (e.target as HTMLInputElement).checked })}
            class="text-iiif-blue w-5 h-5"
          />
        </div>
        <div class="flex items-center justify-between p-3 bg-nb-white border">
          <div>
            <span class="text-xs font-bold text-nb-black/80 block">Field Contrast Mode</span>
            <span class="text-[9px] text-nb-black/40 uppercase font-black">Optimized for outdoor use</span>
          </div>
          <input
            type="checkbox"
            checked={settings.fieldMode}
            onchange={(e) => onUpdate({ fieldMode: (e.target as HTMLInputElement).checked })}
            class="text-iiif-blue w-5 h-5"
          />
        </div>
      </section>

      <!-- Section: Developer Tools / Admin Mode -->
      <section class="pt-6 border-t border-nb-black/10 space-y-3">
        <label class="block text-[10px] font-black text-nb-black/40 uppercase tracking-widest mb-4">Developer Tools</label>
        <div class={cn(
          'flex items-center justify-between p-3 border transition-nb',
          adminMode ? 'bg-nb-purple/5 border-nb-purple/20' : 'bg-nb-white border-nb-black/20'
        )}>
          <div class="flex items-center gap-3">
            <div class={cn('p-2', adminMode ? 'bg-nb-purple text-white' : 'bg-nb-cream text-nb-black/50')}>
              <Icon name="admin_panel_settings" />
            </div>
            <div>
              <span class={cn('text-xs font-bold block', adminMode ? 'text-nb-purple' : 'text-nb-black/80')}>Admin Mode</span>
              <span class="text-[9px] text-nb-black/40 uppercase font-black">Access dependency explorer & tools</span>
            </div>
          </div>
          <input
            type="checkbox"
            checked={adminMode}
            onchange={toggleAdminMode}
            class="text-nb-purple w-5 h-5"
          />
        </div>
        {#if adminMode}
          <div class="p-3 bg-nb-purple/5 border border-nb-purple/10">
            <p class="text-[10px] text-nb-purple mb-2">Admin mode is enabled. You can now access:</p>
            <ul class="text-[10px] text-nb-purple space-y-1">
              <li class="flex items-center gap-1">
                <Icon name="account_tree" class="text-xs" />
                Dependency Explorer (Cmd+K &rarr; "Dependency Explorer")
              </li>
            </ul>
          </div>
        {/if}
      </section>

      <!-- Section: Help & Tooltips (inline, was HelpResetSection sub-component) -->
      <section class="pt-6 border-t border-nb-black/10">
        <label class="block text-[10px] font-black text-nb-black/40 uppercase tracking-widest mb-4">Help & Tooltips</label>
        <div class="bg-nb-white border p-4 space-y-4">
          <div class="flex items-center justify-between">
            <div>
              <span class="text-xs font-bold text-nb-black/80 block">Contextual Help</span>
              <span class="text-[9px] text-nb-black/40">{tipCount} tips dismissed</span>
            </div>
            <div class="flex gap-2">
              <Button variant="ghost" size="bare"
                onclick={handleResetTooltips}
                class="text-[10px] font-bold text-nb-black/50 hover:text-nb-black/80 px-3 py-1.5 hover:bg-nb-cream transition-nb"
              >
                Reset Tooltips
              </Button>
              <Button variant="ghost" size="bare"
                onclick={handleHelpReset}
                class={cn(
                  'text-[10px] font-bold px-3 py-1.5 transition-nb',
                  resetConfirm
                    ? 'bg-nb-red text-white'
                    : 'text-nb-black/50 hover:text-nb-black/80 hover:bg-nb-cream'
                )}
              >
                {resetConfirm ? 'Click to Confirm' : 'Reset All Help'}
              </Button>
            </div>
          </div>
          <p class="text-[10px] text-nb-black/40 leading-relaxed">
            Show all help tooltips and welcome messages again. Useful if you want a refresher on features.
          </p>
        </div>
      </section>
    </div>

    <!-- Footer -->
    <div class="p-6 bg-nb-white border-t flex justify-end">
      <Button variant="ghost" size="bare"
        onclick={onClose}
        class="bg-nb-black text-white px-10 py-3 font-black uppercase tracking-widest text-xs hover:bg-nb-black transition-nb shadow-brutal"
      >
        Commit Environment Profile
      </Button>
    </div>
  </div>
</div>
