// components/views/MapView.tsx

import React, { useMemo, useState, useRef, useEffect } from 'react';
import { IIIFItem, IIIFCanvas, isCanvas, getIIIFValue } from '../../types';
import { Icon } from '../Icon';
import { useAppSettings } from '../../hooks/useAppSettings';
import { useContextualStyles } from '../../hooks/useContextualStyles';
import { useTerminology } from '../../hooks/useTerminology';

interface MapViewProps {
  root: IIIFItem | null;
  onSelect: (item: IIIFItem) => void;
}

interface GeoItem {
  canvas: IIIFCanvas;
  lat: number;
  lng: number;
}

interface MapBounds {
  minLat: number;
  maxLat: number;
  minLng: number;
  maxLng: number;
}

export const MapView: React.FC<MapViewProps> = ({ root, onSelect }) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [dimensions, setDimensions] = useState({ width: 800, height: 600 });
  const [hoveredItem, setHoveredItem] = useState<GeoItem | null>(null);
  const [selectedCluster, setSelectedCluster] = useState<GeoItem[] | null>(null);
  const [zoom, setZoom] = useState(1);
  const [pan, setPan] = useState({ x: 0, y: 0 });

  const { settings } = useAppSettings();
  const fieldMode = settings.fieldMode;
  const cx = useContextualStyles(fieldMode);
  const { t, isAdvanced } = useTerminology({ level: settings.abstractionLevel });

  useEffect(() => {
    const updateDimensions = () => {
      if (containerRef.current) {
        setDimensions({
          width: containerRef.current.clientWidth,
          height: containerRef.current.clientHeight
        });
      }
    };
    updateDimensions();
    window.addEventListener('resize', updateDimensions);
    return () => window.removeEventListener('resize', updateDimensions);
  }, []);

  const { geoItems, bounds, clusters } = useMemo(() => {
    if (!root) return { geoItems: [], bounds: null, clusters: [] };

    const items: GeoItem[] = [];
    const traverse = (item: IIIFItem) => {
      if (isCanvas(item)) {
        const canvas = item as IIIFCanvas;
        const locMeta = canvas.metadata?.find(m =>
          getIIIFValue(m.label, 'en')?.toLowerCase() === 'location' ||
          getIIIFValue(m.label, 'en')?.toLowerCase() === 'gps'
        );

        if (locMeta) {
          const locValue = getIIIFValue(locMeta.value, 'en');
          if (locValue) {
            const coords = parseCoordinates(locValue);
            if (coords) {
              items.push({ canvas, lat: coords.lat, lng: coords.lng });
            }
          }
        }
      }
      if (item.items) {
        item.items.forEach(traverse);
      }
    };
    traverse(root);

    if (items.length === 0) return { geoItems: [], bounds: null, clusters: [] };

    // Calculate bounds
    const bounds: MapBounds = {
      minLat: Math.min(...items.map(i => i.lat)),
      maxLat: Math.max(...items.map(i => i.lat)),
      minLng: Math.min(...items.map(i => i.lng)),
      maxLng: Math.max(...items.map(i => i.lng))
    };

    // Add padding to bounds
    const latPad = (bounds.maxLat - bounds.minLat) * 0.1 || 0.01;
    const lngPad = (bounds.maxLng - bounds.minLng) * 0.1 || 0.01;
    bounds.minLat -= latPad;
    bounds.maxLat += latPad;
    bounds.minLng -= lngPad;
    bounds.maxLng += lngPad;

    // Simple clustering based on pixel proximity
    const clusters = clusterItems(items, bounds, dimensions, zoom);

    return { geoItems: items, bounds, clusters };
  }, [root, dimensions, zoom]);

  const geoToPixel = (lat: number, lng: number): { x: number; y: number } => {
    if (!bounds) return { x: 0, y: 0 };

    const latRange = bounds.maxLat - bounds.minLat;
    const lngRange = bounds.maxLng - bounds.minLng;

    const x = ((lng - bounds.minLng) / lngRange) * dimensions.width * zoom + pan.x;
    const y = ((bounds.maxLat - lat) / latRange) * dimensions.height * zoom + pan.y;

    return { x, y };
  };

  if (!root || geoItems.length === 0) {
    return (
      <div className={`flex-1 flex flex-col items-center justify-center ${fieldMode ? 'bg-black text-white' : 'bg-slate-50 text-slate-400'} p-8`}>
        <Icon name="map" className={`text-6xl mb-4 ${fieldMode ? 'text-slate-500' : 'text-slate-300'}`} />
        <p className="text-lg font-medium">No Geotagged Items</p>
        <p className="text-sm mt-2">Items need GPS coordinates in their metadata to appear on the map.</p>
        <p className={`text-xs mt-4 ${fieldMode ? 'text-slate-500' : 'text-slate-400'}`}>
          Add a "Location" metadata field with coordinates like "40.7128, -74.0060"
        </p>
      </div>
    );
  }

  return (
    <div className={`flex flex-col h-full ${fieldMode ? 'bg-black' : 'bg-slate-200'}`}>
      {/* Header */}
      <div className={`h-14 ${cx.headerBg} ${cx.border} flex items-center justify-between px-6 shadow-sm`}>
        <div className="flex items-center gap-4">
          <h2 className={`font-bold ${cx.text} flex items-center gap-2`}>
            <Icon name="map" className="text-green-500" />
            Map View
          </h2>
          <span className={`text-sm ${cx.textMuted}`}>{geoItems.length} geotagged items</span>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => setZoom(z => Math.max(0.5, z - 0.25))}
            className={`p-2 rounded ${fieldMode ? 'hover:bg-slate-800' : 'hover:bg-slate-100'}`}
          >
            <Icon name="remove" />
          </button>
          <span className={`text-sm ${cx.textMuted} w-16 text-center`}>{Math.round(zoom * 100)}%</span>
          <button
            onClick={() => setZoom(z => Math.min(4, z + 0.25))}
            className={`p-2 rounded ${fieldMode ? 'hover:bg-slate-800' : 'hover:bg-slate-100'}`}
          >
            <Icon name="add" />
          </button>
          <button
            onClick={() => { setZoom(1); setPan({ x: 0, y: 0 }); }}
            className={`p-2 rounded ml-2 ${fieldMode ? 'hover:bg-slate-800' : 'hover:bg-slate-100'}`}
            title="Reset view"
          >
            <Icon name="center_focus_strong" />
          </button>
        </div>
      </div>

      {/* Map Container */}
      <div
        ref={containerRef}
        className="flex-1 relative overflow-hidden bg-gradient-to-b from-blue-100 to-green-100"
        style={{
          backgroundImage: `
            linear-gradient(rgba(100,150,200,0.1) 1px, transparent 1px),
            linear-gradient(90deg, rgba(100,150,200,0.1) 1px, transparent 1px)
          `,
          backgroundSize: `${50 * zoom}px ${50 * zoom}px`
        }}
      >
        {/* Markers */}
        {clusters.map((cluster, idx) => {
          const pos = geoToPixel(cluster.lat, cluster.lng);
          const isCluster = cluster.items.length > 1;

          return (
            <div
              key={idx}
              className={`absolute transform -translate-x-1/2 -translate-y-full cursor-pointer transition-transform hover:scale-110 z-10 ${
                hoveredItem && cluster.items.includes(hoveredItem) ? 'scale-125 z-20' : ''
              }`}
              style={{ left: pos.x, top: pos.y }}
              onMouseEnter={() => setHoveredItem(cluster.items[0])}
              onMouseLeave={() => setHoveredItem(null)}
              onClick={() => {
                if (isCluster) {
                  setSelectedCluster(cluster.items);
                } else {
                  onSelect(cluster.items[0].canvas);
                }
              }}
            >
              {/* Pin */}
              <div className={`relative ${isCluster ? 'w-10 h-10' : 'w-8 h-10'}`}>
                <svg viewBox="0 0 24 32" className="w-full h-full drop-shadow-lg">
                  <path
                    d="M12 0C5.4 0 0 5.4 0 12c0 9 12 20 12 20s12-11 12-20c0-6.6-5.4-12-12-12z"
                    fill={isCluster ? '#ef4444' : '#3b82f6'}
                  />
                  <circle cx="12" cy="12" r="6" fill="white" />
                </svg>
                {isCluster ? (
                  <span className="absolute inset-0 flex items-center justify-center text-xs font-bold text-red-600 -mt-2">
                    {cluster.items.length}
                  </span>
                ) : cluster.items[0].canvas._blobUrl ? (
                  <img
                    src={cluster.items[0].canvas._blobUrl}
                    className="absolute top-1 left-1 w-6 h-6 rounded-full object-cover border-2 border-white"
                  />
                ) : (
                  <Icon name="image" className="absolute top-2 left-2 text-blue-600 text-xs" />
                )}
              </div>
            </div>
          );
        })}

        {/* Hover tooltip */}
        {hoveredItem && !selectedCluster && (
          <div
            className={`absolute ${fieldMode ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-200'} rounded-lg shadow-xl border p-2 z-30 pointer-events-none`}
            style={{
              left: geoToPixel(hoveredItem.lat, hoveredItem.lng).x + 20,
              top: geoToPixel(hoveredItem.lat, hoveredItem.lng).y - 20
            }}
          >
            <div className="flex gap-2 items-center">
              {hoveredItem.canvas._blobUrl && (
                <img src={hoveredItem.canvas._blobUrl} className="w-12 h-12 rounded object-cover" />
              )}
              <div>
                <div className="font-bold text-sm text-slate-800">
                  {getIIIFValue(hoveredItem.canvas.label, 'none') || 'Untitled'}
                </div>
                {isAdvanced && (
                  <div className="text-xs text-slate-500">
                    {hoveredItem.lat.toFixed(4)}, {hoveredItem.lng.toFixed(4)}
                  </div>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Cluster popup */}
        {selectedCluster && (
          <div className="absolute inset-0 bg-black/30 z-40 flex items-center justify-center p-8">
            <div className={`${fieldMode ? 'bg-slate-900 border-slate-800' : 'bg-white'} rounded-xl shadow-2xl max-w-2xl w-full max-h-[80vh] overflow-hidden`}>
              <div className="p-4 border-b flex justify-between items-center">
                <h3 className={`font-bold ${cx.text}`}>
                  {selectedCluster.length} items at this location
                </h3>
                <button onClick={() => setSelectedCluster(null)} className="text-slate-400 hover:text-slate-600">
                  <Icon name="close" />
                </button>
              </div>
              <div className="p-4 overflow-y-auto max-h-[60vh] grid grid-cols-3 gap-3">
                {selectedCluster.map(item => (
                  <div
                    key={item.canvas.id}
                    className="bg-slate-50 rounded-lg overflow-hidden cursor-pointer hover:ring-2 ring-blue-500 transition-all"
                    onClick={() => { setSelectedCluster(null); onSelect(item.canvas); }}
                  >
                    <div className="aspect-square bg-slate-200">
                      {item.canvas._blobUrl ? (
                        <img src={item.canvas._blobUrl} className="w-full h-full object-cover" />
                      ) : (
                        <div className="w-full h-full flex items-center justify-center">
                          <Icon name="image" className="text-slate-400 text-3xl" />
                        </div>
                      )}
                    </div>
                    <div className="p-2">
                      <div className="text-xs font-medium text-slate-700 truncate">
                        {getIIIFValue(item.canvas.label, 'none') || 'Untitled'}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Coordinates display - only for advanced users */}
        {bounds && isAdvanced && (
          <div className="absolute bottom-4 left-4 bg-white/90 backdrop-blur rounded px-3 py-1 text-xs text-slate-600">
            Bounds: {bounds.minLat.toFixed(2)}°, {bounds.minLng.toFixed(2)}° to {bounds.maxLat.toFixed(2)}°, {bounds.maxLng.toFixed(2)}°
          </div>
        )}
      </div>
    </div>
  );
};

function parseCoordinates(str: string): { lat: number; lng: number } | null {
  // Try various formats
  // "40.7128, -74.0060"
  // "40.7128°N, 74.0060°W"
  // "40° 42' 46" N, 74° 0' 22" W"

  // Simple decimal format
  const decimalMatch = str.match(/(-?\d+\.?\d*)\s*[,\s]\s*(-?\d+\.?\d*)/);
  if (decimalMatch) {
    const lat = parseFloat(decimalMatch[1]);
    const lng = parseFloat(decimalMatch[2]);
    if (!isNaN(lat) && !isNaN(lng) && Math.abs(lat) <= 90 && Math.abs(lng) <= 180) {
      return { lat, lng };
    }
  }

  // Degree format with N/S/E/W
  const degreeMatch = str.match(/(\d+\.?\d*)\s*°?\s*([NS])?\s*[,\s]\s*(\d+\.?\d*)\s*°?\s*([EW])?/i);
  if (degreeMatch) {
    let lat = parseFloat(degreeMatch[1]);
    let lng = parseFloat(degreeMatch[3]);
    if (degreeMatch[2]?.toUpperCase() === 'S') lat = -lat;
    if (degreeMatch[4]?.toUpperCase() === 'W') lng = -lng;
    if (!isNaN(lat) && !isNaN(lng)) {
      return { lat, lng };
    }
  }

  return null;
}

interface Cluster {
  lat: number;
  lng: number;
  items: GeoItem[];
}

function clusterItems(items: GeoItem[], bounds: MapBounds, dimensions: { width: number; height: number }, zoom: number): Cluster[] {
  const clusterRadius = 40; // pixels
  const clusters: Cluster[] = [];

  const latRange = bounds.maxLat - bounds.minLat;
  const lngRange = bounds.maxLng - bounds.minLng;

  const getPixel = (item: GeoItem) => ({
    x: ((item.lng - bounds.minLng) / lngRange) * dimensions.width * zoom,
    y: ((bounds.maxLat - item.lat) / latRange) * dimensions.height * zoom
  });

  for (const item of items) {
    const pos = getPixel(item);
    let addedToCluster = false;

    for (const cluster of clusters) {
      const clusterPos = getPixel({ lat: cluster.lat, lng: cluster.lng } as GeoItem);
      const dist = Math.sqrt(Math.pow(pos.x - clusterPos.x, 2) + Math.pow(pos.y - clusterPos.y, 2));

      if (dist < clusterRadius) {
        cluster.items.push(item);
        // Update cluster center
        cluster.lat = cluster.items.reduce((sum, i) => sum + i.lat, 0) / cluster.items.length;
        cluster.lng = cluster.items.reduce((sum, i) => sum + i.lng, 0) / cluster.items.length;
        addedToCluster = true;
        break;
      }
    }

    if (!addedToCluster) {
      clusters.push({ lat: item.lat, lng: item.lng, items: [item] });
    }
  }

  return clusters;
}

// src/features/map/ui/organisms/MapView.svelte
<!--
  MapView.svelte — Geographic Map View
  ======================================
  React source: src/features/map/ui/organisms/MapView.tsx

  ARCHITECTURE:
  - Feature organism: Geotagged canvas display with clustering
  - Uses PaneLayout with variant="canvas" (overflow-hidden)
  - Map rendering is custom (pixel-positioned markers via geoToPixel)
  - No external map library — pure CSS/div positioning

  PROPS:
  - root: IIIFItem — IIIF tree
  - cx: ContextualClassNames
  - fieldMode: boolean
  - t: TerminologyFn
  - isAdvanced: boolean
  - onSelect: (item: IIIFItem) => void
  - onSwitchView: (mode: string) => void
-->

<script lang="ts">
  import { PaneLayout, Row } from '@/src/shared/ui/layout';
  import ViewHeader from '@/src/shared/ui/molecules/ViewHeader/ViewHeader.svelte';
  import type { ContextualClassNames } from '@/src/shared/ui/molecules/ViewHeader/types';
  import Center from '@/src/shared/ui/layout/primitives/Center.svelte';
  import Button from '@/src/shared/ui/atoms/Button.svelte';
  import { cn } from '@/src/shared/lib/cn';
  import { MapStore } from '@/src/features/map/stores/map.svelte';
  import type { GeoItem, Cluster } from '@/src/features/map/stores/map.svelte';
  import type { IIIFItem } from '@/src/shared/types';
  import { getIIIFValue } from '@/src/shared/types';

  interface Props {
    root: IIIFItem;
    cx: ContextualClassNames;
    fieldMode: boolean;
    t: (key: string, fallback?: string) => string;
    isAdvanced: boolean;
    onSelect: (item: IIIFItem) => void;
    onSwitchView: (mode: string) => void;
  }

  let { root, cx, fieldMode, t, isAdvanced, onSelect, onSwitchView }: Props = $props();

  // ── Feature Store ──
  const map = new MapStore();

  // ── Local State ──
  let containerEl = $state<HTMLDivElement | undefined>(undefined);
  let containerWidth = $state(800);
  let containerHeight = $state(600);

  // ── Derived ──
  const hasItems = $derived(map.hasGeoData);
  const clusters = $derived(map.clusters);
  const geoItems = $derived(map.geoItems);
  const hoveredId = $derived(map.hoveredItemId);
  const selectedClusterId = $derived(map.selectedClusterId);

  // Find the hovered geo item for tooltip rendering
  const hoveredGeoItem = $derived(
    hoveredId ? geoItems.find((g) => g.id === hoveredId) ?? null : null
  );

  // Find the selected cluster for popup rendering
  const selectedCluster = $derived(
    selectedClusterId ? clusters.find((c) => c.id === selectedClusterId) ?? null : null
  );

  // ── Effects ──

  // Initialize map store from root's items (canvases with metadata)
  $effect(() => {
    // @migration: root.items may be canvases or manifests; extract canvas-level metadata
    const items = root.items ?? [];
    const canvases = items
      .filter((item: IIIFItem) => item.type === 'Canvas' || item.type === 'Manifest')
      .flatMap((item: IIIFItem) => {
        if (item.type === 'Canvas') return [item];
        // For manifests, extract their child canvases
        return item.items ?? [];
      })
      .map((canvas: IIIFItem) => ({
        id: canvas.id,
        label: getIIIFValue(canvas.label) || canvas.id,
        metadata: canvas.metadata?.map((m) => ({
          label: getIIIFValue(m.label),
          value: getIIIFValue(m.value),
        })),
      }));

    map.loadFromManifest(canvases);
  });

  // Observe container size for pixel projection accuracy
  $effect(() => {
    const el = containerEl;
    if (!el) return;

    const observer = new ResizeObserver((entries) => {
      for (const entry of entries) {
        containerWidth = entry.contentRect.width;
        containerHeight = entry.contentRect.height;
      }
    });
    observer.observe(el);
    return () => observer.disconnect();
  });

  // ── Handlers ──
  function handleClusterClick(cluster: Cluster): void {
    if (cluster.items.length === 1) {
      // Single-item cluster: select directly
      onSelect({ id: cluster.items[0].canvasId, type: 'Canvas' } as IIIFItem);
    } else {
      map.selectCluster(cluster.id);
    }
  }

  function handleMarkerClick(item: GeoItem): void {
    onSelect({ id: item.canvasId, type: 'Canvas' } as IIIFItem);
  }

  function handleMarkerHover(item: GeoItem | null): void {
    map.setHoveredItem(item?.id ?? null);
  }

  function handleClusterItemClick(item: GeoItem): void {
    map.selectCluster(null);
    onSelect({ id: item.canvasId, type: 'Canvas' } as IIIFItem);
  }

  function handleZoomIn(): void {
    map.zoomIn();
  }

  function handleZoomOut(): void {
    map.zoomOut();
  }

  function handleResetView(): void {
    map.resetView();
  }

  function dismissClusterPopup(): void {
    map.selectCluster(null);
  }

  // ── Panning via pointer drag ──
  let isPanning = $state(false);
  let panStartX = $state(0);
  let panStartY = $state(0);
  let panOriginX = $state(0);
  let panOriginY = $state(0);

  function handlePointerDown(e: PointerEvent): void {
    // Only initiate pan on the background (not markers/clusters)
    if ((e.target as HTMLElement).closest('[data-marker], [data-cluster], [data-popup]')) return;
    isPanning = true;
    panStartX = e.clientX;
    panStartY = e.clientY;
    panOriginX = map.panX;
    panOriginY = map.panY;
    (e.target as HTMLElement).setPointerCapture?.(e.pointerId);
  }

  function handlePointerMove(e: PointerEvent): void {
    if (!isPanning) return;
    const dx = e.clientX - panStartX;
    const dy = e.clientY - panStartY;
    map.setPan(panOriginX + dx, panOriginY + dy);
  }

  function handlePointerUp(): void {
    isPanning = false;
  }
</script>

<PaneLayout variant="canvas">
  {#snippet header()}
    <ViewHeader {cx}>
      {#snippet title()}
        <span class={cn('font-mono uppercase text-sm font-semibold', cx.text)}>
          {t('map', 'Map')}
        </span>
        {#if hasItems}
          <span class={cn(
            'ml-2 px-1.5 py-0.5 rounded text-xs font-bold',
            cx.accent || 'bg-nb-black text-nb-white'
          )}>
            {map.itemCount}
          </span>
        {/if}
      {/snippet}

      {#snippet actions()}
        <Row gap="xs">
          <Button
            variant="ghost"
            size="sm"
            onclick={handleZoomIn}
            aria-label={t('zoomIn', 'Zoom in')}
          >
            +
          </Button>
          <Button
            variant="ghost"
            size="sm"
            onclick={handleResetView}
            aria-label={t('resetZoom', 'Reset zoom')}
          >
            {t('reset', 'Reset')}
          </Button>
          <Button
            variant="ghost"
            size="sm"
            onclick={handleZoomOut}
            aria-label={t('zoomOut', 'Zoom out')}
          >
            &minus;
          </Button>
        </Row>
      {/snippet}
    </ViewHeader>
  {/snippet}

  {#snippet body()}
    {#if !hasItems}
      <Center flex class="h-full">
        <div class={cn('text-center p-8', cx.textMuted || 'text-nb-black/50')}>
          <div class="text-4xl mb-4" aria-hidden="true">&#x1f5fa;</div>
          <p class="text-lg font-medium">{t('noGeoItems', 'No geotagged items')}</p>
          <p class="text-sm mt-2">
            {t('noGeoItemsHint', 'Add GPS coordinates to canvas metadata to see them on the map.')}
          </p>
        </div>
      </Center>
    {:else}
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <div
        bind:this={containerEl}
        class={cn(
          'h-full w-full relative select-none',
          isPanning ? 'cursor-grabbing' : 'cursor-grab'
        )}
        style="background: radial-gradient(circle at 30% 40%, rgba(0, 85, 255, 0.08) 0%, transparent 60%),
               radial-gradient(circle at 70% 60%, rgba(0, 204, 102, 0.06) 0%, transparent 50%),
               linear-gradient(135deg, {fieldMode ? '#1a1a00' : '#f8f6f0'} 0%, {fieldMode ? '#0d0d00' : '#eee8d5'} 100%);"
        role="img"
        aria-label={t('mapAria', 'Geographic map of geotagged items')}
        onpointerdown={handlePointerDown}
        onpointermove={handlePointerMove}
        onpointerup={handlePointerUp}
        onpointercancel={handlePointerUp}
      >
        <!-- Grid pattern overlay -->
        <div
          class="absolute inset-0 pointer-events-none opacity-10"
          style="background-image:
            linear-gradient(rgba(0,0,0,0.1) 1px, transparent 1px),
            linear-gradient(90deg, rgba(0,0,0,0.1) 1px, transparent 1px);
            background-size: {40 * map.zoom}px {40 * map.zoom}px;
            background-position: {map.panX}px {map.panY}px;"
          aria-hidden="true"
        ></div>

        <!-- Cluster badges: circles with item counts -->
        {#each clusters as cluster (cluster.id)}
          {#if cluster.items.length > 1}
            {@const pos = map.geoToPixel(cluster.centerLat, cluster.centerLng, containerWidth, containerHeight)}
            {@const size = Math.min(24 + cluster.items.length * 4, 56)}
            <button
              data-cluster
              class={cn(
                'absolute rounded-full flex items-center justify-center font-mono font-bold text-xs',
                'border-2 transition-transform hover:scale-110 z-10',
                cx.accent || 'bg-nb-black text-nb-white border-nb-black',
                selectedClusterId === cluster.id && 'ring-2 ring-offset-2 ring-blue-500 scale-110'
              )}
              style="left: {pos.x}px; top: {pos.y}px; transform: translate(-50%, -50%); width: {size}px; height: {size}px;"
              onclick={() => handleClusterClick(cluster)}
              aria-label="{cluster.items.length} {t('itemsInCluster', 'items in this area')}"
            >
              {cluster.items.length}
            </button>
          {/if}
        {/each}

        <!-- Individual markers (single-item clusters or all items if no clustering overlap) -->
        {#each clusters as cluster (cluster.id)}
          {#if cluster.items.length === 1}
            {@const item = cluster.items[0]}
            {@const pos = map.geoToPixel(item.lat, item.lng, containerWidth, containerHeight)}
            <button
              data-marker
              class={cn(
                'absolute w-8 h-8 rounded-full overflow-hidden border-2',
                'transition-all hover:scale-125 hover:z-20 z-10',
                hoveredId === item.id ? 'scale-125 z-20 ring-2 ring-blue-500' : '',
                cx.border || 'border-nb-black',
                cx.surface || 'bg-nb-white'
              )}
              style="left: {pos.x}px; top: {pos.y}px; transform: translate(-50%, -50%);"
              onclick={() => handleMarkerClick(item)}
              onmouseenter={() => handleMarkerHover(item)}
              onmouseleave={() => handleMarkerHover(null)}
              onfocus={() => handleMarkerHover(item)}
              onblur={() => handleMarkerHover(null)}
              aria-label="{item.label} ({map.formatCoordinates(item.lat, item.lng)})"
            >
              <!-- @migration: thumbnail URL would come from canvas thumbnail resolution -->
              <div
                class={cn('w-full h-full flex items-center justify-center text-xs font-bold', cx.accent || 'bg-nb-cream text-nb-black')}
                aria-hidden="true"
              >
                {item.label.charAt(0).toUpperCase()}
              </div>
            </button>
          {/if}
        {/each}

        <!-- Hover tooltip -->
        {#if hoveredGeoItem}
          {@const pos = map.geoToPixel(hoveredGeoItem.lat, hoveredGeoItem.lng, containerWidth, containerHeight)}
          <div
            class={cn(
              'absolute z-50 px-3 py-2 rounded shadow-lg pointer-events-none',
              'border-2 max-w-[200px]',
              cx.surface || 'bg-nb-white',
              cx.border || 'border-nb-black'
            )}
            style="left: {pos.x + 24}px; top: {pos.y - 12}px;"
            role="tooltip"
          >
            <p class={cn('text-sm font-semibold truncate', cx.text || 'text-nb-black')}>
              {hoveredGeoItem.label}
            </p>
            {#if isAdvanced}
              <p class={cn('text-xs mt-0.5', cx.textMuted || 'text-nb-black/50')}>
                {map.formatCoordinates(hoveredGeoItem.lat, hoveredGeoItem.lng)}
              </p>
            {/if}
          </div>
        {/if}

        <!-- Cluster popup (expanded grid of items) -->
        {#if selectedCluster}
          <!-- svelte-ignore a11y_no_static_element_interactions -->
          <div
            data-popup
            class={cn(
              'absolute z-50 p-4 rounded-lg shadow-xl border-2 max-w-[320px]',
              cx.surface || 'bg-nb-white',
              cx.border || 'border-nb-black'
            )}
            style="left: 50%; top: 50%; transform: translate(-50%, -50%);"
            role="dialog"
            aria-label="{selectedCluster.items.length} {t('clusteredItems', 'clustered items')}"
            onkeydown={(e) => { if (e.key === 'Escape') dismissClusterPopup(); }}
          >
            <div class="flex items-center justify-between mb-3">
              <span class={cn('text-sm font-bold', cx.text || 'text-nb-black')}>
                {selectedCluster.items.length} {t('items', 'items')}
              </span>
              <Button
                variant="ghost"
                size="bare"
                onclick={dismissClusterPopup}
                aria-label={t('closeCluster', 'Close cluster popup')}
                class="text-lg leading-none"
              >
                &#x2715;
              </Button>
            </div>
            <div class="grid grid-cols-3 gap-2 max-h-[240px] overflow-y-auto">
              {#each selectedCluster.items as item (item.id)}
                <button
                  class={cn(
                    'rounded overflow-hidden border-2 transition-colors hover:border-blue-500',
                    cx.border || 'border-nb-black/20'
                  )}
                  onclick={() => handleClusterItemClick(item)}
                  aria-label={item.label}
                >
                  <div
                    class={cn('w-full aspect-square flex items-center justify-center text-sm font-bold', cx.accent || 'bg-nb-cream text-nb-black')}
                  >
                    {item.label.charAt(0).toUpperCase()}
                  </div>
                  <p class={cn('text-[10px] p-1 truncate text-center', cx.textMuted || 'text-nb-black/60')}>
                    {item.label}
                  </p>
                </button>
              {/each}
            </div>
          </div>
        {/if}

        <!-- Coordinates / bounds display (advanced mode) -->
        {#if isAdvanced && map.bounds}
          <div
            class={cn(
              'absolute bottom-2 left-2 text-[10px] font-mono px-2 py-1 rounded border',
              cx.surface || 'bg-nb-white/90',
              cx.border || 'border-nb-black/20',
              cx.textMuted || 'text-nb-black/60'
            )}
            aria-live="polite"
          >
            <span>{t('bounds', 'Bounds')}: {map.formatBounds()}</span>
            <span class="ml-2">{t('zoom', 'Zoom')}: {map.zoom.toFixed(1)}x</span>
          </div>
        {/if}

        <!-- Zoom level indicator (bottom right) -->
        <div
          class={cn(
            'absolute bottom-2 right-2 text-[10px] font-mono px-2 py-1 rounded border',
            cx.surface || 'bg-nb-white/90',
            cx.border || 'border-nb-black/20',
            cx.textMuted || 'text-nb-black/60'
          )}
          aria-hidden="true"
        >
          {map.itemCount} {t('points', 'points')}
        </div>
      </div>
    {/if}
  {/snippet}
</PaneLayout>
