// src/widgets/ContextualHelp/ui/ContextualHelp.svelte
<!--
  ContextualHelp.svelte -- Contextual help banner + hover tooltip
  ================================================================
  React source: src/widgets/ContextualHelp/ui/ContextualHelp.tsx (139 lines)

  Architecture:
    - Widget layer: two logical components in the React source:
      1. ContextualHelp (disabled welcome banner -- currently a no-op)
      2. ViewHelp (compact hover-expand help tooltip per view mode)
    - In Svelte, both are combined in this single file using snippets.
    - Reads from WELCOME_MESSAGES constant and guidanceService for seen state.
    - ViewHelp expands on hover/click to show tips for the current mode.

  Props:
    mode            -- Current view mode string (e.g. 'archive', 'viewer', 'boards')
    isInspectorOpen -- Optional flag (unused currently, reserved for layout hints)

  NOTE: The ContextualHelp banner is intentionally DISABLED in the React source.
        Only ViewHelp is active. The banner code is preserved as a commented reference.
-->
<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/ui/molecules/ViewHeader/types';
  import Button from '@/src/shared/ui/atoms/Button.svelte';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';
  import { cn } from '@/src/shared/lib/cn';
  import { guidance } from '@/src/shared/services/guidanceService';
  import { WELCOME_MESSAGES } from '@/src/shared/constants/helpContent';

  interface Props {
    mode: string;
    isInspectorOpen?: boolean;
    cx?: ContextualClassNames;
  }

  let {
    mode,
    isInspectorOpen = false,
    cx,
  }: Props = $props();

  // ── Banner state (DISABLED -- same as React source) ──
  // The banner feature was disabled upstream to reduce visual noise.
  // Only shows help if user explicitly asks for it via ? key.
  // Kept here as scaffold for future re-enablement.

  // ── ViewHelp state ──
  let isExpanded = $state(false);

  // Derived: get content for the current mode
  const content = $derived(WELCOME_MESSAGES[mode] ?? null);

  // ── Handlers ──
  function handleToggle() {
    isExpanded = !isExpanded;
  }

  function handleMouseEnter() {
    isExpanded = true;
  }

  function handleMouseLeave() {
    isExpanded = false;
  }
</script>

<!--
  ContextualHelp Banner (DISABLED)
  The banner feature is intentionally disabled in the React source to reduce
  visual noise. It was never enabled for users. The banner would show a brief
  welcome message the first time a user visits each view, but this was deemed
  too intrusive. Only ViewHelp (the compact hover tooltip below) is active.

  To re-enable: wire guidanceService.hasSeen/markSeen, add bannerVisible state,
  and uncomment the banner markup from the React source reference.
-->

<!--
  ViewHelp: Compact help icon that expands to tooltip on hover/click
-->
{#if content}
  <div class="relative">
    <Button
      variant="ghost"
      size="bare"
      onclick={handleToggle}
      class={cn(
        'flex items-center gap-1.5 px-2 py-1 text-xs transition-nb',
        isExpanded
          ? 'bg-nb-blue/20 text-nb-blue'
          : 'text-nb-black/40 hover:text-nb-black/60 hover:bg-nb-cream'
      )}
    >
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <span
        onmouseenter={handleMouseEnter}
        onmouseleave={handleMouseLeave}
        class="flex items-center gap-1.5"
      >
        <Icon name="help_outline" class="text-sm" />
        {#if isExpanded}
          <span>Help</span>
        {/if}
      </span>
    </Button>

    {#if isExpanded}
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <div
        class={cn(
          'absolute top-full right-0 mt-1 w-64 shadow-brutal p-3 z-50',
          'animate-in fade-in zoom-in-95',
          cx?.surface || 'bg-nb-white'
        )}
        onmouseenter={handleMouseEnter}
        onmouseleave={handleMouseLeave}
      >
        <h4 class={cn('text-xs font-semibold mb-1', cx?.text)}>{content.title}</h4>
        <p class={cn('text-[11px] leading-relaxed mb-2', cx?.textMuted)}>{content.body}</p>
        {#if content.tips && content.tips.length > 0}
          <ul class="space-y-1">
            {#each content.tips as tip (tip)}
              <li class={cn('flex items-start gap-1.5 text-[10px]', cx?.textMuted)}>
                <Icon name="arrow_right" class="text-[10px] text-nb-black/30 mt-0.5" />
                {tip}
              </li>
            {/each}
          </ul>
        {/if}
      </div>
    {/if}
  </div>
{/if}

// src/widgets/ContextualHelp/ui/ContextualHelp.tsx

import React, { useEffect, useState } from 'react';
import { Button } from '@/src/shared/ui/atoms';
import { Icon } from '@/src/shared/ui/atoms/Icon';
import { guidance } from '@/src/shared/services/guidanceService';
import { WELCOME_MESSAGES } from '@/src/shared/constants/helpContent';
import { useContextualStyles } from '@/src/shared/lib/hooks/useContextualStyles';
import { cn } from '@/src/shared/lib/cn';

interface ContextualHelpProps {
  mode: string;
  isInspectorOpen?: boolean;
}

/**
 * Lightweight contextual help banner
 * Shows a brief welcome message the first time a user visits each view
 * Non-intrusive: appears at top of content area, easy to dismiss
 */
export const ContextualHelp: React.FC<ContextualHelpProps> = ({ mode }) => {
  const cx = useContextualStyles();
  const [visible, setVisible] = useState(false);
  const [content, setContent] = useState<typeof WELCOME_MESSAGES['archive'] | null>(null);

  useEffect(() => {
    // DISABLED: Too many tooltips create visual noise
    // Only show help if user explicitly asks for it via ? key
    setVisible(false);
    setContent(null);
    return;
    
    /* Original code - disabled
    const topicId = `intro-${mode}` as const;
    const welcomeContent = WELCOME_MESSAGES[mode];

    if (welcomeContent && !guidance.hasSeen(topicId)) {
      setContent(welcomeContent);
      const timer = setTimeout(() => setVisible(true), 300);
      return () => clearTimeout(timer);
    } else {
      setVisible(false);
      setContent(null);
    }
    */
  }, [mode]);

  const dismiss = () => {
    const topicId = `intro-${mode}`;
    guidance.markSeen(topicId as any);
    setVisible(false);
  };

  if (!visible || !content) return null;

  return (
    <div className="mx-4 mt-4 mb-2 animate-in slide-in-from-top-2 ">
      <div className="bg-gradient-to-r from-nb-blue/10 to-nb-blue/10 border border-nb-blue/20 p-4">
        <div className="flex items-start gap-3">
          <div className="w-8 h-8 bg-nb-blue/20 flex items-center justify-center shrink-0">
            <Icon name="lightbulb" className="text-nb-blue text-sm" />
          </div>
          <div className="flex-1 min-w-0">
            <h4 className={cn('text-sm font-semibold mb-1', cx.text)}>{content.title}</h4>
            <p className={cn('text-xs leading-relaxed mb-2', cx.textMuted)}>{content.body}</p>
            {content.tips && content.tips.length > 0 && (
              <ul className="space-y-1">
                {content.tips.slice(0, 2).map((tip, i) => (
                  <li key={i} className={cn('flex items-center gap-1.5 text-[11px]', cx.textMuted)}>
                    <Icon name="check" className="text-nb-green text-[10px]" />
                    {tip}
                  </li>
                ))}
              </ul>
            )}
          </div>
          <Button variant="ghost" size="bare"
            onClick={dismiss}
            className="text-nb-black/40 hover:text-nb-black/60 p-1 shrink-0"
            title="Dismiss"
          >
            <Icon name="close" className="text-sm" />
          </Button>
        </div>
      </div>
    </div>
  );
};

/**
 * Compact view-specific help indicator
 * Shows in the corner, expands on hover/click
 */
export const ViewHelp: React.FC<{ mode: string }> = ({ mode }) => {
  const cx = useContextualStyles();
  const [expanded, setExpanded] = useState(false);
  const content = WELCOME_MESSAGES[mode];

  if (!content) return null;

  return (
    <div className="relative">
      <Button variant="ghost" size="bare"
        onClick={() => setExpanded(!expanded)}
        onMouseEnter={() => setExpanded(true)}
        onMouseLeave={() => setExpanded(false)}
        className={`flex items-center gap-1.5 px-2 py-1 text-xs transition-nb ${
          expanded
            ? 'bg-nb-blue/20 text-nb-blue'
            : 'text-nb-black/40 hover:text-nb-black/60 hover:bg-nb-cream'
        }`}
      >
        <Icon name="help_outline" className="text-sm" />
        {expanded && <span>Help</span>}
      </Button>

      {expanded && (
        <div
          className={cn('absolute top-full right-0 mt-1 w-64 shadow-brutal p-3 z-50 animate-in fade-in zoom-in-95', cx.surface)}
          onMouseEnter={() => setExpanded(true)}
          onMouseLeave={() => setExpanded(false)}
        >
          <h4 className={cn('text-xs font-semibold mb-1', cx.text)}>{content.title}</h4>
          <p className={cn('text-[11px] leading-relaxed mb-2', cx.textMuted)}>{content.body}</p>
          {content.tips && (
            <ul className="space-y-1">
              {content.tips.map((tip, i) => (
                <li key={i} className={cn('flex items-start gap-1.5 text-[10px]', cx.textMuted)}>
                  <Icon name="arrow_right" className="text-[10px] text-nb-black/30 mt-0.5" />
                  {tip}
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
};
