// ui/primitives/Button.tsx
/**
 * Button - Atomic UI Primitive (Neobrutalist)
 *
 * Sharp corners, thick borders, offset shadow, UPPERCASE text,
 * press-translate effect on active. size="bare" preserves 650+ usages.
 */

import React from 'react';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger' | 'success';
export type ButtonSize = 'bare' | 'sm' | 'base' | 'lg' | 'xl';

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?: ButtonSize;
  loading?: boolean;
  icon?: React.ReactNode;
  iconAfter?: React.ReactNode;
  fullWidth?: boolean;
  minimal?: boolean;
}

const variantStyles: Record<ButtonVariant, React.CSSProperties> = {
  primary: {
    backgroundColor: 'var(--theme-accent-primary, #0055FF)',
    color: 'var(--theme-text-inverse, #FFFFFF)',
    border: '2px solid var(--theme-border-default, #000000)',
    boxShadow: 'var(--theme-shadow-base, 4px 4px 0 0 #000)',
  },
  secondary: {
    backgroundColor: 'var(--theme-surface-secondary, #FFF8E7)',
    color: 'var(--theme-text-primary, #000000)',
    border: '2px solid var(--theme-border-default, #000000)',
    boxShadow: 'var(--theme-shadow-sm, 2px 2px 0 0 #000)',
  },
  ghost: {
    backgroundColor: 'transparent',
    color: 'inherit',
    border: '2px solid transparent',
  },
  danger: {
    backgroundColor: 'var(--theme-error-color, #FF3333)',
    color: 'var(--theme-text-inverse, #FFFFFF)',
    border: '2px solid var(--theme-border-default, #000000)',
    boxShadow: 'var(--theme-shadow-base, 4px 4px 0 0 #000)',
  },
  success: {
    backgroundColor: 'var(--theme-success-color, #00CC66)',
    color: 'var(--theme-text-primary, #000000)',
    border: '2px solid var(--theme-border-default, #000000)',
    boxShadow: 'var(--theme-shadow-base, 4px 4px 0 0 #000)',
  },
};

const sizeStyles: Record<ButtonSize, React.CSSProperties> = {
  bare: {
    // No sizing - allows Tailwind classes to control appearance
  },
  sm: {
    height: '32px',
    padding: '0 12px',
    fontSize: '0.75rem',
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.06em',
    position: 'relative' as const,
  },
  base: {
    height: '40px',
    padding: '0 16px',
    fontSize: '0.875rem',
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
  },
  lg: {
    height: '48px',
    padding: '0 24px',
    fontSize: '1rem',
    fontWeight: 800,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
  },
  xl: {
    height: '56px',
    padding: '0 32px',
    fontSize: '1.125rem',
    fontWeight: 800,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
  },
};

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  size = 'base',
  loading = false,
  icon,
  iconAfter,
  fullWidth = false,
  minimal = false,
  disabled,
  children,
  style,
  className,
  ...props
}) => {
  const baseStyle: React.CSSProperties = {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    fontFamily: '"Space Grotesk", system-ui, sans-serif',
    cursor: disabled ? 'not-allowed' : 'pointer',
    transition: 'all 0.1s linear',
    width: fullWidth ? '100%' : 'auto',
    opacity: disabled ? 0.5 : 1,
    borderRadius: 0,
    ...variantStyles[variant],
    ...sizeStyles[size],
    ...(minimal && {
      backgroundColor: 'transparent',
      borderColor: 'transparent',
      boxShadow: 'none',
    }),
    ...style,
  };

  const touchClass = size === 'sm' ? 'touch-target-sm' : '';
  const combinedClassName = [touchClass, className].filter(Boolean).join(' ') || undefined;

  return (
    <button
      style={baseStyle}
      disabled={disabled || loading}
      aria-disabled={disabled || loading}
      className={combinedClassName}
      {...props}
    >
      {loading && (
        <span style={{ marginRight: '0.5rem' }} aria-hidden="true">
          <svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="3"
            strokeLinecap="square"
            style={{ animation: 'spin 1s linear infinite' }}
          >
            <path d="M21 12a9 9 0 11-6.219-8.56" />
          </svg>
        </span>
      )}
      {icon && !loading && <span style={{ display: 'flex' }}>{icon}</span>}
      {children && <span>{children}</span>}
      {iconAfter && <span style={{ display: 'flex' }}>{iconAfter}</span>}
    </button>
  );
};

// src/shared/ui/atoms/Button.svelte
<!--
  Button - Atomic UI Primitive (Neobrutalist)

  ORIGINAL: ui/primitives/Button.tsx (162 lines)
  CSS custom properties for full theming factory compatibility.
  Sharp corners, thick borders, offset shadow, UPPERCASE text.
  size="bare" preserves 650+ usages (no height/padding).
-->
<script module lang="ts">
  import type { ButtonVariant, ButtonSize } from './types';

  const VARIANT_STYLES: Record<ButtonVariant, string> = {
    primary: [
      'background-color: var(--theme-accent-primary, #0055FF)',
      'color: var(--theme-text-inverse, #FFFFFF)',
      'border: 2px solid var(--theme-border-default, #000)',
      'box-shadow: var(--theme-shadow-base, 4px 4px 0 0 #000)',
    ].join('; '),
    secondary: [
      'background-color: var(--theme-surface-secondary, #FFF8E7)',
      'color: var(--theme-text-primary, #000)',
      'border: 2px solid var(--theme-border-default, #000)',
      'box-shadow: var(--theme-shadow-sm, 2px 2px 0 0 #000)',
    ].join('; '),
    ghost: 'background-color: transparent; color: inherit; border: 2px solid transparent',
    danger: [
      'background-color: var(--theme-error-color, #FF3333)',
      'color: var(--theme-text-inverse, #FFFFFF)',
      'border: 2px solid var(--theme-border-default, #000)',
      'box-shadow: var(--theme-shadow-base, 4px 4px 0 0 #000)',
    ].join('; '),
    success: [
      'background-color: var(--theme-success-color, #00CC66)',
      'color: var(--theme-text-primary, #000)',
      'border: 2px solid var(--theme-border-default, #000)',
      'box-shadow: var(--theme-shadow-base, 4px 4px 0 0 #000)',
    ].join('; '),
  };

  const SIZE_STYLES: Record<ButtonSize, string> = {
    bare: '',
    sm: 'height: 32px; padding: 0 12px; font-size: 0.75rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; position: relative',
    base: 'height: 40px; padding: 0 16px; font-size: 0.875rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.04em',
    lg: 'height: 48px; padding: 0 24px; font-size: 1rem; font-weight: 800; text-transform: uppercase; letter-spacing: 0.04em',
    xl: 'height: 56px; padding: 0 32px; font-size: 1.125rem; font-weight: 800; text-transform: uppercase; letter-spacing: 0.04em',
  };

  const BASE_STYLE = 'display: inline-flex; align-items: center; justify-content: center; gap: 0.5rem; font-family: "Space Grotesk", system-ui, sans-serif; transition: all 0.1s linear; border-radius: 0';
</script>

<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    variant?: ButtonVariant;
    size?: ButtonSize;
    loading?: boolean;
    icon?: Snippet;
    iconAfter?: Snippet;
    fullWidth?: boolean;
    minimal?: boolean;
    disabled?: boolean;
    children?: Snippet;
    class?: string;
    style?: string;
    onclick?: (e: MouseEvent) => void;
    type?: 'button' | 'submit' | 'reset';
    id?: string;
    title?: string;
    'aria-label'?: string;
    [key: string]: unknown;
  }

  let {
    variant = 'primary',
    size = 'base',
    loading = false,
    icon,
    iconAfter,
    fullWidth = false,
    minimal = false,
    disabled = false,
    children,
    class: className = '',
    style: userStyle = '',
    onclick,
    type = 'button',
    ...rest
  }: Props = $props();

  let isDisabled = $derived(disabled || loading);

  let buttonStyle = $derived.by(() => {
    const parts = [BASE_STYLE, VARIANT_STYLES[variant], SIZE_STYLES[size]];
    parts.push(isDisabled ? 'cursor: not-allowed; opacity: 0.5' : 'cursor: pointer; opacity: 1');
    if (fullWidth) parts.push('width: 100%');
    if (minimal) parts.push('background-color: transparent; border-color: transparent; box-shadow: none');
    if (userStyle) parts.push(userStyle);
    return parts.filter(Boolean).join('; ');
  });

  let touchClass = $derived(size === 'sm' ? 'touch-target-sm' : '');
  let combinedClass = $derived([touchClass, className].filter(Boolean).join(' '));
</script>

<button
  {type}
  style={buttonStyle}
  disabled={isDisabled}
  aria-disabled={isDisabled || undefined}
  class={combinedClass || undefined}
  {onclick}
  {...rest}
>
  {#if loading}
    <span style="margin-right: 0.5rem" aria-hidden="true">
      <svg
        width="16"
        height="16"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="3"
        stroke-linecap="square"
        style="animation: spin 1s linear infinite"
      >
        <path d="M21 12a9 9 0 11-6.219-8.56" />
      </svg>
    </span>
  {/if}
  {#if icon && !loading}
    <span style="display: flex">{@render icon()}</span>
  {/if}
  {#if children}
    <span>{@render children()}</span>
  {/if}
  {#if iconAfter}
    <span style="display: flex">{@render iconAfter()}</span>
  {/if}
</button>

<style>
  @keyframes spin {
    from { transform: rotate(0deg); }
    to { transform: rotate(360deg); }
  }
</style>
