// src/shared/ui/atoms/ZoomControl.tsx
/**
 * ZoomControl Atom
 *
 * Zoom in/out/reset controls for IIIF viewer interfaces.
 * Composes Button atoms with zoom level display.
 *
 * ATOMIC DESIGN:
 * - Composes: Button atom
 * - Has local state: current zoom percentage display
 * - No domain logic (zoom state managed by viewer parent)
 *
 * IDEAL OUTCOME: Precise zoom control with clear level indication
 * FAILURE PREVENTED: Lost zoom state, imprecise zoom jumps
 *
 * @example
 * <ZoomControl
 *   zoom={1.5}
 *   min={0.5}
 *   max={5}
 *   step={0.25}
 *   onZoomChange={(z) => setZoom(z)}
 * />
 */

import React, { useCallback } from 'react';
import { Button } from '@/ui/primitives/Button';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';

export interface ZoomControlProps {
  /** Current zoom level (1 = 100%) */
  zoom: number;
  /** Minimum zoom level */
  min?: number;
  /** Maximum zoom level */
  max?: number;
  /** Zoom step increment */
  step?: number;
  /** Called when zoom changes */
  onZoomChange: (zoom: number) => void;
  /** Called when reset is clicked */
  onReset?: () => void;
  /** Fit-to-view handler */
  onFit?: () => void;
  /** Compact mode (no label) */
  compact?: boolean;
  /** Disabled state */
  disabled?: boolean;
  /** Contextual styles from template (required for theming) */
  cx: ContextualClassNames;
  fieldMode?: boolean;
}

/**
 * ZoomControl Component
 *
 * Zoom controls with percentage display.
 */
export const ZoomControl: React.FC<ZoomControlProps> = ({
  zoom,
  min = 0.25,
  max = 5,
  step = 0.25,
  onZoomChange,
  onReset,
  onFit,
  compact = false,
  disabled = false,
  cx,
}) => {

  const handleZoomIn = useCallback(() => {
    const newZoom = Math.min(zoom + step, max);
    onZoomChange(newZoom);
  }, [zoom, step, max, onZoomChange]);

  const handleZoomOut = useCallback(() => {
    const newZoom = Math.max(zoom - step, min);
    onZoomChange(newZoom);
  }, [zoom, step, min, onZoomChange]);

  const handleReset = useCallback(() => {
    if (onReset) {
      onReset();
    } else {
      onZoomChange(1);
    }
  }, [onReset, onZoomChange]);

  const canZoomIn = zoom < max;
  const canZoomOut = zoom > min;
  const canReset = zoom !== 1;

  // Format zoom as percentage
  const zoomPercent = Math.round(zoom * 100);

  return (
    <div
      className={`
        inline-flex items-center gap-1
         border ${cx.border} ${cx.surface} p-1
`}
      role="group"
      aria-label="Zoom controls"
    >
      {/* Zoom Out */}
      <Button
        variant="ghost"
        size="sm"
        onClick={handleZoomOut}
        disabled={disabled || !canZoomOut}
        aria-label="Zoom out"
        className="!px-2"
      >
        <span className="material-icons">remove</span>
      </Button>

      {/* Zoom Level Display */}
      <div
        className={`
          min-w-[60px] text-center text-sm font-medium
          ${cx.text} select-none
`}
        aria-live="polite"
        aria-atomic="true"
      >
        {zoomPercent}%
      </div>

      {/* Zoom In */}
      <Button
        variant="ghost"
        size="sm"
        onClick={handleZoomIn}
        disabled={disabled || !canZoomIn}
        aria-label="Zoom in"
        className="!px-2"
      >
        <span className="material-icons">add</span>
      </Button>

      {/* Divider */}
      <div className={`w-px h-6 ${cx.divider} mx-1`} />

      {/* Reset / Fit */}
      {!compact && (
        <>
          <Button
            variant="ghost"
            size="sm"
            onClick={handleReset}
            disabled={disabled || !canReset}
            aria-label="Reset zoom"
          >
            100%
          </Button>

          {onFit && (
            <Button
              variant="ghost"
              size="sm"
              onClick={onFit}
              disabled={disabled}
              aria-label="Fit to view"
              className="!px-2"
            >
              <span className="material-icons">fit_screen</span>
            </Button>
          )}
        </>
      )}
    </div>
  );
};

// src/shared/ui/atoms/ZoomControl.svelte
<!--
  ZoomControl - Zoom in/out/reset controls

  ORIGINAL: src/shared/ui/atoms/ZoomControl.tsx (174 lines)
  Composes Button atoms. Theme-aware via cx prop.
  aria-live="polite" on zoom display for screen readers.
-->
<script lang="ts">
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import Button from './Button.svelte';
  import Icon from './Icon.svelte';

  interface Props {
    zoom: number;
    min?: number;
    max?: number;
    step?: number;
    onZoomChange: (zoom: number) => void;
    onReset?: () => void;
    onFit?: () => void;
    compact?: boolean;
    disabled?: boolean;
    cx: ContextualClassNames;
  }

  let {
    zoom,
    min = 0.25,
    max = 5,
    step = 0.25,
    onZoomChange,
    onReset,
    onFit,
    compact = false,
    disabled = false,
    cx,
  }: Props = $props();

  function handleZoomIn() {
    onZoomChange(Math.min(zoom + step, max));
  }

  function handleZoomOut() {
    onZoomChange(Math.max(zoom - step, min));
  }

  function handleReset() {
    if (onReset) {
      onReset();
    } else {
      onZoomChange(1);
    }
  }

  let canZoomIn = $derived(zoom < max);
  let canZoomOut = $derived(zoom > min);
  let canReset = $derived(zoom !== 1);
  let zoomPercent = $derived(Math.round(zoom * 100));
</script>

<div
  class="inline-flex items-center gap-1 border {cx.border} {cx.surface} p-1"
  role="group"
  aria-label="Zoom controls"
>
  <Button
    variant="ghost"
    size="sm"
    onclick={handleZoomOut}
    disabled={disabled || !canZoomOut}
    aria-label="Zoom out"
    class="!px-2"
  >
    {#snippet icon()}<Icon name="remove" />{/snippet}
  </Button>

  <div
    class="min-w-[60px] text-center text-sm font-medium {cx.text} select-none"
    aria-live="polite"
    aria-atomic="true"
  >
    {zoomPercent}%
  </div>

  <Button
    variant="ghost"
    size="sm"
    onclick={handleZoomIn}
    disabled={disabled || !canZoomIn}
    aria-label="Zoom in"
    class="!px-2"
  >
    {#snippet icon()}<Icon name="add" />{/snippet}
  </Button>

  <div class="w-px h-6 {cx.divider} mx-1"></div>

  {#if !compact}
    <Button
      variant="ghost"
      size="sm"
      onclick={handleReset}
      disabled={disabled || !canReset}
      aria-label="Reset zoom"
    >
      100%
    </Button>

    {#if onFit}
      <Button
        variant="ghost"
        size="sm"
        onclick={onFit}
        {disabled}
        aria-label="Fit to view"
        class="!px-2"
      >
        {#snippet icon()}<Icon name="fit_screen" />{/snippet}
      </Button>
    {/if}
  {/if}
</div>
