// components/staging/ArchivePane.tsx

import React, { useCallback, useMemo, useState } from 'react';
import { ArchiveCollection, ArchiveLayout, SourceManifest, SourceManifests } from '../../types';
import { Icon } from '../Icon';
import { CollectionCard } from './CollectionCard';
import { findManifest } from '../../services/stagingService';
import { useTerminology } from '@/src/app/providers/useTerminology';
import { useKeyboardDragDrop } from '../../hooks/useKeyboardDragDrop';
import { FEATURE_FLAGS } from '../../constants';

interface ArchivePaneProps {
  archiveLayout: ArchiveLayout;
  sourceManifests: SourceManifests;
  onAddToCollection: (collectionId: string, manifestIds: string[]) => void;
  onRemoveFromCollection: (collectionId: string, manifestIds: string[]) => void;
  onCreateCollection: (name: string, parentId?: string | null) => void;
  onRenameCollection: (collectionId: string, newName: string) => void;
  onDeleteCollection: (collectionId: string) => void;
  onOpenSendToModal: (manifestIds: string[]) => void;
  onFocus: () => void;
  isFocused: boolean;
}

export const ArchivePane: React.FC<ArchivePaneProps> = ({
  archiveLayout,
  sourceManifests,
  onAddToCollection,
  onRemoveFromCollection,
  onCreateCollection,
  onRenameCollection,
  onDeleteCollection,
  onOpenSendToModal,
  onFocus,
  isFocused
}) => {
  // Use terminology hook for user-friendly labels
  const { t, formatCount } = useTerminology({ level: 'standard' });

  const [dragOverCollectionId, setDragOverCollectionId] = useState<string | null>(null);
  const [newCollectionName, setNewCollectionName] = useState('');
  const [showNewCollectionInput, setShowNewCollectionInput] = useState(false);
  const [focusedCollectionId, setFocusedCollectionId] = useState<string | null>(null);

  // Phase 5: Keyboard drag and drop for collections (when enabled)
  const enableKeyboardDnd = FEATURE_FLAGS.USE_KEYBOARD_DND;

  // Flatten collections for keyboard navigation
  const flattenCollections = useCallback((collection: ArchiveCollection): ArchiveCollection[] => {
    const result: ArchiveCollection[] = [collection];
    collection.children.forEach(child => {
      result.push(...flattenCollections(child));
    });
    return result;
  }, []);

  const allCollections = useMemo(() => {
    return flattenCollections(archiveLayout.root);
  }, [archiveLayout.root, flattenCollections]);

  const keyboardDnd = useKeyboardDragDrop({
    items: allCollections,
    onReorder: () => {
      // Reordering collections not yet supported
    },
    onMove: (itemId, targetId) => {
      // This would be called when moving a manifest to a collection via keyboard
      onAddToCollection(targetId, [itemId]);
    },
    getItemId: (item) => item.id
  });

  // Get manifests for a collection
  const getManifestsForCollection = useCallback((collection: ArchiveCollection): SourceManifest[] => {
    return collection.manifestRefs
      .map(id => findManifest(sourceManifests, id))
      .filter((m): m is SourceManifest => m !== undefined);
  }, [sourceManifests]);

  // Get unassigned manifests
  const unassignedManifests = useMemo((): SourceManifest[] => {
    return archiveLayout.unassignedManifests
      .map(id => findManifest(sourceManifests, id))
      .filter((m): m is SourceManifest => m !== undefined);
  }, [archiveLayout.unassignedManifests, sourceManifests]);

  // Handle creating new collection
  const handleCreateCollection = useCallback(() => {
    if (newCollectionName.trim()) {
      onCreateCollection(newCollectionName.trim());
      setNewCollectionName('');
      setShowNewCollectionInput(false);
    }
  }, [newCollectionName, onCreateCollection]);

  // Handle drag over unassigned section
  const handleUnassignedDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    // No-op for unassigned section - items are already unassigned
    setDragOverCollectionId(null);
  }, []);

  // Render collection recursively
  const renderCollection = useCallback((collection: ArchiveCollection, isRoot: boolean = false, level: number = 0) => {
    const manifests = getManifestsForCollection(collection);
    const isFocused = focusedCollectionId === collection.id;
    const isSelected = enableKeyboardDnd && keyboardDnd.state.selectedId === collection.id;
    const isDropTarget = enableKeyboardDnd && keyboardDnd.state.dropTargetId === collection.id;

    return (
      <div
        key={collection.id}
        className="space-y-3"
        role="treeitem"
        aria-level={level + 1}
        aria-selected={isSelected}
        tabIndex={isFocused ? 0 : -1}
        onKeyDown={enableKeyboardDnd ? (e) => keyboardDnd.handlers.onKeyDown(e, collection) : undefined}
        onFocus={() => {
          setFocusedCollectionId(collection.id);
          if (enableKeyboardDnd) {
            keyboardDnd.handlers.onFocus(collection);
          }
        }}
      >
        <CollectionCard
          collection={collection}
          manifests={manifests}
          isRoot={isRoot}
          isDragOver={dragOverCollectionId === collection.id || isDropTarget}
          onDrop={(ids) => onAddToCollection(collection.id, ids)}
          onDragEnter={() => setDragOverCollectionId(collection.id)}
          onDragLeave={() => setDragOverCollectionId(null)}
          onRemoveManifest={(id) => onRemoveFromCollection(collection.id, [id])}
          onRename={(name) => onRenameCollection(collection.id, name)}
          onDelete={() => onDeleteCollection(collection.id)}
          onAddSubCollection={() => {
            const name = prompt('New sub-collection name:');
            if (name) onCreateCollection(name, collection.id);
          }}
        />

        {/* Render children */}
        {collection.children.length > 0 && (
          <div className="ml-6 pl-4 border-l-2 border-slate-200 space-y-3">
            {collection.children.map(child => renderCollection(child, false, level + 1))}
          </div>
        )}
      </div>
    );
  }, [
    getManifestsForCollection,
    dragOverCollectionId,
    onAddToCollection,
    onRemoveFromCollection,
    onRenameCollection,
    onDeleteCollection,
    onCreateCollection,
    focusedCollectionId,
    enableKeyboardDnd,
    keyboardDnd
  ]);

  // Stats
  const stats = useMemo(() => {
    const countCollections = (collection: ArchiveCollection): number => {
      return 1 + collection.children.reduce((sum, child) => sum + countCollections(child), 0);
    };
    const countAssignedManifests = (collection: ArchiveCollection): number => {
      return collection.manifestRefs.length +
        collection.children.reduce((sum, child) => sum + countAssignedManifests(child), 0);
    };

    return {
      totalCollections: countCollections(archiveLayout.root),
      assignedManifests: countAssignedManifests(archiveLayout.root),
      unassignedCount: archiveLayout.unassignedManifests.length
    };
  }, [archiveLayout]);

  return (
    <div
      className={`
        flex flex-col h-full transition-colors
        ${isFocused ? 'border-amber-500/30 bg-amber-900/10' : 'bg-slate-800/50'}
      `}
      onClick={onFocus}
    >
      {/* Header */}
      <div className="flex-shrink-0 p-4 border-b border-slate-700 bg-slate-800">
        <div className="flex items-center justify-between mb-3">
          <div>
            <h3 className="font-bold text-white flex items-center gap-2">
              <Icon name="account_tree" className="text-amber-500" />
              Your Archive
            </h3>
            <p className="text-[11px] text-slate-400 mt-0.5">
              Organize {t('Manifest').toLowerCase()}s into {t('Collection').toLowerCase()}s
            </p>
          </div>
          <div className="text-right">
            <div className="text-lg font-bold text-white">{stats.totalCollections}</div>
            <div className="text-[10px] text-slate-400">{t('Collection').toLowerCase()}s</div>
          </div>
        </div>

        {/* New collection input */}
        {showNewCollectionInput ? (
          <div className="flex gap-2">
            <input
              type="text"
              value={newCollectionName}
              onChange={(e) => setNewCollectionName(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleCreateCollection()}
              placeholder={`${t('Collection')} name...`}
              autoFocus
              className="flex-1 px-3 py-2 text-sm bg-slate-700 border border-slate-600 rounded-lg outline-none focus:border-amber-400 text-white placeholder-slate-400"
            />
            <button
              onClick={handleCreateCollection}
              disabled={!newCollectionName.trim()}
              className="px-4 py-2 bg-amber-500 text-white rounded-lg font-medium text-sm hover:bg-amber-600 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Create
            </button>
            <button
              onClick={() => {
                setShowNewCollectionInput(false);
                setNewCollectionName('');
              }}
              className="px-3 py-2 text-slate-400 hover:text-white"
            >
              <Icon name="close" />
            </button>
          </div>
        ) : (
          <button
            onClick={() => setShowNewCollectionInput(true)}
            className="w-full py-2 border-2 border-dashed border-slate-600 rounded-lg text-sm text-slate-400 hover:border-amber-400 hover:text-amber-400 hover:bg-amber-900/20 transition-colors flex items-center justify-center gap-2"
          >
            <Icon name="create_new_folder" />
            New {t('Collection')}
          </button>
        )}
      </div>

      {/* Collection tree */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {/* Root collection and children */}
        {renderCollection(archiveLayout.root, true)}

        {/* Unassigned section */}
        {unassignedManifests.length > 0 && (
          <div
            onDragOver={(e) => e.preventDefault()}
            onDrop={handleUnassignedDrop}
            className="mt-6 pt-4 border-t border-slate-700"
          >
            <div className="flex items-center gap-2 mb-3">
              <Icon name="inbox" className="text-slate-400" />
              <h4 className="font-medium text-slate-300">
                Unassigned {t('Manifest')}s
              </h4>
              <span className="ml-auto text-[11px] text-slate-400 bg-slate-700 px-2 py-0.5 rounded-full">
                {unassignedManifests.length}
              </span>
            </div>

            <div className="space-y-2">
              {unassignedManifests.map((manifest) => (
                <div
                  key={manifest.id}
                  draggable
                  onDragStart={(e) => {
                    e.dataTransfer.setData('application/iiif-manifest-ids', JSON.stringify([manifest.id]));
                  }}
                  className="group flex items-center gap-3 p-3 bg-slate-700 border border-slate-600 rounded-lg cursor-grab active:cursor-grabbing hover:border-slate-500 hover:shadow-sm transition-all"
                >
                  <Icon name="drag_indicator" className="text-slate-300 group-hover:text-slate-500" />
                  <div className="w-8 h-8 bg-emerald-900/50 rounded flex items-center justify-center flex-shrink-0">
                    <Icon name="menu_book" className="text-emerald-600 text-sm" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="text-sm font-medium text-slate-700 truncate">
                      {manifest.name}
                    </div>
                    <div className="text-[10px] text-slate-400">
                      {manifest.files.length} files
                    </div>
                  </div>
                  <button
                    onClick={() => onOpenSendToModal([manifest.id])}
                    className="opacity-0 group-hover:opacity-100 px-2 py-1 bg-amber-100 text-amber-700 rounded text-[10px] font-medium hover:bg-amber-200 transition-opacity"
                  >
                    Add to {t('Collection')}...
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Empty state when no collections */}
        {archiveLayout.root.children.length === 0 && unassignedManifests.length === 0 && (
          <div className="text-center py-12 px-4">
            <div className="w-16 h-16 bg-amber-50 rounded-full flex items-center justify-center mx-auto mb-4">
              <Icon name="create_new_folder" className="text-3xl text-amber-400" />
            </div>
            <p className="text-sm font-medium text-slate-700 mb-1">
              No {t('Collection').toLowerCase()}s yet
            </p>
            <p className="text-xs text-slate-500 mb-4">
              Create your first {t('Collection').toLowerCase()} to organize your files
            </p>
            <div className="bg-slate-50 rounded-lg p-3 text-left">
              <p className="text-[11px] font-medium text-slate-600 mb-2">How to organize:</p>
              <ul className="text-[11px] text-slate-500 space-y-1">
                <li className="flex items-start gap-1.5">
                  <Icon name="drag_indicator" className="text-xs text-blue-500 mt-0.5 flex-shrink-0" />
                  <span>Drag files from the left to add them</span>
                </li>
                <li className="flex items-start gap-1.5">
                  <Icon name="create_new_folder" className="text-xs text-amber-500 mt-0.5 flex-shrink-0" />
                  <span>Create {t('Collection').toLowerCase()}s to group related files</span>
                </li>
                <li className="flex items-start gap-1.5">
                  <Icon name="account_tree" className="text-xs text-emerald-500 mt-0.5 flex-shrink-0" />
                  <span>Nest {t('Collection').toLowerCase()}s for hierarchy</span>
                </li>
              </ul>
            </div>
          </div>
        )}
      </div>

      {/* Footer with validation indicators */}
      <div className="flex-shrink-0 p-3 border-t border-slate-200 bg-white">
        <div className="flex items-center justify-between text-[10px]">
          {stats.unassignedCount > 0 ? (
            <div className="flex items-center gap-1 text-amber-600">
              <Icon name="warning" className="text-sm" />
              {stats.unassignedCount} {t('Manifest').toLowerCase()}{stats.unassignedCount !== 1 ? 's' : ''} not in any {t('Collection').toLowerCase()}
            </div>
          ) : (
            <div className="flex items-center gap-1 text-emerald-600">
              <Icon name="check_circle" className="text-sm" />
              All {t('Manifest').toLowerCase()}s assigned
            </div>
          )}
          <span className="text-slate-400">
            {stats.assignedManifests} in {t('Collection').toLowerCase()}s
          </span>
        </div>
      </div>
    </div>
  );
};

// src/features/staging/ui/molecules/ArchivePane.svelte
<!--
  ArchivePane Molecule

  Right pane showing archive collection structure with drag-drop.
  Displays collections and allows organizing manifests into them.

  Ported from: src/features/staging/ui/molecules/ArchivePane.tsx (369 lines)

  Architecture:
  - Per-node state managed via Maps/Sets in the parent scope
  - CollectionNode rendered as {#snippet} with state lookups
  - Drag-drop with IIIF Content State interop on drop
  - Inline rename with input element
-->
<script lang="ts">
  import type { SourceManifests } from '@/src/entities/collection/model/stagingService';
  import type { ArchiveLayout, ArchiveNode } from '@/src/features/staging/stores/stagingState.svelte';
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import { cn } from '@/src/shared/lib/cn';
  import { Button, Icon } from '@/src/shared/ui/atoms';
  import { contentStateService } from '@/src/shared/services/contentState';

  interface ArchivePaneProps {
    archiveLayout: ArchiveLayout;
    sourceManifests: SourceManifests;
    onAddToCollection: (collectionId: string, manifestIds: string[]) => void;
    onRemoveFromCollection: (collectionId: string, manifestIds: string[]) => void;
    onCreateCollection: (name: string) => string;
    onRenameCollection: (collectionId: string, newName: string) => void;
    onDeleteCollection: (collectionId: string) => void;
    onFocus: () => void;
    isFocused: boolean;
    onContextMenu?: (e: MouseEvent, collectionId: string) => void;
    cx?: Partial<ContextualClassNames>;
    fieldMode?: boolean;
  }

  let {
    archiveLayout,
    sourceManifests,
    onAddToCollection,
    onRemoveFromCollection,
    onCreateCollection,
    onRenameCollection,
    onDeleteCollection,
    onFocus,
    isFocused,
    onContextMenu,
    cx,
    fieldMode: _fieldMode,
  }: ArchivePaneProps = $props();

  // --- Header state ---
  let showNewCollectionInput = $state(false);
  let newCollectionName = $state('');

  // --- New collection drop zone state ---
  let isNewCollectionDragOver = $state(false);

  // --- Per-node state (managed via Maps/Sets) ---
  // All collection nodes start expanded; user can toggle individual nodes
  let userCollapsedNodes = $state(new Set<string>());
  let expandedNodes = $derived.by(() => {
    const allIds = new Set<string>();
    for (const child of archiveLayout.root.children) {
      if (!userCollapsedNodes.has(child.id)) {
        allIds.add(child.id);
      }
    }
    return allIds;
  });
  let renamingNodeId = $state<string | null>(null);
  let dragOverNodeId = $state<string | null>(null);
  let renameText = $state('');

  // --- Header handlers ---

  function handleCreateCollection() {
    if (newCollectionName.trim()) {
      onCreateCollection(newCollectionName);
      newCollectionName = '';
      showNewCollectionInput = false;
    }
  }

  function handleCreateKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter') handleCreateCollection();
    if (e.key === 'Escape') showNewCollectionInput = false;
  }

  // --- New collection drop zone handlers ---

  function handleNewCollectionDragOver(e: DragEvent) {
    e.preventDefault();
    e.dataTransfer!.dropEffect = 'copy';
    isNewCollectionDragOver = true;
  }

  function handleNewCollectionDragLeave(e: DragEvent) {
    const currentTarget = e.currentTarget as HTMLElement;
    if (currentTarget.contains(e.relatedTarget as Node)) return;
    isNewCollectionDragOver = false;
  }

  function handleNewCollectionDrop(e: DragEvent) {
    e.preventDefault();
    isNewCollectionDragOver = false;
    const raw = e.dataTransfer!.getData('application/iiif-manifest-ids');
    if (!raw) return;
    try {
      const ids = JSON.parse(raw) as string[];
      if (ids.length > 0) {
        const newId = onCreateCollection('New Collection');
        onAddToCollection(newId, ids);
      }
    } catch {
      /* ignore malformed data */
    }
  }

  // --- CollectionNode helpers ---

  function extractManifestIds(e: DragEvent): string[] | null {
    // Try application/iiif-manifest-ids first (internal drag)
    const raw = e.dataTransfer!.getData('application/iiif-manifest-ids');
    if (raw) {
      try {
        const ids = JSON.parse(raw) as string[];
        if (ids.length > 0) return ids;
      } catch {
        /* ignore malformed data */
      }
    }

    // Fallback: try IIIF Content State (external drag interop)
    try {
      const contentState = contentStateService.handleDrop(e.dataTransfer!);
      if (contentState?.manifestId) {
        return [contentState.manifestId];
      }
    } catch {
      /* ignore */
    }

    return null;
  }

  function handleNodeDragOver(e: DragEvent, nodeId: string) {
    e.preventDefault();
    e.dataTransfer!.dropEffect = 'copy';
    dragOverNodeId = nodeId;
  }

  function handleNodeDragLeave(e: DragEvent) {
    const currentTarget = e.currentTarget as HTMLElement;
    if (currentTarget.contains(e.relatedTarget as Node)) return;
    dragOverNodeId = null;
  }

  function handleNodeDrop(e: DragEvent, nodeId: string) {
    e.preventDefault();
    dragOverNodeId = null;

    const ids = extractManifestIds(e);
    if (ids) {
      onAddToCollection(nodeId, ids);
    }
  }

  function handleToggleExpand(nodeId: string) {
    const next = new Set(userCollapsedNodes);
    if (expandedNodes.has(nodeId)) {
      // Currently expanded → collapse by adding to userCollapsedNodes
      next.add(nodeId);
    } else {
      // Currently collapsed → expand by removing from userCollapsedNodes
      next.delete(nodeId);
    }
    userCollapsedNodes = next;
  }

  function startRenaming(nodeId: string, currentName: string) {
    renamingNodeId = nodeId;
    renameText = currentName;
  }

  function handleRenameSubmit(nodeId: string) {
    if (renameText.trim()) {
      onRenameCollection(nodeId, renameText);
      renamingNodeId = null;
    }
  }

  function handleRenameKeyDown(e: KeyboardEvent, nodeId: string) {
    if (e.key === 'Enter') handleRenameSubmit(nodeId);
    if (e.key === 'Escape') renamingNodeId = null;
  }
</script>

{#snippet collectionNode(node: ArchiveNode)}
  {@const isExpanded = expandedNodes.has(node.id)}
  {@const isRenaming = renamingNodeId === node.id}
  {@const isDragOver = dragOverNodeId === node.id}
  {@const manifestCount = node.manifestIds?.length || 0}

  <div
    class={cn(
      'border-b transition-all duration-150',
      isDragOver ? 'border-2 border-dashed border-nb-blue bg-nb-blue/5' : 'border-nb-black/10',
    )}
    onclick={onFocus}
    onkeydown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onFocus(); } }}
    ondragover={(e) => handleNodeDragOver(e, node.id)}
    ondragleave={handleNodeDragLeave}
    ondrop={(e) => handleNodeDrop(e, node.id)}
    role="treeitem"
    aria-selected={false}
    tabindex="0"
  >
    <!-- Collection header -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div
      class="flex items-center gap-2 p-2 hover:bg-nb-cream cursor-pointer group"
      oncontextmenu={(e) => { e.preventDefault(); onContextMenu?.(e, node.id); }}
    >
      <Button
        variant="ghost"
        size="bare"
        onclick={() => handleToggleExpand(node.id)}
        class="p-0.5 hover:bg-nb-cream rounded"
      >
        <Icon
          name={isExpanded ? 'expand_more' : 'chevron_right'}
          class="text-base"
        />
      </Button>

      <Icon name="folder" class="text-base text-nb-blue" />

      {#if isRenaming}
        <!-- svelte-ignore a11y_autofocus -->
        <input
          type="text"
          bind:value={renameText}
          onblur={() => handleRenameSubmit(node.id)}
          onkeydown={(e) => handleRenameKeyDown(e, node.id)}
          class="flex-1 px-1 py-0.5 text-sm border border-nb-black/20 rounded"
          autofocus
          onclick={(e) => e.stopPropagation()}
        />
      {:else}
        <span class="flex-1 text-sm font-medium text-nb-black/80">
          {node.name}
        </span>
        <span class="text-xs text-nb-black/50 px-2 py-0.5 bg-nb-cream rounded">
          {manifestCount}
        </span>
      {/if}

      <!-- Actions (visible on hover) -->
      <div class="hidden group-hover:flex gap-1">
        <Button
          variant="ghost"
          size="bare"
          onclick={(e) => {
            e.stopPropagation();
            startRenaming(node.id, node.name);
          }}
          class="p-0.5 hover:bg-nb-cream text-nb-black/60 text-xs"
          title="Rename"
        >
          <Icon name="edit" class="text-sm" />
        </Button>
        <Button
          variant="ghost"
          size="bare"
          onclick={(e) => {
            e.stopPropagation();
            onDeleteCollection(node.id);
          }}
          class="p-0.5 hover:bg-nb-red/40 text-nb-red text-xs"
          title="Delete"
        >
          <Icon name="delete" class="text-sm" />
        </Button>
      </div>
    </div>

    <!-- Manifests in collection -->
    {#if isExpanded && node.manifestIds && node.manifestIds.length > 0}
      <div class="bg-nb-white border-l border-nb-black/20 ml-4">
        {#each node.manifestIds as manifestId (manifestId)}
          {@const manifest = sourceManifests.manifests.find((m) => m.id === manifestId)}
          {#if manifest}
            <div
              class="flex items-center gap-2 p-2 pl-6 hover:bg-nb-cream text-xs text-nb-black/80 group"
            >
              <Icon name="description" class="text-sm text-nb-black/40" />
              <span class="flex-1 truncate">{manifest.name}</span>
              <Button
                variant="ghost"
                size="bare"
                onclick={(e) => {
                  e.stopPropagation();
                  onRemoveFromCollection(node.id, [manifestId]);
                }}
                class="opacity-0 group-hover:opacity-100 p-0.5 hover:bg-nb-red/40 text-nb-red"
                title="Remove from collection"
              >
                <Icon name="close" class="text-sm" />
              </Button>
            </div>
          {/if}
        {/each}
      </div>
    {/if}

    <!-- Empty state -->
    {#if isExpanded && (!node.manifestIds || node.manifestIds.length === 0)}
      <div class={cn(
        'p-3 pl-10 text-xs italic',
        isDragOver ? 'text-nb-blue font-medium' : 'text-nb-black/40',
      )}>
        {isDragOver ? 'Drop here to add' : 'No manifests. Drag from left pane to add.'}
      </div>
    {/if}
  </div>
{/snippet}

<div
  class={cn(
    'h-full flex flex-col bg-nb-cream/30 border border-nb-black/20 overflow-hidden',
    isFocused && 'ring-2 ring-nb-blue',
  )}
>
  <!-- Header -->
  <div
    class="p-3 border-b border-nb-black/20 bg-nb-cream/40"
    onclick={onFocus}
    role="presentation"
  >
    <div class="flex items-center justify-between mb-2">
      <h3 class="text-sm font-bold text-nb-black/80">Archive Layout</h3>
      <Button
        variant="ghost"
        size="bare"
        onclick={() => { showNewCollectionInput = !showNewCollectionInput; }}
        class="p-1 hover:bg-nb-cream text-nb-black/60 text-sm"
        title="Create new collection"
      >
        <Icon name="add" class="text-base" />
      </Button>
    </div>

    {#if showNewCollectionInput}
      <div class="flex gap-2">
        <!-- svelte-ignore a11y_autofocus -->
        <input
          type="text"
          bind:value={newCollectionName}
          onkeydown={handleCreateKeyDown}
          placeholder="Collection name..."
          class="flex-1 px-2 py-1 text-sm border border-nb-black/20 rounded"
          autofocus
        />
        <Button
          variant="ghost"
          size="bare"
          onclick={handleCreateCollection}
          class="px-2 py-1 text-sm bg-nb-blue text-white hover:bg-nb-blue"
        >
          Create
        </Button>
      </div>
    {/if}
  </div>

  <!-- Collections list -->
  <div class="flex-1 overflow-y-auto">
    {#if archiveLayout.root.children.length === 0}
      <div class="p-6 text-center text-sm text-nb-black/50">
        <Icon name="inbox" class="text-4xl mb-2 block opacity-50" />
        <p>No collections yet</p>
        <p class="text-xs mt-1">Create one using the + button above, or drag items here</p>
      </div>
    {:else}
      {#each archiveLayout.root.children as collection (collection.id)}
        {@render collectionNode(collection)}
      {/each}
    {/if}

    <!-- Drop zone for creating new collection -->
    <div
      class={cn(
        'm-2 p-4 border-2 border-dashed text-center text-xs transition-all duration-150',
        isNewCollectionDragOver
          ? 'border-nb-blue bg-nb-blue/10 text-nb-blue font-medium scale-[1.02]'
          : 'border-nb-black/15 text-nb-black/30',
      )}
      ondragover={handleNewCollectionDragOver}
      ondragleave={handleNewCollectionDragLeave}
      ondrop={handleNewCollectionDrop}
      role="listitem"
    >
      <Icon
        name="add"
        class={cn('text-lg mb-1 block transition-colors', isNewCollectionDragOver ? 'text-nb-blue' : 'text-nb-black/20')}
      />
      {isNewCollectionDragOver ? 'Drop to create new collection' : 'Drop here for new collection'}
    </div>
  </div>

  <!-- Footer -->
  <div class="p-2 border-t border-nb-black/20 bg-nb-cream/40 text-xs text-nb-black/50">
    <div class="flex justify-between">
      <span>
        {archiveLayout.root.children.length} collection{archiveLayout.root.children.length !== 1 ? 's' : ''}
      </span>
      <span>
        {sourceManifests.manifests.length} manifest{sourceManifests.manifests.length !== 1 ? 's' : ''}
      </span>
    </div>
  </div>
</div>
