// src/widgets/NavigationHeader/NavigationHeader.tsx
/**
 * NavigationHeader Widget
 *
 * Composes: ArchiveHeader (from archive) + User Context
 *
 * This widget combines archive navigation with user context information
 * for the main application header.
 *
 * WIDGET COMPOSITION RULES:
 * - Pure composition only - no business logic
 * - Imports organisms from features (archive)
 * - Receives cx and fieldMode via props from template
 * - Exists strictly between Organisms and Pages
 */

import React from 'react';
import type { IIIFItem } from '@/src/shared/types';

import { ArchiveHeader } from '@/src/features/archive/ui/organisms/ArchiveHeader';
import type { ArchiveViewMode } from '@/src/features/archive/model';
import { HeaderTopBar } from './HeaderTopBar';
import { HeaderBreadcrumb } from './HeaderBreadcrumb';
import { HeaderUserMenu } from './HeaderUserMenu';

export interface NavigationHeaderProps {
  /** Current search/filter value */
  filter: string;
  /** Called when filter changes */
  onFilterChange: (value: string) => void;
  /** Current view mode */
  view: ArchiveViewMode;
  /** Called when view mode changes */
  onViewChange: (view: ArchiveViewMode) => void;
  /** Whether mobile layout is active */
  isMobile: boolean;
  /** Number of selected items */
  selectedCount: number;
  /** Whether selection has GPS metadata */
  selectionHasGPS: boolean;
  /** Callback to clear selection */
  onClearSelection: () => void;
  /** Callback to group selected items */
  onGroupIntoManifest: () => void;
  /** Callback to open map view */
  onOpenMap: () => void;
  /** Callback to edit metadata */
  onEditMetadata: () => void;
  /** Callback to batch edit */
  onBatchEdit: () => void;
  /** Contextual styles from template */
  cx: {
    surface: string;
    text: string;
    accent: string;
    border: string;
    divider: string;
    headerBg: string;
    textMuted: string;
    input: string;
    label: string;
    active: string;
    inactive: string;
    warningBg: string;
    pageBg: string;
  };
  /** Current field mode */
  fieldMode: boolean;
  /** Terminology function from template */
  t: (key: string) => string;
  /** User context - current user name */
  userName?: string;
  /** User context - current user avatar */
  userAvatar?: string;
  /** User context - organization name */
  organizationName?: string;
  /** Callback for user menu */
  onUserMenu?: () => void;
  /** Callback for settings */
  onSettings?: () => void;
  /** Callback for help */
  onHelp?: () => void;
  /** Current breadcrumb path */
  breadcrumbPath?: IIIFItem[];
  /** Callback when breadcrumb item is clicked */
  onBreadcrumbClick?: (item: IIIFItem) => void;
  /** Root item for breadcrumb */
  rootItem?: IIIFItem | null;
}

/**
 * NavigationHeader Widget
 *
 * Composes archive navigation with user context for the application header.
 * This widget sits between organisms and pages.
 *
 * @example
 * <FieldModeTemplate>
 *   {({ cx, fieldMode, t }) => (
 *     <NavigationHeader
 *       filter={filter}
 *       onFilterChange={setFilter}
 *       view={view}
 *       onViewChange={setView}
 *       isMobile={isMobile}
 *       selectedCount={selectedCount}
 *       selectionHasGPS={selectionHasGPS}
 *       onClearSelection={clearSelection}
 *       onGroupIntoManifest={handleGroup}
 *       onOpenMap={() => setView('map')}
 *       onEditMetadata={handleEdit}
 *       onBatchEdit={handleBatch}
 *       cx={cx}
 *       fieldMode={fieldMode}
 *       t={t}
 *       userName="Jane Doe"
 *       organizationName="Example Museum"
 *       onUserMenu={handleUserMenu}
 *       onSettings={handleSettings}
 *       breadcrumbPath={breadcrumbPath}
 *       onBreadcrumbClick={handleBreadcrumb}
 *       rootItem={root}
 *     />
 *   )}
 * </FieldModeTemplate>
 */
export const NavigationHeader: React.FC<NavigationHeaderProps> = ({
  filter,
  onFilterChange,
  view,
  onViewChange,
  isMobile,
  selectedCount,
  selectionHasGPS,
  onClearSelection,
  onGroupIntoManifest,
  onOpenMap,
  onEditMetadata,
  onBatchEdit,
  cx,
  fieldMode,
  t,
  userName,
  userAvatar,
  organizationName,
  onUserMenu,
  onSettings,
  onHelp,
  breadcrumbPath = [],
  onBreadcrumbClick,
  rootItem,
}) => {
  return (
    <header
      className={`flex flex-col border-b ${cx.border} ${cx.headerBg}`}
      role="banner"
    >
      {/* Top Row: Brand, Breadcrumb, User Context */}
      <div className="flex items-center justify-between px-4 py-2 border-b border-nb-black/20">
        {/* Left: Brand & Breadcrumb */}
        <div className="flex items-center gap-4 flex-1 min-w-0">
          <HeaderTopBar fieldMode={fieldMode} textColor={cx.text} />
          <HeaderBreadcrumb
            rootItem={rootItem}
            breadcrumbPath={breadcrumbPath}
            onBreadcrumbClick={onBreadcrumbClick}
            textMutedColor={cx.textMuted}
            t={t}
          />
        </div>

        {/* Right: User Context */}
        <HeaderUserMenu
          fieldMode={fieldMode}
          userName={userName}
          userAvatar={userAvatar}
          organizationName={organizationName}
          textMutedColor={cx.textMuted}
          onHelp={onHelp}
          onSettings={onSettings}
          onUserMenu={onUserMenu}
          t={t}
        />
      </div>

      {/* Bottom Row: Archive Controls (from archive feature) */}
      <ArchiveHeader
        filter={filter}
        onFilterChange={onFilterChange}
        view={view}
        onViewChange={onViewChange}
        isMobile={isMobile}
        selectedCount={selectedCount}
        selectionHasGPS={selectionHasGPS}
        onClearSelection={onClearSelection}
        onGroupIntoManifest={onGroupIntoManifest}
        onOpenMap={onOpenMap}
        onEditMetadata={onEditMetadata}
        onBatchEdit={onBatchEdit}
        cx={{
          surface: cx.surface,
          text: cx.text,
          accent: cx.accent,
        }}
        fieldMode={fieldMode}
      />
    </header>
  );
};

export default NavigationHeader;

// src/widgets/NavigationHeader/NavigationHeader.svelte
<!--
  NavigationHeader.svelte -- Application header composition widget
  ==================================================================
  React source: src/widgets/NavigationHeader/NavigationHeader.tsx (211 lines)

  Architecture:
    - Widget layer: PURE COMPOSITION of sub-components
    - Two-row header layout:
      Row 1 (top): Brand/logo + Breadcrumb trail + User menu
      Row 2 (bottom): ArchiveHeader (already migrated Svelte component)
    - Sub-components HeaderTopBar, HeaderBreadcrumb, HeaderUserMenu are inlined
      directly since they are simple enough not to warrant separate files.
    - ArchiveHeader IS migrated and rendered with bridged props.
-->
<script lang="ts">
  import type { IIIFItem } from '@/src/shared/types';
  import type { ContextualClassNames } from '@/src/shared/ui/molecules/ViewHeader/types';
  import Button from '@/src/shared/ui/atoms/Button.svelte';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';
  import { cn } from '@/src/shared/lib/cn';

  // ArchiveHeader is already migrated
  import ArchiveHeader from '@/src/features/archive/ui/organisms/ArchiveHeader.svelte';

  type ViewMode = 'grid' | 'list' | 'grouped';
  type SortMode = 'name' | 'date' | 'size';
  type SortDirection = 'asc' | 'desc';

  interface Props {
    filter: string;
    onFilterChange: (value: string) => void;
    view: ViewMode;
    onViewChange: (view: ViewMode) => void;
    isMobile: boolean;
    selectedCount: number;
    selectionHasGPS: boolean;
    onClearSelection: () => void;
    onGroupIntoManifest: () => void;
    onOpenMap: () => void;
    onEditMetadata: () => void;
    onBatchEdit: () => void;
    cx: ContextualClassNames;
    fieldMode: boolean;
    t: (key: string) => string;
    userName?: string;
    userAvatar?: string;
    organizationName?: string;
    onUserMenu?: () => void;
    onSettings?: () => void;
    onHelp?: () => void;
    breadcrumbPath?: IIIFItem[];
    onBreadcrumbClick?: (item: IIIFItem) => void;
    rootItem?: IIIFItem | null;
  }

  let {
    filter,
    onFilterChange,
    view,
    onViewChange,
    isMobile,
    selectedCount,
    selectionHasGPS,
    onClearSelection,
    onGroupIntoManifest,
    onOpenMap,
    onEditMetadata,
    onBatchEdit,
    cx,
    fieldMode,
    t,
    userName,
    userAvatar,
    organizationName,
    onUserMenu,
    onSettings,
    onHelp,
    breadcrumbPath = [],
    onBreadcrumbClick,
    rootItem,
  }: Props = $props();

  // ── Bridge: ArchiveHeader needs a bindable filter, but we receive callback ──
  // We use a local $state synced with the prop via $effect for two-way bridging.
  let localFilter = $state(filter);

  $effect(() => {
    // Sync prop -> local when parent changes it
    localFilter = filter;
  });

  // When localFilter changes from ArchiveHeader's bind:filter, notify parent
  $effect(() => {
    if (localFilter !== filter) {
      onFilterChange(localFilter);
    }
  });

  // ── ArchiveHeader needs additional props that NavigationHeader does not expose ──
  // These are internal defaults for the composed ArchiveHeader.
  let sortBy = $state<SortMode>('name');
  let sortDirection = $state<SortDirection>('asc');
  let groupByManifest = $state(false);
  let showViewerPanel = $state(false);
  let showInspectorPanel = $state(false);

  // ── Helpers ──
  function getItemLabel(item: IIIFItem): string {
    if (item.label) {
      const values = Object.values(item.label);
      if (values.length > 0 && values[0].length > 0) {
        return values[0][0];
      }
    }
    return item.id ?? 'Untitled';
  }
</script>

<header
  class={cn('flex flex-col border-b', cx.border, cx.headerBg)}
  role="banner"
>
  <!-- Row 1: Brand, Breadcrumb, User Context -->
  <div class={cn('flex items-center justify-between px-4 py-2 border-b border-nb-black/20')}>
    <!-- Left: Brand & Breadcrumb -->
    <div class="flex items-center gap-4 flex-1 min-w-0">
      <!-- HeaderTopBar (inlined): Application brand mark -->
      <div class="flex items-center gap-2 shrink-0">
        <div class={cn(
          'w-6 h-6 flex items-center justify-center',
          fieldMode ? 'bg-nb-yellow text-nb-black' : 'bg-nb-black text-nb-white'
        )}>
          <Icon name="grid_view" class="text-xs" />
        </div>
        <span class={cn('font-mono text-sm font-bold uppercase tracking-wide', cx.text)}>
          Field Studio
        </span>
      </div>

      <!-- HeaderBreadcrumb (inlined): Clickable breadcrumb trail -->
      {#if rootItem || breadcrumbPath.length > 0}
        <nav class="flex items-center gap-1 text-xs truncate" aria-label="Breadcrumb">
          {#if rootItem}
            <button
              class={cn(
                'hover:underline truncate max-w-[120px] transition-nb',
                cx.textMuted
              )}
              onclick={() => rootItem && onBreadcrumbClick?.(rootItem)}
              title={getItemLabel(rootItem)}
            >
              {getItemLabel(rootItem)}
            </button>
          {/if}
          {#each breadcrumbPath as crumb, i (crumb.id ?? i)}
            <span class={cn('opacity-40 select-none', cx.textMuted)}>/</span>
            <button
              class={cn(
                'hover:underline truncate max-w-[120px] transition-nb',
                i === breadcrumbPath.length - 1 ? cx.text : cx.textMuted
              )}
              onclick={() => onBreadcrumbClick?.(crumb)}
              title={getItemLabel(crumb)}
            >
              {getItemLabel(crumb)}
            </button>
          {/each}
        </nav>
      {/if}
    </div>

    <!-- Right: User Context (inlined HeaderUserMenu) -->
    <div class="flex items-center gap-3 shrink-0">
      {#if organizationName}
        <span class={cn('text-[10px] font-mono uppercase tracking-wide hidden sm:inline', cx.textMuted)}>
          {organizationName}
        </span>
      {/if}

      {#if userName}
        <div class="flex items-center gap-2">
          {#if userAvatar}
            <img
              src={userAvatar}
              alt={userName}
              class="w-5 h-5 rounded-full object-cover"
            />
          {:else}
            <div class={cn(
              'w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-bold',
              fieldMode ? 'bg-nb-yellow/30 text-nb-yellow' : 'bg-nb-black/10 text-nb-black/60'
            )}>
              {userName.charAt(0).toUpperCase()}
            </div>
          {/if}
          <span class={cn('text-xs font-mono hidden sm:inline', cx.textMuted)}>
            {userName}
          </span>
        </div>
      {/if}

      {#if onHelp}
        <Button variant="ghost" size="bare" onclick={onHelp} title="Help">
          <Icon name="help_outline" class={cn('text-sm', cx.textMuted)} />
        </Button>
      {/if}

      {#if onSettings}
        <Button variant="ghost" size="bare" onclick={onSettings} title="Settings">
          <Icon name="settings" class={cn('text-sm', cx.textMuted)} />
        </Button>
      {/if}

      {#if onUserMenu}
        <Button variant="ghost" size="bare" onclick={onUserMenu} title="User menu">
          <Icon name="more_vert" class={cn('text-sm', cx.textMuted)} />
        </Button>
      {/if}
    </div>
  </div>

  <!-- Row 2: Archive Controls (already migrated) -->
  <ArchiveHeader
    {cx}
    {fieldMode}
    bind:filter={localFilter}
    {view}
    onViewChange={onViewChange}
    {sortBy}
    onSortChange={(s) => sortBy = s}
    {sortDirection}
    onSortDirectionChange={(d) => sortDirection = d}
    {groupByManifest}
    onToggleGroupByManifest={() => groupByManifest = !groupByManifest}
    {selectedCount}
    {selectionHasGPS}
    {onClearSelection}
    {onGroupIntoManifest}
    {onOpenMap}
    {onEditMetadata}
    {onBatchEdit}
    {showViewerPanel}
    onToggleViewerPanel={() => showViewerPanel = !showViewerPanel}
    {showInspectorPanel}
    onToggleInspectorPanel={() => showInspectorPanel = !showInspectorPanel}
  />
</header>
