// components/Inspector.tsx

import React, { useState, useEffect, useRef, useCallback } from 'react';
import { IIIFItem, IIIFCanvas, AppSettings, IIIFManifest, getIIIFValue } from '../types';
import { Icon } from './Icon';
import { MuseumLabel } from './MuseumLabel';
import { ShareButton } from './ShareButton';
import { ProvenancePanel } from './ProvenancePanel';
import { GeoEditor } from './GeoEditor';
import { RESOURCE_TYPE_CONFIG, isFieldVisible, getFieldsByCategory } from '../constants';

interface InspectorProps {
  resource: IIIFItem | null;
  onUpdateResource: (r: Partial<IIIFItem>) => void;
  settings: AppSettings;
  visible: boolean;
  onClose: () => void;
  isMobile?: boolean;
}


const IIIF_SPECS: Record<string, { 
    desc: string, 
    implication: string,
}> = {
  'Collection': {
    desc: 'The master container for multiple research units. It groups Manifests into a cohesive archive.',
    implication: 'Treats nested items as part of a curated series. This level cannot have its own visual pixels, only child links.'
  },
  'Manifest': {
    desc: 'The primary unit of description. Represents a single physical artifact, document, or field notebook.',
    implication: 'The "Atomic" unit of research. All internal views are considered parts of ONE cohesive physical object.'
  },
  'Canvas': {
    desc: 'A virtual workspace where media is pinned. It defines the coordinates for all your scholarly notes.',
    implication: 'Pins media to a specific coordinate grid. Annotations created here are forever linked to these pixel addresses.'
  },
  'Range': {
    desc: 'A structural division within a manifest, like a chapter or section.',
    implication: 'Provides navigation structure for long or complex objects.'
  }
};

const DebouncedInput = ({ value, onChange, ...props }: any) => {
  const [innerValue, setInnerValue] = useState(value ?? '');
  const onChangeRef = useRef<(val: string) => void>(onChange);
  const timeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const isTyping = useRef<boolean>(false);

  // Keep onChange ref current without triggering effects
  onChangeRef.current = onChange;

  // Sync from external prop changes only when not actively typing
  useEffect(() => {
    if (!isTyping.current) {
      setInnerValue(value ?? '');
    }
  }, [value]);

  const handleChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const newVal = e.target.value;
    isTyping.current = true;
    setInnerValue(newVal);

    if (timeoutRef.current) clearTimeout(timeoutRef.current);
    timeoutRef.current = setTimeout(() => {
      onChangeRef.current(newVal);
      isTyping.current = false;
    }, 300);
  }, []);

  // Cleanup timeout on unmount
  useEffect(() => {
    return () => {
      if (timeoutRef.current) clearTimeout(timeoutRef.current);
    };
  }, []);

  return <input {...props} value={innerValue} onChange={handleChange} />;
};

const DebouncedTextarea = ({ value, onChange, ...props }: any) => {
  const [innerValue, setInnerValue] = useState(value ?? '');
  const onChangeRef = useRef<(val: string) => void>(onChange);
  const timeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const isTyping = useRef<boolean>(false);

  onChangeRef.current = onChange;

  useEffect(() => {
    if (!isTyping.current) {
      setInnerValue(value ?? '');
    }
  }, [value]);

  const handleChange = useCallback((e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const newVal = e.target.value;
    isTyping.current = true;
    setInnerValue(newVal);

    if (timeoutRef.current) clearTimeout(timeoutRef.current);
    timeoutRef.current = setTimeout(() => {
      onChangeRef.current(newVal);
      isTyping.current = false;
    }, 300);
  }, []);

  useEffect(() => {
    return () => {
      if (timeoutRef.current) clearTimeout(timeoutRef.current);
    };
  }, []);

  return <textarea {...props} value={innerValue} onChange={handleChange} />;
};

export const Inspector: React.FC<InspectorProps> = ({ resource, onUpdateResource, settings, visible, onClose, isMobile }) => {
  // Persist tab state per resource type in localStorage
  const getStoredTab = (resourceType: string): 'metadata' | 'provenance' | 'geo' | 'learn' => {
    try {
      const stored = localStorage.getItem(`inspector-tab-${resourceType}`);
      if (stored && ['metadata', 'provenance', 'geo', 'learn'].includes(stored)) {
        return stored as 'metadata' | 'provenance' | 'geo' | 'learn';
      }
    } catch (e) {
      // localStorage may be unavailable
    }
    return 'metadata';
  };

  const [tab, setTab] = useState<'metadata' | 'provenance' | 'geo' | 'learn'>(() =>
    resource ? getStoredTab(resource.type) : 'metadata'
  );
  const [showAddMenu, setShowAddMenu] = useState(false);

  // Restore tab when resource type changes
  useEffect(() => {
    if (resource?.type) {
      setTab(getStoredTab(resource.type));
    }
  }, [resource?.type]);

  // Persist tab when it changes
  useEffect(() => {
    if (resource?.type && tab) {
      try {
        localStorage.setItem(`inspector-tab-${resource.type}`, tab);
      } catch (e) {
        // localStorage may be unavailable
      }
    }
  }, [tab, resource?.type]);

  if (!visible || !resource) return null;

  const config = RESOURCE_TYPE_CONFIG[resource.type] || RESOURCE_TYPE_CONFIG['Content'];
  const spec = IIIF_SPECS[resource.type];
  
  const label = getIIIFValue(resource.label, settings.language) || '';
  const summary = getIIIFValue(resource.summary, settings.language) || '';

  const getPreviewUrl = (node: any): string | undefined => {
      if (node.thumbnail?.[0]?.id) return node.thumbnail[0].id;
      if (node.type === 'Canvas') {
          return node.items?.[0]?.items?.[0]?.body?.id || node._blobUrl;
      }
      if (node.type === 'Manifest' && node.items?.[0]) {
          return getPreviewUrl(node.items[0]);
      }
      return node._blobUrl;
  };

  const imageUrl = getPreviewUrl(resource);

  const handleUpdateMetadataField = (index: number, key: string, val: string) => {
      const newMeta = [...(resource.metadata || [])];
      newMeta[index] = { 
          label: { [settings.language]: [key] }, 
          value: { [settings.language]: [val] } 
      };
      onUpdateResource({ metadata: newMeta });
  };

  const handleAddMetadataField = (labelStr: string) => {
      const newMeta = [...(resource.metadata || []), { label: { [settings.language]: [labelStr] }, value: { [settings.language]: [''] } }];
      onUpdateResource({ metadata: newMeta });
      setShowAddMenu(false);
  };

  const handleRemoveMetadataField = (index: number) => {
      const newMeta = resource.metadata?.filter((_, i) => i !== index);
      onUpdateResource({ metadata: newMeta });
  };

  const inspectorStyles = isMobile 
    ? `fixed inset-0 z-[1100] bg-white flex flex-col animate-slide-in-right`
    : `w-80 bg-white border-l border-slate-200 flex flex-col h-full shadow-xl z-30 animate-slide-in-right shrink-0`;

  return (
    <aside className={inspectorStyles} aria-label="Resource Inspector">
        {/* Fixed Header */}
        <div className={`h-14 flex items-center justify-between px-4 border-b shrink-0 ${settings.fieldMode ? 'bg-black text-white border-slate-800' : 'bg-slate-50 border-slate-200'}`}>
             <div className="flex items-center gap-2">
                <Icon name={config.icon} className={`${config.colorClass} text-sm`}/>
                <span className={`text-xs font-black uppercase tracking-widest ${settings.fieldMode ? 'text-yellow-400' : config.colorClass}`}>Inspector</span>
             </div>
             <div className="flex items-center gap-2">
                <ShareButton item={resource} fieldMode={settings.fieldMode} />
                <button 
                    aria-label="Close Inspector"
                    onClick={onClose} 
                    className={`p-2 rounded-lg ${settings.fieldMode ? 'hover:bg-slate-800' : 'hover:bg-slate-200'}`}
                >
                    <Icon name="close"/>
                </button>
             </div>
        </div>

        {/* Tabs */}
        <div role="tablist" aria-label="Inspector tabs" className={`flex border-b shrink-0 ${settings.fieldMode ? 'bg-black border-slate-800' : 'bg-white'}`}>
            {['metadata', 'provenance', 'geo', 'learn'].map(t => (
                <button
                  key={t}
                  className={`flex-1 py-4 text-[10px] font-black uppercase tracking-widest transition-all ${tab === t ? (settings.fieldMode ? 'text-yellow-400 border-b-2 border-yellow-400' : 'text-iiif-blue border-b-2 border-iiif-blue bg-blue-50/20') : 'text-slate-400 hover:text-slate-600'}`}
                  onClick={() => setTab(t as any)}
                  aria-selected={tab === t}
                  role="tab"
                  aria-controls={`inspector-tab-${t}`}
                  id={`tab-${t}`}
                >
                  {t === 'provenance' ? 'History' : t === 'geo' ? 'Location' : t}
                </button>
            ))}
        </div>

      {/* Scrollable Content */}
      <div className={`flex-1 overflow-y-auto p-5 space-y-6 custom-scrollbar min-h-0 ${settings.fieldMode ? 'bg-black' : 'bg-white'}`}>
        {tab === 'metadata' && (
            <div role="tabpanel" id="inspector-tab-metadata" aria-labelledby="tab-metadata" className="space-y-6">
                {imageUrl && (
                    <div className={`aspect-video rounded-xl overflow-hidden border shadow-inner relative group ring-1 shrink-0 ${settings.fieldMode ? 'bg-slate-900 border-slate-800 ring-slate-800' : 'bg-slate-900 border-slate-200 ring-slate-100'}`}>
                        <img src={imageUrl} className="w-full h-full object-contain" alt="Preview" />
                    </div>
                )}

                <div className="space-y-4">
                    <div className="snappy-transition focus-within:scale-[1.01]">
                        <label htmlFor="archival-label" className={`block text-[10px] font-black mb-1 uppercase tracking-widest ${settings.fieldMode ? 'text-slate-500' : 'text-slate-400'}`}>Archival Label</label>
                        <DebouncedInput 
                            id="archival-label"
                            type="text" 
                            value={label} 
                            onChange={(val: string) => onUpdateResource({ label: { [settings.language]: [val] } })} 
                            className={`w-full text-sm p-4 rounded-lg outline-none font-bold shadow-sm border snappy-transition ${settings.fieldMode ? 'bg-slate-900 text-white border-slate-800 focus:border-yellow-400' : 'bg-white text-slate-900 border-slate-300 focus:ring-2 focus:ring-iiif-blue'}`} 
                        />
                    </div>

                    <div className="snappy-transition focus-within:scale-[1.01]">
                        <label htmlFor="scientific-summary" className={`block text-[10px] font-black mb-1 uppercase tracking-widest ${settings.fieldMode ? 'text-slate-500' : 'text-slate-400'}`}>Scientific Summary</label>
                        <DebouncedTextarea 
                            id="scientific-summary"
                            value={summary} 
                            onChange={(val: string) => onUpdateResource({ summary: { [settings.language]: [val] } })} 
                            className={`w-full text-sm p-4 rounded-lg outline-none min-h-[100px] leading-relaxed shadow-sm border snappy-transition ${settings.fieldMode ? 'bg-slate-900 text-white border-slate-800 focus:border-yellow-400' : 'bg-white text-slate-900 border-slate-300 focus:ring-2 focus:ring-iiif-blue'}`} 
                            placeholder="Describe context..."
                        />
                    </div>

                    <div className={`pt-4 border-t ${settings.fieldMode ? 'border-slate-800' : 'border-slate-100'}`}>
                        <div className="flex justify-between items-center mb-3">
                            <label className={`text-[10px] font-black uppercase tracking-widest ${settings.fieldMode ? 'text-slate-500' : 'text-slate-400'}`}>Field Metadata</label>
                            <div className="relative">
                                <button 
                                    aria-label="Add metadata field"
                                    aria-haspopup="true"
                                    aria-expanded={showAddMenu}
                                    onClick={() => setShowAddMenu(!showAddMenu)} 
                                    className={`text-[10px] font-bold uppercase tracking-tighter flex items-center gap-1 ${settings.fieldMode ? 'text-yellow-400' : 'text-iiif-blue'}`}
                                >
                                    Add Field <Icon name="expand_more" className="text-[10px]"/>
                                </button>
                                {showAddMenu && (
                                    <div className="absolute right-0 top-full mt-1 bg-white border border-slate-200 shadow-xl rounded-lg py-2 z-50 min-w-[140px] max-h-[200px] overflow-y-auto custom-scrollbar">
                                        {settings.metadataTemplate.map(prop => (
                                            <button key={prop} onClick={() => handleAddMetadataField(prop)} className="w-full px-4 py-1.5 text-left text-[10px] font-bold text-slate-600 hover:bg-blue-50 transition-colors">{prop}</button>
                                        ))}
                                    </div>
                                )}
                            </div>
                        </div>
                        <div className="space-y-3">
                            {(resource.metadata || []).map((md, idx) => {
                                const mKey = getIIIFValue(md.label, settings.language);
                                const mVal = getIIIFValue(md.value, settings.language);
                                return (
                                    <div key={idx} className={`group relative p-3 rounded-lg border snappy-transition shadow-sm focus-within:scale-[1.02] ${settings.fieldMode ? 'bg-slate-900 border-slate-800' : 'bg-slate-50 border-slate-200 hover:border-slate-300 hover:bg-white'}`}>
                                        <DebouncedInput 
                                            aria-label={`Field name for index ${idx + 1}`}
                                            className={`w-full text-[10px] font-black uppercase bg-transparent outline-none mb-1 border-b ${settings.fieldMode ? 'text-slate-500 border-slate-800 focus:border-slate-700' : 'text-slate-500 border-transparent focus:border-slate-200'}`}
                                            value={mKey}
                                            onChange={(val: string) => handleUpdateMetadataField(idx, val, mVal)}
                                        />
                                        <DebouncedInput 
                                            aria-label={`Field value for ${mKey}`}
                                            className={`w-full text-xs font-bold bg-transparent outline-none ${settings.fieldMode ? 'text-white' : 'text-slate-800'}`}
                                            value={mVal}
                                            onChange={(val: string) => handleUpdateMetadataField(idx, mKey, val)}
                                        />
                                        <button 
                                            aria-label={`Remove field ${mKey}`}
                                            onClick={() => handleRemoveMetadataField(idx)}
                                            className="absolute top-2 right-2 text-slate-300 hover:text-red-500 opacity-0 group-hover:opacity-100 transition-opacity"
                                        >
                                            <Icon name="close" className="text-xs"/>
                                        </button>
                                    </div>
                                );
                            })}
                        </div>
                    </div>

                    {/* Standard Fields (visible at standard+ complexity) */}
                    {isFieldVisible('rights', settings.metadataComplexity) && (
                        <div className={`pt-4 border-t ${settings.fieldMode ? 'border-slate-800' : 'border-slate-100'}`}>
                            <label htmlFor="rights-field" className={`block text-[10px] font-black mb-1 uppercase tracking-widest ${settings.fieldMode ? 'text-slate-500' : 'text-slate-400'}`}>
                                Rights Statement
                            </label>
                            <select
                                id="rights-field"
                                value={resource.rights || ''}
                                onChange={e => onUpdateResource({ rights: e.target.value || undefined })}
                                className={`w-full text-xs p-3 rounded-lg outline-none font-bold shadow-sm border ${settings.fieldMode ? 'bg-slate-900 text-white border-slate-800' : 'bg-white text-slate-900 border-slate-300 focus:ring-2 focus:ring-iiif-blue'}`}
                            >
                                <option value="">No rights statement</option>
                                <option value="https://creativecommons.org/publicdomain/zero/1.0/">CC0 - Public Domain</option>
                                <option value="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</option>
                                <option value="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</option>
                                <option value="http://rightsstatements.org/vocab/InC/1.0/">In Copyright</option>
                            </select>
                        </div>
                    )}

                    {isFieldVisible('navDate', settings.metadataComplexity) && (
                        <div className={`pt-4 border-t ${settings.fieldMode ? 'border-slate-800' : 'border-slate-100'}`}>
                            <label htmlFor="navdate-field" className={`block text-[10px] font-black mb-1 uppercase tracking-widest ${settings.fieldMode ? 'text-slate-500' : 'text-slate-400'}`}>
                                Navigation Date
                            </label>
                            <input
                                id="navdate-field"
                                type="date"
                                value={resource.navDate ? resource.navDate.split('T')[0] : ''}
                                onChange={e => onUpdateResource({ navDate: e.target.value ? new Date(e.target.value).toISOString() : undefined })}
                                className={`w-full text-xs p-3 rounded-lg outline-none font-bold shadow-sm border ${settings.fieldMode ? 'bg-slate-900 text-white border-slate-800' : 'bg-white text-slate-900 border-slate-300 focus:ring-2 focus:ring-iiif-blue'}`}
                            />
                            <p className={`text-[9px] mt-1 ${settings.fieldMode ? 'text-slate-600' : 'text-slate-400'}`}>
                                Used for timeline navigation in viewers
                            </p>
                        </div>
                    )}

                    {/* Advanced Fields (visible at advanced complexity only) */}
                    {isFieldVisible('behavior', settings.metadataComplexity) && (
                        <div className={`pt-4 border-t ${settings.fieldMode ? 'border-slate-800' : 'border-slate-100'}`}>
                            <label className={`block text-[10px] font-black mb-2 uppercase tracking-widest ${settings.fieldMode ? 'text-slate-500' : 'text-slate-400'}`}>
                                Behaviors
                                <span className={`ml-2 text-[8px] font-mono px-1.5 py-0.5 rounded ${settings.fieldMode ? 'bg-slate-800 text-slate-400' : 'bg-purple-100 text-purple-600'}`}>
                                    advanced
                                </span>
                            </label>
                            <div className="flex flex-wrap gap-1">
                                {(resource.behavior || []).map((b, i) => (
                                    <span key={i} className={`text-[9px] font-bold px-2 py-1 rounded-full ${settings.fieldMode ? 'bg-slate-800 text-yellow-400' : 'bg-purple-100 text-purple-700'}`}>
                                        {b}
                                        <button
                                            onClick={() => {
                                                const newBehaviors = resource.behavior?.filter((_, idx) => idx !== i);
                                                onUpdateResource({ behavior: newBehaviors?.length ? newBehaviors : undefined });
                                            }}
                                            className="ml-1 hover:text-red-500"
                                            aria-label={`Remove behavior ${b}`}
                                        >
                                            ×
                                        </button>
                                    </span>
                                ))}
                                {(!resource.behavior || resource.behavior.length === 0) && (
                                    <span className={`text-[9px] italic ${settings.fieldMode ? 'text-slate-600' : 'text-slate-400'}`}>
                                        No behaviors set
                                    </span>
                                )}
                            </div>
                        </div>
                    )}

                    {isFieldVisible('viewingDirection', settings.metadataComplexity) && (resource.type === 'Manifest' || resource.type === 'Range') && (
                        <div className={`pt-4 border-t ${settings.fieldMode ? 'border-slate-800' : 'border-slate-100'}`}>
                            <label htmlFor="viewingdir-field" className={`block text-[10px] font-black mb-1 uppercase tracking-widest ${settings.fieldMode ? 'text-slate-500' : 'text-slate-400'}`}>
                                Viewing Direction
                                <span className={`ml-2 text-[8px] font-mono px-1.5 py-0.5 rounded ${settings.fieldMode ? 'bg-slate-800 text-slate-400' : 'bg-purple-100 text-purple-600'}`}>
                                    advanced
                                </span>
                            </label>
                            <select
                                id="viewingdir-field"
                                value={(resource as IIIFManifest).viewingDirection || 'left-to-right'}
                                onChange={e => onUpdateResource({ viewingDirection: e.target.value as any })}
                                className={`w-full text-xs p-3 rounded-lg outline-none font-bold shadow-sm border ${settings.fieldMode ? 'bg-slate-900 text-white border-slate-800' : 'bg-white text-slate-900 border-slate-300 focus:ring-2 focus:ring-iiif-blue'}`}
                            >
                                <option value="left-to-right">Left to Right</option>
                                <option value="right-to-left">Right to Left</option>
                                <option value="top-to-bottom">Top to Bottom</option>
                                <option value="bottom-to-top">Bottom to Top</option>
                            </select>
                        </div>
                    )}

                    {/* Complexity indicator */}
                    <div className={`pt-4 border-t ${settings.fieldMode ? 'border-slate-800' : 'border-slate-100'}`}>
                        <div className={`flex items-center justify-between text-[9px] ${settings.fieldMode ? 'text-slate-600' : 'text-slate-400'}`}>
                            <span className="uppercase font-black tracking-widest">Field Complexity</span>
                            <span className={`font-mono px-2 py-0.5 rounded ${
                                settings.metadataComplexity === 'simple' ? 'bg-green-100 text-green-700' :
                                settings.metadataComplexity === 'standard' ? 'bg-blue-100 text-blue-700' :
                                'bg-purple-100 text-purple-700'
                            }`}>
                                {settings.metadataComplexity}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        )}

        {tab === 'provenance' && (
            <div role="tabpanel" id="inspector-tab-provenance" aria-labelledby="tab-provenance">
                <ProvenancePanel resourceId={resource.id} fieldMode={settings.fieldMode} />
            </div>
        )}

        {tab === 'geo' && (
            <div role="tabpanel" id="inspector-tab-geo" aria-labelledby="tab-geo" className="space-y-4 animate-in fade-in duration-300">
                <div className={`border rounded-lg overflow-hidden ${settings.fieldMode ? 'border-slate-800' : 'border-slate-200'}`}>
                    <GeoEditor
                        item={resource}
                        onChange={(navPlace) => onUpdateResource({ navPlace } as any)}
                        height={300}
                        editable={true}
                    />
                </div>
                <div className={`text-[10px] ${settings.fieldMode ? 'text-slate-500' : 'text-slate-400'}`}>
                    <p className="font-bold uppercase tracking-wider mb-1">About navPlace</p>
                    <p className="leading-relaxed">
                        The navPlace property associates a IIIF resource with a geographic location using GeoJSON.
                        This enables map-based discovery and navigation of archival materials.
                    </p>
                </div>
            </div>
        )}

        {tab === 'learn' && spec && (
            <div role="tabpanel" id="inspector-tab-learn" aria-labelledby="tab-learn" className="space-y-4 animate-in fade-in duration-300">
                <div className={`border p-5 rounded-2xl ${settings.fieldMode ? 'bg-slate-900 border-slate-800' : `${config.bgClass} ${config.borderClass.replace('200','300')}`}`}>
                    <h3 className={`text-sm font-black uppercase mb-2 flex items-center gap-2 ${settings.fieldMode ? 'text-yellow-400' : config.colorClass}`}>
                        <Icon name={config.icon} className="text-xs" /> {resource.type} Model
                    </h3>
                    <div className={`items-center gap-3 p-3 rounded-xl mb-4 shadow-sm flex ${settings.fieldMode ? 'bg-black/50 border border-slate-800' : 'bg-white/80 backdrop-blur-sm border border-blue-100/50'}`}>
                        <Icon name="psychology" className={settings.fieldMode ? 'text-yellow-400' : config.colorClass} />
                        <div>
                            <p className="text-[9px] font-black text-slate-400 uppercase">Archival Metaphor</p>
                            <p className={`text-xs font-bold ${settings.fieldMode ? 'text-white' : 'text-slate-700'}`}>{config.metaphor}</p>
                        </div>
                    </div>
                    <p className={`text-xs leading-relaxed font-medium mb-4 ${settings.fieldMode ? 'text-slate-400' : 'text-slate-600'}`}>{spec.desc}</p>
                </div>
                <MuseumLabel title="Archival Implication" type={settings.fieldMode ? 'spec' : 'exhibit'}>
                    {spec.implication}
                </MuseumLabel>
            </div>
        )}
      </div>
    </aside>
  );
};

// src/features/metadata-edit/ui/organisms/Inspector.svelte
<!--
  Inspector.svelte — Resource Inspector Panel (Svelte 5)
  ======================================================
  Migrated from: src/features/metadata-edit/ui/organisms/Inspector.tsx (427 lines)

  Side panel for inspecting and editing a single IIIF resource.
  Tabs: metadata, annotations, structure, learn, design.
  Includes resizable panel handle, tab persistence, and validation badges.

  Key Svelte 5 migration decisions:
  - React.memo eliminated (Svelte fine-grained reactivity handles this)
  - useResizablePanel -> resizable Svelte action from layout system
  - usePersistedTab -> $state + $effect with localStorage
  - useInspectorValidation -> pure validateResource() with $derived
  - useState/useCallback/useMemo -> $state/$derived/plain functions
  - useEffect for forceTab sync -> $effect
  - useEffect for annotation selection sync -> $effect
-->
<script module lang="ts">
  /** Allowed inspector tabs (Rule 2.F: static data in script module) */
  export const ALLOWED_TABS = ['metadata', 'annotations', 'structure', 'learn', 'design'] as const;
  export type InspectorTab = typeof ALLOWED_TABS[number];

  /** localStorage key for persisted tab selection */
  const TAB_STORAGE_KEY = 'inspector-tab';

  /** Time range for audio/video annotations */
  export interface TimeRange {
    start: number;
    end?: number;
  }

  /** Resource type visual config (inlined from RESOURCE_TYPE_CONFIG) */
  const RESOURCE_TYPE_CONFIG: Record<string, {
    icon: string;
    colorClass: string;
    bgClass: string;
    borderClass: string;
  }> = {
    'Collection': { icon: 'folder', colorClass: 'text-amber-600', bgClass: 'bg-amber-100', borderClass: 'border-amber-200' },
    'Manifest':   { icon: 'menu_book', colorClass: 'text-emerald-600', bgClass: 'bg-emerald-100', borderClass: 'border-emerald-200' },
    'Canvas':     { icon: 'crop_original', colorClass: 'text-blue-500', bgClass: 'bg-blue-100', borderClass: 'border-blue-200' },
    'Range':      { icon: 'segment', colorClass: 'text-indigo-500', bgClass: 'bg-indigo-100', borderClass: 'border-indigo-200' },
    'AnnotationPage': { icon: 'layers', colorClass: 'text-purple-500', bgClass: 'bg-purple-100', borderClass: 'border-purple-200' },
    'Annotation': { icon: 'chat_bubble', colorClass: 'text-teal-500', bgClass: 'bg-teal-100', borderClass: 'border-teal-200' },
    'Content':    { icon: 'image', colorClass: 'text-slate-500', bgClass: 'bg-slate-100', borderClass: 'border-slate-200' },
  };

  /** IIIF specification descriptions per resource type */
  const IIIF_SPECS: Record<string, { desc: string; implication: string }> = {
    'Collection': {
      desc: 'The master container for multiple research units. It groups Manifests into a cohesive archive.',
      implication: 'Treats nested items as part of a curated series. This level cannot have its own visual pixels, only child links.',
    },
    'Manifest': {
      desc: 'The primary unit of description. Represents a single physical artifact, document, or field notebook.',
      implication: 'The "Atomic" unit of research. All internal views are considered parts of ONE cohesive physical object.',
    },
    'Canvas': {
      desc: 'A virtual workspace where media is pinned. It defines the coordinates for all your scholarly notes.',
      implication: 'Pins media to a specific coordinate grid. Annotations created here are forever linked to these pixel addresses.',
    },
    'Range': {
      desc: 'A structural division within a manifest, like a chapter or section.',
      implication: 'Provides navigation structure for long or complex objects.',
    },
  };
</script>

<script lang="ts">
  import { cn } from '@/src/shared/lib/cn';
  import { getIIIFValue, isManifest } from '@/src/shared/types';
  import type { IIIFItem, IIIFAnnotation, IIIFCanvas, IIIFManifest } from '@/src/shared/types';
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import { PanelLayout } from '@/src/shared/ui/layout';
  import { resizable } from '@/src/shared/ui/layout';
  import type { ResizableParams } from '@/src/shared/ui/layout';
  import Button from '@/src/shared/ui/atoms/Button.svelte';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';
  import MuseumLabel from '@/src/shared/ui/molecules/MuseumLabel.svelte';
  import { validateResource, fixIssue, fixAll } from '../../lib/inspectorValidation';
  import type { ValidationIssue } from '../../lib/inspectorValidation';

  // Sub-components: MetadataFieldsPanel exists as stub; others are TODO placeholders
  // <!-- @migration: not yet migrated -->
  // import MetadataFieldsPanel from '../molecules/MetadataFieldsPanel.svelte';
  // import AnnotationCreateForm from '../atoms/AnnotationCreateForm.svelte';
  // import AnnotationsTabPanel from '../molecules/AnnotationsTabPanel.svelte';
  // import StructureTabPanel from '../molecules/StructureTabPanel.svelte';
  // import ShareButton from '../atoms/ShareButton.svelte';

  // ---------------------------------------------------------------------------
  // Props
  // ---------------------------------------------------------------------------

  interface Props {
    resource: IIIFItem | null;
    onUpdateResource: (r: Partial<IIIFItem>) => void;
    cx: ContextualClassNames;
    fieldMode: boolean;
    language?: string;
    abstractionLevel?: 'simple' | 'standard' | 'advanced';
    visible: boolean;
    onClose: () => void;
    isMobile?: boolean;
    /** Optional custom design tab content snippet */
    designTab?: import('svelte').Snippet;
    annotations?: IIIFAnnotation[];
    canvases?: IIIFCanvas[];
    annotationModeActive?: boolean;
    annotationDrawingState?: {
      pointCount: number;
      isDrawing: boolean;
      canSave: boolean;
    };
    annotationText?: string;
    onAnnotationTextChange?: (text: string) => void;
    annotationMotivation?: 'commenting' | 'tagging' | 'describing';
    onAnnotationMotivationChange?: (motivation: 'commenting' | 'tagging' | 'describing') => void;
    onSaveAnnotation?: () => void;
    onClearAnnotation?: () => void;
    mediaType?: 'image' | 'video' | 'audio' | 'other';
    timeRange?: TimeRange | null;
    currentPlaybackTime?: number;
    forceTab?: InspectorTab;
    onDeleteAnnotation?: (annotationId: string) => void;
    onEditAnnotation?: (annotationId: string, newText: string) => void;
    onStartAnnotation?: () => void;
    selectedAnnotationId?: string | null;
  }

  let {
    resource,
    onUpdateResource,
    cx,
    fieldMode,
    language = 'en',
    abstractionLevel = 'standard',
    visible,
    onClose,
    isMobile = false,
    designTab,
    annotations = [],
    canvases = [],
    annotationModeActive = false,
    annotationDrawingState,
    annotationText = '',
    onAnnotationTextChange,
    annotationMotivation = 'commenting',
    onAnnotationMotivationChange,
    onSaveAnnotation,
    onClearAnnotation,
    mediaType,
    timeRange,
    currentPlaybackTime,
    forceTab,
    onDeleteAnnotation,
    onEditAnnotation,
    onStartAnnotation,
    selectedAnnotationId: selectedAnnotationIdProp,
  }: Props = $props();

  // ---------------------------------------------------------------------------
  // Tab persistence (localStorage + $state)
  // ---------------------------------------------------------------------------

  function loadPersistedTab(): InspectorTab {
    try {
      const stored = localStorage.getItem(TAB_STORAGE_KEY);
      if (stored && ALLOWED_TABS.includes(stored as InspectorTab)) {
        return stored as InspectorTab;
      }
    } catch { /* localStorage unavailable */ }
    return 'metadata';
  }

  let tab = $state<InspectorTab>(loadPersistedTab());

  // Persist tab selection
  $effect(() => {
    try {
      localStorage.setItem(TAB_STORAGE_KEY, tab);
    } catch { /* ignore */ }
  });

  // Force tab when annotation mode is activated (or external forceTab changes)
  $effect(() => {
    if (forceTab && ALLOWED_TABS.includes(forceTab)) {
      tab = forceTab;
    }
  });

  // ---------------------------------------------------------------------------
  // Internal annotation selection state
  // ---------------------------------------------------------------------------

  let selectedAnnotationId = $state<string | null>(null);

  // Sync external annotation selection (from viewer click) to internal state
  $effect(() => {
    if (selectedAnnotationIdProp !== undefined) {
      selectedAnnotationId = selectedAnnotationIdProp;
    }
  });

  function toggleAnnotationSelection(annotationId: string) {
    selectedAnnotationId = selectedAnnotationId === annotationId ? null : annotationId;
  }

  // ---------------------------------------------------------------------------
  // Validation (pure computation via $derived)
  // ---------------------------------------------------------------------------

  let validationResult = $derived(
    resource ? validateResource(resource, resource.type) : { issues: [], errorCount: 0, warningCount: 0, infoCount: 0, autoFixableIssues: [], isValid: true }
  );

  let validationIssues = $derived(validationResult.issues);

  function getFieldValidation(fieldName: string) {
    const fieldIssues = validationIssues.filter(i => i.field === fieldName);
    if (fieldIssues.length === 0) return { status: 'pristine' as const };
    const firstIssue = fieldIssues[0];
    return {
      status: 'invalid' as const,
      message: firstIssue.title,
      fix: firstIssue.autoFixable ? () => {
        const fixed = fixIssue(resource!, firstIssue);
        if (fixed) onUpdateResource(fixed);
      } : undefined,
    };
  }

  let labelValidation = $derived(getFieldValidation('label'));
  let summaryValidation = $derived(getFieldValidation('summary'));

  function handleFixIssue(issue: ValidationIssue) {
    if (!resource) return;
    const fixed = fixIssue(resource, issue);
    if (fixed) onUpdateResource(fixed);
  }

  function handleFixAll() {
    if (!resource) return;
    const fixed = fixAll(resource, validationResult.autoFixableIssues);
    if (fixed) onUpdateResource(fixed);
  }

  // ---------------------------------------------------------------------------
  // Derived display values
  // ---------------------------------------------------------------------------

  let config = $derived(
    resource ? (RESOURCE_TYPE_CONFIG[resource.type] || RESOURCE_TYPE_CONFIG['Content']) : RESOURCE_TYPE_CONFIG['Content']
  );

  let spec = $derived(resource ? IIIF_SPECS[resource.type] : undefined);

  let label = $derived(
    resource ? getIIIFValue(resource.label, language) || '' : ''
  );

  let summary = $derived(
    resource ? getIIIFValue(resource.summary, language) || '' : ''
  );

  // Determine available tabs
  let availableTabs = $derived.by((): InspectorTab[] => {
    const tabs: InspectorTab[] = ['metadata', 'annotations'];
    if (resource && isManifest(resource)) tabs.push('structure');
    tabs.push('learn');
    if (designTab) tabs.push('design');
    return tabs;
  });

  // Tab badge computation
  function getTabBadge(tabName: string): { count?: number; dotColor?: string } {
    switch (tabName) {
      case 'metadata': {
        const errorCount = validationIssues.filter(i => i.severity === 'error').length;
        if (errorCount > 0) return { count: errorCount, dotColor: 'bg-nb-red' };
        if (validationIssues.length > 0) return { count: validationIssues.length };
        return {};
      }
      case 'annotations':
        return annotations.length > 0 ? { count: annotations.length } : {};
      case 'structure': {
        const rangeCount = resource && isManifest(resource)
          ? (resource as IIIFManifest).structures?.length || 0
          : 0;
        return rangeCount > 0 ? { count: rangeCount } : {};
      }
      default:
        return {};
    }
  }

  // ---------------------------------------------------------------------------
  // Resizable panel config
  // ---------------------------------------------------------------------------

  let resizableParams: ResizableParams = {
    id: 'inspector',
    size: 320,
    min: 280,
    max: 480,
    direction: 'horizontal',
  };

  // Track resize state for visual indicator
  let isResizing = $state(false);

  // ---------------------------------------------------------------------------
  // Styling
  // ---------------------------------------------------------------------------

  let inspectorStyles = $derived(
    isMobile
      ? cn(
          'fixed inset-0 z-[1100] flex flex-col animate-slide-in-right',
          fieldMode ? 'bg-nb-black' : 'bg-nb-white'
        )
      : cn(
          'border-l-2 flex flex-col h-full z-30 animate-slide-in-right shrink-0 relative panel-fixed inspector-panel',
          fieldMode ? 'bg-nb-black border-l-nb-yellow/30' : 'bg-nb-white border-l-nb-black/20'
        )
  );
</script>

{#if visible && resource}
  <aside
    class={inspectorStyles}
    use:resizable={isMobile ? undefined : resizableParams}
    aria-label="Resource Inspector"
  >
    <PanelLayout bodyClass={cn('p-4 space-y-4 custom-scrollbar', cx.pageBg)}>
      {#snippet header()}
        <!-- Title bar -- unified StatusBar style -->
        <div class={cn(
          'h-header-compact flex items-center justify-between px-3',
          fieldMode ? 'bg-nb-black' : 'bg-nb-cream'
        )}>
          <div class="flex items-center gap-2">
            <Icon name={config.icon} class={cn('text-sm', fieldMode ? 'text-nb-yellow' : 'text-nb-black')} />
            <span class={cn(
              'text-xs font-bold uppercase tracking-wider font-mono',
              fieldMode ? 'text-nb-yellow' : 'text-nb-black'
            )}>
              Inspector
            </span>
          </div>
          <div class="flex items-center gap-2">
            <!-- TODO: migrate ShareButton -->
            <!-- <ShareButton item={resource} fieldMode={fieldMode} /> -->
            <Button variant="ghost" size="bare"
              aria-label="Close Inspector"
              onclick={onClose}
              class={cn('p-2', fieldMode ? 'text-nb-yellow/60 hover:text-nb-yellow' : 'text-nb-black/40 hover:text-nb-black')}
            >
              <Icon name="close" />
            </Button>
          </div>
        </div>

        <!-- Tabs -- sub-header style -->
        <div
          role="tablist"
          aria-label="Inspector tabs"
          class={cn(
            'flex px-2 gap-1 border-b-2 shrink-0',
            fieldMode ? 'bg-nb-black border-nb-yellow/30' : 'bg-nb-white border-nb-black/20'
          )}
        >
          {#each availableTabs as tabName (tabName)}
            {@const badge = getTabBadge(tabName)}
            <Button variant="ghost" size="bare"
              class={cn(
                'py-2.5 px-3 text-nb-caption font-bold uppercase tracking-wider font-mono transition-nb border-b-2',
                tab === tabName ? cx.active : cx.inactive
              )}
              onclick={() => { tab = tabName; }}
              aria-selected={tab === tabName}
              role="tab"
            >
              <span class="flex items-center justify-center gap-1">
                {tabName}
                {#if badge.count !== undefined && badge.count > 0}
                  <span class={cn(
                    'text-[8px] px-1.5 py-0.5',
                    fieldMode ? 'bg-nb-black' : 'bg-nb-cream'
                  )}>
                    {badge.count}
                  </span>
                {/if}
                {#if badge.dotColor}
                  <span class={cn('w-1.5 h-1.5 rounded-full shrink-0', badge.dotColor)} />
                {/if}
                {#if tabName === 'annotations' && annotationModeActive}
                  <span class={cn(
                    'w-1.5 h-1.5 animate-pulse ml-1',
                    fieldMode ? 'bg-nb-yellow' : 'bg-nb-blue'
                  )} />
                {/if}
              </span>
            </Button>
          {/each}
        </div>
      {/snippet}

      {#snippet body()}
        <!-- Metadata Tab -->
        {#if tab === 'metadata'}
          <!-- TODO: migrate MetadataFieldsPanel -->
          <div role="tabpanel" class="space-y-4">
            <div class={cn('p-3 border text-xs', fieldMode ? 'border-nb-yellow/30 text-nb-yellow/60' : 'border-nb-black/10 text-nb-black/50')}>
              MetadataFieldsPanel placeholder -- pending migration.
              Resource: {resource.type} "{label}"
              {#if validationIssues.length > 0}
                <div class="mt-2">
                  {validationIssues.length} validation issue{validationIssues.length === 1 ? '' : 's'}
                  {#if validationResult.autoFixableIssues.length > 0}
                    ({validationResult.autoFixableIssues.length} auto-fixable)
                  {/if}
                </div>
              {/if}
            </div>
          </div>
        {/if}

        <!-- Annotations Tab -->
        {#if tab === 'annotations'}
          <div role="tabpanel" class="space-y-4">
            {#if annotationModeActive}
              <!-- TODO: migrate AnnotationCreateForm -->
              <div class={cn('p-3 border text-xs', fieldMode ? 'border-nb-yellow/30 text-nb-yellow/60' : 'border-nb-black/10 text-nb-black/50')}>
                AnnotationCreateForm placeholder -- pending migration.
                {#if mediaType}Media type: {mediaType}{/if}
                {#if annotationDrawingState?.canSave}
                  <div class="mt-1">Ready to save annotation.</div>
                {/if}
              </div>
            {/if}

            <!-- TODO: migrate AnnotationsTabPanel -->
            <div class={cn('p-3 border text-xs', fieldMode ? 'border-nb-yellow/30 text-nb-yellow/60' : 'border-nb-black/10 text-nb-black/50')}>
              AnnotationsTabPanel placeholder -- pending migration.
              {annotations.length} annotation{annotations.length === 1 ? '' : 's'}
              {#if onStartAnnotation}
                <div class="mt-2">
                  <Button variant="ghost" size="bare"
                    onclick={onStartAnnotation}
                    class={cn('text-xs underline', fieldMode ? 'text-nb-yellow' : 'text-nb-blue')}
                  >
                    + Add annotation
                  </Button>
                </div>
              {/if}
            </div>
          </div>
        {/if}

        <!-- Structure Tab -->
        {#if tab === 'structure' && resource && isManifest(resource)}
          <div role="tabpanel">
            <!-- TODO: migrate StructureTabPanel -->
            <div class={cn('p-3 border text-xs', fieldMode ? 'border-nb-yellow/30 text-nb-yellow/60' : 'border-nb-black/10 text-nb-black/50')}>
              StructureTabPanel placeholder -- pending migration.
              {(resource as IIIFManifest).structures?.length || 0} range{((resource as IIIFManifest).structures?.length || 0) === 1 ? '' : 's'}
            </div>
          </div>
        {/if}

        <!-- Learn Tab -->
        {#if tab === 'learn' && spec}
          <div role="tabpanel" class="space-y-4">
            <div class={cn(
              'border p-4',
              fieldMode ? 'bg-nb-black border-nb-black' : cn(config.bgClass, config.borderClass)
            )}>
              <h3 class={cn(
                'text-sm font-bold uppercase mb-2 flex items-center gap-2',
                fieldMode ? 'text-nb-yellow' : config.colorClass
              )}>
                <Icon name={config.icon} class="text-xs" />
                {resource.type} Model
              </h3>
              <p class={cn(
                'text-xs leading-relaxed font-medium mb-3',
                fieldMode ? 'text-nb-yellow/40' : 'text-nb-black/60'
              )}>
                {spec.desc}
              </p>
            </div>
            <MuseumLabel title="Archival Implication" type={fieldMode ? 'spec' : 'exhibit'}>
              {spec.implication}
            </MuseumLabel>
          </div>
        {/if}

        <!-- Design Tab -->
        {#if tab === 'design' && designTab}
          <div role="tabpanel">
            {@render designTab()}
          </div>
        {/if}
      {/snippet}
    </PanelLayout>

    <!-- Resize Handle - Desktop Only -->
    {#if !isMobile}
      <div
        data-resize-handle
        class={cn(
          'absolute left-0 top-0 bottom-0 w-1 z-30 group',
          'cursor-col-resize',
          'transition-nb',
          'hover:bg-nb-black/20',
          isResizing && (fieldMode ? 'bg-nb-yellow/30' : 'bg-iiif-blue/30')
        )}
        onpointerdown={() => { isResizing = true; }}
        onpointerup={() => { isResizing = false; }}
      >
        <div
          class={cn(
            'absolute left-0 top-1/2 -translate-y-1/2',
            'w-1 h-12',
            'transition-nb',
            'opacity-0 group-hover:opacity-100 group-focus:opacity-100',
            isResizing
              ? (fieldMode ? 'bg-nb-yellow opacity-100' : 'bg-iiif-blue opacity-100')
              : (fieldMode ? 'bg-nb-yellow/60 group-hover:bg-nb-yellow' : 'bg-nb-black/40 group-hover:bg-iiif-blue')
          )}
        />
      </div>
    {/if}
  </aside>
{/if}
