// src/shared/ui/atoms/Card.svelte
<!--
  Card - Elevated surface container

  ORIGINAL: ui/primitives/Card.tsx (70 lines)
  CSS custom properties for theming factory compatibility.
  Neobrutalist: zero border-radius, offset shadow, thick borders.
-->
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    header?: Snippet;
    footer?: Snippet;
    children?: Snippet;
    selected?: boolean;
    disabled?: boolean;
    class?: string;
    style?: string;
    [key: string]: unknown;
  }

  let {
    header,
    footer,
    children,
    selected = false,
    disabled = false,
    class: className = '',
    style: userStyle = '',
    ...rest
  }: Props = $props();

  let cardStyle = $derived.by(() => {
    const parts = [
      'display: flex',
      'flex-direction: column',
      'border-radius: 0',
      `border: 2px solid ${selected ? 'var(--theme-accent-primary, #0055FF)' : 'var(--theme-border-default, #000)'}`,
      `background-color: ${selected ? 'var(--theme-surface-accent, #FFF8E7)' : 'var(--theme-surface-primary, #FFF)'}`,
      'box-shadow: var(--theme-shadow-sm, 2px 2px 0 0 #000)',
      'transition: box-shadow 0.1s linear, border-color 0.1s linear',
    ];
    if (disabled) {
      parts.push('opacity: 0.6', 'pointer-events: none');
    }
    if (userStyle) parts.push(userStyle);
    return parts.join('; ');
  });

  const dividerStyle = 'border-top: 1px solid var(--theme-border-default, #000); margin: 0';
</script>

<div style={cardStyle} class={className || undefined} {...rest}>
  {#if header}
    <div style="padding: 0.75rem">{@render header()}</div>
    {#if children || footer}
      <hr style={dividerStyle} />
    {/if}
  {/if}
  {#if children}
    <div style="padding: 0.75rem; flex: 1">{@render children()}</div>
  {/if}
  {#if footer}
    {#if header || children}
      <hr style={dividerStyle} />
    {/if}
    <div style="padding: 0.75rem">{@render footer()}</div>
  {/if}
</div>

// ui/primitives/Card.tsx
/**
 * Card - Atomic UI Primitive
 *
 * Elevated surface container. Zero business logic — styling is
 * entirely derived from design tokens. Supports header/footer
 * slot composition for molecule-level assembly.
 */

import React from 'react';
import { COLORS, ELEVATION, INTERACTION, LAYOUT, SPACING } from '../../designSystem';

export interface CardProps extends React.HTMLAttributes<HTMLDivElement> {
  /** Content rendered in the card header region */
  header?: React.ReactNode;
  /** Content rendered in the card footer region */
  footer?: React.ReactNode;
  /** Whether the card is in a selected/active state */
  selected?: boolean;
  /** Whether the card is in a disabled/archived state */
  disabled?: boolean;
}

export const Card: React.FC<CardProps> = ({
  header,
  footer,
  selected = false,
  disabled = false,
  children,
  style,
  ...props
}) => {
  const cardStyle: React.CSSProperties = {
    display: 'flex',
    flexDirection: 'column',
    borderRadius: LAYOUT.borderRadius.lg,
    border: `1px solid ${selected ? COLORS.primary[500] : COLORS.border.default}`,
    backgroundColor: selected ? COLORS.primary[50] : COLORS.background.elevated,
    boxShadow: ELEVATION.sm,
    transition: `box-shadow ${INTERACTION.duration.base} ${INTERACTION.easing.default}, border-color ${INTERACTION.duration.base} ${INTERACTION.easing.default}`,
    opacity: disabled ? 0.6 : 1,
    pointerEvents: disabled ? 'none' : undefined,
    ...style,
  };

  const dividerStyle: React.CSSProperties = {
    borderTop: `1px solid ${COLORS.border.default}`,
    margin: 0,
  };

  return (
    <div style={cardStyle} {...props}>
      {header && (
        <>
          <div style={{ padding: SPACING[3] }}>{header}</div>
          {(children || footer) && <hr style={dividerStyle} />}
        </>
      )}
      {children && (
        <div style={{ padding: SPACING[3], flex: 1 }}>{children}</div>
      )}
      {footer && (
        <>
          {(header || children) && <hr style={dividerStyle} />}
          <div style={{ padding: SPACING[3] }}>{footer}</div>
        </>
      )}
    </div>
  );
};
