// src/features/structure-view/ui/organisms/StructureTreeView.tsx
/**
 * Structure Tree View Organism
 *
 * Main tree view component for the structure feature.
 * Composes molecules: TreeNodeItem, StructureToolbar, EmptyStructure, VirtualTreeList
 * Uses model: useStructureTree
 *
 * ATOMIC DESIGN:
 * - Organism level: has business logic via hook
 * - Composes molecules and atoms
 * - No direct service calls
 *
 * FEATURES:
 * - Virtual scrolling for 1000+ nodes
 * - Search/filter with auto-expand
 * - Drag-drop visual feedback
 * - Mobile responsive (adaptive indentation)
 * - Keyboard navigation support
 */

import React, { useCallback, useEffect, useRef, useState } from 'react';
import type { IIIFItem } from '@/src/shared/types';
import { EmptyStructure, StructureToolbar, VirtualTreeList } from '../molecules';
import { TreeSearchBar } from '../atoms';
import { useStructureTree } from '../../model/useStructureTree';
import type { DropPosition } from '../atoms/DropIndicator';
import { useResponsive } from '@/src/shared/lib/hooks';

// Feature flags for gradual rollout
const FEATURES = {
  TREE_VIRTUALIZATION: true,
  TREE_SEARCH: true,
};

interface StructureTreeViewProps {
  root: IIIFItem | null;
  onUpdate?: (newRoot: IIIFItem) => void;
  onSelect?: (id: string) => void;
  onOpen?: (item: IIIFItem) => void;
  selectedId?: string | null;
  className?: string;
  /** Height of the tree container (default: 100% of parent) */
  containerHeight?: number;
  /** Enable field mode theming */
  fieldMode?: boolean;
}

export const StructureTreeView: React.FC<StructureTreeViewProps> = ({
  root,
  onUpdate,
  onSelect,
  onOpen,
  selectedId,
  className = '',
  containerHeight = 400,
  fieldMode = false,
}) => {
  const { isMobile, isTablet } = useResponsive();
  const scrollContainerRef = useRef<HTMLDivElement | null>(null);

  // Tree state and operations
  const {
    flattenedNodes,
    filteredNodes,
    selectedIds,
    selectNode,
    selectRange,
    clearSelection,
    toggleExpanded,
    expandAll,
    collapseAll,
    draggingId,
    setDraggingId,
    setDropTargetId,
    canDrop,
    findNode,
    treeStats,
    filterQuery,
    setFilterQuery,
    matchCount,
    setScrollContainerRef,
  } = useStructureTree({ root, onUpdate });

  // Sync scroll container ref
  useEffect(() => {
    if (scrollContainerRef.current) {
      setScrollContainerRef(scrollContainerRef.current);
    }
  }, [setScrollContainerRef]);

  // Sync external selection
  React.useEffect(() => {
    if (selectedId && !selectedIds.has(selectedId)) {
      selectNode(selectedId, false);
    }
  }, [selectedId]); // eslint-disable-line react-hooks/exhaustive-deps

  // Notify parent of selection changes
  React.useEffect(() => {
    if (onSelect && selectedIds.size === 1) {
      const [id] = selectedIds;
      onSelect(id);
    }
  }, [selectedIds, onSelect]);

  // Keyboard shortcut: Ctrl+F to focus search
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'f') {
        e.preventDefault();
        const searchInput = document.getElementById('tree-search-input');
        searchInput?.focus();
      }
    };
    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, []);

  // Handle node selection
  const handleSelect = useCallback(
    (id: string, additive: boolean) => {
      selectNode(id, additive);
    },
    [selectNode]
  );

  // Handle drag start
  const handleDragStart = useCallback(
    (id: string) => {
      setDraggingId(id);
    },
    [setDraggingId]
  );

  // Handle drag end
  const handleDragEnd = useCallback(() => {
    setDraggingId(null);
    setDropTargetId(null);
  }, [setDraggingId, setDropTargetId]);

  // Handle drop with position
  const handleDrop = useCallback(
    (targetId: string, position?: DropPosition) => {
      if (!draggingId) return;

      if (canDrop(draggingId, targetId)) {
        const draggedNode = findNode(draggingId);
        const targetNode = findNode(targetId);

        if (draggedNode && targetNode && onUpdate && root) {
          // TODO: Implement actual move using hierarchy utils with position
          console.log('Move', draggedNode.type, 'to', targetNode.type, 'position:', position);
        }
      }

      setDraggingId(null);
      setDropTargetId(null);
    },
    [draggingId, canDrop, findNode, onUpdate, root, setDraggingId, setDropTargetId]
  );

  // Handle double click to open
  const handleDoubleClick = useCallback(
    (id: string) => {
      const node = findNode(id);
      if (node && onOpen) {
        onOpen(node);
      }
    },
    [findNode, onOpen]
  );

  // Calculate responsive indentation
  const indentPerLevel = isMobile ? 8 : isTablet ? 12 : 16;

  // Apply responsive indentation to nodes
  const nodesWithResponsiveIndent = React.useMemo(() => {
    const nodesToRender = filterQuery ? filteredNodes : flattenedNodes;
    return nodesToRender.map((node) => ({
      ...node,
      depth: node.depth, // Keep original depth, will be used with responsive indent
    }));
  }, [flattenedNodes, filteredNodes, filterQuery]);

  if (!root) {
    return <EmptyStructure className={className} />;
  }

  return (
    <div
      className={`
        flex flex-col h-full
        bg-nb-black
        border border-nb-black/20  overflow-hidden
        shadow-brutal-sm
        ${className}
      `}
    >
      {/* Search Bar - refined with archival aesthetic */}
      {FEATURES.TREE_SEARCH && (
        <div className="p-4 border-b border-nb-black/20 bg-nb-black/30">
          <TreeSearchBar
            query={filterQuery}
            onQueryChange={setFilterQuery}
            matchCount={matchCount}
            totalCount={flattenedNodes.length}
          />
        </div>
      )}

      <StructureToolbar
        totalNodes={filterQuery ? matchCount : flattenedNodes.length}
        selectedCount={selectedIds.size}
        onExpandAll={expandAll}
        onCollapseAll={collapseAll}
        onClearSelection={clearSelection}
        abstractionLevel={fieldMode ? 'advanced' : 'standard'}
      />

      {/* Tree Content - Virtual or Standard */}
      {FEATURES.TREE_VIRTUALIZATION ? (
        <VirtualTreeList
          nodes={nodesWithResponsiveIndent}
          containerHeight={containerHeight}
          onSelect={handleSelect}
          onToggleExpand={toggleExpanded}
          onDragStart={handleDragStart}
          onDragEnd={handleDragEnd}
          onDrop={handleDrop}
          onDoubleClick={handleDoubleClick}
          onScrollContainerRef={(el) => {
            scrollContainerRef.current = el;
            setScrollContainerRef(el);
          }}
          className="flex-1"
        />
      ) : (
        <div className="flex-1 overflow-y-auto" ref={scrollContainerRef}>
          {nodesWithResponsiveIndent.map((node) => (
            <div key={node.id} onDoubleClick={() => handleDoubleClick(node.id)}>
              {/* Note: Would need to update TreeNodeItem to accept responsive indent */}
            </div>
          ))}
        </div>
      )}

      {/* Status bar - abstraction-aware, reduced visual noise */}
      {treeStats && (
        <div className="px-4 py-2.5 border-t border-nb-black/20 bg-nb-black/80 text-sm text-nb-black/50 flex items-center justify-between">
          <span className="font-serif">
            {(() => {
              // Convert technical types to friendly counts
              const counts = treeStats.typeCounts;
              const items = (counts.Canvas || 0) + (counts.Annotation || 0);
              const albums = counts.Collection || 0;
              const groups = counts.Manifest || 0;
              
              const parts = [];
              if (albums > 0) parts.push(`${albums} ${albums === 1 ? 'album' : 'albums'}`);
              if (groups > 0) parts.push(`${groups} ${groups === 1 ? 'group' : 'groups'}`);
              if (items > 0) parts.push(`${items} ${items === 1 ? 'item' : 'items'}`);
              
              return parts.join(' · ') || 'Empty archive';
            })()}
          </span>
          {filterQuery && (
            <span className="text-nb-orange font-medium">
              Showing {matchCount} of {flattenedNodes.length}
            </span>
          )}
        </div>
      )}
    </div>
  );
};

StructureTreeView.displayName = 'StructureTreeView';

export default StructureTreeView;

// src/features/structure-view/ui/organisms/StructureTreeView.svelte
<!--
  StructureTreeView.svelte — Main structure tree organism
  React source: StructureTreeView.tsx (281L)

  ARCHITECTURE:
  - Feature organism: has business logic via StructureTreeStore
  - Composes: VirtualTreeList, TreeSearchBar, StructureToolbar, EmptyStructure
  - Syncs external selection, handles keyboard shortcuts
  - Mobile responsive with adaptive indentation

  PROPS:
  - root: IIIFItem | null — IIIF tree root
  - onUpdate: (newRoot) => void — tree structure changed
  - onSelect: (id) => void — node selected
  - onOpen: (item) => void — node double-clicked (navigate)
  - selectedId: string | null — externally selected ID
  - containerHeight: number — virtual list height
  - fieldMode: boolean
-->
<script lang="ts">
  import { cn } from '@/src/shared/lib/cn';
  import type { IIIFItem } from '@/src/shared/types';
  import { StructureTreeStore } from '../../stores/structureTree.svelte';
  import { TreeSearchBar } from '../atoms';
  import type { DropPosition } from '../atoms/types';
  import { EmptyStructure, StructureToolbar, VirtualTreeList } from '../molecules';

  interface Props {
    root: IIIFItem | null;
    onUpdate?: (newRoot: IIIFItem) => void;
    onSelect?: (id: string) => void;
    onOpen?: (item: IIIFItem) => void;
    selectedId?: string | null;
    class?: string;
    containerHeight?: number;
    fieldMode?: boolean;
  }

  let {
    root,
    onUpdate,
    onSelect,
    onOpen,
    selectedId = null,
    class: className = '',
    containerHeight = 400,
    fieldMode = false,
  }: Props = $props();

  // ── Store ──
  const tree = new StructureTreeStore();

  // ── Build tree when root changes ──
  $effect(() => {
    if (root) {
      const state = buildSimpleState(root);
      tree.buildFromVault(state, root.id);
    }
  });

  // ── Sync external selection ──
  $effect(() => {
    if (selectedId && !tree.selectedIds.has(selectedId)) {
      tree.selectNode(selectedId);
    }
  });

  // ── Notify parent of selection changes ──
  $effect(() => {
    if (onSelect && tree.selectedIds.size === 1) {
      const [id] = tree.selectedIds;
      onSelect(id);
    }
  });

  // ── Keyboard shortcut: Ctrl/Cmd+F to focus search ──
  $effect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'f') {
        e.preventDefault();
        const searchInput = document.querySelector<HTMLInputElement>(
          '[aria-label="Search structure tree"]',
        );
        searchInput?.focus();
      }
    };
    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  });

  // ── Derived values ──
  const visibleNodes = $derived(tree.visibleNodes);
  const flattenedNodes = $derived(tree.flattenedNodes);
  const matchCount = $derived(tree.matchCount);
  const filterQuery = $derived(tree.filterQuery);
  const treeStats = $derived(tree.treeStats);

  // ── Handlers ──
  function handleSelect(id: string, additive: boolean) {
    tree.selectNode(id, { additive });
  }

  function handleDragStart(id: string) {
    tree.startDrag(id);
  }

  function handleDragEnd() {
    tree.endDrag();
  }

  function handleDrop(targetId: string, position?: DropPosition) {
    const draggingId = tree.draggingId;
    if (!draggingId) return;

    if (tree.canDrop(draggingId, targetId)) {
      const draggedNode = tree.findNode(draggingId);
      const targetNode = tree.findNode(targetId);

      if (draggedNode && targetNode && onUpdate && root) {
        // @migration: Implement actual tree move using vault operations
        console.debug(`Move ${draggedNode.type} to ${targetNode.type} position: ${position}`);
      }
    }

    tree.endDrag();
  }

  function handleDoubleClick(id: string) {
    const node = tree.findNode(id);
    if (node && onOpen) {
      onOpen(node as unknown as IIIFItem);
    }
  }

  // ── Build a simplified NormalizedState from an IIIFItem tree ──
  function buildSimpleState(
    item: IIIFItem,
  ): { entities: Record<string, Record<string, unknown>>; typeIndex: Record<string, string>; references: Record<string, string[]> } {
    const entities: Record<string, Record<string, unknown>> = {};
    const typeIndex: Record<string, string> = {};
    const references: Record<string, string[]> = {};

    function walk(node: IIIFItem) {
      const type = node.type || 'Unknown';
      if (!entities[type]) entities[type] = {};
      entities[type][node.id] = node;
      typeIndex[node.id] = type;

      const childIds: string[] = [];
      const children = (node.items ?? []) as IIIFItem[];
      for (const child of children) {
        childIds.push(child.id);
        walk(child);
      }
      references[node.id] = childIds;
    }

    walk(item);
    return { entities, typeIndex, references };
  }
</script>

{#if !root}
  <EmptyStructure class={className} />
{:else}
  <div
    class={cn(
      'flex flex-col h-full',
      'bg-nb-black',
      'border border-nb-black/20 overflow-hidden',
      'shadow-brutal-sm',
      className,
    )}
  >
    <!-- Search Bar -->
    <div class="p-4 border-b border-nb-black/20 bg-nb-black/30">
      <TreeSearchBar
        query={filterQuery}
        onQueryChange={(q) => tree.setFilterQuery(q)}
        {matchCount}
        totalCount={flattenedNodes.length}
      />
    </div>

    <!-- Toolbar: expand/collapse, selection info -->
    <StructureToolbar
      totalNodes={filterQuery ? matchCount : flattenedNodes.length}
      selectedCount={tree.selectedIds.size}
      onExpandAll={() => tree.expandAll()}
      onCollapseAll={() => tree.collapseAll()}
      onClearSelection={() => tree.clearSelection()}
      abstractionLevel={fieldMode ? 'advanced' : 'standard'}
    />

    <!-- Virtual Tree Content -->
    <VirtualTreeList
      nodes={visibleNodes}
      {containerHeight}
      onSelect={handleSelect}
      onToggleExpand={(id) => tree.toggleExpanded(id)}
      onDragStart={handleDragStart}
      onDragEnd={handleDragEnd}
      onDrop={handleDrop}
      onDoubleClick={handleDoubleClick}
      class="flex-1"
    />

    <!-- Status bar -->
    {#if treeStats}
      <div
        class="px-4 py-2.5 border-t border-nb-black/20 bg-nb-black/80 text-sm text-nb-cream/50 flex items-center justify-between"
      >
        <span class="font-serif">
          {treeStats.totalNodes}
          {treeStats.totalNodes === 1 ? 'node' : 'nodes'}
        </span>
        {#if filterQuery}
          <span class="text-nb-orange font-medium">
            Showing {matchCount} of {flattenedNodes.length}
          </span>
        {/if}
      </div>
    {/if}
  </div>
{/if}
