// src/features/timeline/ui/organisms/TimelineView.svelte
<!--
  TimelineView.svelte — Chronological Timeline View
  ====================================================
  React source: src/features/timeline/ui/organisms/TimelineView.tsx

  ARCHITECTURE:
  - Feature organism: Date-grouped canvas display with zoom levels
  - Uses PaneLayout with variant="default" (scrollable body)
  - SubBar shows date range minimap
  - Pure Svelte rendering (no external lib)

  PROPS:
  - root: IIIFItem — IIIF tree
  - cx: ContextualClassNames
  - fieldMode: boolean
  - t: TerminologyFn
  - onSelect: (item: IIIFItem) => void
  - onSwitchView: (mode: string) => void
-->

<script lang="ts">
  import { PaneLayout, Row } from '@/src/shared/ui/layout';
  import ViewHeader from '@/src/shared/ui/molecules/ViewHeader/ViewHeader.svelte';
  import type { ContextualClassNames } from '@/src/shared/ui/molecules/ViewHeader/types';
  import Center from '@/src/shared/ui/layout/primitives/Center.svelte';
  import Button from '@/src/shared/ui/atoms/Button.svelte';
  import { cn } from '@/src/shared/lib/cn';
  import { TimelineStore } from '@/src/features/timeline/stores/timeline.svelte';
  import type { ZoomLevel, TimelineGroup, TimelineItem } from '@/src/features/timeline/stores/timeline.svelte';
  import type { IIIFItem } from '@/src/shared/types';
  import { getIIIFValue } from '@/src/shared/types';

  interface Props {
    root: IIIFItem;
    cx: ContextualClassNames;
    fieldMode: boolean;
    t: (key: string, fallback?: string) => string;
    onSelect: (item: IIIFItem) => void;
    onSwitchView: (mode: string) => void;
  }

  let { root, cx, fieldMode, t, onSelect, onSwitchView }: Props = $props();

  // ── Feature Store ──
  const timeline = new TimelineStore();

  // ── Derived ──
  const groups = $derived(timeline.groups);
  const hasItems = $derived(timeline.hasData);
  const zoomLevel = $derived(timeline.zoomLevel);
  const totalItems = $derived(timeline.totalItems);
  const selectedDate = $derived(timeline.selectedDate);

  const gridColumnsClass = $derived(
    zoomLevel === 'day' ? 'grid-cols-7' :
    zoomLevel === 'month' ? 'grid-cols-4' : 'grid-cols-3'
  );

  const zoomLevels: ZoomLevel[] = ['day', 'month', 'year'];

  // ── Effects ──

  // Initialize timeline store from root's canvases (items with navDate)
  $effect(() => {
    // @migration: root.items may be canvases or manifests; extract canvas-level navDate
    const items = root.items ?? [];
    const canvases = items
      .filter((item: IIIFItem) => item.type === 'Canvas' || item.type === 'Manifest')
      .flatMap((item: IIIFItem) => {
        if (item.type === 'Canvas') return [item];
        return item.items ?? [];
      })
      .map((canvas: IIIFItem) => ({
        id: canvas.id,
        label: getIIIFValue(canvas.label) || canvas.id,
        navDate: canvas.navDate,
      }));

    timeline.loadFromCanvases(canvases);
  });

  // ── Handlers ──
  function handleDotClick(dateKey: string): void {
    timeline.toggleDate(dateKey);
  }

  function handleItemClick(item: TimelineItem): void {
    onSelect({ id: item.canvasId, type: 'Canvas' } as IIIFItem);
  }

  function handleZoomChange(level: ZoomLevel): void {
    timeline.setZoomLevel(level);
  }

  // ── Minimap helpers ──
  // Position dots proportionally across the minimap bar
  function getMinimapPosition(group: TimelineGroup): number {
    return timeline.getTimelinePosition(group.date) * 100;
  }
</script>

<PaneLayout variant="default">
  {#snippet header()}
    <ViewHeader {cx}>
      {#snippet title()}
        <span class={cn('font-mono uppercase text-sm font-semibold', cx.text)}>
          {t('timeline', 'Timeline')}
        </span>
        {#if hasItems}
          <span class={cn(
            'ml-2 px-1.5 py-0.5 rounded text-xs font-bold',
            cx.accent || 'bg-nb-black text-nb-white'
          )}>
            {totalItems}
          </span>
        {/if}
      {/snippet}

      {#snippet actions()}
        <div class="flex items-center gap-1" role="radiogroup" aria-label={t('zoomLevel', 'Zoom level')}>
          {#each zoomLevels as level}
            <Button
              variant={zoomLevel === level ? 'primary' : 'ghost'}
              size="sm"
              onclick={() => handleZoomChange(level)}
              aria-checked={zoomLevel === level ? 'true' : 'false'}
              role="radio"
            >
              {t(level, level)}
            </Button>
          {/each}
        </div>
      {/snippet}

      <!-- Date range minimap in subbar -->
      {#snippet subbar()}
        {#if hasItems}
          <div class="relative flex items-center w-full h-6">
            <!-- Base line -->
            <div class={cn(
              'absolute left-0 right-0 top-1/2 h-px -translate-y-1/2',
              cx.border || 'bg-nb-black/20'
            )}></div>
            <!-- Date dots -->
            {#each groups as group (group.key)}
              {@const pct = getMinimapPosition(group)}
              <button
                class={cn(
                  'absolute w-2 h-2 rounded-full -translate-x-1/2 -translate-y-1/2 top-1/2',
                  'transition-all hover:scale-150',
                  selectedDate === group.key
                    ? cn('w-3 h-3', cx.accent || 'bg-nb-black')
                    : cn(cx.textMuted || 'bg-nb-black/30')
                )}
                style="left: {pct}%;"
                onclick={() => handleDotClick(group.key)}
                title="{group.displayDate}: {group.items.length} {t('items', 'items')}"
                aria-label="{group.displayDate}, {group.items.length} {t('items', 'items')}"
              ></button>
            {/each}
            <!-- Min date label -->
            {#if timeline.minDate}
              <span class={cn('absolute left-0 -bottom-0.5 text-[9px] font-mono', cx.textMuted || 'text-nb-black/40')}>
                {timeline.formatShortDate(timeline.minDate)}
              </span>
            {/if}
            <!-- Max date label -->
            {#if timeline.maxDate}
              <span class={cn('absolute right-0 -bottom-0.5 text-[9px] font-mono', cx.textMuted || 'text-nb-black/40')}>
                {timeline.formatShortDate(timeline.maxDate)}
              </span>
            {/if}
          </div>
        {/if}
      {/snippet}
    </ViewHeader>
  {/snippet}

  {#snippet body()}
    {#if !hasItems}
      <Center flex class="h-full">
        <div class={cn('text-center p-8', cx.textMuted || 'text-nb-black/50')}>
          <div class="text-4xl mb-4" aria-hidden="true">&#x1f4c5;</div>
          <p class="text-lg font-medium">{t('noDatedItems', 'No dated items')}</p>
          <p class="text-sm mt-2">
            {t('noDatedItemsHint', 'Add navDate to canvases to see them on the timeline.')}
          </p>
        </div>
      </Center>
    {:else}
      <div class="relative pl-10 pr-4 py-6" role="list" aria-label={t('timeline', 'Timeline')}>
        <!-- Vertical connector line -->
        <div
          class={cn('absolute left-[22px] top-0 bottom-0 w-0.5', cx.border || 'bg-nb-black/15')}
          aria-hidden="true"
        ></div>

        {#each groups as group (group.key)}
          {@const isExpanded = selectedDate === null || selectedDate === group.key}
          {@const isSelected = selectedDate === group.key}

          <div class="relative mb-8" aria-expanded={isExpanded}>
            <!-- Timeline dot -->
            <button
              class={cn(
                'absolute left-[-22px] top-1 w-4 h-4 rounded-full border-2',
                'transition-all hover:scale-125 -translate-x-1/2',
                isSelected
                  ? cn('scale-110', cx.accent || 'bg-nb-black border-nb-black')
                  : cn(cx.surface || 'bg-nb-white', cx.border || 'border-nb-black/40')
              )}
              onclick={() => handleDotClick(group.key)}
              aria-pressed={isSelected}
              aria-label="{t('toggle', 'Toggle')} {group.displayDate} ({group.items.length} {t('items', 'items')})"
            ></button>

            <!-- Date header -->
            <div class={cn('mb-3 flex items-baseline gap-2', cx.text || 'text-nb-black')}>
              <span class="font-semibold text-sm font-mono uppercase">
                {group.displayDate}
              </span>
              <span class={cn('text-xs', cx.textMuted || 'text-nb-black/50')}>
                {group.items.length} {group.items.length === 1 ? t('item', 'item') : t('items', 'items')}
              </span>
            </div>

            <!-- Items grid (visible when group is expanded) -->
            {#if isExpanded}
              <div class={cn('grid gap-2', gridColumnsClass)}>
                {#each group.items as item (item.id)}
                  <button
                    class={cn(
                      'rounded overflow-hidden border-2 text-left',
                      'transition-all hover:shadow-md hover:-translate-y-0.5',
                      cx.surface || 'bg-nb-white',
                      cx.border || 'border-nb-black/20',
                      'hover:border-nb-black/50'
                    )}
                    onclick={() => handleItemClick(item)}
                    aria-label="{item.label} — {timeline.formatShortDate(item.date)}"
                  >
                    <!-- @migration: thumbnail would come from canvas thumbnail resolution -->
                    <div
                      class={cn(
                        'w-full aspect-square flex items-center justify-center',
                        'text-lg font-bold',
                        cx.accent || 'bg-nb-cream text-nb-black/30'
                      )}
                      aria-hidden="true"
                    >
                      {item.label.charAt(0).toUpperCase()}
                    </div>
                    <div class="p-1.5">
                      {#if zoomLevel === 'day'}
                        <p class={cn('text-[10px] font-mono', cx.textMuted || 'text-nb-black/50')}>
                          {timeline.formatTime(item.date)}
                        </p>
                      {/if}
                      <p class={cn('text-xs truncate', cx.text || 'text-nb-black')}>
                        {item.label}
                      </p>
                      {#if zoomLevel !== 'day'}
                        <p class={cn('text-[10px]', cx.textMuted || 'text-nb-black/40')}>
                          {timeline.formatShortDate(item.date)}
                        </p>
                      {/if}
                    </div>
                  </button>
                {/each}
              </div>
            {/if}
          </div>
        {/each}
      </div>
    {/if}
  {/snippet}
</PaneLayout>

// src/features/timeline/ui/organisms/TimelineView.tsx
/**
 * TimelineView Organism
 *
 * Main organism for the timeline feature. Displays IIIF items with navDate
 * in a chronological visualization with zoom levels and grouping.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Receives cx and fieldMode via props from FieldModeTemplate (no hook calls)
 * - Composes molecules: EmptyState, TimelineTick, RangeSelector
 * - Domain logic delegated to useTimeline hook
 * - No prop-drilling of fieldMode
 *
 * IDEAL OUTCOME: Users can browse and navigate dated IIIF items temporally
 * FAILURE PREVENTED: Invalid date sorting, inconsistent grouping, poor performance
 *
 * LEGACY NOTE: This is the refactored version of components/views/TimelineView.tsx
 * The original component (255 lines) mixed date calculations with UI.
 * This organism delegates to useTimeline hook.
 *
 * DECOMPOSITION NOTE: Future molecules to extract:
 * - TimelineHeader: Zoom controls + stats
 * - TimelineMinimap: Date range bar with markers
 * - TimelineGroup: Date group with items
 * - TimelineItemCard: Individual item thumbnail
 */

import React from 'react';
import { getIIIFValue, type IIIFItem } from '@/src/shared/types';
import type { ContextualClassNames } from '@/src/shared/lib/hooks/useContextualStyles';
import type { AppMode } from '@/src/shared/types';
import { Icon } from '@/src/shared/ui/atoms';
import { Button } from '@/ui/primitives/Button';
import { EmptyState } from '@/src/shared/ui/molecules/EmptyState';
import { ViewToggle } from '@/src/shared/ui/molecules/ViewToggle';
import { ViewHeader, ViewHeaderTitle, ViewHeaderActions } from '@/src/shared/ui/molecules/ViewHeader';
import { TimelineTick } from '@/src/shared/ui/molecules/TimelineTick';
import { PaneLayout } from '@/src/shared/ui/layout';
import { VIEW_MODE_OPTIONS, saveViewMode, type ArchiveViewMode } from '@/src/features/archive/model';
import {
  formatShortDate,
  formatTime,
  getGridColumns,
  getTimelinePosition,
  useTimeline,
  type ZoomLevel,
} from '../../model';

export interface TimelineViewProps {
  /** Root IIIF item containing dated canvases */
  root: IIIFItem | null;
  /** Called when a canvas is selected */
  onSelect: (item: IIIFItem) => void;
  /** Contextual styles from template */
  cx: ContextualClassNames;
  /** Current field mode */
  fieldMode: boolean;
  /** Called when view mode changes (grid/list/map/timeline) */
  onSwitchView?: (mode: AppMode) => void;
}

const ZOOM_OPTIONS: { level: ZoomLevel; label: string }[] = [
  { level: 'day', label: 'Day' },
  { level: 'month', label: 'Month' },
  { level: 'year', label: 'Year' },
];

/**
 * TimelineView Organism
 *
 * @example
 * <FieldModeTemplate>
 *   {({ cx, fieldMode }) => (
 *     <TimelineView
 *       root={root}
 *       onSelect={handleSelect}
 *       cx={cx}
 *       fieldMode={fieldMode}
 *     />
 *   )}
 * </FieldModeTemplate>
 */
export const TimelineView: React.FC<TimelineViewProps> = ({
  root,
  onSelect,
  cx,
  fieldMode,
  onSwitchView,
}) => {
  const {
    groups,
    minDate,
    maxDate,
    totalItems,
    zoomLevel,
    selectedDate,
    setZoomLevel,
    toggleDate,
    hasItems,
  } = useTimeline(root);

  // Empty state
  if (!hasItems) {
    return (
      <PaneLayout className={cx.surface}>
        <PaneLayout.Header>
          <ViewHeader cx={cx} fieldMode={fieldMode}>
            <ViewHeaderTitle title="Timeline" />
            <ViewHeaderActions>
              {onSwitchView && (
                <ViewToggle
                  value="timeline"
                  onChange={(v) => {
                    const mode = v as ArchiveViewMode;
                    if (mode === 'grid' || mode === 'list') {
                      saveViewMode(mode);
                      onSwitchView('archive');
                    } else {
                      onSwitchView(mode as AppMode);
                    }
                  }}
                  options={VIEW_MODE_OPTIONS}
                  ariaLabel="View mode toggle"
                  cx={cx}
                  fieldMode={fieldMode}
                />
              )}
            </ViewHeaderActions>
          </ViewHeader>
        </PaneLayout.Header>
        <PaneLayout.Body>
          <EmptyState
            icon="event"
            title="No Dated Items"
            message="Items need a navDate property to appear in the timeline."
            cx={cx}
            fieldMode={fieldMode}
          />
        </PaneLayout.Body>
      </PaneLayout>
    );
  }

  return (
    <PaneLayout className={cx.surface}>
      {/* Header */}
      <PaneLayout.Header>
        <ViewHeader cx={cx} fieldMode={fieldMode}>
          <ViewHeaderTitle
            title="Timeline"
            badge={`${totalItems} dated item${totalItems !== 1 ? 's' : ''}`}
          />
          <ViewHeaderActions>
            {/* Zoom Controls */}
            <div className={`flex items-center gap-1 p-0.5 ${fieldMode ? 'bg-nb-yellow/10' : 'bg-nb-black/5'}`}>
              {ZOOM_OPTIONS.map(({ level, label }) => (
                <Button
                  key={level}
                  onClick={() => setZoomLevel(level)}
                  variant={zoomLevel === level ? 'primary' : 'ghost'}
                  size="sm"
                  className="text-xs font-bold"
                >
                  {label}
                </Button>
              ))}
            </div>
            {onSwitchView && (
              <ViewToggle
                value="timeline"
                onChange={(v) => {
                  const mode = v as ArchiveViewMode;
                  if (mode === 'grid' || mode === 'list') {
                    saveViewMode(mode);
                    onSwitchView('archive');
                  } else {
                    onSwitchView(mode as AppMode);
                  }
                }}
                options={VIEW_MODE_OPTIONS}
                ariaLabel="View mode toggle"
                cx={cx}
                fieldMode={fieldMode}
              />
            )}
          </ViewHeaderActions>
        </ViewHeader>
      </PaneLayout.Header>

      {/* Date Range Minimap — hidden on mobile (dots too small for touch) */}
      <PaneLayout.SubBar visible={!!(minDate && maxDate)}>
        {minDate && maxDate && (
        <div className={`h-10 ${cx.surface} hidden sm:flex items-center px-6 text-xs ${cx.textMuted}`}>
          <span>{formatShortDate(minDate)}</span>
          <div className={`flex-1 mx-4 h-1 ${cx.border} relative`}>
            {groups.map((g) => {
              if (!g.items[0]?.navDate) return null;
              const percent = getTimelinePosition(
                new Date(g.items[0].navDate),
                minDate,
                maxDate
              );
              return (
                <div
                  key={g.date}
                  className="absolute w-2 h-2 bg-nb-purple -top-0.5 cursor-pointer hover:scale-150 transition-transform"
                  style={{ left: `${percent}%` }}
                  title={`${g.displayDate}: ${g.items.length} items`}
                  onClick={() => toggleDate(g.date)}
                />
              );
            })}
          </div>
          <span>{formatShortDate(maxDate)}</span>
        </div>
        )}
      </PaneLayout.SubBar>

      {/* Timeline Content */}
      <PaneLayout.Body scroll className="p-4 sm:p-6">
        <div className="max-w-4xl mx-auto">
          {groups.map((group, groupIdx) => (
            <div key={group.date} className="relative pl-8 pb-8">
              {/* Timeline connector line */}
              {groupIdx < groups.length - 1 && (
                <div className={`absolute left-3 top-6 bottom-0 w-0.5 ${fieldMode ? 'bg-nb-black/80' : 'bg-nb-cream'}`} />
              )}

              {/* Timeline dot */}
              <div
                className={`absolute left-0 top-1 w-8 h-8 sm:w-6 sm:h-6 flex items-center justify-center cursor-pointer transition-nb ${
                  selectedDate === group.date
                    ? 'bg-nb-purple'
                    : fieldMode ? 'bg-nb-black/60' : 'bg-nb-black/30'
                }`}
                onClick={() => toggleDate(group.date)}
              >
                <div className="w-2 h-2 bg-nb-white " />
              </div>

              {/* Date header */}
              <div
                className="flex items-center gap-3 mb-3 cursor-pointer group"
                onClick={() => toggleDate(group.date)}
              >
                <TimelineTick
                  timestamp={group.date}
                  label={group.displayDate}
                  items={group.items.map(item => ({
                    id: item.id,
                    title: item.label ? String(item.label) : 'Untitled',
                    type: item.type || 'Canvas',
                    timestamp: item.navDate || group.date
                  }))}
                  position={groupIdx / groups.length}
                  onSelectItem={(id) => onSelect(group.items.find(i => i.id === id) || group.items[0])}
                  selected={selectedDate === group.date}
                  cx={cx}
                />
              </div>

              {/* Items grid */}
              <div className={`grid gap-3 ${getGridColumns(zoomLevel)}`}>
                {group.items.map((item) => (
                  <div
                    key={item.id}
                    className={` shadow-brutal-sm border cursor-pointer transition-nb group overflow-hidden ${
                      fieldMode
                        ? 'bg-nb-black border-nb-black/80 hover:border-nb-purple'
                        : 'bg-nb-white border-nb-black/20 hover:shadow-brutal-sm hover:border-nb-purple/40'
                    }`}
                    onClick={() => onSelect(item)}
                  >
                    <div className={`aspect-square relative overflow-hidden ${fieldMode ? 'bg-nb-black/80' : 'bg-nb-cream'}`}>
                      {item._blobUrl ? (
                        <img
                          src={item._blobUrl}
                          className="w-full h-full object-cover"
                          loading="lazy"
                        />
                      ) : (
                        <div className="w-full h-full flex items-center justify-center">
                          <Icon name="image" className={`text-2xl ${fieldMode ? 'text-nb-black/50' : 'text-nb-black/30'}`} />
                        </div>
                      )}
                      {zoomLevel !== 'day' && item.navDate && (
                        <div className="absolute bottom-0 left-0 right-0 bg-nb-black/60 text-white text-[8px] px-1 py-0.5 truncate">
                          {formatShortDate(new Date(item.navDate))}
                        </div>
                      )}
                    </div>
                    {zoomLevel === 'day' && (
                      <div className="p-1.5">
                        <div className={`text-[10px] truncate ${fieldMode ? 'text-nb-black/30' : 'text-nb-black/60'}`}>
                          {getIIIFValue(item.label, 'none') || 'Untitled'}
                        </div>
                        {item.navDate && (
                          <div className={`text-[9px] ${cx.textMuted}`}>
                            {formatTime(new Date(item.navDate))}
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </PaneLayout.Body>
    </PaneLayout>
  );
};
