// src/shared/ui/layout/primitives/Center.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { cn } from '@/src/shared/lib/cn';

  interface Props {
    flex?: boolean;
    class?: string;
    children: Snippet;
  }

  let { flex, class: className = '', children }: Props = $props();

  let classes = $derived(cn('flex items-center justify-center', flex && 'flex-1', className));
</script>

<div class={classes}>
  {@render children()}
</div>

// src/shared/ui/layout/primitives/Center.tsx
import React from 'react';
import { cn } from '@/src/shared/lib/cn';

interface CenterProps {
  flex?: boolean;
  className?: string;
  children: React.ReactNode;
}

export function Center({ flex, className, children }: CenterProps) {
  const classes = cn(
    'flex items-center justify-center',
    flex && 'flex-1',
    className,
  );

  return <div className={classes}>{children}</div>;
}
