// src/shared/ui/layout/primitives/Shelf.tsx
import React from 'react';
import { shelfHeightClasses, shelfWidthClasses } from '../types';
import type { ShelfHeight, ShelfWidth } from '../types';
import { cn } from '@/src/shared/lib/cn';

interface ShelfProps {
  h?: ShelfHeight;
  w?: ShelfWidth | number;
  shrink?: boolean;
  className?: string;
  children: React.ReactNode;
}

export function Shelf({ h = 'auto', w, shrink = false, className, children }: ShelfProps) {
  const classes = cn(
    !shrink && 'shrink-0',
    shelfHeightClasses[h],
    typeof w === 'string' ? shelfWidthClasses[w] : undefined,
    className,
  );

  const style = typeof w === 'number' ? { width: w } : undefined;

  return <div className={classes} style={style}>{children}</div>;
}

// src/shared/ui/layout/primitives/Shelf.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { ShelfHeight, ShelfWidth } from '../types';
  import { shelfHeightClasses, shelfWidthClasses } from '../types';
  import { cn } from '@/src/shared/lib/cn';

  interface Props {
    h?: ShelfHeight;
    w?: ShelfWidth | number;
    shrink?: boolean;
    class?: string;
    children: Snippet;
  }

  let { h = 'auto', w, shrink, class: className = '', children }: Props = $props();

  let classes = $derived(cn(
    !shrink && 'shrink-0',
    shelfHeightClasses[h],
    typeof w === 'string' ? shelfWidthClasses[w] : undefined,
    className
  ));
  let widthStyle = $derived(typeof w === 'number' ? `${w}px` : undefined);
</script>

<div class={classes} style:width={widthStyle}>
  {@render children()}
</div>
