// src/widgets/AnnotationToolbar/AnnotationToolbar.tsx
/**
 * AnnotationToolbar Widget
 *
 * Composes: AnnotationToolPanel (from viewer) + MetadataEditorPanel (from metadata-edit)
 *
 * This widget combines annotation controls with metadata editing capabilities
 * for a unified annotation editing experience.
 *
 * WIDGET COMPOSITION RULES:
 * - Pure composition only - no business logic
 * - Imports organisms from features (viewer, metadata-edit)
 * - Receives cx and fieldMode via props from template
 * - Exists strictly between Organisms and Pages
 */

import React from 'react';
import type { IIIFAnnotation, IIIFCanvas, IIIFItem } from '@/src/shared/types';
import { AnnotationToolPanel } from '@/src/features/viewer/ui/organisms/AnnotationToolPanel';
import { MetadataEditorPanel } from '@/src/features/metadata-edit/ui/organisms/MetadataEditorPanel';

export interface AnnotationToolbarProps {
  /** Canvas to annotate */
  canvas: IIIFCanvas;
  /** Image URL for the canvas */
  imageUrl: string;
  /** Existing annotations */
  existingAnnotations?: IIIFAnnotation[];
  /** Callback when annotation is created */
  onCreateAnnotation: (annotation: IIIFAnnotation) => void;
  /** Callback when panel closes */
  onClose: () => void;
  /** Resource for metadata editing */
  resource: IIIFItem | null;
  /** Called when resource is updated */
  onUpdateResource: (r: Partial<IIIFItem>) => void;
  /** Current language for metadata values */
  language: string;
  /** Contextual styles from template */
  cx: {
    surface: string;
    text: string;
    textMuted: string;
    accent: string;
    border: string;
    divider: string;
    headerBg: string;
    input: string;
    label: string;
    active: string;
    inactive?: string;
    warningBg?: string;
    pageBg?: string;
  };
  /** Current field mode */
  fieldMode: boolean;
  /** Terminology function from template */
  t: (key: string) => string;
}

/**
 * AnnotationToolbar Widget
 *
 * Composes annotation tools with metadata editing for a complete
 * annotation workflow. This widget sits between organisms and pages,
 * combining viewer and metadata-edit features.
 *
 * @example
 * <FieldModeTemplate>
 *   {({ cx, fieldMode, t }) => (
 *     <AnnotationToolbar
 *       canvas={selectedCanvas}
 *       imageUrl={imageUrl}
 *       existingAnnotations={annotations}
 *       onCreateAnnotation={handleCreate}
 *       onClose={handleClose}
 *       resource={selectedItem}
 *       onUpdateResource={handleUpdate}
 *       language={language}
 *       cx={cx}
 *       fieldMode={fieldMode}
 *       t={t}
 *     />
 *   )}
 * </FieldModeTemplate>
 */
export const AnnotationToolbar: React.FC<AnnotationToolbarProps> = ({
  canvas,
  imageUrl,
  existingAnnotations = [],
  onCreateAnnotation,
  onClose,
  resource,
  onUpdateResource,
  language,
  cx,
  fieldMode,
  t: _t,
}) => {
  return (
    <div className="flex flex-col h-full">
      {/* Annotation Tool Panel from viewer feature */}
      <div className="flex-1 min-h-0">
        <AnnotationToolPanel
          canvas={canvas}
          imageUrl={imageUrl}
          existingAnnotations={existingAnnotations}
          onCreateAnnotation={onCreateAnnotation}
          onClose={onClose}
          cx={{
            text: cx.text,
            textMuted: cx.textMuted,
            active: cx.active,
            surface: cx.surface,
          }}
        />
      </div>

      {/* Metadata Editor Panel from metadata-edit feature */}
      {resource && (
        <div className="border-t border-nb-black/20 max-h-80 overflow-auto">
          <MetadataEditorPanel
            resource={resource}
            onUpdateResource={onUpdateResource}
            language={language}
            cx={{
              surface: cx.surface,
              text: cx.text,
              accent: cx.accent,
              border: cx.border,
              divider: cx.divider,
              headerBg: cx.headerBg,
              textMuted: cx.textMuted,
              input: cx.input,
              label: cx.label,
              active: cx.active,
            }}
            fieldMode={fieldMode}
            onClose={onClose}
          />
        </div>
      )}
    </div>
  );
};

export default AnnotationToolbar;

// src/widgets/AnnotationToolbar/AnnotationToolbar.svelte
<!--
  AnnotationToolbar.svelte -- Annotation + Metadata editing composition widget
  =============================================================================
  React source: src/widgets/AnnotationToolbar/AnnotationToolbar.tsx (147 lines)

  Architecture:
    - Widget layer: PURE COMPOSITION only, zero business logic
    - Stacks two feature organisms vertically:
      1. AnnotationToolPanel (from features/viewer) -- annotation drawing/creation
      2. MetadataEditorPanel (from features/metadata-edit) -- resource metadata editing
    - Both sub-components are NOT YET MIGRATED to Svelte; styled placeholder boxes used.
    - Receives cx and fieldMode via props from parent template.
    - Widget exists strictly between Organisms and Pages per FSD rules.

  Props:
    canvas                -- IIIFCanvas to annotate
    imageUrl              -- Image URL for the canvas
    existingAnnotations   -- Existing IIIFAnnotation[] on the canvas
    onCreateAnnotation    -- Callback for annotation creation
    onClose               -- Callback when panel closes
    resource              -- IIIFItem for metadata editing (nullable)
    onUpdateResource      -- Callback for resource updates
    language              -- Current language code for metadata values
    cx                    -- ContextualClassNames for theming
    fieldMode             -- Field mode toggle
    t                     -- Terminology function from template
-->
<script lang="ts">
  import type { IIIFAnnotation, IIIFCanvas, IIIFItem } from '@/src/shared/types';
  import type { ContextualClassNames } from '@/src/shared/ui/molecules/ViewHeader/types';
  import Icon from '@/src/shared/ui/atoms/Icon.svelte';
  import { cn } from '@/src/shared/lib/cn';
  // TODO(loop): Replace placeholders with actual components once props are stabilized
  // import AnnotationToolPanel from '@/src/features/viewer/ui/organisms/AnnotationToolPanel.svelte';
  // import MetadataEditorPanel from '@/src/features/metadata-edit/ui/organisms/MetadataEditorPanel.svelte';

  interface Props {
    canvas: IIIFCanvas;
    imageUrl: string;
    existingAnnotations?: IIIFAnnotation[];
    onCreateAnnotation: (annotation: IIIFAnnotation) => void;
    onClose: () => void;
    resource: IIIFItem | null;
    onUpdateResource: (r: Partial<IIIFItem>) => void;
    language: string;
    cx: ContextualClassNames;
    fieldMode: boolean;
    t: (key: string) => string;
  }

  let {
    canvas,
    imageUrl,
    existingAnnotations = [],
    onCreateAnnotation,
    onClose,
    resource,
    onUpdateResource,
    language,
    cx,
    fieldMode,
    t,
  }: Props = $props();
</script>

<div class="flex flex-col h-full">
  <!-- Annotation Tool Panel from viewer feature (flex-1 for primary content) -->
  <div class="flex-1 min-h-0">
    <!-- TODO(loop): Replace placeholder with AnnotationToolPanel component.
         Props: canvas, imageUrl, existingAnnotations, onCreateAnnotation, onClose,
                cx subset { text, textMuted, active, surface } -->
    <div
      class={cn(
        'flex flex-col items-center justify-center h-full gap-2 border-2 border-dashed rounded',
        'text-xs',
        cx.border || 'border-nb-black/15',
        cx.textMuted || 'text-nb-black/40'
      )}
      data-placeholder="AnnotationToolPanel"
    >
      <Icon name="draw" class="text-2xl opacity-40" />
      <span class="font-mono uppercase tracking-wide">AnnotationToolPanel</span>
      <span class="text-[10px] opacity-60">Pending migration from features/viewer</span>
    </div>
  </div>

  <!-- Metadata Editor Panel from metadata-edit feature (conditional, scrollable) -->
  {#if resource}
    <div class={cn('border-t max-h-80 overflow-auto', cx.border || 'border-nb-black/20')}>
      <!-- TODO(loop): Replace placeholder with MetadataEditorPanel component.
           Props: resource, onUpdateResource, language, fieldMode, onClose,
                  cx subset { surface, text, accent, border, divider, headerBg,
                              textMuted, input, label, active } -->
      <div
        class={cn(
          'flex flex-col items-center justify-center h-24 gap-1 border-2 border-dashed rounded m-2',
          'text-xs',
          cx.border || 'border-nb-black/15',
          cx.textMuted || 'text-nb-black/40'
        )}
        data-placeholder="MetadataEditorPanel"
      >
        <Icon name="edit_note" class="text-lg opacity-40" />
        <span class="font-mono uppercase tracking-wide">MetadataEditorPanel</span>
        <span class="text-[10px] opacity-60">Pending migration from features/metadata-edit</span>
      </div>
    </div>
  {/if}
</div>
