// src/features/viewer/ui/atoms/FullscreenButton.tsx
/**
 * FullscreenButton Atom
 *
 * Fullscreen toggle button for media player.
 * Handles fullscreen state and browser API differences.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Minimal local UI state (fullscreen detection)
 * - No domain logic
 * - Props-only API
 * - Uses design tokens
 *
 * @module features/viewer/ui/atoms/FullscreenButton
 */

import React, { useCallback, useEffect, useState } from 'react';
import { IconButton } from '@/src/shared/ui/molecules';
import type { ContextualClassNames } from '@/hooks/useContextualStyles';

export interface FullscreenButtonProps {
  /** Reference to the container element to make fullscreen */
  containerRef: React.RefObject<HTMLElement>;
  /** Callback when fullscreen state changes */
  onFullscreenChange?: (isFullscreen: boolean) => void;
  /** Size variant */
  size?: 'sm' | 'md' | 'lg';
  /** Additional CSS classes */
  className?: string;
  /** Contextual styles from parent */
  cx?: ContextualClassNames;
  /** Field mode flag */
  fieldMode?: boolean;
}

export const FullscreenButton: React.FC<FullscreenButtonProps> = ({
  containerRef,
  onFullscreenChange,
  size = 'md',
  className = '',
  cx: _cx,
  fieldMode = false,
}) => {
  const [isFullscreen, setIsFullscreen] = useState(false);

  // Update fullscreen state when it changes
  useEffect(() => {
    const handleFullscreenChange = () => {
      const fullscreenElement =
        document.fullscreenElement ||
        (document as Document & { webkitFullscreenElement?: Element }).webkitFullscreenElement;
      const newState = !!fullscreenElement;
      setIsFullscreen(newState);
      onFullscreenChange?.(newState);
    };

    document.addEventListener('fullscreenchange', handleFullscreenChange);
    document.addEventListener('webkitfullscreenchange', handleFullscreenChange);

    return () => {
      document.removeEventListener('fullscreenchange', handleFullscreenChange);
      document.removeEventListener('webkitfullscreenchange', handleFullscreenChange);
    };
  }, [onFullscreenChange]);

  const toggleFullscreen = useCallback(async () => {
    const container = containerRef.current;
    if (!container) return;

    try {
      if (isFullscreen) {
        if (document.exitFullscreen) {
          await document.exitFullscreen();
        } else if ((document as Document & { webkitExitFullscreen?: () => Promise<void> }).webkitExitFullscreen) {
          await (document as Document & { webkitExitFullscreen: () => Promise<void> }).webkitExitFullscreen();
        }
      } else {
        if (container.requestFullscreen) {
          await container.requestFullscreen();
        } else if ((container as HTMLElement & { webkitRequestFullscreen?: () => Promise<void> }).webkitRequestFullscreen) {
          await (container as HTMLElement & { webkitRequestFullscreen: () => Promise<void> }).webkitRequestFullscreen();
        }
      }
    } catch (error) {
      // Silently fail if fullscreen is not supported or blocked
      console.warn('Fullscreen toggle failed:', error);
    }
  }, [isFullscreen, containerRef]);

  const icon = isFullscreen ? 'fullscreen_exit' : 'fullscreen';
  const label = isFullscreen ? 'Exit fullscreen' : 'Enter fullscreen';

  return (
    <IconButton
      icon={icon}
      ariaLabel={label}
      onClick={toggleFullscreen}
      variant="ghost"
      size={size}
      className={className}
      fieldMode={fieldMode}
    />
  );
};

export default FullscreenButton;

// src/features/viewer/ui/atoms/FullscreenButton.svelte
<!--
  FullscreenButton — Browser fullscreen toggle

  ORIGINAL: src/features/viewer/ui/atoms/FullscreenButton.tsx
  LAYER: atom
  FSD: features/viewer/ui/atoms

  Handles fullscreen state and webkit variants. Tracks fullscreen state
  via document.fullscreenchange / webkitfullscreenchange events.
-->

<script lang="ts">
  import { cn } from '@/src/shared/lib/cn';
  import { LIGHT_CLASSES, FIELD_CLASSES } from '@/src/shared/lib/contextual-styles';
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';
  import IconButton from '@/src/shared/ui/molecules/IconButton.svelte';

  interface Props {
    /** Callback when fullscreen state changes */
    onFullscreenChange?: (isFullscreen: boolean) => void;
    /** Size variant */
    size?: 'sm' | 'md' | 'lg';
    /** Field mode flag */
    fieldMode?: boolean;
    /** Additional CSS classes */
    class?: string;
  }

  let {
    onFullscreenChange,
    size = 'md',
    fieldMode = false,
    class: className = '',
  }: Props = $props();

  let isFullscreen = $state(false);

  let resolvedCx: ContextualClassNames = $derived(
    fieldMode ? FIELD_CLASSES : LIGHT_CLASSES
  );

  let icon = $derived(isFullscreen ? 'fullscreen_exit' : 'fullscreen');
  let label = $derived(isFullscreen ? 'Exit fullscreen' : 'Enter fullscreen');

  function handleFullscreenChange() {
    const doc = document as Document & { webkitFullscreenElement?: Element };
    const fullscreenElement = document.fullscreenElement || doc.webkitFullscreenElement;
    const newState = !!fullscreenElement;
    isFullscreen = newState;
    onFullscreenChange?.(newState);
  }

  $effect(() => {
    document.addEventListener('fullscreenchange', handleFullscreenChange);
    document.addEventListener('webkitfullscreenchange', handleFullscreenChange);
    return () => {
      document.removeEventListener('fullscreenchange', handleFullscreenChange);
      document.removeEventListener('webkitfullscreenchange', handleFullscreenChange);
    };
  });

  async function toggleFullscreen() {
    try {
      if (isFullscreen) {
        const doc = document as Document & { webkitExitFullscreen?: () => Promise<void> };
        if (document.exitFullscreen) {
          await document.exitFullscreen();
        } else if (doc.webkitExitFullscreen) {
          await doc.webkitExitFullscreen();
        }
      } else {
        const el = document.documentElement as HTMLElement & { webkitRequestFullscreen?: () => Promise<void> };
        if (el.requestFullscreen) {
          await el.requestFullscreen();
        } else if (el.webkitRequestFullscreen) {
          await el.webkitRequestFullscreen();
        }
      }
    } catch {
      // Silently fail if fullscreen is not supported or blocked
    }
  }
</script>

<IconButton
  {icon}
  {label}
  onclick={toggleFullscreen}
  {size}
  cx={resolvedCx}
  class={className}
/>
