// src/features/viewer/ui/atoms/UpscaleToggle.svelte
<!--
  UpscaleToggle — Checkbox/button for image upscaling

  ORIGINAL: src/features/viewer/ui/atoms/UpscaleToggle.tsx
  LAYER: atom
  FSD: features/viewer/ui/atoms

  Toggle button for allowing upscaling beyond original image size.
  Zero state - controlled by parent.
-->

<script lang="ts">
  import { cn } from '@/src/shared/lib/cn';
  import type { ContextualClassNames } from '@/src/shared/lib/contextual-styles';

  interface Props {
    /** Whether upscale is enabled */
    value?: boolean;
    /** Callback when toggle is clicked */
    onChange: (enabled: boolean) => void;
    /** Tooltip text */
    title?: string;
    /** Contextual styles from parent */
    cx?: Partial<ContextualClassNames>;
    /** Field mode flag */
    fieldMode?: boolean;
  }

  let {
    value = false,
    onChange,
    title = 'Allow upscaling beyond original size',
    cx: _cx,
    fieldMode = false,
  }: Props = $props();
</script>

<button
  class={cn(
    'text-[9px] font-bold uppercase tracking-wide px-2 py-1 border transition-all duration-150',
    value
      ? 'bg-nb-blue border-nb-blue text-white'
      : fieldMode
        ? 'bg-transparent border-nb-black/40 text-nb-black/60'
        : 'bg-transparent border-nb-black/20 text-nb-black/50 hover:border-nb-black/40'
  )}
  onclick={() => onChange(!value)}
  {title}
  aria-pressed={value}
  aria-label={title}
>
  Upscale ^
</button>

// src/features/viewer/ui/atoms/UpscaleToggle.tsx
/**
 * UpscaleToggle Atom
 *
 * Toggle button for allowing upscaling beyond original image size.
 * Displays "^" prefix when active.
 *
 * ATOMIC DESIGN COMPLIANCE:
 * - Zero state (controlled by parent)
 * - No domain logic
 * - Props-only API
 * - Uses design tokens
 *
 * @module features/viewer/ui/atoms/UpscaleToggle
 */

import React from 'react';
import { Button } from '@/ui/primitives/Button';
import type { ContextualClassNames } from '@/hooks/useContextualStyles';

export interface UpscaleToggleProps {
  /** Whether upscale is enabled */
  enabled: boolean;
  /** Callback when toggle is clicked */
  onChange: (enabled: boolean) => void;
  /** Tooltip text */
  title?: string;
  /** Contextual styles from parent */
  cx?: ContextualClassNames;
  /** Field mode flag */
  fieldMode?: boolean;
}

export const UpscaleToggle: React.FC<UpscaleToggleProps> = ({
  enabled,
  onChange,
  title = 'Allow upscaling beyond original size',
  cx: _cx,
  fieldMode = false,
}) => {
  const handleClick = () => {
    onChange(!enabled);
  };

  const activeStyles = {
    backgroundColor: '#2563eb',
    borderColor: '#1d4ed8',
    color: '#ffffff',
  };

  const inactiveStyles = fieldMode
    ? { backgroundColor: 'transparent', borderColor: '#475569', color: '#94a3b8' }
    : { backgroundColor: 'transparent', borderColor: '#cbd5e1', color: '#94a3b8' };

  return (
    <Button
      onClick={handleClick}
      variant={enabled ? 'primary' : 'ghost'}
      size="sm"
      title={title}
      style={{
        ...(enabled ? activeStyles : inactiveStyles),
        fontSize: '9px',
        fontWeight: 700,
        textTransform: 'uppercase',
        padding: '4px 8px',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderRadius: '4px',
        transition: 'all 150ms ease',
      }}
    >
      Upscale ^
    </Button>
  );
};

export default UpscaleToggle;
